import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.RingTheory.Nullstellensatz
import Mathlib.RingTheory.Spectrum.Prime.Basic
import Mathlib.RingTheory.Polynomial.Basic

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin
open MvPolynomial

set_option pp.rawOnError true

#doc (Manual) "Affine varieties" =>

%%%
file := "Affine-varieties"
%%%

In this chapter we introduce affine varieties.
We introduce them in the context of coordinates, but over the course of the other chapters we'll gradually move away from this perspective to viewing varieties as "intrinsic objects", rather than embedded in coordinates.

For simplicity, we'll do almost everything over the field of complex numbers, but the discussion generalizes to any algebraically closed field.

# Affine varieties

:::PROTOTYPE
$`\mathbb{V}(y - x^2)` is a parabola in $`\mathbb{A}^2`.
:::

:::DEFINITION
Given a set of polynomials $`S \subseteq \mathbb{C}[x_1, \dots, x_n]` (not necessarily finite or even countable), we let $`\mathbb{V}(S)` denote the set of points vanishing on _all_ the polynomials in $`S`.
Such a set is called an *affine variety*.
It lives in *$`n`-dimensional affine space*, denoted $`\mathbb{A}^n` (to distinguish it from projective space later).
:::

For example, a parabola is the zero locus of the polynomial $`y - x^2`.

:::figure "figures/algebraic-geometry/affine-parabola.svg"
The parabola $`\mathbb{V}(y - x^2)` in the affine plane $`\mathbb{A}^2`.
:::

:::EXAMPLE "Examples of affine varieties"
These examples are in two-dimensional space $`\mathbb{A}^2`, whose points are pairs $`(x, y)`.

1. A straight line can be thought of as $`\mathbb{V}(Ax + By + C)`.
2. A parabola as above can be pictured as $`\mathbb{V}(y - x^2)`.
3. A hyperbola might be $`\mathbb{V}(xy - 1)`.
4. The two axes can be thought of as $`\mathbb{V}(xy)`; this is the set of points such that $`x = 0` _or_ $`y = 0`.
5. A point $`(x_0, y_0)` can be thought of as $`\mathbb{V}(x - x_0, y - y_0)`.
6. The entire space $`\mathbb{A}^2` can be thought of as $`\mathbb{V}(0)`.
7. The empty set is the zero locus of the constant polynomial $`1`, that is $`\mathbb{V}(1)`.
:::

:::aside
Over a field $`k`, with $`K` an algebra containing it, the vanishing set of an ideal $`I` of $`k`-polynomials is Mathlib's {name}`MvPolynomial.zeroLocus`, a subset of the coordinate space $`\sigma \to K` (functions assigning a $`K`-value to each variable name in $`\sigma`).
A point lies in it exactly when every polynomial of the ideal evaluates to zero there.

```lean
example {σ k : Type*} [Field k] (K : Type*) [Field K] [Algebra k K]
    (I : Ideal (MvPolynomial σ k)) : Set (σ → K) :=
  MvPolynomial.zeroLocus K I
```
:::

# Naming affine varieties via ideals

:::PROTOTYPE
$`\mathbb{V}(I)` is a parabola, where $`I = (y - x^2)`.
:::

As you might have already noticed, a variety can be named by $`\mathbb{V}(-)` in multiple ways.
For example, the set of solutions to $$`x = 3 \text{ and } y = 4`
is just the point $`(3, 4)`.
But this is also the set of solutions to $$`x = 3 \text{ and } y = x + 1.`
So, for example $$`\{(3, 4)\} = \mathbb{V}(x - 3, y - 4) = \mathbb{V}(x - 3, y - x - 1).`
That's a little annoying, because in an ideal{margin}[Pun not intended but left for amusement value.] world we would have _one_ name for every variety.
Let's see if we can achieve this.

A partial solution is to use _ideals_ rather than small sets.
That is, consider the ideal $$`I = \left( x - 3, y - 4 \right) = \left\{ p(x, y) \cdot (x - 3) + q(x, y) \cdot (y - 4) \mid p, q \in \mathbb{C}[x, y] \right\}`
and look at $`\mathbb{V}(I)`.

:::QUESTION
Convince yourself that $`\mathbb{V}(I) = \{(3, 4)\}`.
:::

So rather than writing $`\mathbb{V}(x - 3, y - 4)` it makes sense to think about this as $`\mathbb{V}(I)`, where $`I = (x - 3, y - 4)` is the _ideal_ generated by the two polynomials $`x - 3` and $`y - 4`.
This is an improvement because

:::QUESTION
Check that $`(x - 3, y - x - 1) = (x - 3, y - 4)`.
:::

Needless to say, this pattern holds in general.

:::QUESTION
Let $`\{f_i\}` be a set of polynomials, and consider the ideal $`I` generated by these $`\{f_i\}`.
Show that $`\mathbb{V}(\{f_i\}) = \mathbb{V}(I)`.
:::

Thus we will only consider $`\mathbb{V}(I)` when $`I` is an ideal.
Of course, frequently our ideals are generated by one or two polynomials, which leads to:

:::ABUSE
Given a set of polynomials $`f_1, \dots, f_m` we let $`\mathbb{V}(f_1, \dots, f_m)` be shorthand for $`\mathbb{V}\left( \left( f_1, \dots, f_m \right) \right)`.
In other words we let $`\mathbb{V}(f_1, \dots, f_m)` abbreviate $`\mathbb{V}(I)`, where $`I` is the _ideal_ $`I = (f_1, \dots, f_m)`.
:::

This is where the Noetherian condition really shines: it guarantees that every ideal $`I \subseteq \mathbb{C}[x_1, \dots, x_n]` can be written in the form above with _finitely_ many polynomials, because it is _finitely generated_.
(The fact that $`\mathbb{C}[x_1, \dots, x_n]` is Noetherian follows from the Hilbert basis theorem.)
This is a relief, because dealing with infinite sets of polynomials is not much fun.

:::aside
The ideal generated by a set of polynomials is {name}`Ideal.span`, and the Hilbert basis theorem is the statement that a polynomial ring over a Noetherian ring is again Noetherian.
Applied inductively it gives the {name}`IsNoetherianRing` instance for $`k[x_1, \dots, x_n]`, which is exactly what makes every ideal finitely generated.
:::

# Radical ideals and Hilbert's Nullstellensatz

:::PROTOTYPE
$`\sqrt{(x^2)} = (x)` in $`\mathbb{C}[x]`, $`\sqrt{(12)} = (6)` in $`\mathbb{Z}`.
:::

You might ask whether the name is unique now: that is, if $`\mathbb{V}(I) = \mathbb{V}(J)`, does it follow that $`I = J`?
The answer is unfortunately no: the counterexample can be found in just $`\mathbb{A}^1`.
It is $$`\mathbb{V}(x) = \mathbb{V}(x^2).`
In other words, the set of solutions to $`x = 0` is the same as the set of solutions to $`x^2 = 0`.

Well, that's stupid.
We want an operation which takes the ideal $`(x^2)` and makes it into the ideal $`(x)`.
The way to do so is using the radical of an ideal.

:::DEFINITION
Let $`R` be a ring.
The *radical* of an ideal $`I \subseteq R`, denoted $`\sqrt I`, is defined by $$`\sqrt I = \left\{ r \in R \mid r^m \in I \text{ for some integer } m \ge 1 \right\}.`
If $`I = \sqrt I`, we say the ideal $`I` itself is *radical*.
:::

For example, $`\sqrt{(x^2)} = (x)`.
You may like to take the time to verify that $`\sqrt I` is actually an ideal.

:::REMARK "Number theoretic motivation"
This is actually the same as the notion of "radical" in number theory.
In $`\mathbb{Z}`, the radical of an ideal $`(n)` corresponds to just removing all the duplicate prime factors, so for example $$`\sqrt{(12)} = (6).`
In particular, if you try to take $`\sqrt{(6)}`, you just get $`(6)` back; you don't squeeze out any new prime factors.

This is actually true more generally, and there is a nice corresponding alternate definition: for any ideal $`I`, we have $$`\sqrt I = \bigcap_{I \subseteq \mathfrak{p} \text{ prime}} \mathfrak{p}.`
:::

:::aside
The radical is {name}`Ideal.radical` and the property of being one's own radical is {name}`Ideal.IsRadical`; the intersection-of-primes description is {name}`Ideal.radical_eq_sInf`.
:::

Here are the immediate properties you should know.

:::PROPOSITION "Properties of radical"
In any ring:

- If $`I` is an ideal, then $`\sqrt I` is always a radical ideal.
- Prime ideals are radical.
- For $`I \subseteq \mathbb{C}[x_1, \dots, x_n]` we have $`\mathbb{V}(I) = \mathbb{V}(\sqrt I)`.
:::

:::PROOF
These are all obvious.

- If $`f^m \in \sqrt I` then $`f^{mn} \in I`, so $`f \in \sqrt I`.
- If $`f^n \in \mathfrak{p}` for a prime $`\mathfrak{p}`, then either $`f \in \mathfrak{p}` or $`f^{n-1} \in \mathfrak{p}`, and in the latter case we may continue by induction.
- We have $`f(x_1, \dots, x_n) = 0` if and only if $`f(x_1, \dots, x_n)^m = 0` for some integer $`m`.
:::

The last bit makes sense: you would never refer to $`x = 0` as $`x^2 = 0`, and hence we would always want to call $`\mathbb{V}(x^2)` just $`\mathbb{V}(x)`.
With this, we obtain a theorem called Hilbert's Nullstellensatz.

:::THEOREM "Hilbert's Nullstellensatz"
Given an affine variety $`V = \mathbb{V}(I)`, the set of polynomials which vanish on all points of $`V` is precisely $`\sqrt I`.
Thus if $`I` and $`J` are ideals in $`\mathbb{C}[x_1, \dots, x_n]`, then $$`\mathbb{V}(I) = \mathbb{V}(J) \text{ if and only if } \sqrt I = \sqrt J.`
:::

In other words

:::MORAL
Radical ideals in $`\mathbb{C}[x_1, \dots, x_n]` correspond exactly to $`n`-dimensional affine varieties.
:::

The proof of Hilbert's Nullstellensatz is given in the problems (via the Rabinowitsch trick); for now it is worth remarking that it relies essentially on the fact that $`\mathbb{C}` is _algebraically closed_.
For example, it is false in $`\mathbb{R}[x]`, with $`(x^2 + 1)` being a maximal ideal with empty vanishing set.

:::aside
This is exactly Mathlib's {name}`MvPolynomial.vanishingIdeal_zeroLocus_eq_radical`: the ideal of polynomials vanishing on the zero locus of $`I` is the radical of $`I`.
It is stated for `[IsAlgClosed K]` with finitely many variables `[Finite σ]`, which is precisely the algebraic-closedness hypothesis the theorem cannot do without — over $`\mathbb{R}` it fails.
The recovered polynomials themselves are the {name}`MvPolynomial.vanishingIdeal` of the {name}`MvPolynomial.zeroLocus`, and the two maps form a Galois connection, {name}`MvPolynomial.zeroLocus_vanishingIdeal_galoisConnection`.
:::

# Pictures of varieties in the affine line

:::PROTOTYPE
Finite sets of points (in fact these are the only nontrivial examples).
:::

Let's first draw some pictures.
In what follows I'll draw $`\mathbb{C}` as a straight line… sorry.

First of all, let's look at just the complex line $`\mathbb{A}^1`.
What are the various varieties on it?
For starters, we have a single point $`9 \in \mathbb{C}`, generated by $`(x - 9)`.

:::figure "figures/algebraic-geometry/affine-line-x9.svg"
The closed set $`\mathbb{V}(x - 9)` is a single point of the affine line $`\mathbb{A}^1`.
:::

Another example is the point $`4`.
And in fact, if we like we can get an ideal consisting of just these two points; consider $`\mathbb{V}\left( (x - 4)(x - 9) \right)`.

:::figure "figures/algebraic-geometry/affine-line-4-9.svg"
The closed set $`\mathbb{V}\left( (x - 4)(x - 9) \right) = \{4, 9\}` on $`\mathbb{A}^1`.
:::

In general, in $`\mathbb{A}^1` you can get finitely many points $`\left\{ a_1, \dots, a_n \right\}` by just taking $$`\mathbb{V}\left( (x - a_1)(x - a_2) \dots (x - a_n) \right).`
On the other hand, you can't get the set $`\{0, 1, 2, \dots\}` as an affine variety; the only polynomial vanishing on all those points is the zero polynomial.
In fact, you can convince yourself that these are the only affine varieties, with two exceptions:

- The entire line $`\mathbb{A}^1` is given by $`\mathbb{V}(0)`, and
- The empty set is given by $`\mathbb{V}(1)`.

:::EXERCISE
Show that these are the only varieties of $`\mathbb{A}^1`.
(Let $`\mathbb{V}(I)` be the variety and pick a $`0 \neq f \in I`.)
:::

As you might correctly guess, we have:

:::THEOREM "Intersections and unions of varieties"
1. The intersection of affine varieties (even infinitely many) is an affine variety.
2. The union of finitely many affine varieties is an affine variety.

In fact we have $$`\bigcap_\alpha \mathbb{V}(I_\alpha) = \mathbb{V}\left( \sum_\alpha I_\alpha \right) \qquad\text{and}\qquad \bigcup_{k=1}^n \mathbb{V}(I_k) = \mathbb{V}\left( \bigcap_{k=1}^n I_k \right).`
:::

You are welcome to prove this easy result yourself.

:::REMARK
Part (a) is a little misleading in that the sum $`I + J` need not be radical: take for example $`I = (y - x^2)` and $`J = (y)` in $`\mathbb{C}[x, y]`, where $`x \in \sqrt{I + J}` and $`x \notin I + J`.
But in part (b) for radical ideals $`I` and $`J`, the intersection $`I \cap J` is radical.
:::

As another easy result concerning the relation between the ideal and variety, we have:

:::PROPOSITION "$\\mathbb{V}(-)$ is inclusion reversing"
If $`I \subseteq J` then $`\mathbb{V}(I) \supseteq \mathbb{V}(J)`.
Thus $`\mathbb{V}(-)` is _inclusion-reversing_.
:::

:::QUESTION
Verify this.
:::

Thus, bigger ideals correspond to smaller varieties.

These results will be used a lot throughout the chapter, so it would be useful for you to be comfortable with the inclusion-reversing nature of $`\mathbb{V}`.

:::EXERCISE
Some quick exercises to help you be more familiar with the concepts.

1. Let $`I = (y - x^2)` and $`J = (x + 1, y + 2)`. What is $`\mathbb{V}(I)` and $`\mathbb{V}(J)`?
2. What is the ideal $`K` such that $`\mathbb{V}(K)` is the union of the parabola $`y = x^2` and the point $`(-1, -2)`?
3. Let $`L = (y - 1)`. What is $`\mathbb{V}(L)`?
4. The intersection $`\mathbb{V}(I) \cap \mathbb{V}(L)` consist of two points $`(1, 1)` and $`(-1, 1)`. What's the ideal corresponding to it, in terms of $`I` and $`L`?
5. What is $`\mathbb{V}(I \cap L)`? What about $`\mathbb{V}(I L)`?
:::

:::QUESTION
Note that the intersection of infinitely many ideals is still an ideal, but the union of infinitely many affine varieties may not be an affine variety.

Consider $`I_k = (x - k)` in $`\mathbb{C}[x]`, and take the infinite intersection $`I = \bigcap_{k \in \mathbb{N}} I_k`.
What is $`\mathbb{V}(I)` and $`\bigcup_{k \in \mathbb{N}} \mathbb{V}(I_k)`?
:::

# Prime ideals correspond to irreducible affine varieties

:::PROTOTYPE
$`(xy)` corresponds to the union of two lines in $`\mathbb{A}^2`.
:::

Note that most of the affine varieties of $`\mathbb{A}^1`, like $`\{4, 9\}`, are just unions of the simplest "one-point" ideals.
To ease our classification, we can restrict our attention to the case of _irreducible_ varieties:

:::DEFINITION
A variety $`V` is *irreducible* if it cannot be written as the union of two proper sub-varieties $`V = V_1 \cup V_2`.
:::

:::ABUSE
Warning: in other literature, irreducible is part of the definition of variety.
:::

:::EXAMPLE "Irreducible varieties of the affine line"
The irreducible varieties of $`\mathbb{A}^1` are:

- the empty set $`\mathbb{V}(1)`,
- a single point $`\mathbb{V}(x - a)`, and
- the entire line $`\mathbb{A}^1 = \mathbb{V}(0)`.
:::

:::EXAMPLE "The union of two axes"
Let's take a non-prime ideal in $`\mathbb{C}[x, y]`, such as $`I = (xy)`.
Its vanishing set $`\mathbb{V}(I)` is the union of two lines $`x = 0` and $`y = 0`.
So $`\mathbb{V}(I)` is reducible.
:::

In general:

:::THEOREM "Prime iff irreducible"
Let $`I` be a radical ideal, and $`V = \mathbb{V}(I)` a nonempty variety.
Then $`I` is prime if and only if $`V` is irreducible.
:::

:::PROOF
First, assume $`V` is irreducible; we'll show $`I` is prime.
Let $`f, g \in \mathbb{C}[x_1, \dots, x_n]` so that $`fg \in I`.
Then $`V` is a subset of the union $`\mathbb{V}(f) \cup \mathbb{V}(g)`; actually, $`V = \left( V \cap \mathbb{V}(f) \right) \cup \left( V \cap \mathbb{V}(g) \right)`.
Since $`V` is irreducible, we may assume $`V = V \cap \mathbb{V}(f)`, hence $`f` vanishes on all of $`V`.
So $`f \in I`.

The reverse direction is similar.
:::

:::aside
Prime and maximal ideals are {name}`Ideal.IsPrime` and {name}`Ideal.IsMaximal`.
The correspondence above is the geometric shadow of the fact that, in the {name}`PrimeSpectrum` of the next chapter, the irreducible closed subsets are exactly the closures of prime ideals.
:::

# Pictures in the affine plane and space

:::PROTOTYPE
Various curves and hypersurfaces.
:::

With this notion, we can now draw pictures in "complex affine plane", $`\mathbb{A}^2`.
What are the irreducible affine varieties in it?

As we saw in the previous discussion, naming irreducible affine varieties in $`\mathbb{A}^2` amounts to naming the prime ideals of $`\mathbb{C}[x, y]`.
Here are a few.

- The ideal $`(0)` is prime. $`\mathbb{V}(0)` as usual corresponds to the entire plane.
- The ideal $`(x - a, y - b)` is prime, since $`\mathbb{C}[x, y] / (x - a, y - b) \cong \mathbb{C}` is an integral domain.
  (In fact, since $`\mathbb{C}` is a field, the ideal $`(x - a, y - b)` is _maximal_.)
  The vanishing set of this is $`\mathbb{V}(x - a, y - b) = \{ (a, b) \} \in \mathbb{C}^2`, so these ideals correspond to a single point.
- Let $`f(x, y)` be an irreducible polynomial, like $`y - x^2`.
  Then $`(f)` is a prime ideal! Here $`\mathbb{V}(I)` is a "degree one curve".

By using some polynomial algebra (again you're welcome to check this; Euclidean algorithm), these are in fact the only prime ideals of $`\mathbb{C}[x, y]`.
Here's a picture.

:::figure "figures/algebraic-geometry/affine-parabola-point.svg"
The prime ideal $`(y - x^2)` cuts out a curve, while the maximal ideal $`(x - 1, y + 2)` is a single point off it.
:::

As usual, you can make varieties which are just unions of these irreducible ones.
For example, if you wanted the variety consisting of a parabola $`y = x^2` plus the point $`(20, 15)` you would write $$`\mathbb{V} \left( (y - x^2)(x - 20), (y - x^2)(y - 15) \right).`

The picture in $`\mathbb{A}^3` is harder to describe.
Again, you have points $`\mathbb{V}(x - a, y - b, z - c)` corresponding to be zero-dimensional points $`(a, b, c)`, and two-dimensional surfaces $`\mathbb{V}(f)` for each irreducible polynomial $`f` (for example, $`x + y + z = 0` is a plane).
But there are more prime ideals, like $`\mathbb{V}(x, y)`, which corresponds to the intersection of the planes $`x = 0` and $`y = 0`: this is the one-dimensional $`z`-axis.
It turns out there is no reasonable way to classify the "one-dimensional" varieties; they correspond to "irreducible curves".

Thus, as Ravi Vakil {cite}`ref:vakil` says: the purely algebraic question of determining the prime ideals of $`\mathbb{C}[x, y, z]` has a fundamentally geometric answer.

# Maximal ideals

:::PROTOTYPE
All maximal ideals are $`(x_1 - a_1, \dots, x_n - a_n)`.
:::

Recall that bigger ideals correspond to smaller varieties.

As the above pictures might have indicated, the smallest varieties are _single points_.
Moreover, as you might guess from the name, the biggest ideals are the _maximal ideals_.
As an example, all ideals of the form $$`\left( x_1 - a_1, \dots, x_n - a_n \right)`
are maximal, since the quotient $$`\mathbb{C}[x_1, \dots, x_n] / \left( x_1 - a_1, \dots, x_n - a_n \right) \cong \mathbb{C}`
is a field.
The question is: are all maximal ideals of this form?

The answer is in the affirmative.

:::THEOREM "Weak Nullstellensatz, phrased with maximal ideals"
Every maximal ideal of $`\mathbb{C}[x_1, \dots, x_n]` is of the form $`(x_1 - a_1, \dots, x_n - a_n)`.
:::

The proof of this is surprisingly nontrivial, so we won't include it here yet; see {cite}`ref:vakil`.
Again this uses the fact that $`\mathbb{C}` is algebraically closed.
(For example $`(x^2 + 1)` is a maximal ideal of $`\mathbb{R}[x]`.)
Thus:

:::MORAL
Over $`\mathbb{C}`, maximal ideals correspond to single points.
:::

Consequently, our various ideals over $`\mathbb{C}` correspond to various flavors of affine varieties:

- a *radical ideal* is an *affine variety*;
- a *prime ideal* is an *irreducible variety*;
- a *maximal ideal* is a *single point*;
- _any_ ideal is a … *scheme*?

There's one thing I haven't talked about: what's the last entry?

# Motivating schemes with non-radical ideals

One of the most elementary motivations for the scheme is that we would like to use them to count multiplicity.
That is, consider the intersection $$`\mathbb{V}(y - x^2) \cap \mathbb{V}(y) \subseteq \mathbb{A}^2.`
This is the intersection of the parabola with the tangent $`x`-axis.

:::figure "figures/algebraic-geometry/affine-parabola-origin.svg"
The parabola $`\mathbb{V}(y - x^2)` meets the tangent $`x`-axis at the origin.
:::

Unfortunately, as a variety, it is just a single point!
However, we want to think of this as a "double point": after all, in some sense it has multiplicity $`2`.
You can detect this when you look at the ideals: $$`(y - x^2) + (y) = (x^2, y)`
and thus, if we blithely ignore taking the radical, we get $$`\mathbb{C}[x, y] / (x^2, y) \cong \mathbb{C}[\varepsilon] / (\varepsilon^2).`
So the ideals in question are noticing the presence of a double point.

In order to encapsulate this, we need a more refined object than a variety, which (at the end of the day) is just a set of points; it's not possible using topology alone to encode more information (there is only one topology on a single point!).
This refined object is the _scheme_.

:::aside
The scheme-theoretic replacement for "the points of an affine variety" is the {name}`PrimeSpectrum` of a ring — _all_ of its prime ideals, not just the maximal ones — carrying the Zariski topology of the next chapter.
Passing from the coordinate ring $`\mathbb{C}[x_1, \dots, x_n]/I` to `PrimeSpectrum` of the quotient is what lets a non-radical ideal like $`(x^2, y)` remember the doubled point that the bare set forgets.
:::

# Problems

:::PROBLEM
Show that $`I \subseteq \sqrt I` and $`\sqrt I \cap \sqrt J = \sqrt{I J} \subseteq \sqrt{I \cap J}`, for two ideals $`I` and $`J`.
:::

:::PROBLEM "Real varieties are principal"
Show that a _real_ affine variety $`V \subseteq \mathbb{A}_\mathbb{R}^n` can always be written in the form $`\mathbb{V}(f)`.
(Hint: squares are nonnegative.)
:::

:::PROBLEM "Complex varieties can't be empty"
Prove that if $`I` is a proper ideal in $`\mathbb{C}[x_1, \dots, x_n]` then $`\mathbb{V}(I) \neq \varnothing`.
(Hint: this is actually an equivalent formulation of the Weak Nullstellensatz.)
:::

:::PROBLEM "Rabinowitsch trick"
Show that Hilbert's Nullstellensatz in $`n` dimensions follows from the Weak Nullstellensatz.
(Hint: use the weak Nullstellensatz on $`n + 1` dimensions.
Given $`f` vanishing on everything, consider $`x_{n+1} f - 1`.)
:::
