import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.GradedAlgebra.HomogeneousLocalization
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Topology
import Mathlib.LinearAlgebra.Projectivization.Basic
import Mathlib.Topology.Compactification.OnePoint.ProjectiveLine
import Mathlib.Data.Complex.Basic

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Projective varieties" =>

%%%
file := "Projective-varieties"
%%%

Having studied affine varieties in $`\mathbb{A}^n`, we now consider $`\mathbb{CP}^n`.
We will also make it into a baby ringed space in the same way as with $`\mathbb{A}^n`.

# Graded rings

:::PROTOTYPE
$`\mathbb{C}[x_0, \dots, x_n]` is a graded ring.
:::

We first take the time to state what a graded ring is, just so that we have this language to use (now and later).

:::DEFINITION
A *graded ring* $`R` is a ring with the following additional structure: as an abelian group, it decomposes as $$`R = \bigoplus_{d \ge 0} R^d`
where $`R^0`, $`R^1`, …, are abelian groups.
The ring multiplication has the property that if $`r \in R^d` and $`s \in R^e`, we have $`rs \in R^{d+e}`.
Elements of an $`R^d` are called *homogeneous elements*; we write "$`d = \deg r`" to mean "$`r \in R^d`".

We denote by $`R^+` the ideal $`R \setminus R^0` generated by the homogeneous elements of nonzero degree, and call it the *irrelevant ideal*.
:::

:::REMARK
For experts: all our graded rings are commutative with $`1`.
:::

:::EXAMPLE "Examples of graded rings"
1. The ring $`\mathbb{C}[x]` is graded by degree: as abelian groups, $`\mathbb{C}[x] \cong \mathbb{C} \oplus x\mathbb{C} \oplus x^2\mathbb{C} \oplus \dots`.
2. More generally, the polynomial ring $`\mathbb{C}[x_0, \dots, x_n]` is graded by degree.
:::

:::ABUSE
The notation $`\deg r` is abusive in the case $`r = 0`; note that $`0 \in R^d` for every $`d`.
So it makes sense to talk about "the" degree of $`r` except when $`r = 0`.
:::

We will frequently refer to homogeneous ideals:

:::DEFINITION
An ideal $`I \subseteq \mathbb{C}[x_0, \dots, x_n]` is *homogeneous* if it can be written as $`I = (f_1, \dots, f_m)` where each $`f_i` is a homogeneous polynomial.
:::

:::REMARK
If $`I` and $`J` are homogeneous, then so are $`I + J`, $`IJ`, $`I \cap J`, $`\sqrt I`.
:::

:::LEMMA "Graded quotients are graded too"
Let $`I` be a homogeneous ideal of a graded ring $`R`.
Then $$`R/I = \bigoplus_{d \ge 0} R^d / (R^d \cap I)`
realizes $`R/I` as a graded ring.
:::

Since these assertions are just algebra, we omit their proofs here.

:::REMARK
In some other books, a homogeneous ideal (or *graded ideal*) is sometimes equivalently defined as an ideal $`I` such that $`I = \bigoplus_{d \ge 0} (R^d \cap I)` as abelian group.
In fact, we can verify that graded ideals are precisely the ones such that the quotient is naturally graded.
:::

:::EXAMPLE "Example of a graded quotient ring"
Let $`R = \mathbb{C}[x, y]` and set $`I = (x^3, y^2)`.
Let $`S = R/I`.
Then $$`S^0 = \mathbb{C}, \quad S^1 = \mathbb{C} x \oplus \mathbb{C} y, \quad S^2 = \mathbb{C} x^2 \oplus \mathbb{C} xy, \quad S^3 = \mathbb{C} x^2 y, \quad S^d = 0 \ (d \ge 4).`
So in fact $`S = R/I` is graded, and is a six-dimensional $`\mathbb{C}`-vector space.
:::

# The ambient space

:::PROTOTYPE
Perhaps $`\mathbb{V}_+(x^2 + y^2 - z^2)`.
:::

The set of points we choose to work with is $`\mathbb{CP}^n` this time, which for us can be thought of as the set of $`n`-tuples $$`\left( x_0 : x_1 : \dots : x_n \right)`
not all zero, up to scaling.
Equivalently, it is the set of lines through the origin in $`\mathbb{C}^{n+1}`.
Projective space is defined in full in the earlier chapter on topological constructions, and you should refer there if you aren't familiar with projective space.

The right way to think about it is "$`\mathbb{A}^n` plus points at infinity":

:::DEFINITION
We define the set $$`U_i = \left\{ (x_0 : \dots : x_n) \mid x_i \neq 0 \right\} \subseteq \mathbb{CP}^n.`
These are called the *standard affine charts*.
:::

The name comes from:

:::EXERCISE "Mandatory"
Give a natural bijection from $`U_i` to $`\mathbb{A}^n`.
Thus we can think of $`\mathbb{CP}^n` as the affine set $`U_i` plus "points at infinity".
:::

:::REMARK
In fact, these charts $`U_i` make $`\mathbb{CP}^n` with its usual topology into a complex manifold with holomorphic transition functions.
:::

:::EXAMPLE "Colloquially, $\\mathbb{CP}^1 = \\mathbb{A}^1 \\cup \\{\\infty\\}$"
The space $`\mathbb{CP}^1` consists of pairs $`(s : t)`, which you can think of as representing the complex number $`z/1`.
In particular $`U_1 = \{ (z : 1) \}` is basically another copy of $`\mathbb{A}^1`.
There is only one new point, $`(1 : 0)`.
:::

However, like before we want to impose a Zariski topology on it.
For concreteness, let's consider $`\mathbb{CP}^2 = \left\{ (x_0 : x_1 : x_2) \right\}`.
We wish to consider zero loci in $`\mathbb{CP}^2`, just like we did in affine space, and hence obtain a notion of a projective variety.

But this isn't so easy: for example, the function "$`x_0`" is not a well-defined function on points in $`\mathbb{CP}^2` because $`(x_0 : x_1 : x_2) = (5x_0 : 5x_1 : 5x_2)`!
So we'd love to consider these "pseudo-functions" that still have zero loci.
These are just the homogeneous polynomials $`f`, because $`f` is homogeneous of degree $`d` if and only if $$`f(\lambda x_0, \dots, \lambda x_n) = \lambda^d f(x_0, \dots, x_n).`
In particular, the relation "$`f(x_0, \dots, x_n) = 0`" is well-defined if $`f` is homogeneous.
Thus, we can say:

:::DEFINITION
If $`f` is homogeneous, we can then define its *vanishing locus* as $$`\mathbb{V}_+(f) = \left\{ (x_0 : \dots : x_n) \mid f(x_0, \dots, x_n) = 0 \right\}.`
:::

The homogeneous condition is really necessary.
For example, to require "$`x_0 - 1 = 0`" makes no sense, since the points $`(1 : 1 : 1)` and $`(2015 : 2015 : 2015)` are the same.

It's trivial to verify that homogeneous polynomials do exactly what we want; hence we can now define:

:::DEFINITION
A *projective variety* in $`\mathbb{CP}^n` is the common zero locus of an arbitrary collection of homogeneous polynomials in $`n + 1` variables.
:::

::::EXAMPLE "A conic in $\\mathbb{CP}^2$, or a cone in $\\mathbb{C}^3$"
Let's try to picture the variety $$`\mathbb{V}_+(x^2 + y^2 - z^2) \subseteq \mathbb{CP}^2`
which consists of the points $`[x : y : z]` such that $`x^2 + y^2 = z^2`.
If we view this as subspace of $`\mathbb{C}^3` (i.e. by thinking of $`\mathbb{CP}^2` as the set of lines through the origin), then we get a "cone".

:::figure "figures/algebraic-geometry/proj-var-cone.svg"
:::

If we take the standard affine charts now, we obtain:

- At $`x = 1`, we get a hyperbola $`\mathbb{V}(1 + y^2 - z^2)`.
- At $`y = 1`, we get a hyperbola $`\mathbb{V}(1 + x^2 - z^2)`.
- At $`z = 1`, we get a circle $`\mathbb{V}(x^2 + y^2 - 1)`.

That said, over $`\mathbb{C}` a hyperbola and circle are the same thing; I'm cheating a little by drawing $`\mathbb{C}` as one-dimensional, just like last chapter.
::::

:::QUESTION
Draw the intersection of the cone above with the $`z = 1` plane, and check that you do in fact get a circle.
(This geometric picture will be crucial later.)
:::

# Homogeneous ideals

Now, the next thing we want to do is define $`\mathbb{V}_+(I)` for an ideal $`I`.
Of course, we again run into an issue with things like $`x_0 - 1` not making sense.

The way out of this is to use only _homogeneous_ ideals.

:::DEFINITION
If $`I` is a homogeneous ideal, we define $$`\mathbb{V}_+(I) = \{ x \mid f(x) = 0 \; \forall f \in I\}.`
:::

:::EXERCISE
Show that the notion "$`f(x) = 0 \; \forall f \in I`" is well-defined for a homogeneous ideal $`I`.
:::

So, we would hope for a Nullstellensatz-like theorem which bijects the homogeneous radical ideals to projective varieties.
Unfortunately:

:::EXAMPLE "Irrelevant ideal"
To crush some dreams and hopes, consider the ideal $$`I = (x_0, x_1, \dots, x_n).`
This is called the *irrelevant ideal*; it is a homogeneous radical yet $`\mathbb{V}_+(I) = \varnothing`.
:::

However, other than the irrelevant ideal:

:::THEOREM "Homogeneous Nullstellensatz"
Let $`I` and $`J` be homogeneous ideals.

1. If $`\mathbb{V}_+(I) = \mathbb{V}_+(J) \neq \varnothing` then $`\sqrt I = \sqrt J`.
2. If $`\mathbb{V}_+(I) = \varnothing`, then either $`I = (1)` or $`\sqrt I = (x_0, x_1, \dots, x_n)`.

Thus there is a natural bijection between:

- projective varieties in $`\mathbb{CP}^n`, and
- homogeneous radical ideals of $`\mathbb{C}[x_0, \dots, x_n]` except for the irrelevant ideal.
:::

:::PROOF
For the first part, let $`V = \mathbb{V}_+(I)` and $`W = \mathbb{V}_+(J)` be projective varieties in $`\mathbb{CP}^n`.
We can consider them as _affine varieties_ in $`\mathbb{A}^{n+1}` by using the interpretation of $`\mathbb{CP}^n` as lines through the origin in $`\mathbb{C}^n`.

Algebraically, this is done by taking the homogeneous ideals $`I, J \subseteq \mathbb{C}[x_0, \dots, x_n]` and using the same ideals to cut out _affine_ varieties $`V_{\text{aff}} = \mathbb{V}(I)` and $`W_{\text{aff}} = \mathbb{V}(J)` in $`\mathbb{A}^{n+1}`.
For example, the cone $`x^2 + y^2 - z^2 = 0` is a conic (a one-dimensional curve) in $`\mathbb{CP}^2`, but can also be thought of as a cone (which is a two-dimensional surface) in $`\mathbb{A}^3`.

Then for (a), we have $`V_{\text{aff}} = W_{\text{aff}}`, so $`\sqrt I = \sqrt J`.

For (b), either $`V_{\text{aff}}` is empty or it is just the origin of $`\mathbb{A}^{n+1}`, so the Nullstellensatz implies either $`I = (1)` or $`\sqrt I = (x_0, \dots, x_n)` as desired.
:::

Projective analogues of the earlier theorem on intersections and unions of varieties hold verbatim for projective varieties as well.

# As ringed spaces

:::PROTOTYPE
The regular functions on $`\mathbb{CP}^1` minus a point are exactly those of the form $`P(s/t)`.
:::

Now, let us make every projective variety $`V` into a baby ringed space.
We already have the set of points, a subset of $`\mathbb{CP}^n`.

The topology is defined as follows.

:::DEFINITION
We endow $`\mathbb{CP}^n` with the *Zariski topology* by declaring the sets of the form $`\mathbb{V}_+(I)`, where $`I` is a homogeneous ideal, to be the closed sets.

Every projective variety $`V` then inherits the Zariski topology from its parent $`\mathbb{CP}^n`.
The *distinguished open sets* $`D(f)` are $`V \setminus \mathbb{V}_+(f)`.
:::

Thus every projective variety $`V` is now a topological space.
It remains to endow it with a sheaf of regular functions $`\mathcal{O}_V`.
To do this we have to be a little careful.
In the affine case we had a nice little ring of functions, the coordinate ring $`\mathbb{C}[x_0, \dots, x_n] / I`, that we could use to provide the numerator and denominators.
So, it seems natural to then define:

:::DEFINITION
The *homogeneous coordinate ring* of a projective variety $`V = \mathbb{V}_+(I) \subseteq \mathbb{CP}^n`, where $`I` is homogeneous radical, is defined as the ring $$`\mathbb{C}[V] = \mathbb{C}[x_0, \dots, x_n] / I.`
:::

:::REMARK
Unlike the affine case, an element of $`\mathbb{C}[V]` no longer correspond to a function from $`V` to $`\mathbb{C}`; nevertheless, it is a function from $`\mathbb{V}(I) \subseteq \mathbb{A}^{n+1}` to $`\mathbb{C}`.
:::

However, when we define a rational function we must impose a new requirement that the numerator and denominator are the same degree.

:::DEFINITION
Let $`U \subseteq V` be an open set of a projective variety $`V`.
A *rational function* $`\phi` on a projective variety $`V` is a quotient $`f/g`, where $`f, g \in \mathbb{C}[V]`, and $`f` and $`g` are homogeneous of the same degree, and $`\mathbb{V}_+(g) \cap U = \varnothing`.
In this way we obtain a function $`\phi \colon U \to \mathbb{C}`.
:::

:::EXAMPLE "Examples of rational functions"
Let $`V = \mathbb{CP}^1` have coordinates $`(s : t)`.

1. If $`U = V`, then constant functions $`c/1` are the only rational functions on $`U`.
2. Now let $`U_1 = V \setminus \{(1 : 0)\}`.
   Then, an example of a regular function is $$`\frac{s^2 + 9t^2}{t^2} = \left( \frac st \right)^2 + 9.`
   If we think of $`U_1` as $`\mathbb{C}` (i.e. $`\mathbb{CP}^1` minus an infinity point, hence like $`\mathbb{A}^1`) then really this is just the function $`x^2 + 9`.
:::

Then we can repeat the same definition as before:

:::DEFINITION
Let $`U \subseteq V` be an open set of a projective variety $`V`.
We say a function $`\phi \colon U \to \mathbb{C}` is a *regular function* if for every point $`p`, we can find an open set $`U_p` containing $`p` and a rational function $`f_p/g_p` on $`U_p` such that $$`\phi(x) = \frac{f_p(x)}{g_p(x)} \qquad \forall x \in U_p.`
In particular, we require $`U_p \cap \mathbb{V}_+(g_p) = \varnothing`.
We denote the set of all regular functions on $`U` by $`\mathcal{O}_V(U)`.
:::

Of course, the rational functions from the previous example are examples of regular functions as well.
This completes the definition of a projective variety $`V` as a baby ringed space.

# Examples of regular functions

Naturally, I ought to tell you what the regular functions on distinguished open sets are; this is an analog to the affine result from last time.

:::THEOREM "Regular functions on distinguished open sets for projective varieties"
Let $`V` be a projective variety, and let $`g \in \mathbb{C}[V]` be homogeneous of _positive degree_ (thus $`g` is nonconstant).
Then $$`\mathcal{O}_V(D(g)) = \left\{ \frac{f}{g^r} \mid f \in \mathbb{C}[V] \text{ homogeneous of degree } r\deg g \right\}.`
:::

What about the case $`g = 1`?
A similar result holds, but we need the assumption that $`V` is irreducible.

:::DEFINITION
A projective variety $`V` is irreducible if it can't be written as the union of two proper (projective) sub-varieties.
:::

:::THEOREM "Only constant regular functions on projective space"
Let $`V` be an _irreducible_ projective variety.
Then the only regular functions on $`V` are constant, thus we have $$`\mathcal{O}_V(V) \cong \mathbb{C}.`
This relies on the fact that $`\mathbb{C}` is algebraically closed.
:::

Proofs of these are omitted for now.

:::EXAMPLE "Irreducibility is needed above"
The reason we need $`V` irreducible is otherwise we could, for example, take $`V` to be the union of two points; in this case $`\mathcal{O}_V(V) \cong \mathbb{C}^{\oplus 2}`.
:::

:::REMARK
It might seem strange that $`\mathcal{O}_V(D(g))` behaves so differently when $`g = 1`.
One vague explanation is that in a projective variety, a distinguished open $`D(g)` looks much like an affine variety if $`\deg g > 0`.
For example, in $`\mathbb{CP}^1` we have $`\mathbb{CP}^1 \setminus \{0\} \cong \mathbb{A}^1` (where $`\cong` is used in a sense that I haven't made precise).
Thus the claim becomes related to the corresponding affine result.
But if $`\deg g = 0` and $`g \neq 0`, then $`D(g)` is the entire projective variety, which does not look affine, and thus the analogy breaks down.
:::

:::EXAMPLE "Regular functions on $\\mathbb{CP}^1$"
Let $`V = \mathbb{CP}^1`, with coordinates $`(s : t)`.

1. By the theorem above, if $`U_1` is the standard affine chart omitting the point $`(1 : 0)`, we have $`\mathcal{O}_V(U_1) = \left\{ \frac{f}{t^n} \mid \deg f = n \right\}`.
   One can write this as $$`\mathcal{O}_V(U_1) \cong \left\{ P(s/t) \mid P \in \mathbb{C}[x] \right\} \cong \mathcal{O}_{\mathbb{A}^1}(\mathbb{A}^1).`
   This conforms with our knowledge that $`U_1` "looks very much like $`\mathbb{A}^1`".
2. As $`V` is irreducible, $`\mathcal{O}_V(V) = \mathbb{C}`: there are no nonconstant functions on $`\mathbb{CP}^1`.
:::

:::EXAMPLE "Regular functions on $\\mathbb{CP}^2$"
Let $`\mathbb{CP}^2` have coordinates $`(x : y : z)` and let $`U_0 = \left\{ (x : y : 1) \in \mathbb{CP}^2 \right\}` be the distinguished open set $`D(z)`.
Then in the same vein, $$`\mathcal{O}_{\mathbb{CP}^2}(U_0) = \left\{ \frac{P(x, y)}{z^n} \mid \deg P = n \right\} \cong \left\{ P(x/z, y/z) \mid P \in \mathbb{C}[x, y] \right\}.`
:::

# Formalization

:::LEANCOMPANION
:::

## Graded rings

A grading of a ring by an index monoid is Mathlib's `GradedRing` (a `GradedAlgebra` when a base field is remembered): the data of the homogeneous pieces $`R^d` as submodules, together with a `DirectSum.Decomposition` witnessing $`R = \bigoplus_d R^d` and the multiplicativity $`R^d \cdot R^e \subseteq R^{d+e}`.
For a polynomial ring the grading is by degree: a polynomial is homogeneous of degree $`n` exactly when `MvPolynomial.IsHomogeneous` holds, each variable $`x_i` has degree $`1`, and a constant has degree $`0`.

```lean
example (σ : Type*) (φ : MvPolynomial σ ℂ) (n : ℕ) : Prop := φ.IsHomogeneous n

example (σ : Type*) (i : σ) :
    (MvPolynomial.X i : MvPolynomial σ ℂ).IsHomogeneous 1 :=
  MvPolynomial.isHomogeneous_X ℂ i

example (σ : Type*) (c : ℂ) :
    (MvPolynomial.C c : MvPolynomial σ ℂ).IsHomogeneous 0 :=
  MvPolynomial.isHomogeneous_C σ c
```

Homogeneity of an ideal is `Ideal.IsHomogeneous`, and such ideals are bundled as `HomogeneousIdeal`; the induced grading on the quotient is what makes `HomogeneousIdeal` the right notion, and the irrelevant ideal $`R^+` is `HomogeneousIdeal.irrelevant`.

```lean
example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] (I : Ideal A) : Prop := I.IsHomogeneous 𝒜

example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] :
    HomogeneousIdeal 𝒜 := HomogeneousIdeal.irrelevant 𝒜
```

The defining feature of the grading is that a product of homogeneous elements is homogeneous, with degrees adding.
Show that in $`\mathbb{C}[x_0, \dots, x_n]` the product $`x_i x_j` is homogeneous of degree $`2`.

```lean
example {σ : Type*} (i j : σ) :
    (MvPolynomial.X i * MvPolynomial.X j :
      MvPolynomial σ ℂ).IsHomogeneous 2 := by
  sorry
```

:::solution
```lean
example {σ : Type*} (i j : σ) :
    (MvPolynomial.X i * MvPolynomial.X j :
      MvPolynomial σ ℂ).IsHomogeneous 2 :=
  (MvPolynomial.isHomogeneous_X ℂ i).mul (MvPolynomial.isHomogeneous_X ℂ j)
```
:::

## The ambient space

Projective space $`\mathbb{CP}^n` — nonzero vectors up to scaling, equivalently lines through the origin — is Mathlib's `Projectivization`, with a point named from a nonzero vector by `Projectivization.mk`.
The defining scaling relation is `Projectivization.mk_eq_mk_iff'`: two nonzero vectors give the same point exactly when one is a scalar multiple of the other.

```lean
example (K V : Type*) [DivisionRing K] [AddCommGroup V] [Module K V] : Type _ :=
  Projectivization K V

example {K V : Type*} [DivisionRing K] [AddCommGroup V] [Module K V]
    (v : V) (hv : v ≠ 0) : Projectivization K V := Projectivization.mk K v hv

example {K V : Type*} [DivisionRing K] [AddCommGroup V] [Module K V]
    (v w : V) (hv : v ≠ 0) (hw : w ≠ 0) :
    Projectivization.mk K v hv = Projectivization.mk K w hw
      ↔ ∃ a : K, a • w = v :=
  Projectivization.mk_eq_mk_iff' K v w hv hw
```

The points-of-a-graded-ring analogue of the affine spectrum is Mathlib's `ProjectiveSpectrum` of a graded algebra: it consists of the _relevant_ homogeneous prime ideals — those not containing the irrelevant ideal — which is exactly the "throw away the origin" bookkeeping that projective space needs.
The projective vanishing locus $`\mathbb{V}_+(-)` is `ProjectiveSpectrum.zeroLocus`, and it is this Proj that carries the Zariski topology.

```lean
example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] : Type _ := ProjectiveSpectrum 𝒜

example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] (s : Set A) : Set (ProjectiveSpectrum 𝒜) :=
  ProjectiveSpectrum.zeroLocus 𝒜 s

recall {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] : TopologicalSpace (ProjectiveSpectrum 𝒜)
```

A caution about the point set $`\mathbb{CP}^n` itself: Mathlib puts a topology on `Projectivization` only in the projective-line case $`\mathbb{CP}^1`, transported from the one-point compactification `OnePoint K` through `OnePoint.equivProjectivization`.
The Zariski topology used throughout this chapter lives on `ProjectiveSpectrum`, not on `Projectivization`.

```lean
example (K : Type*) [Field K] [DecidableEq K] :
    OnePoint K ≃ Projectivization K (Fin 2 → K) :=
  OnePoint.equivProjectivization K
```

The prototypical fact is that a point is unchanged under rescaling, so that $`(x_0 : \dots : x_n) = (5x_0 : \dots : 5x_n)`.
Show that scaling a nonzero vector by a nonzero scalar names the same point of projective space.

```lean
example {K V : Type*} [DivisionRing K] [AddCommGroup V] [Module K V]
    (v : V) (hv : v ≠ 0) (c : K) (hc : c ≠ 0) :
    Projectivization.mk K (c • v) (smul_ne_zero hc hv)
      = Projectivization.mk K v hv := by
  sorry
```

:::solution
```lean
example {K V : Type*} [DivisionRing K] [AddCommGroup V] [Module K V]
    (v : V) (hv : v ≠ 0) (c : K) (hc : c ≠ 0) :
    Projectivization.mk K (c • v) (smul_ne_zero hc hv)
      = Projectivization.mk K v hv := by
  rw [Projectivization.mk_eq_mk_iff']
  exact ⟨c, rfl⟩
```
:::

## Homogeneous ideals

The vanishing locus of an ideal has an adjoint, `ProjectiveSpectrum.vanishingIdeal`, recording the homogeneous ideal of "functions" vanishing on a set of points.
The two form a Galois connection, and in particular $`\mathbb{V}_+(-)` is inclusion-reversing.

```lean
example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜]
    (t : Set (ProjectiveSpectrum 𝒜)) : HomogeneousIdeal 𝒜 :=
  ProjectiveSpectrum.vanishingIdeal t
```

Show the inclusion-reversing property: if $`I \subseteq J` are homogeneous ideals then $`\mathbb{V}_+(J) \subseteq \mathbb{V}_+(I)`.

```lean
example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] (I J : HomogeneousIdeal 𝒜) (h : I ≤ J) :
    ProjectiveSpectrum.zeroLocus 𝒜 (J : Set A)
      ⊆ ProjectiveSpectrum.zeroLocus 𝒜 (I : Set A) := by
  sorry
```

:::solution
```lean
example {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubmonoidClass σ A]
    (𝒜 : ℕ → σ) [GradedRing 𝒜] (I J : HomogeneousIdeal 𝒜) (h : I ≤ J) :
    ProjectiveSpectrum.zeroLocus 𝒜 (J : Set A)
      ⊆ ProjectiveSpectrum.zeroLocus 𝒜 (I : Set A) :=
  ProjectiveSpectrum.zeroLocus_anti_mono_homogeneousIdeal 𝒜 h
```
:::

## As ringed spaces

The "quotient of two homogeneous elements of the same degree" is exactly the degree-zero part of a localization, and Mathlib packages it as `HomogeneousLocalization`: its elements are fractions $`f/g` with $`f`, $`g` homogeneous of matching degree, which is what makes them honest functions on the projective variety.
This is the commutative ring the structure sheaf of the projective spectrum assigns to a basic open, and `HomogeneousLocalization.val` sends such a fraction to its value in the ordinary localization.

```lean
example {ι A σ : Type*} [AddCommMonoid ι] [DecidableEq ι]
    [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
    (𝒜 : ι → σ) [GradedRing 𝒜] (x : Submonoid A) :
    Type _ := HomogeneousLocalization 𝒜 x

recall {ι A σ : Type*} [AddCommMonoid ι] [DecidableEq ι]
    [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
    (𝒜 : ι → σ) [GradedRing 𝒜] (x : Submonoid A) :
    CommRing (HomogeneousLocalization 𝒜 x)
```

Because these fractions add like fractions, taking the value commutes with addition.
Show that `HomogeneousLocalization.val` respects the ring addition.

```lean
example {ι A σ : Type*} [AddCommMonoid ι] [DecidableEq ι]
    [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
    (𝒜 : ι → σ) [GradedRing 𝒜] (x : Submonoid A)
    (a b : HomogeneousLocalization 𝒜 x) : (a + b).val = a.val + b.val := by
  sorry
```

:::solution
```lean
example {ι A σ : Type*} [AddCommMonoid ι] [DecidableEq ι]
    [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
    (𝒜 : ι → σ) [GradedRing 𝒜] (x : Submonoid A)
    (a b : HomogeneousLocalization 𝒜 x) : (a + b).val = a.val + b.val :=
  HomogeneousLocalization.val_add a b
```
:::

## Examples of regular functions

The numerators appearing in these regular functions are homogeneous polynomials of a fixed degree, so a sum like $`s^2 + 9t^2` from the $`\mathbb{CP}^1` example is again homogeneous of that degree.
Show that $`s^2 + 9t^2` is homogeneous of degree $`2`, writing $`s = x_0` and $`t = x_1`.

```lean
example :
    (MvPolynomial.X 0 ^ 2 + MvPolynomial.C 9 * MvPolynomial.X 1 ^ 2 :
      MvPolynomial (Fin 2) ℂ).IsHomogeneous 2 := by
  sorry
```

:::solution
```lean
example :
    (MvPolynomial.X 0 ^ 2 + MvPolynomial.C 9 * MvPolynomial.X 1 ^ 2 :
      MvPolynomial (Fin 2) ℂ).IsHomogeneous 2 :=
  (MvPolynomial.isHomogeneous_X_pow 0 2).add
    (MvPolynomial.isHomogeneous_C_mul_X_pow 9 1 2)
```
:::
