import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.Algebra.Ring.Basic
import Mathlib.Algebra.Field.Defs
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Ideal.Maximal
import Mathlib.RingTheory.Ideal.Prime
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.UniqueFactorizationDomain.Defs
import Mathlib.RingTheory.UniqueFactorizationDomain.Basic
import Mathlib.Algebra.EuclideanDomain.Defs
import Mathlib.Algebra.EuclideanDomain.Int
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.SimpleRing.Basic

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Flavors of rings" =>

%%%
file := "Flavors-of-rings"
%%%


We continue our exploration of rings by considering some nice-ness properties that rings or ideals can satisfy, which will be valuable later on.
As before, number theory is interlaced as motivation.
I guess I can tell you at the outset what the completed table is going to look like, so you know what to expect.

:::table +header
* * Ring noun
  * Ideal adjective
  * Relation
* * PID
  * principal
  * $`R` is a PID $`\iff` $`R` is an integral domain, and every $`I` is principal
* * Noetherian ring
  * finitely generated
  * $`R` is Noetherian $`\iff` every $`I` is fin. gen.
* * field
  * maximal
  * $`R/I` is a field $`\iff` $`I` is maximal
* * integral domain
  * prime
  * $`R/I` is an integral domain $`\iff` $`I` is prime
:::

# Fields

:::PROTOTYPE
$`\mathbb{Q}` is a field, but $`\mathbb{Z}` is not.
:::

We already saw this definition last chapter: a field $`K` is a nontrivial ring for which every nonzero element is a unit.

In particular, there are only two ideals in a field: the ideal $`(0)`, which is maximal, and the entire field $`K`.

# Integral domains

:::PROTOTYPE
$`\mathbb{Z}` is an integral domain.
:::

In practice, we are often not so lucky that we have a full-fledged field.
Now it would be nice if we could still conclude the zero product property: if $`ab = 0` then either $`a = 0` or $`b = 0`.
If our ring is a field, this is true: if $`b \neq 0`, then we can multiply by $`b^{-1}` to get $`a = 0`.
But many other rings we consider like $`\mathbb{Z}` and $`\mathbb{Z}[x]` also have this property, despite not having division.

Not all rings though: in $`\mathbb{Z}/15\mathbb{Z}`, $$`3 \cdot 5 \equiv 0 \pmod{15}.`
If $`a, b \neq 0` but $`ab = 0` then we say $`a` and $`b` are *zero divisors* of the ring $`R`.
So we give a name to such rings.

:::DEFINITION
A nontrivial ring with no zero divisors is called an *integral domain*.{margin}[Some authors abbreviate this to "domain", notably Artin.]
:::

:::QUESTION
Show that a field is an integral domain.
:::

:::EXERCISE "Cancellation in integral domains"
Suppose $`ac = bc` in an integral domain, and $`c \neq 0`.
Show that $`a = b`.
(There is no $`c^{-1}` to multiply by, so you have to use the definition.)
:::

:::EXAMPLE "Examples of integral domains"
Every field is an integral domain, so all the previous examples apply.
In addition:

1. $`\mathbb{Z}` is an integral domain, but it is not a field.
2. $`\mathbb{R}[x]` is not a field, since there is no polynomial $`P(x)` with $`xP(x) = 1`.
   However, $`\mathbb{R}[x]` is an integral domain, because if $`P(x)Q(x) = 0` then one of $`P` or $`Q` is zero.
3. $`\mathbb{Z}[x]` is also an example of an integral domain.
   In fact, $`R[x]` is an integral domain for any integral domain $`R` (why?).
4. $`\mathbb{Z}/n\mathbb{Z}` is a field (hence integral domain) exactly when $`n` is prime.
   When $`n` is not prime, it is a ring but not an integral domain.

The trivial ring $`0` is _not_ considered an integral domain.
:::

At this point, we go ahead and say:

:::DEFINITION
An integral domain where all ideals are principal is called a *principal ideal domain (PID)*.
:::

Recall that the ideal $`(a, b)` is the ring-analog of the gcd operation, so essentially what this definition is saying is that: if any family of elements $`\{a_i\}` is taken, then the ideal generated by all of the $`a_i` is in fact generated by a single element $`a`.

In other words,

:::MORAL
In a PID, you can take the gcd of any collection of elements.
:::

The ring $`\mathbb{Z}/6\mathbb{Z}` is an example of a ring which is a principal ideal ring, but not an integral domain.
As we alluded to earlier, we will never really use "principal ideal ring" in any real way: we typically will want to strengthen it to PID.

# Prime ideals

:::PROTOTYPE
$`(5)` is a prime ideal of $`\mathbb{Z}`.
:::

We know that every integer can be factored (up to sign) as a unique product of primes; for example $`15 = 3 \cdot 5` and $`-10 = -2 \cdot 5`.
You might remember the proof involves the so-called Bézout's lemma, which essentially says that $`(a, b) = (\gcd(a, b))`; in other words we've carefully used the fact that $`\mathbb{Z}` is a PID.

It turns out that for general rings, the situation is not as nice as factoring elements because most rings are not PID's.
The classic example of something going wrong is $$`6 = 2 \cdot 3 = (1 - \sqrt{-5})(1 + \sqrt{-5})` in $`\mathbb{Z}[\sqrt{-5}]`.
Nonetheless, we can sidestep the issue and talk about factoring _ideals_: somehow the example $`10 = 2 \cdot 5` should be $`(10) = (2) \cdot (5)`, which says "every multiple of $`10` is the product of a multiple of $`2` and a multiple of $`5`".
I'd have to tell you then how to multiply two ideals, which I do in the chapter on unique factorization.

Let's at least figure out what primes are.
In $`\mathbb{Z}`, we have that $`p \neq 1` is prime if whenever $`p \mid xy`, either $`p \mid x` or $`p \mid y`.
We port over this definition to our world of ideals.

:::DEFINITION
A _proper_ ideal $`I \subsetneq R` is a *prime ideal* if whenever $`xy \in I`, either $`x \in I` or $`y \in I`.
:::

The condition that $`I` is proper is analogous to the fact that we don't consider $`1` to be a prime number.

:::EXAMPLE "Examples and non-examples of prime ideals"
1. The ideal $`(7)` of $`\mathbb{Z}` is prime.
2. The ideal $`(8)` of $`\mathbb{Z}` is not prime, since $`2 \cdot 4 = 8`.
3. The ideal $`(x)` of $`\mathbb{Z}[x]` is prime.
4. The ideal $`(x^2)` of $`\mathbb{Z}[x]` is not prime, since $`x \cdot x = x^2`.
5. The ideal $`(3, x)` of $`\mathbb{Z}[x]` is prime.
   This is actually easiest to see using the prime-iff-quotient-is-a-domain theorem below.
6. The ideal $`(5) = 5\mathbb{Z} + 5i\mathbb{Z}` of $`\mathbb{Z}[i]` is not prime, since the elements $`3 + i` and $`3 - i` have product $`10 \in (5)`, yet neither is itself in $`(5)`.
:::

:::REMARK
Ideals have the nice property that they get rid of "sign issues".
For example, in $`\mathbb{Z}`, do we consider $`-3` to be a prime?
When phrased with ideals, this annoyance goes away: $`(-3) = (3)`.
More generally, for a ring $`R`, talking about ideals lets us ignore multiplication by a unit.
(Note that $`-1` is a unit in $`\mathbb{Z}`.)
:::

:::EXERCISE
What do you call a ring $`R` for which the zero ideal $`(0)` is prime?
:::

We also have:

:::THEOREM "Prime ideal ⟺ quotient is integral domain"
An ideal $`I` is prime if and only if $`R/I` is an integral domain.
:::

:::EXERCISE "Mandatory"
Convince yourself the theorem is true; it is just definition chasing.
(A possible start is to consider $`R = \mathbb{Z}` and $`I = (15)`.)
:::

I now must regrettably inform you that unique factorization is still not true even with the notion of a "prime" ideal (though again I haven't told you how to multiply two ideals yet).
But it will become true with some additional assumptions that will arise in algebraic number theory (relevant buzzword: Dedekind domain).

# Maximal ideals

:::PROTOTYPE
The ideal $`(x, 5)` is maximal in $`\mathbb{Z}[x]`, by quotienting.
:::

Here's another flavor of an ideal.

:::DEFINITION
A proper ideal $`I` of a ring $`R` is *maximal* if it is not contained in any other proper ideal.
:::

:::EXAMPLE "Examples of maximal ideals"
1. The ideal $`I = (7)` of $`\mathbb{Z}` is maximal, because if an ideal $`J` contains $`7` and an element $`n` not in $`I` it must contain $`\gcd(7, n) = 1`, and hence $`J = \mathbb{Z}`.
2. The ideal $`(x)` is _not_ maximal in $`\mathbb{Z}[x]`, because it's contained in $`(x, 5)` (among others).
3. On the other hand, $`(x, 5)` is indeed maximal in $`\mathbb{Z}[x]`.
   This is actually easiest to verify using the maximal-iff-quotient-is-a-field theorem below.
4. Also, $`(x)` is maximal in $`\mathbb{C}[x]`, again appealing to the theorem below.
:::

:::EXERCISE
What do you call a ring $`R` for which the zero ideal $`(0)` is maximal?
:::

There's an analogous theorem to the one for prime ideals.

:::THEOREM "I maximal ⟺ R/I field"
An ideal $`I` is maximal if and only if $`R/I` is a field.
:::

:::PROOF
A ring is a field if and only if $`(0)` is the only maximal ideal.
So this follows by the inclusion-preserving bijection between ideals of $`R/I` and ideals of $`R` containing $`I` (a problem from the previous chapter).
:::

:::COROLLARY "Maximal ideals are prime"
If $`I` is a maximal ideal of a ring $`R`, then $`I` is prime.
:::

:::PROOF
If $`I` is maximal, then $`R/I` is a field, hence an integral domain, so $`I` is prime.
:::

In practice, because modding out by generated ideals is pretty convenient, this is a very efficient way to check whether an ideal is maximal.

:::EXAMPLE "Modding out in ℤ[x]"
1. This instantly implies that $`(x, 5)` is a maximal ideal in $`\mathbb{Z}[x]`, because if we mod out by $`x` and $`5` in $`\mathbb{Z}[x]`, we just get $`\mathbb{F}_5`, which is a field.
2. On the other hand, modding out by just $`x` gives $`\mathbb{Z}`, which is an integral domain but not a field; that's why $`(x)` is prime but not maximal.
:::

As we saw, any maximal ideal is prime.
But now note that $`\mathbb{Z}` has the special property that all of its nonzero prime ideals are also maximal.
It's with this condition and a few other minor conditions that you get a so-called _Dedekind domain_ where prime factorization of ideals _does_ work.
More on that later.

# Field of fractions

:::PROTOTYPE
$`\operatorname{Frac}(\mathbb{Z}) = \mathbb{Q}`.
:::

As long as we are here, we take the time to introduce a useful construction that turns any integral domain into a field.

:::DEFINITION
Given an integral domain $`R`, we define its *field of fractions* or *fraction field* $`\operatorname{Frac}(R)` as follows: it consists of elements $`a/b`, where $`a, b : R` and $`b \neq 0`.
We set $`a/b \sim c/d` if and only if $`bc = ad`.
Addition and multiplication is defined by $$`\frac{a}{b} + \frac{c}{d} = \frac{ad + bc}{bd}` $$`\frac{a}{b} \cdot \frac{c}{d} = \frac{ac}{bd}.`
:::

In fact everything you know about $`\mathbb{Q}` basically carries over by analogy.
You can prove if you want that this is indeed a field, but considering how comfortable we are that $`\mathbb{Q}` is well-defined, I wouldn't worry about it…

:::DEFINITION
Let $`k` be a field.
We define $`k(x) = \operatorname{Frac}(k[x])` (read "$`k` of $`x`"), and call it the *field of rational functions*.
:::

:::EXAMPLE "Examples of fraction fields"
1. By _definition_, $`\operatorname{Frac}(\mathbb{Z}) = \mathbb{Q}`.
2. The field $`\mathbb{R}(x)` consists of rational functions in $`x`: $$`\mathbb{R}(x) = \left\{ \frac{f(x)}{g(x)} \mid f, g : \mathbb{R}[x] \right\}.`
   For example, $`\frac{2x}{x^2 - 3}` might be a typical element.
:::

:::EXAMPLE "Gaussian rationals"
Just like we defined $`\mathbb{Z}[i]` by abusing notation, we can also write $`\mathbb{Q}(i) = \operatorname{Frac}(\mathbb{Z}[i])`.
Officially, it should consist of $$`\mathbb{Q}(i) = \left\{ \frac{f(i)}{g(i)} \mid g(i) \neq 0 \right\}` for polynomials $`f` and $`g` with rational coefficients.
But since $`i^2 = -1` this just leads to $$`\mathbb{Q}(i) = \left\{ \frac{a + bi}{c + di} \mid a, b, c, d : \mathbb{Q}, (c, d) \neq (0, 0) \right\}.`
And since $`\frac{1}{c + di} = \frac{c - di}{c^2 + d^2}` we end up with $$`\mathbb{Q}(i) = \{ a + bi \mid a, b : \mathbb{Q} \}.`
:::

# Unique factorization domains (UFD's)

:::PROTOTYPE
$`\mathbb{Z}` and polynomial rings in general.
:::

Here is one stray definition that will be important for those with a number-theoretic inclination.
Over the positive integers, we have a fundamental theorem of arithmetic, stating that every integer is uniquely the product of prime numbers.

We can even make an analogous statement in $`\mathbb{Z}` or $`\mathbb{Z}[i]`, if we allow representations like $`6 = (-2)(-3)` and so on.
The trick is that we only consider everything _up to units_; so $`6 = (-2)(-3) = 2 \cdot 3` are considered the same.

The general definition goes as follows.

:::DEFINITION
A nonzero non-unit of an integral domain $`R` is *irreducible* if it cannot be written as the product of two non-units.

An integral domain $`R` is a *unique factorization domain* if every nonzero non-unit of $`R` can be written as the product of irreducible elements, which is unique up to multiplication by units.
:::

:::QUESTION
Verify that $`\mathbb{Z}` is a UFD.
:::

:::EXAMPLE "Examples of UFD's"
1. Fields are a "degenerate" example of UFD's: every nonzero element is a unit, so there is nothing to check.
2. $`\mathbb{Z}` is a UFD.
   The irreducible elements are $`p` and $`-p`, for example $`5` or $`-17`.
3. $`\mathbb{Q}[x]` is a UFD: polynomials with rational coefficients can be uniquely factored, up to scaling by constants (as the units of $`\mathbb{Q}[x]` are just the rational numbers).
4. $`\mathbb{Z}[x]` is a UFD.
5. The Gaussian integers $`\mathbb{Z}[i]` turns out to be a UFD too (and this will be proved in the chapters on algebraic number theory).
6. $`\mathbb{Z}[\sqrt{-5}]` is the classic non-example of a UFD: one may write $$`6 = 2 \cdot 3 = (1 - \sqrt{-5})(1 + \sqrt{-5})` but each of $`2`, $`3`, $`1 \pm \sqrt{-5}` is irreducible.
   (It turns out the right way to fix this is by considering prime _ideals_ instead, and this is one big motivation for algebraic number theory.)
7. Theorem we won't prove: if $`R` is a UFD, so is $`R[x]` (and hence by induction so is $`R[x, y]`, $`R[x, y, z]`, …).
:::

We have the following theorem:

:::THEOREM
Let $`R` be a PID.
Then $`R` is a UFD.
:::

If we look at the non-example above: $$`6 = 2 \cdot 3 = (1 - \sqrt{-5})(1 + \sqrt{-5})`
The failure of $`\mathbb{Z}[\sqrt{-5}]` to be a UFD here is reflected by the fact that we cannot decompose any factor into further irreducible factors; indeed, the ideal $$`(2, 1 + \sqrt{-5})` is not principal — there is no element that is the gcd of $`2` and $`1 + \sqrt{-5}`.

In a similar manner, we can prove that a PID is a UFD, assuming a decomposition into irreducible factors exists.

# Extra: Euclidean domains

This chapter will not be used later on, but it is of historical interest.

Recall that a PID is a ring where you can take the gcd of any family of elements.

We all know that the most popular algorithm to compute the gcd of two elements in $`\mathbb{Z}` is the Euclidean algorithm:

- Start with two integers $`a` and $`b`.
- If either of $`a` and $`b` is $`0`, we're done.
  The gcd is the nonzero element.
- Otherwise, assume $`|a| \geq |b|`, divide $`a` by $`b` to get some remainder $`r` such that $`|r| < |b|`, replace $`a` with $`r`, and continue the algorithm.

This algorithm is very efficient — it can be proven that the algorithm only takes logarithmically many steps in the size of $`a` and $`b` — for instance, if $`a` and $`b` are on the order of $`10^{100}`, at worst $`500` steps are needed.

Naturally, the following questions are raised:

> On which rings can we perform the same algorithm?

We will see that we can in fact do it on several rings!
For example, the ring of Gaussian integers $`\mathbb{Z}[i]`, the Eisenstein integers $`\mathbb{Z}[\omega]`, and so on.

If we look at the algorithm description above, what makes the algorithm work?
It's the absolute value $`|\cdot|` which is used to compare the magnitude of two numbers, and this absolute value satisfies two conditions:

- It outputs nonnegative integer values — that way, the algorithm will eventually terminate.
- For any two ring elements $`a` and $`b`, where $`b \neq 0`, there exist some $`q` such that $`r = a - qb` has smaller absolute value than $`b`.

So, naturally, for any ring with a similar integer-valued function, we can perform the algorithm.
We call a function $`\operatorname{Norm} \colon R \to \mathbb{Z}_{\geq 0}` that satisfies the two conditions above an *Euclidean norm*, and an integral domain $`R` that has a norm an *Euclidean domain*.

:::EXAMPLE "The ring of Gaussian integers is a Euclidean domain"
On $`\mathbb{Z}[i]`, the usual norm $$`|a + bi| = a^2 + b^2` is a Euclidean norm.

Indeed, for any elements $`a` and $`b` with $`b \neq 0`, we can compute the remainder $`r` by dividing $`a` by $`b`, let $`q` be the Gaussian integer that is closest to $`\frac{a}{b}` (that is, $`|\frac{a}{b} - q|` is minimized) and let $`r = a - bq`, then it can be proven that $`|r| < |b|`.

The proof is done by showing $`|\frac{a}{b} - q| < 1` — if we look at the lattice of points contained in $`\mathbb{Z}[i]` embedded in the complex plane, then for any value of $`\frac{a}{b} : \mathbb{C}`, rounding it to the nearest integer will move it by at most $`\frac{\sqrt{2}}{2} < 1`.
:::

:::figure "figures/abstract-algebra/zi-rounding.svg"
Rounding a complex number (red) to the nearest Gaussian integer (blue lattice) moves it by at most $`\frac{\sqrt{2}}{2}`.
:::

:::EXAMPLE "The ring of Eisenstein integers is a Euclidean domain"
Similarly, let $`\omega = \frac{1 + \sqrt{3}i}{2}` (that is $`\omega^3 = -1`), then $`\mathbb{Z}[\omega]` is a Euclidean domain with the usual norm $$`|a + bi| = a^2 + b^2` or equivalently $$`|a + b\omega| = a^2 + ab + b^2.`
:::

:::EXAMPLE "The ring ℤ[√11] is a Euclidean domain"
As before.
This time, the natural norm{margin}[See the later discussion of norms and traces for the explanation why this norm is the natural one.] will be: $$`\operatorname{Norm}_{\mathbb{Q}(\sqrt{11})/\mathbb{Q}}(a + b\sqrt{11}) = (a + b\sqrt{11})(a - b\sqrt{11}) = a^2 - 11b^2.`
Since we need a Euclidean norm, we will take $`\operatorname{Norm}(a + b\sqrt{11}) = |a^2 - 11b^2|`.

Given two elements $`a` and $`b` in $`\mathbb{Z}[\sqrt{11}]` with $`b \neq 0`, we will try to compute $`r` such that $`\operatorname{Norm}(r) < \operatorname{Norm}(b)` as $`r = a - qb` as before.

This time around, we cannot draw $`\mathbb{Z}[\sqrt{11}]` as a lattice of points — it is dense in $`\mathbb{R}` — so, each point $`a + b\sqrt{11}` will be drawn at the coordinate $`(a + b\sqrt{11}, a - b\sqrt{11})`.

Instead of a ball (as in imaginary quadratic fields, that is, $`\mathbb{Q}(\sqrt{-d})` for integer $`d`), the set of points with norm $`1` forms a hyperbola.

As such, rounding to the nearest point is not always the best way — nevertheless, it can be proven (by exhaustive case checking, similar to the case of $`\mathbb{Z}[i]`) that for every value of $`\frac{a}{b} : \mathbb{Q}(\sqrt{11})`, there is some $`q : \mathbb{Z}[\sqrt{11}]` such that $`\operatorname{Norm}(\frac{a}{b} - q) < 1`.
Thus $`\operatorname{Norm}` is a Euclidean norm.
:::

:::figure "figures/abstract-algebra/zsqrt11-norm.svg"
The lattice $`\mathbb{Z}[\sqrt{11}]`, plotting $`a + b\sqrt{11}` at $`(a + b\sqrt{11}, a - b\sqrt{11})`; the red hyperbolas bound the points of norm less than $`1`.
:::

That having said, sometimes the natural norm of a Euclidean domain need not be Euclidean. $`\mathbb{Z}[\frac{1 + \sqrt{69}}{2}]` is the first example.

:::EXAMPLE "ℚ[x] is a Euclidean domain"
Similarly, in $`\mathbb{Q}[x]` we can let the norm be the degree of a polynomial — the polynomial division with remainder algorithm will take care of computing the gcd.
:::

Back to the topic of PID.
In a Euclidean domain, you can compute the gcd of any two elements.
What about an infinite family of elements?

Turns out the situation is very nice:

:::PROPOSITION
A Euclidean domain is a PID.
:::

Actually, we don't need to provide an explicit algorithm to compute the gcd of an infinite family of elements — of course any such algorithm cannot terminate in a finite amount of time! — but we only need to show the gcd exists, we can cheat our way out.

Note that in the Euclidean algorithm, the norm of the elements _keeps decreasing_ until one of the elements becomes $`0`.
So, if we're given an arbitrary family of elements, we take the ideal generated by these elements — certainly the gcd is inside that ideal — and we _take the nonzero element with the smallest norm_.
This is the gcd.

With that intuition in mind, we formalize our proof:

::::PROOF
Let $`I` be any ideal.
We need to show $`I` is principal.

Let $`a` be a nonzero element with smallest norm in $`I` — such an element exists because $`\mathbb{Z}_{\geq 0}` is well-ordered.

:::QUESTION
Show that, for every other element $`b \in I`, then $`a \mid b`.
:::

Thus, $`I = (a)`, we're done.
::::

:::EXAMPLE "The ring ℤ[(1 + √(−19))/2] is not a Euclidean domain"
Let $`R = \mathbb{Z}[\frac{1 + \sqrt{-19}}{2}]`.

With the above example in mind, what can we say about this ring?

This is in fact a principal ideal domain (we will not prove it here), but there is in fact no Euclidean norm on this ring.
:::

We will prove the above claim.
The general plan is:

- Show that the existence of a Euclidean norm implies the existence of something that we call a *universal side divisor*.
- Show that $`R` has no universal side divisor.
- Thus, $`R` cannot have a Euclidean norm.

First, look at the examples above of $`\mathbb{Z}[i]` and $`\mathbb{Z}[\omega]`.
We see that the units are the elements with the smallest norm.

So far, nothing useful — every ring has the unit $`1`.
Next, we look at the elements with the next-smallest norm:

- In $`\mathbb{Z}[i]`, the element $`1 + i` has norm $`2`, and is an element with smallest norm that is not $`0` or a unit.
  (The other elements are $`\pm 1 \pm i`.)
- In $`\mathbb{Z}[\omega]`, the units are $`\{\pm 1, \pm \omega, \pm(\omega - 1)\}` with norm $`1`.
  An element with next-smallest norm is $`1 + \omega` with norm $`3`.

Now, in order to proceed with the proof, we have to define a *side divisor*.
Recall that $`b` is a divisor of $`a` if there is some $`q` such that $`a = bq`.
We say $`b` is a *side divisor* (read: "almost divisor") of $`a` if there is some $`q` such that the remainder $`a - bq` is either $`0` or a unit.

:::EXAMPLE
In $`\mathbb{Z}[i]`, consider $`b = 3 + i`.
The set of numbers $`a` for which $`b \mid a` forms a sublattice; if we add a unit to these values of $`a`, we get the set of numbers $`a` for which $`b` is a side divisor of $`a`, thus giving a picture to the concept of "almost divisor".
:::

:::figure "figures/abstract-algebra/zi-multiples.svg"
The multiples of $`b = 3 + i` in $`\mathbb{Z}[i]`, marked in red.
:::

:::figure "figures/abstract-algebra/zi-side-divisors.svg"
The points of which $`3 + i` is a side divisor (blue) or an exact divisor (red).
:::

Finally, we define a *universal side divisor* to be a number $`b` such that $`b` is a side divisor of every element $`a : R`.

:::EXAMPLE
Checking similarly, in $`\mathbb{Z}[i]`, then $`2 + i` and $`1 + i` are universal side divisors.
:::

:::figure "figures/abstract-algebra/zi-universal-side.svg"
The universal side divisor $`2 + i`: every point is at distance $`1` from a multiple $`r(2 + i)` (arrows), or is itself a multiple (red).
:::

Now, the connection between the two concepts considered above.

:::LEMMA
In a Euclidean domain, the smallest-norm nonzero element $`b` that is not a unit is a universal side divisor.
:::

:::PROOF
Just run the Euclidean algorithm between any number and $`b` for one step, the remainder must be $`0` or a unit.
:::

And finally,

:::PROPOSITION
There is no universal side divisor in $`R`.
:::

:::PROOF
All numbers are of the form $`\frac{a}{2} + \frac{b\sqrt{-19}}{2}` where $`a` and $`b` have the same parity.
The absolute value of a complex number, defined as $`\frac{a^2}{4} + \frac{19b^2}{4}`, is multiplicative and is greater than $`1` for all numbers in $`\mathbb{Z}[\frac{1 + \sqrt{-19}}{2}]` except for $`-1, 0, 1`, which have absolute values of $`1, 0, 1`, respectively.
Since there are no numbers in the ring with absolute values greater than $`0` and less than $`1`, all numbers in the ring with absolute values greater than $`1` do not have multiplicative inverses in the ring.
Hence, the only units are $`1` and $`-1`.

When we multiply all the elements in the ring by $`x`, the distances between pairs of elements in the complex plane multiplies by $`|x|`.
Initially, the distances between pairs of elements were at least $`1`.

- If $`x` is real and $`|x| \geq 2`, then $`xR` doesn't contain any elements of the form $`a + \frac{\sqrt{-19}}{2}`, so $`x` is not a universal side divisor.
- If $`x` is non-real and $`|x| \geq 2`, then an element in $`xR` can only be real if it was previously non-real.
  This means the elements of $`xR` on the real axis have absolute value of at least $`2|\frac{1 + \sqrt{-19}}{2}| = 2\sqrt{5} \geq 4`.
  Hence, $`x` is not a side divisor of $`2`, so $`x` is not a universal side divisor.

Since $`R` does not have a universal side divisor, $`R` is not a Euclidean domain.
:::

# Problems

Not olympiad problems, but again the spirit is very close to what you might see in an olympiad.

:::PROBLEM
Consider the ring $$`\mathbb{Q}[\sqrt{2}] = \{ a + b\sqrt{2} \mid a, b : \mathbb{Q} \}.`
Is it a field?
:::

:::PROBLEM "Homomorphisms from fields are injective"
Let $`K` be a field and $`R` a nontrivial ring.
Prove that any homomorphism $`\psi \colon K \to R` is injective.{margin}[Note that $`\psi` cannot be the zero map for us, since we require $`\psi(1_K) = 1_R`. You sometimes find different statements in the literature.]
:::

:::PROBLEM "Pre-image of prime ideals"
Suppose $`\phi \colon R \to S` is a ring homomorphism, and $`I \subseteq S` is a prime ideal.
Prove that $`\phi^{\mathrm{pre}}(I)` is prime as well.
:::

:::PROBLEM (chili := 1)
Let $`R` be an integral domain with finitely many elements.
Prove that $`R` is a field.
:::

:::PROBLEM "Krull's theorem"
Let $`R` be a ring and $`J` a proper ideal.

1. Prove that if $`R` is Noetherian, then $`J` is contained in a maximal ideal $`I`.
2. Use Zorn's lemma (from the Set Theory chapters) to prove the result even if $`R` isn't Noetherian.
:::

:::PROBLEM "Spec k[x]"
Describe the prime ideals of $`\mathbb{C}[x]` and $`\mathbb{R}[x]`.
:::

:::PROBLEM
How many prime ideals of $`\mathbb{Z}[\sqrt{2017}]` are _not_ maximal ideals?
:::

:::PROBLEM
Let $`R` denote the set of rational numbers $`q` such that, when $`q` is written in lowest terms, the denominator is not a multiple of $`5`.
Then $`R` is a ring (under the usual addition and multiplication).
Classify all the ideals of $`R`.
Which of these ideals are prime / maximal?
:::

:::PROBLEM
Recall that a ring $`R` is *Artinian* if it satisfies the *descending chain condition*: there does _not_ exist an infinite descending chain of ideals $`I_1 \supsetneq I_2 \supsetneq I_3 \supsetneq \dots`.

1. Show that if $`R` is Artinian and an integral domain, then it's a field.
2. More generally, show that every prime ideal in an Artinian ring is maximal.
:::

# Formalization

:::LEANCOMPANION
:::

## Fields

A field is `Field K`: a nontrivial commutative ring in which every nonzero element is a unit.
One consequence the chapter highlights is that a field has only two ideals, $`(0)` and the whole ring.
Show it with `Ideal.eq_bot_or_top` — every ideal `I` of a field is either `⊥` or `⊤`.

```lean
example (K : Type*) [Field K] (I : Ideal K) : I = ⊥ ∨ I = ⊤ := by
  sorry
```

:::solution
```lean
example (K : Type*) [Field K] (I : Ideal K) : I = ⊥ ∨ I = ⊤ :=
  I.eq_bot_or_top
```
:::

A related fact, one of the chapter's problems, is that any homomorphism out of a field into a nontrivial ring is injective.
That is packaged as `RingHom.injective`, resting on the fact just above: a field has no ideals besides `⊥` and `⊤`, so the kernel of any homomorphism out of it must collapse to `⊥`.

```lean
example (K R : Type*) [Field K] [Ring R] [Nontrivial R] (ψ : K →+* R) :
    Function.Injective ψ :=
  ψ.injective
```

## Integral domains

`IsDomain R` packages the predicate, and the zero-product property becomes `mul_eq_zero`.

```lean
example (R : Type*) [CommRing R] [IsDomain R] (a b : R)
    (h : a * b = 0) : a = 0 ∨ b = 0 := mul_eq_zero.mp h
```

The chapter's cancellation exercise — if $`ac = bc` with $`c \neq 0` in an integral domain, then $`a = b` — is `mul_right_cancel₀`, which is exactly the missing $`c^{-1}` made rigorous.

```lean
example (R : Type*) [CommRing R] [IsDomain R] (a b c : R)
    (hc : c ≠ 0) (h : a * c = b * c) : a = b := by
  sorry
```

:::solution
```lean
example (R : Type*) [CommRing R] [IsDomain R] (a b c : R)
    (hc : c ≠ 0) (h : a * c = b * c) : a = b :=
  mul_right_cancel₀ hc h
```
:::

`IsPrincipalIdealRing R` is the principal-ideals condition; pairing it with `IsDomain` records that $`R` is a PID.

```lean
recall : IsPrincipalIdealRing ℤ
recall : IsDomain ℤ
```

A field is automatically a domain.

```lean
recall (K : Type*) [Field K] : IsDomain K
```

## Prime ideals

`Ideal.IsPrime I` is the predicate that the quotient by $`I` is a domain (equivalently, the closure-under-products definition above).

```lean
example (R : Type*) [CommRing R] (I : Ideal R) [I.IsPrime] :
    IsDomain (R ⧸ I) := Ideal.Quotient.isDomain I
```

The chapter asks what you call a ring for which the zero ideal $`(0)` is prime — an integral domain.
Prove the forward half of that answer with `Ideal.isPrime_bot`: in any integral domain, `⊥` is a prime ideal.

```lean
example (R : Type*) [CommRing R] [IsDomain R] : (⊥ : Ideal R).IsPrime := by
  sorry
```

:::solution
```lean
example (R : Type*) [CommRing R] [IsDomain R] :
    (⊥ : Ideal R).IsPrime := Ideal.isPrime_bot
```
:::

## Maximal ideals

`Ideal.IsMaximal I` is the corresponding predicate; the quotient by a maximal ideal is a field.

```lean
noncomputable example (R : Type*) [CommRing R] (I : Ideal R)
    [I.IsMaximal] : Field (R ⧸ I) := Ideal.Quotient.field I
```

The corollary that maximal ideals are prime is `Ideal.IsMaximal.isPrime`.

```lean
example (R : Type*) [CommRing R] (I : Ideal R) [hI : I.IsMaximal] :
    I.IsPrime := hI.isPrime
```

The chapter's companion question — what you call a ring for which $`(0)` is maximal — is a field.
Prove that direction with `Ideal.bot_isMaximal`: in any field, `⊥` is a maximal ideal.

```lean
example (K : Type*) [Field K] : (⊥ : Ideal K).IsMaximal := by
  sorry
```

:::solution
```lean
example (K : Type*) [Field K] : (⊥ : Ideal K).IsMaximal :=
  Ideal.bot_isMaximal
```
:::

## Field of fractions

The field of fractions is `FractionRing R`, and `IsFractionRing R K` records that a field `K` *is* the fraction field of `R`.
The prototype $`\operatorname{Frac}(\mathbb{Z}) = \mathbb{Q}` is available as an instance.

```lean
example : IsFractionRing ℤ ℚ := inferInstance
```

An integral domain always embeds into its field of fractions.
For the prototype, show that the inclusion $`\mathbb{Z} \hookrightarrow \mathbb{Q}` — spelled `algebraMap ℤ ℚ`, the canonical ring homomorphism from `ℤ` into `ℚ` — is injective, via `IsFractionRing.injective`.

```lean
example : Function.Injective (algebraMap ℤ ℚ) := by
  sorry
```

:::solution
```lean
example : Function.Injective (algebraMap ℤ ℚ) :=
  IsFractionRing.injective ℤ ℚ
```
:::

## Unique factorization domains

`UniqueFactorizationMonoid R` is the multiplicative-monoid form of the condition, and `Irreducible` is the elementwise predicate.
The chapter's question is to verify that $`\mathbb{Z}` is a UFD; Mathlib already carries this as an instance, so `inferInstance` confirms it.

```lean
example : UniqueFactorizationMonoid ℤ := sorry
```

:::solution
```lean
example : UniqueFactorizationMonoid ℤ := inferInstance
```
:::

The theorem that every PID is a UFD is recorded as an instance too.

```lean
recall (R : Type*) [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R] : UniqueFactorizationMonoid R
```

## Euclidean domains

`EuclideanDomain` records the norm and the division algorithm; $`\mathbb{Z}` is the canonical example.

```lean
recall : EuclideanDomain ℤ
```

The chapter's proposition — a Euclidean domain is a PID — is already recorded as the instance `EuclideanDomain.to_principal_ideal_domain`, so `inferInstance` confirms it.
The well-ordering argument from the chapter is what justifies that instance mathematically: an element of least norm in a nonzero ideal generates it.

```lean
example (R : Type*) [EuclideanDomain R] : IsPrincipalIdealRing R := sorry
```

:::solution
```lean
example (R : Type*) [EuclideanDomain R] :
    IsPrincipalIdealRing R := inferInstance
```
:::
