import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.GroupTheory.QuotientGroup.Defs
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.GroupTheory.Coset.Card

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Homomorphisms and quotient groups" =>

%%%
file := "Homomorphisms-and-quotient-groups"
%%%


# Generators and group presentations

:::PROTOTYPE
$`D_{2n} = \langle r, s \mid r^n = s^2 = 1 \rangle`
:::

Let $`G` be a group.
Recall that for some element $`x : G`, we could consider the subgroup $$`\{\dots, x^{-2}, x^{-1}, 1, x, x^2, \dots\}` of $`G`.
Here's a more pictorial version of what we did: *put $`x` in a box, seal it tightly, and shake vigorously*.
Using just the element $`x`, we get a pretty explosion that produces the subgroup above.

What happens if we put two elements $`x`, $`y` in the box?
Among the elements that get produced are things like $$`xyxyx, \quad x^2 y^9 x^{-5} y^3, \quad y^{-2015}, \quad \dots`
Essentially, I can create any finite product of $`x`, $`y`, $`x^{-1}`, $`y^{-1}`.
This leads us to define:

:::DEFINITION
Let $`S` be a subset of $`G`.
The subgroup *generated* by $`S`, denoted $`\langle S \rangle`, is the set of elements which can be written as a finite product of elements in $`S` (and their inverses).
If $`\langle S \rangle = G` then we say $`S` is a set of *generators* for $`G`, as the elements of $`S` together create all of $`G`.
:::

The subgroup generated by a subset is `Subgroup.closure S`.

```lean -show
section
```

```lean
example (G : Type*) [Group G] (S : Set G)
    (x : G) (hx : x ∈ S) :
    x ∈ Subgroup.closure S :=
  Subgroup.subset_closure hx
```

:::EXERCISE
Why is the condition "and their inverses" not necessary if $`G` is a finite group?
(As usual, assume Lagrange's theorem.)
:::

:::EXAMPLE "ℤ is the infinite cyclic group"
Consider $`1` as an element of $`\mathbb{Z} = (\mathbb{Z}, +)`.
We see $`\langle 1 \rangle = \mathbb{Z}`, meaning $`\{1\}` generates $`\mathbb{Z}`.
It's important that $`-1`, the inverse of $`1` is also allowed: we need it to write all integers as the sum of $`1` and $`-1`.
:::

This gives us an idea for a way to try and express groups compactly.
Why not just write down a list of generators for the groups?
For example, we could write $$`\mathbb{Z} \cong \langle a \rangle` meaning that $`\mathbb{Z}` is just the group generated by one element.

There's one issue: the generators usually satisfy certain properties.
For example, consider $`\mathbb{Z}/100\mathbb{Z}`.
It's also generated by a single element $`x`, but this $`x` has the additional property that $`x^{100} = 1`.
This motivates us to write $$`\mathbb{Z}/100\mathbb{Z} = \langle x \mid x^{100} = 1 \rangle.`
I'm sure you can see where this is going.
All we have to do is specify a set of generators and *relations* between the generators, and say that two elements are equal if and only if you can get from one to the other using relations.
Such an expression is appropriately called a *group presentation*.

:::EXAMPLE "Dihedral group"
The dihedral group of order $`2n` has a presentation $$`D_{2n} = \langle r, s \mid r^n = s^2 = 1, rs = sr^{-1} \rangle.`
Thus each element of $`D_{2n}` can be written uniquely in the form $`r^\alpha` or $`sr^\alpha`, where $`\alpha = 0, 1, \dots, n-1`.
:::

:::EXAMPLE "Klein four group"
The *Klein four group*, isomorphic to $`\mathbb{Z}/2\mathbb{Z} \times \mathbb{Z}/2\mathbb{Z}`, is given by the presentation $$`\langle a, b \mid a^2 = b^2 = 1, ab = ba \rangle.`
:::

:::EXAMPLE "Free group"
The *free group on $`n` elements* is the group whose presentation has $`n` generators and no relations at all.
It is denoted $`F_n`, so $$`F_n = \langle x_1, x_2, \dots, x_n \rangle.`
In other words, $`F_2 = \langle a, b \rangle` is the set of strings formed by appending finitely many copies of $`a`, $`b`, $`a^{-1}`, $`b^{-1}` together.
:::

:::QUESTION
Notice that $`F_1 \cong \mathbb{Z}`.
:::

:::ABUSE
One might unfortunately notice that "subgroup generated by $`a` and $`b`" has exactly the same notation as the free group $`\langle a, b \rangle`.
We'll try to be clear based on context which one we mean.
:::

Presentations are nice because they provide a compact way to write down groups.
They do have some shortcomings, though.{margin}[Actually, determining whether two elements of a presentation are equal is undecidable. In fact, it is undecidable to even determine if a group is finite from its presentation.]

:::EXAMPLE "Presentations can look very different"
The same group can have very different presentations.
For instance consider $$`D_{2n} = \langle x, y \mid x^2 = y^2 = 1, (xy)^n = 1 \rangle.` (To see why this is equivalent, set $`x = s`, $`y = rs`.)
:::

```lean -show
end
```

# Homomorphisms

:::PROTOTYPE
The "mod out by $`100`" map, $`\mathbb{Z} \to \mathbb{Z}/100\mathbb{Z}`.
:::

How can groups talk to each other?

Two groups are "the same" if we can write an isomorphism between them.
And as we saw, two metric spaces are "the same" if we can write a homeomorphism between them.
But what's the group analogy of a continuous map?
We simply drop the "bijection" condition.

:::DEFINITION
Let $`G = (G, \star)` and $`H = (H, \ast)` be groups.
A *group homomorphism* is a map $`\phi \colon G \to H` such that for any $`g_1, g_2 : G` we have $$`\phi(g_1 \star g_2) = \phi(g_1) \ast \phi(g_2).` `MonoidHom G H` (notation `G →* H`) is a group homomorphism; the additive analog is `AddMonoidHom` (`G →+ H`).
Both bundle the function with the operation-respecting condition.

```lean -show
section
```

```lean
recall MonoidHom.map_mul {M N : Type*} [MulOne M]
    [MulOne N] (f : M →* N) (a b : M) :
    f (a * b) = f a * f b
```
:::

(Not to be confused with "homeomorphism" from last chapter: note the spelling.)

:::EXAMPLE "Examples of homomorphisms"
Let $`G` and $`H` be groups.

1. Any isomorphism $`G \to H` is a homomorphism.
   In particular, the identity map $`G \to G` is a homomorphism.
2. The *trivial homomorphism* $`G \to H` sends everything to $`1_H`.
3. There is a homomorphism from $`\mathbb{Z}` to $`\mathbb{Z}/100\mathbb{Z}` by sending each integer to its residue modulo $`100`.
4. There is a homomorphism from $`\mathbb{Z}` to itself by $`x \mapsto 10x` which is injective but not surjective.
5. There is a homomorphism from $`S_n` to $`S_{n+1}` by "embedding": every permutation on $`\{1, \dots, n\}` can be thought of as a permutation on $`\{1, \dots, n+1\}` if we simply let $`n+1` be a fixed point.
6. A homomorphism $`\phi \colon D_{12} \to D_6` is given by $`s_{12} \mapsto s_6` and $`r_{12} \mapsto r_6`.
7. Specifying a homomorphism $`\mathbb{Z} \to G` is the same as specifying just the image of the element $`1 : \mathbb{Z}`.
   Why?
:::

The last two examples illustrate something: suppose we have a presentation of $`G`.
To specify a homomorphism $`G \to H`, we only have to specify where each generator of $`G` goes, in such a way that the relations are all satisfied.

Important remark: the right way to think about an isomorphism is as a "bijective homomorphism".
To be explicit,

:::EXERCISE
Show that $`G \cong H` if and only if there exist homomorphisms $`\phi \colon G \to H` and $`\psi \colon H \to G` such that $`\phi \circ \psi = \mathrm{id}_H` and $`\psi \circ \phi = \mathrm{id}_G`.
:::

So the definitions of homeomorphism of metric spaces and isomorphism of groups are not too different.

Some obvious properties of homomorphisms follow.

:::FACT
Let $`\phi \colon G \to H` be a homomorphism.
Then $`\phi(1_G) = 1_H` and $`\phi(g^{-1}) = \phi(g)^{-1}`.
These are projections off any `MonoidHom`:

```lean
example (G H : Type*) [Group G] [Group H] (φ : G →* H) :
    φ 1 = 1 := φ.map_one
example (G H : Type*) [Group G] [Group H]
    (φ : G →* H) (g : G) : φ g⁻¹ = (φ g)⁻¹ := φ.map_inv g
```
:::

:::PROOF
Boring, and I'm sure you could do it yourself if you wanted to.
:::

Now let me define a very important property of a homomorphism.

:::DEFINITION
The *kernel* of a homomorphism $`\phi \colon G \to H` is defined by $$`\ker \phi \coloneqq \{g : G \mid \phi(g) = 1_H\}.`
It is a *subgroup* of $`G` (in particular, $`1_G \in \ker \phi` for obvious reasons).
Mathlib packages `φ.ker` as a `Subgroup G`:

```lean
example (G H : Type*) [Group G] [Group H]
    (φ : G →* H) (g : G) : g ∈ φ.ker ↔ φ g = 1 :=
  MonoidHom.mem_ker
```
:::

:::QUESTION
Verify that $`\ker \phi` is in fact a subgroup of $`G`.
:::

We also have the following important fact, which we also encourage the reader to verify.

:::PROPOSITION "Kernel determines injectivity"
The map $`\phi` is injective if and only if $`\ker \phi = \{1_G\}`.
:::

This is `MonoidHom.ker_eq_bot_iff`; the trivial subgroup of any group is written `⊥`.

```lean
example (G H : Type*) [Group G] [Group H] (φ : G →* H) :
    φ.ker = ⊥ ↔ Function.Injective φ :=
  MonoidHom.ker_eq_bot_iff φ
```

To make this concrete, let's compute the kernel of each of our examples.

:::EXAMPLE "Examples of kernels"
1. The kernel of any isomorphism $`G \to H` is trivial, since an isomorphism is injective.
   In particular, the kernel of the identity map $`G \to G` is $`\{1_G\}`.
2. The kernel of the trivial homomorphism $`G \to H` (by $`g \mapsto 1_H`) is all of $`G`.
3. The kernel of the homomorphism $`\mathbb{Z} \to \mathbb{Z}/100\mathbb{Z}` by $`n \mapsto \overline{n}` is precisely $$`100\mathbb{Z} = \{\dots, -200, -100, 0, 100, 200, \dots\}.`
4. The kernel of the map $`\mathbb{Z} \to \mathbb{Z}` by $`x \mapsto 10x` is trivial: $`\{0\}`.
5. There is a homomorphism from $`S_n` to $`S_{n+1}` by "embedding", but it also has trivial kernel because it is injective.
6. A homomorphism $`\phi \colon D_{12} \to D_6` is given by $`s_{12} \mapsto s_6` and $`r_{12} \mapsto r_6`.
   You can check that $$`\ker \phi = \{1, r_{12}^3\} \cong \mathbb{Z}/2\mathbb{Z}.`
7. Exercise below.
:::

:::EXERCISE
Fix any $`g : G`.
Suppose we have a homomorphism $`\mathbb{Z} \to G` by $`n \mapsto g^n`.
What is the kernel?
:::

:::QUESTION
Show that for any homomorphism $`\phi \colon G \to H`, the image $`\phi^{\mathrm{img}}(G)` is a subgroup of $`H`.
Hence, we'll be especially interested in the case where $`\phi` is surjective.
:::

```lean -show
end
```

# Cosets and modding out

:::PROTOTYPE
Modding out by $`n`: $`\mathbb{Z}/(n \cdot \mathbb{Z}) \cong \mathbb{Z}/n\mathbb{Z}`.
:::

_The next few sections are a bit dense.
If this exposition doesn't work for you, try {cite}`ref:gowers`._

Let $`G` and $`Q` be groups, and suppose there exists a *surjective* homomorphism $$`\phi \colon G \twoheadrightarrow Q.`
In other words, if $`\phi` is injective then $`\phi \colon G \to Q` is a bijection, and hence an isomorphism.
But suppose we're not so lucky and $`\ker \phi` is bigger than just $`\{1_G\}`.
What is the correct interpretation of a more general homomorphism?

Let's look at the special case where $`\phi \colon \mathbb{Z} \to \mathbb{Z}/100\mathbb{Z}` is "modding out by $`100`".
We already saw that the kernel of this map is $$`\ker \phi = 100\mathbb{Z} = \{\dots, -200, -100, 0, 100, 200, \dots\}.`
Recall now that $`\ker \phi` is a subgroup of $`G`.
What this means is that *$`\phi` is indifferent to the subgroup $`100\mathbb{Z}` of $`\mathbb{Z}`*: $$`\phi(15) = \phi(2000 + 15) = \phi(-300 + 15) = \phi(700 + 15) = \dots.`
So $`\mathbb{Z}/100\mathbb{Z}` is what we get when we "mod out by $`100`".
Cool.

In other words, let $`G` be a group and $`\phi \colon G \twoheadrightarrow Q` be a surjective homomorphism with kernel $`N \subseteq G`.

:::MORAL
We claim that $`Q` should be thought of as the quotient of $`G` by $`N`.
:::

To formalize this, we will define a so-called *quotient group* $`G/N` in terms of $`G` and $`N` only (without referencing $`Q`) which will be naturally isomorphic to $`Q`.

For motivation, let's give a concrete description of $`Q` using just $`\phi` and $`G`.
Continuing our previous example, let $`N = 100\mathbb{Z}` be our subgroup of $`G`.
Consider the sets $$`\begin{aligned} N &= \{\dots, -200, -100, 0, 100, 200, \dots\} \\ 1 + N &= \{\dots, -199, -99, 1, 101, 201, \dots\} \\ 2 + N &= \{\dots, -198, -98, 2, 102, 202, \dots\} \\ &\vdots \\ 99 + N &= \{\dots, -101, -1, 99, 199, 299, \dots\}. \end{aligned}`
The elements of each set all have the same image when we apply $`\phi`, and moreover any two elements in different sets have different images.
Then the main idea is to notice that

:::MORAL
We can think of $`Q` as the group whose _elements_ are the _sets_ above.
:::

Thus, given $`\phi` we define an equivalence relation $`\sim_N` on $`G` by saying $`x \sim_N y` for $`\phi(x) = \phi(y)`.
This $`\sim_N` divides $`G` into several equivalence classes in $`G` which are in obvious bijection with $`Q`, as above.
Now we claim that we can write these equivalence classes very explicitly.

:::EXERCISE
Show that $`x \sim_N y` if and only if $`x = yn` for some $`n \in N` (in the mod $`100` example, this means they "differ by some multiple of $`100`").
Thus for any $`g : G`, the equivalence class of $`\sim_N` which contains $`g` is given explicitly by $$`gN \coloneqq \{gn \mid n \in N\}.`
:::

Here's the word that describes the types of sets we're running into now.

:::DEFINITION
Let $`H` be any subgroup of $`G` (not necessarily the kernel of some homomorphism).
A set of the form $`gH` is called a *left coset* of $`H`.
:::

:::REMARK
Although the notation might not suggest it, keep in mind that $`g_1 N` is often equal to $`g_2 N` even if $`g_1 \neq g_2`.
In the "mod $`100`" example, $`3 + N = 103 + N`.
In other words, these cosets are *sets*.

This means that if I write "let $`gH` be a coset" without telling you what $`g` is, you can't figure out which $`g` I chose from just the coset itself.
If you don't believe me, here's an example of what I mean: $$`x + 100\mathbb{Z} = \{\dots, -97, 3, 103, 203, \dots\} \implies x = {?}.`
There's no reason to think I picked $`x = 3`.
(I actually picked $`x = -13597`.)
:::

:::REMARK
Given cosets $`g_1 H` and $`g_2 H`, you can check that the map $`x \mapsto g_2 g_1^{-1} x` is a bijection between them.
So actually, all cosets have the same cardinality.
:::

So, long story short,

:::MORAL
Elements of the group $`Q` are naturally identified with left cosets of $`N`.
:::

In practice, people often still prefer to picture elements of $`Q` as single points (for example it's easier to think of $`\mathbb{Z}/2\mathbb{Z}` as $`\{0, 1\}` rather than $`\big\{ \{\dots, -2, 0, 2, \dots\}, \{\dots, -1, 1, 3, \dots\} \big\}`).
If you like this picture, then you might then draw $`G` as a bunch of equally tall fibers (the cosets), which are then "collapsed" onto $`Q`.

:::figure "figures/abstract-algebra/cosets-fiber.svg"
The group $`G` partitioned into cosets of $`N` (the columns), each collapsing to a single point of the quotient $`Q = G/N`.
:::

Now that we've done this, we can give an _intrinsic_ definition for the quotient group we alluded to earlier.

:::DEFINITION
A subgroup $`N` of $`G` is called *normal* if it is the kernel of some homomorphism.
We write this as $`N \trianglelefteq G`.
:::

:::DEFINITION
Let $`N \trianglelefteq G`.
Then the *quotient group*, denoted $`G/N` (and read "$`G` mod $`N`"), is the group defined as follows.

- The elements of $`G/N` will be the left cosets of $`N`.
- We want to define the product of two cosets $`C_1` and $`C_2` in $`G/N`.
  Recall that the cosets are in bijection with elements of $`Q`.
  So let $`q_1` be the value associated to the coset $`C_1`, and $`q_2` the one for $`C_2`.
  Then we can take the product to be the coset corresponding to $`q_1 q_2`.

  Quite importantly, *we can also do this in terms of representatives of the cosets*.
  Let $`g_1 \in C_1` and $`g_2 \in C_2`, so $`C_1 = g_1 N` and $`C_2 = g_2 N`.
  Then $`C_1 \cdot C_2` should be the coset which contains $`g_1 g_2`.
  This is the same as the above definition since $`\phi(g_1 g_2) = \phi(g_1) \phi(g_2) = q_1 q_2`; all we've done is define the product in terms of elements of $`G`, rather than values in $`H`.

  Using the $`gN` notation, and with the coset-warning above in mind, we can write this even more succinctly: $$`(g_1 N) \cdot (g_2 N) \coloneqq (g_1 g_2) N.`
:::

A normal subgroup is recorded by `Subgroup.Normal`, and the quotient group is `G ⧸ N`.

```lean -show
section
```

```lean
recall (G : Type*) [Group G] (N : Subgroup G) [N.Normal] : Group (G ⧸ N)
```

And now you know why the integers modulo $`n` are often written $`\mathbb{Z}/n\mathbb{Z}`!

:::QUESTION
Take a moment to digest the above definition.
:::

By the way we've built it, the resulting group $`G/N` is isomorphic to $`Q`.
In a sense we think of $`G/N` as "$`G` modulo the condition that $`n = 1` for all $`n \in N`".

```lean -show
end
```

# (Optional) Proof of Lagrange's theorem

As an aside, with the language of cosets we can now show Lagrange's theorem in the general case.

:::THEOREM "Lagrange's theorem"
Let $`G` be a finite group, and let $`H` be any subgroup.
Then $`|H|` divides $`|G|`.

```lean -show
section
```

```lean
recall Subgroup.card_subgroup_dvd_card {G : Type*} [Group G]
    (H : Subgroup G) : Nat.card H ∣ Nat.card G
```
:::

The proof is very simple: note that the cosets of $`H` all have the same size and form a partition of $`G` (even when $`H` is not necessarily normal).
Hence if $`n` is the number of cosets, then $`n \cdot |H| = |G|`.

:::QUESTION
Conclude that $`x^{|G|} = 1` by taking $`H = \langle x \rangle \subseteq G`.
:::

:::REMARK
It should be mentioned at this point that in general, if $`G` is a finite group and $`N` is normal, then $`|G/N| = |G|/|N|`.
:::

# Eliminating the homomorphism

:::PROTOTYPE
Again $`\mathbb{Z}/(n \cdot \mathbb{Z}) \cong \mathbb{Z}/n\mathbb{Z}`.
:::

Let's look at the last definition of $`G/N` we provided.
The short version is:

- The elements of $`G/N` are cosets $`gN`, which you can think of as equivalence classes of a relation $`\sim_N` (where $`g_1 \sim_N g_2` if $`g_1 = g_2 n` for some $`n \in N`).
- Given cosets $`g_1 N` and $`g_2 N` the group operation is $$`g_1 N \cdot g_2 N \coloneqq (g_1 g_2) N.`

Question: where do we actually use the fact that $`N` is normal?
We don't talk about $`\phi` or $`Q` anywhere in this definition.

The answer is back in the warning above.
The group operation takes in two cosets, so it doesn't know what $`g_1` and $`g_2` are.
But behind the scenes, *the normal condition guarantees that the group operation can pick any $`g_1` and $`g_2` it wants and still end up with the same coset.*
If we didn't have this property, then it would be hard to define the product of two cosets $`C_1` and $`C_2` because it might make a difference which $`g_1 \in C_1` and $`g_2 \in C_2` we picked.
The fact that $`N` came from a homomorphism meant we could pick any representatives $`g_1` and $`g_2` of the cosets we wanted, because they all had the same $`\phi`-value.

We want some conditions which force this to be true without referencing $`\phi` at all.
Suppose $`\phi \colon G \to K` is a homomorphism of groups with $`H = \ker \phi`.
Aside from the fact $`H` is a group, we can get an "obvious" property:

:::EXERCISE
Show that if $`h \in H`, $`g : G`, then $`g h g^{-1} \in H`.
(Check $`\phi(g h g^{-1}) = 1_K`.)
:::

:::EXAMPLE "Example of a non-normal subgroup"
Let $`D_{12} = \langle r, s \mid r^6 = s^2 = 1, rs = sr^{-1} \rangle`.
Consider the subgroup of order two $`H = \{1, s\}` and notice that $$`r s r^{-1} = r (s r^{-1}) = r (r s) = r^2 s \notin H.`
Hence $`H` is not normal, and cannot be the kernel of any homomorphism.
:::

Well, duh — so what?
Amazingly it turns out that this is the _sufficient_ condition we want.
Specifically, it makes the nice "coset multiplication" we wanted work out.

:::REMARK "For math contest enthusiasts"
This coincidence is really a lot like functional equations at the IMO.
We all know that normal subgroups $`H` satisfy $`g h g^{-1} \in H`; the surprise is that from the latter seemingly weaker condition, we can deduce $`H` is normal.
:::

Thus we have a new criterion for "normal" subgroups which does not make any external references to $`\phi`.

:::THEOREM "Algebraic condition for normal subgroups"
Let $`H` be a subgroup of $`G`.
Then the following are equivalent:

- $`H \trianglelefteq G`.
- For every $`g : G` and $`h \in H`, $`g h g^{-1} \in H`.
:::

::::PROOF
We already showed one direction.

For the other direction, we need to build a homomorphism with kernel $`H`.
So we simply _define_ the group $`G/H` as the cosets.
To put a group operation, we need to verify:

> *Claim.*
> If $`g_1' \sim_H g_1` and $`g_2' \sim_H g_2` then $`g_1' g_2' \sim_H g_1 g_2`.

Boring algebraic manipulation (again functional equation style).
Let $`g_1' = g_1 h_1` and $`g_2' = g_2 h_2`, so we want to show that $`g_1 h_1 g_2 h_2 \sim_H g_1 g_2`.
Since $`H` has the property, $`g_2^{-1} h_1 g_2` is some element of $`H`, say $`h_3`.
Thus $`h_1 g_2 = g_2 h_3`, and the left-hand side becomes $`g_1 g_2 (h_3 h_2)`, which is fine since $`h_3 h_2 \in H`.

With that settled we can just _define_ the product of two cosets (of normal subgroups) by $`(g_1 H) \cdot (g_2 H) = (g_1 g_2) H`.

Thus the claim above shows that this multiplication is well-defined (this verification is the "content" of the theorem).
So $`G/H` is indeed a group!
Moreover there is an obvious "projection" homomorphism $`G \to G/H` (with kernel $`H`), by $`g \mapsto gH`.
::::

`Subgroup.Normal` takes the algebraic condition as its definition:

```lean
example (G : Type*) [Group G] (H : Subgroup G) :
    H.Normal ↔ ∀ n ∈ H, ∀ g : G, g * n * g⁻¹ ∈ H :=
  ⟨fun h => h.conj_mem, fun h => ⟨h⟩⟩
```

:::EXAMPLE "Modding out in the product group"
Consider again the product group $`G \times H`.
Earlier we identified a subgroup $$`G' = \{(g, 1_H) \mid g : G\} \cong G.`
You can easily see that $`G' \trianglelefteq G \times H`.
(Easy calculation.)

Moreover, you can check that $$`(G \times H) / G' \cong H.`
Indeed, we have $`(g, h) \sim_{G'} (1_G, h)` for all $`g : G` and $`h : H`.
:::

:::EXAMPLE "Quotients and products don't necessarily cancel"
It is not necessarily true that $`(G/H) \times H \cong G`.
For example, consider $`G = \mathbb{Z}/4\mathbb{Z}` and the normal subgroup $`H = \{0, 2\} \cong \mathbb{Z}/2\mathbb{Z}`.
Then $`G/H \cong \mathbb{Z}/2\mathbb{Z}`, but $`\mathbb{Z}/4\mathbb{Z} \not\cong \mathbb{Z}/2\mathbb{Z} \times \mathbb{Z}/2\mathbb{Z}`.
(Footnote: the precise condition for this kind of "canceling" is called the Schur-Zassenhaus lemma.)
:::

:::EXAMPLE "Another explicit computation"
Let $`\phi \colon D_8 \to \mathbb{Z}/4\mathbb{Z}` be defined by $$`r \mapsto \overline{2}, \quad s \mapsto \overline{2}.`
The kernel of this map is $`N = \{1, r^2, sr, sr^3\}`.

We can do a quick computation of all the elements of $`D_8` to get $$`\phi(1) = \phi(r^2) = \phi(sr) = \phi(sr^3) = \overline{0} \text{ and } \phi(r) = \phi(r^3) = \phi(s) = \phi(sr^2) = \overline{2}.`
The two relevant fibers are $$`\phi^{\mathrm{pre}}(\overline{0}) = 1N = r^2 N = sr N = sr^3 N = \{1, r^2, sr, sr^3\}` and $$`\phi^{\mathrm{pre}}(\overline{2}) = rN = r^3 N = s N = sr^2 N = \{r, r^3, s, sr^2\}.`
So we see that $`|D_8/N| = 2` is a group of order two, or $`\mathbb{Z}/2\mathbb{Z}`.
Indeed, the image of $`\phi` is $$`\{\overline{0}, \overline{2}\} \cong \mathbb{Z}/2\mathbb{Z}.`
:::

:::QUESTION
Suppose $`G` is abelian.
Why does it follow that any subgroup of $`G` is normal?
:::

Finally here's some food for thought: suppose one has a group presentation for a group $`G` that uses $`n` generators.
Can you write it as a quotient of the form $`F_n / N`, where $`N` is a normal subgroup of $`F_n`?

```lean -show
end
```

# (Digression) The first isomorphism theorem

One quick word about what other sources usually say.

Most textbooks actually _define_ normal using the $`g h g^{-1} \in H` property.
Then they define $`G/H` for normal $`H` in the way I did above, using the coset definition $$`(g_1 H) \cdot (g_2 H) = g_1 g_2 H.`
Using purely algebraic manipulations (like I did) this is well-defined, and so now you have this group $`G/H` or something.
The underlying homomorphism isn't mentioned at all, or is just mentioned in passing.

I think this is incredibly dumb.
The normal condition looks like it gets pulled out of thin air and no one has any clue what's going on, because no one has any clue what a normal subgroup actually should look like.

Other sources like to also write the so-called first isomorphism theorem.{margin}[There is a second and third isomorphism theorem. But four years after learning about them, I _still_ don't remember what they are. So I'm guessing they weren't very important.] It goes like this.

:::THEOREM "First isomorphism theorem"
Let $`\phi \colon G \to H` be a homomorphism.
Then $`G / \ker \phi` is isomorphic to $`\phi^{\mathrm{img}}(G)`.
Mathlib calls this `QuotientGroup.quotientKerEquivRange`:

```lean
noncomputable example {G H : Type*} [Group G] [Group H]
    (φ : G →* H) : G ⧸ φ.ker ≃* φ.range :=
  QuotientGroup.quotientKerEquivRange φ
```
:::

To me, this is just a clumsier way of stating the same idea.

About the only merit this claim has is that if $`\phi` is injective, then the image $`\phi^{\mathrm{img}}(G)` is an _isomorphic copy_ of $`G` inside the group $`H`.
(Try to see this directly!)
This is a pattern we'll often see in other branches of mathematics: whenever we have an _injective structure-preserving map_, often the image of this map will be some "copy" of $`G`.
(Here "structure" refers to the group multiplication, but we'll see some more other examples of "types of objects" later!)
In that sense an injective homomorphism $`\phi \colon G \hookrightarrow H` is an _embedding_ of $`G` into $`H`.

# Problems

:::PROBLEM "18.701 at MIT"
Determine all groups $`G` for which the map $`\phi \colon G \to G` defined by $$`\phi(g) = g^2` is a homomorphism.
:::

:::PROBLEM
Consider the dihedral group $`G = D_{10}`.

1. Is $`H = \langle r \rangle` a normal subgroup of $`G`?
   If so, compute $`G/H` up to isomorphism.
2. Is $`H = \langle s \rangle` a normal subgroup of $`G`?
   If so, compute $`G/H` up to isomorphism.
:::

:::PROBLEM
Does $`S_4` have a normal subgroup of order $`3`?
:::

:::PROBLEM
Let $`G` and $`H` be finite groups, where $`|G| = 1000` and $`|H| = 999`.
Show that a homomorphism $`G \to H` must be trivial.
:::

:::PROBLEM
Let $`\mathbb{C}^\times` denote the nonzero complex numbers under multiplication.
Show that there are five homomorphisms $`\mathbb{Z}/5\mathbb{Z} \to \mathbb{C}^\times` but only two homomorphisms $`D_{10} \to \mathbb{C}^\times`, even though $`\mathbb{Z}/5\mathbb{Z}` is a subgroup of $`D_{10}`.
:::

:::PROBLEM (chili := 1)
Find a non-abelian group $`G` such that every subgroup of $`G` is normal.
(These groups are called *Hamiltonian*.)
:::

:::PROBLEM "PRIMES entrance exam, 2018" (chili := 1)
Let $`G` be a group with presentation given by $$`G = \langle a, b, c \mid ab = c^2 a^4, \; bc = c a^6, \; ac = c a^8, \; c^{2018} = b^{2019} \rangle.`
Determine the order of $`G`.
:::

:::PROBLEM "Homophony group" (chili := 1)
The homophony group (of English) is the group with $`26` generators $`a, b, \dots, z` and one relation for every pair of English words which sound the same.
For example $`\mathit{knight} = \mathit{night}` (and hence $`k = 1`).
Prove that the group is trivial.
:::
