/-
Extraction of each chapter's Lean into standalone, compilable files.

The Colophon tells readers that to attempt an exercise they should "copy
it into a file whose imports match the chapter's source". This module does
that for them: for every chapter it emits

  * `<Chapter>-exercises.lean` — the chapter's header (imports, `open`s,
    options) followed by every code block of its Formalization section in
    order, with the exercises still proved by `sorry`; and
  * `<Chapter>-solutions.lean` — the same, with each exercise replaced by
    the worked solution beneath it.

Taking *every* block, not only the exercises, is what makes the output
compile: the hidden `lean -show` blocks that open sections and declare
shared variables come along, and so do the worked models the exercises
build on. Reusing the chapter header verbatim rather than guessing a
minimal import set is the same bet — whatever the chapter needed, the
extracted file has.

Substitution is per *declaration*, not per block: an exercise block that
also defines a helper (`def toffoli` alongside the `example` about it)
must keep the helper, since the solution block restates only the example.

Driven by `BuildExercises.lean` (as `lake exe exercises`) and by a render
step in `Render.lean`, so the files also land in the published site.
-/

import Napkin.Meta.Extract

namespace Napkin.Meta.Exercises

open Napkin.Meta.Extract

/-- One chapter's extracted Lean. -/
structure Extracted where
  /-- Imports, `open`s and options: everything above the `#doc` line. -/
  header : String
  /-- Every code block in order, exercises left as `sorry`. -/
  exercises : String
  /-- Every code block in order, exercises replaced by their solutions. -/
  solutions : String

/-- Pull a chapter apart into its header and its two code streams.
    Returns `none` for a file with no Formalization code to extract. -/
def extract (text : String) : Option Extracted := Id.run do
  let blocks := collectBlocks text (onlyFormalization := false)
  if blocks.isEmpty then
    return none
  let mut exercises : Array String := #[]
  let mut solutions : Array String := #[]
  -- Index in `solutions` of the block a following solution replaces, and
  -- the part of that block to keep (its non-`sorry` declarations).
  let mut pending : Option (Nat × String) := none
  for b in blocks do
    match b.kind with
    | .plain =>
      exercises := exercises.push b.code
      solutions := solutions.push b.code
      pending :=
        if hasSorry b.code then
          -- Declarations without a `sorry` are context the solution needs.
          let keep := (decls b.code).filter (fun d => !hasSorry d)
          some (solutions.size - 1, String.intercalate "\n" keep.toList)
        else
          none
    | .solution =>
      match pending with
      | some (i, keep) =>
        let merged :=
          if strip keep == "" then b.code else keep ++ "\n\n" ++ b.code
        solutions := solutions.set! i merged
      | none => solutions := solutions.push b.code
      pending := none
  if exercises.isEmpty then
    return none
  return some {
    header := header text
    exercises := String.intercalate "\n\n" exercises.toList
    solutions := String.intercalate "\n\n" solutions.toList
  }

/-- Banner explaining what the generated file is. -/
private def banner (chapter : String) (kind : String) : String :=
  s!"/-\n  {kind} extracted from the chapter \"{chapter}\".\n\n  \
    Generated by `lake exe exercises` — edit the chapter, not this file.\n-/\n"

/-- Write the extracted files for every chapter under `sourceRoot` into
    `dest`, mirroring the source directory layout. Returns how many
    chapters produced output. -/
def writeAll (dest : System.FilePath) : IO Nat := do
  let files ← collectLean sourceRoot
  let mut n := 0
  for f in files do
    let some ex := extract (← IO.FS.readFile f) | continue
    let some stem := f.fileStem | continue
    let rel := (f.parent.getD "." |>.toString).drop sourceRoot.toString.length
    let outDir :=
      dest / (rel.dropWhile (· ∈ System.FilePath.pathSeparators)).toString
    IO.FS.createDirAll outDir
    IO.FS.writeFile (outDir / s!"{stem}-exercises.lean")
      (banner stem "Exercises" ++ ex.header ++ "\n" ++ ex.exercises ++ "\n")
    IO.FS.writeFile (outDir / s!"{stem}-solutions.lean")
      (banner stem "Solutions" ++ ex.header ++ "\n" ++ ex.solutions ++ "\n")
    n := n + 1
  return n

end Napkin.Meta.Exercises
