import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Determinant" =>

%%%
file := "Determinant"
%%%


The goal of this chapter is to give the basis-free definition of the determinant: that is, we're going to define $`\det T` for $`T \colon V \to V` without making reference to the encoding for $`T`.
This will make it obvious that the determinant of a matrix does not depend on the choice of basis, and that several properties are vacuously true (e.g. that the determinant is multiplicative).

The determinant is only defined for finite-dimensional vector spaces, so if you want you can restrict your attention to finite-dimensional vector spaces for this chapter.
On the other hand we do not need the ground field to be algebraically closed.

# Wedge product

:::PROTOTYPE
$`\bigwedge^2(\mathbb{R}^2)` gives parallelograms.
:::

We're now going to define something called the wedge product.
It will look at first like the tensor product $`V \otimes V`, but we'll have one extra relation.

For simplicity, I'll first define the wedge product $`\bigwedge^2(V)`.
But we will later replace $`2` with any $`n`.

:::DEFINITION
Let $`V` be a $`k`-vector space.
The $`2`-wedge product $`\bigwedge^2(V)` is the abelian group generated by elements of the form $`v \wedge w` (where $`v, w : V`), subject to the same relations $$`(v_1 + v_2) \wedge w = v_1 \wedge w + v_2 \wedge w` $$`v \wedge (w_1 + w_2) = v \wedge w_1 + v \wedge w_2` $$`(c \cdot v) \wedge w = v \wedge (c \cdot w)` plus two additional relations: $$`v \wedge v = 0 \quad \text{and} \quad v \wedge w = -w \wedge v.`
As a vector space, its action is given by $`c \cdot (v \wedge w) = (c \cdot v) \wedge w = v \wedge (c \cdot w)`.
:::

:::EXERCISE
Show that the condition $`v \wedge w = -(w \wedge v)` is actually extraneous: you can derive it from the fact that $`v \wedge v = 0`.
(Hint: expand $`(v + w) \wedge (v + w) = 0`.)
:::

This looks almost exactly the same as the definition for a tensor product, with two subtle differences.
The first is that we only have $`V` now, rather than $`V` and $`W` as with the tensor product.{margin}[So maybe the wedge product might be more accurately called the "wedge power"!] Secondly, there is a new _mysterious_ relation $$`v \wedge v = 0 \implies v \wedge w = -(w \wedge v).`
What's that doing there?
It seems kind of weird.

I'll give you a hint.

:::EXAMPLE "Wedge product explicit computation"
Let $`V = \mathbb{R}^2`, and let $`v = ae_1 + be_2`, $`w = ce_1 + de_2`.
Now let's compute $`v \wedge w` in $`\bigwedge^2(V)`. $$`v \wedge w = (ae_1 + be_2) \wedge (ce_1 + de_2)` $$`= ac(e_1 \wedge e_1) + bd(e_2 \wedge e_2) + ad(e_1 \wedge e_2) + bc(e_2 \wedge e_1)` $$`= ad(e_1 \wedge e_2) + bc(e_2 \wedge e_1) = (ad - bc)(e_1 \wedge e_2).`
:::

What is $`ad - bc`?
You might already recognize it:

- You might know that the area of the parallelogram formed by $`v` and $`w` is $`ad - bc`.
- You might recognize it as the determinant of $`\begin{bmatrix} a & c \\ b & d \end{bmatrix}`.
  In fact, you might even know that the determinant is meant to interpret hypervolumes.

This is absolutely no coincidence.
The wedge product is designed to interpret signed areas.
That is, $`v \wedge w` is meant to interpret the area of the parallelogram formed by $`v` and $`w`.

:::figure "figures/linear-algebra/dets-parallelogram.svg"
The parallelogram spanned by $`v = ae_1 + be_2` and $`w = ce_1 + de_2` has signed area $`ad - bc`.
:::
You can see why the condition $`(cv) \wedge w = v \wedge (cw)` would make sense now.
And now of course you know why $`v \wedge v` ought to be zero: it's an area zero parallelogram!

The *miracle of wedge products* is that the only additional condition we need to add to the tensor product axioms is that $`v \wedge v = 0`.
Then suddenly, the wedge will do all our work of interpreting volumes for us.

:::REMARK "Side digression on definitions in mathematics"
This "property-based" philosophy is a common trope in modern mathematics.
You have some intuition about an object you wish to define, and then you write down a wishlist of properties that "should" follow.
But then it turns out the properties are sufficient to work with, and so for the definition, you just define an abstract object satisfying all the properties on your wishlist.
Thereafter the intuition plays no "official" role; it serves only as cheerleading motivation for the wishlist.

For wedge products, the wishlist has only the single property $`v \wedge v = 0`.
:::

In analog to earlier:

:::PROPOSITION "Basis of ⋀²(V)"
Let $`V` be a vector space with basis $`e_1, \dots, e_n`.
Then a basis of $`\bigwedge^2(V)` is $$`e_i \wedge e_j` where $`i < j`.
Hence $`\bigwedge^2(V)` has dimension $`\binom{n}{2}`.
:::

:::PROOF
Surprisingly slippery, and also omitted.
(You can derive it from the corresponding theorem on tensor products.)
:::

Now I have the courage to define a multi-dimensional wedge product.
It's just the same thing with more wedges.

:::DEFINITION
Let $`V` be a vector space and $`m` a positive integer.
The space $`\bigwedge^m(V)` is generated by wedges of the form $$`v_1 \wedge v_2 \wedge \dots \wedge v_m` subject to relations $$`\dots \wedge (v_1 + v_2) \wedge \dots = (\dots \wedge v_1 \wedge \dots) + (\dots \wedge v_2 \wedge \dots)` $$`\dots \wedge (cv_1) \wedge v_2 \wedge \dots = \dots \wedge v_1 \wedge (cv_2) \wedge \dots` $$`\dots \wedge v \wedge v \wedge \dots = 0` $$`\dots \wedge v \wedge w \wedge \dots = -(\dots \wedge w \wedge v \wedge \dots).`
As a vector space $$`c \cdot (v_1 \wedge v_2 \wedge \dots \wedge v_m) = (cv_1) \wedge v_2 \wedge \dots \wedge v_m = v_1 \wedge (cv_2) \wedge \dots \wedge v_m = \dots.`
:::

This definition is pretty wordy, but in English the three conditions say

- We should be able to add products like before,
- You can put constants onto any of the $`m` components (as is directly pointed out in the "vector space" action), and
- Switching any two _adjacent_ wedges negates the whole wedge.

So this is the natural generalization of $`\bigwedge^2(V)`.
You can convince yourself that any element of the form $$`\dots \wedge v \wedge \dots \wedge v \wedge \dots` should still be zero.

Just like $`e_1 \wedge e_2` was a basis earlier, we can find the basis for general $`m` and $`n`.

:::PROPOSITION "Basis of the wedge product"
Let $`V` be a vector space with basis $`e_1, \dots, e_n`.
A basis for $`\bigwedge^m(V)` consists of the elements $$`e_{i_1} \wedge e_{i_2} \wedge \dots \wedge e_{i_m}` where $$`1 \leq i_1 < i_2 < \dots < i_m \leq n.`
Hence $`\bigwedge^m(V)` has dimension $`\binom{n}{m}`.
:::

:::PROOF
We knew earlier that $`e_{i_1} \otimes \dots \otimes e_{i_m}` was a basis for the tensor product.
Here we have the additional property that (a) if two basis elements re-appear then the whole thing becomes zero, thus we should assume the $`i`'s are all distinct; and (b) we can shuffle around elements, and so we arbitrarily decide to put the basis elements in increasing order.
:::

# The determinant

:::PROTOTYPE
$`(ae_1 + be_2) \wedge (ce_1 + de_2) = (ad - bc)(e_1 \wedge e_2)`.
:::

Now we're ready to define the determinant.
Suppose $`T \colon V \to V` is a square matrix.
We claim that the map $`\bigwedge^m(V) \to \bigwedge^m(V)` given on wedges by $$`v_1 \wedge v_2 \wedge \dots \wedge v_m \mapsto T(v_1) \wedge T(v_2) \wedge \dots \wedge T(v_m).` and extending linearly to all of $`\bigwedge^m(V)` is a well-defined linear map.
(Here "well-defined" means that equivalent elements of the domain get mapped to equivalent elements of the codomain.
This, and linearity, both follow from $`T` being a linear map.)
We call that map $`\bigwedge^m(T)`.

:::EXAMPLE "Example of ⋀ᵐ(T)"
In $`V = \mathbb{R}^4` with standard basis $`e_1, e_2, e_3, e_4`, let $`T(e_1) = e_2`, $`T(e_2) = 2e_3`, $`T(e_3) = e_3` and $`T(e_4) = 2e_2 + e_3`.
Then, for example, $`\bigwedge^2(T)` sends $$`(e_1 \wedge e_2) + (e_3 \wedge e_4) \mapsto T(e_1) \wedge T(e_2) + T(e_3) \wedge T(e_4)` $$`= e_2 \wedge 2e_3 + e_3 \wedge (2e_2 + e_3) = 2(e_2 \wedge e_3 + e_3 \wedge e_2) = 0.`
:::

Now here's something interesting.
Suppose $`V` has dimension $`n`, and let $`m = n`.
Then $`\bigwedge^n(V)` has dimension $`\binom{n}{n} = 1` — it's a one dimensional space!
Hence $`\bigwedge^n(V) \cong k`.

So $`\bigwedge^n(T)` can be thought of as a linear map from $`k` to $`k`.
But we know that _a linear map from $`k` to $`k` is just multiplication by a constant_.
Hence $`\bigwedge^n(T)` is multiplication by some constant.

:::DEFINITION
Let $`T \colon V \to V`, where $`V` is an $`n`-dimensional vector space.
Then $`\bigwedge^n(T)` is multiplication by a constant $`c`; we define the *determinant* of $`T` as $`c = \det T`.
:::

:::EXAMPLE "The determinant of a 2 × 2 matrix"
Let $`V = \mathbb{R}^2` again with basis $`e_1` and $`e_2`.
Let $$`T = \begin{bmatrix} a & c \\ b & d \end{bmatrix}.`
In other words, $`T(e_1) = ae_1 + be_2` and $`T(e_2) = ce_1 + de_2`.

Now let's consider $`\bigwedge^2(V)`.
It has a basis $`e_1 \wedge e_2`.
Now $`\bigwedge^2(T)` sends it to $$`e_1 \wedge e_2 \mapsto T(e_1) \wedge T(e_2) = (ae_1 + be_2) \wedge (ce_1 + de_2) = (ad - bc)(e_1 \wedge e_2).`
So $`\bigwedge^2(T) \colon \bigwedge^2(V) \to \bigwedge^2(V)` is multiplication by $`\det T = ad - bc`, because it sent $`e_1 \wedge e_2` to $`(ad - bc)(e_1 \wedge e_2)`.
:::

And that is the definition of a determinant.
Once again, since we defined it in terms of $`\bigwedge^n(T)`, this definition is totally independent of the choice of basis.
In other words, the determinant can be defined based on $`T \colon V \to V` alone without any reference to matrices.

:::QUESTION
Why does $`\bigwedge^n(S \circ T) = \bigwedge^n(S) \circ \bigwedge^n(T)`?
:::

In this way, we also get $$`\det(S \circ T) = \det(S) \det(T)` for free.

More generally if we replace $`2` by $`n`, and write out the result of expanding $$`(a_{11} e_1 + a_{21} e_2 + \dots) \wedge \dots \wedge (a_{1n} e_1 + a_{2n} e_2 + \dots + a_{nn} e_n)` then you will get the formula $$`\det(A) = \sum_{\sigma : S_n} \operatorname{sgn}(\sigma) a_{1, \sigma(1)} a_{2, \sigma(2)} \dots a_{n, \sigma(n)}` called the *Leibniz formula* for determinants.
American high school students will recognize it; this is (unfortunately) taught as the definition of the determinant, rather than a corollary of the better definition using wedge products.

:::EXERCISE
Verify that expanding the wedge product yields the Leibniz formula for $`n = 3`.
:::

# Characteristic polynomials, and Cayley-Hamilton

Let's connect with the theory of eigenvalues.
Take a map $`T \colon V \to V`, where $`V` is $`n`-dimensional over an algebraically closed field, and suppose its eigenvalues are $`\lambda_1, \lambda_2, \dots, \lambda_n` (with repetition).
Then the *characteristic polynomial* is given by $$`p_T(X) = (X - \lambda_1)(X - \lambda_2) \dots (X - \lambda_n).`

Note that if we've written $`T` in Jordan form, that is, $$`T = \begin{bmatrix} \lambda_1 & * & 0 & \dots & 0 \\ 0 & \lambda_2 & * & \dots & 0 \\ 0 & 0 & \lambda_3 & \dots & 0 \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & 0 & \dots & \lambda_n \end{bmatrix}` (here each $`*` is either $`0` or $`1`), then we can hack together the definition $$`p_T(X) \coloneqq \det\left( X \cdot \mathrm{id}_n - T \right) = \det \begin{bmatrix} X - \lambda_1 & * & 0 & \dots & 0 \\ 0 & X - \lambda_2 & * & \dots & 0 \\ 0 & 0 & X - \lambda_3 & \dots & 0 \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & 0 & \dots & X - \lambda_n \end{bmatrix}.`

The latter definition is what you'll see in most linear algebra books because it lets you define the characteristic polynomial without mentioning the word "eigenvalue" (i.e. entirely in terms of arrays of numbers).
I'll admit it does have the merit that it means that given any matrix, it's easy to compute the characteristic polynomial and hence compute the eigenvalues; but I still think the definition should be done in terms of eigenvalues to begin with.
For instance the determinant definition obscures the following theorem, which is actually a complete triviality.

:::THEOREM "Cayley-Hamilton"
Let $`T \colon V \to V` be a map of finite-dimensional vector spaces over an algebraically closed field.
Then for any $`T \colon V \to V`, the map $`p_T(T)` is the zero map.
:::

Here, by $`p_T(T)` we mean that if $$`p_T(X) = X^n + c_{n-1} X^{n-1} + \dots + c_0` then $$`p_T(T) = T^n + c_{n-1} T^{n-1} + \dots + c_1 T + c_0 I` is the zero map, where $`T^k` denotes $`T` applied $`k` times.
We saw this concept already when we proved that $`T` had at least one nonzero eigenvector.

:::EXAMPLE "Example of Cayley-Hamilton using determinant definition"
Suppose $`T = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}`.
Using the determinant definition of characteristic polynomial, we find that $`p_T(X) = (X - 1)(X - 4) - (-2)(-3) = X^2 - 5X - 2`.
Indeed, you can verify that $$`T^2 - 5T - 2 = \begin{bmatrix} 7 & 10 \\ 15 & 22 \end{bmatrix} - 5 \cdot \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} - 2 \cdot \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix}.`
:::

If you define $`p_T` without the word eigenvalue, and adopt the evil view that matrices are arrays of numbers, then this looks like a complete miracle.
(Indeed, just look at the terrible proofs on Wikipedia.)

But if you use the abstract viewpoint of $`T` as a linear map, then the theorem is almost obvious:

:::PROOF
Suppose we write $`V` in Jordan normal form as $$`V = J_1 \oplus \dots \oplus J_m` where $`J_i` has eigenvalue $`\lambda_i` and dimension $`d_i`.
By definition, $$`p_T(T) = (T - \lambda_1)^{d_1} (T - \lambda_2)^{d_2} \dots (T - \lambda_m)^{d_m}.`
By definition, $`(T - \lambda_1)^{d_1}` is the zero map on $`J_1`.
So $`p_T(T)` is zero on $`J_1`.
Similarly it's zero on each of the other $`J_i`'s — end of story.
:::

:::REMARK "Tensoring up"
The Cayley-Hamilton theorem holds without the hypothesis that $`k` is algebraically closed: because for example any real matrix can be regarded as a matrix with complex coefficients (a trick we've mentioned before).
I'll briefly hint at how you can use tensor products to formalize this idea.

Let's take the space $`V = \mathbb{R}^3`, with basis $`e_1, e_2, e_3`.
Thus objects in $`V` are of the form $`r_1 e_1 + r_2 e_2 + r_3 e_3` where $`r_1, r_2, r_3` are real numbers.
We want to consider essentially the same vector space, but with complex coefficients $`z_i` rather than real coefficients $`r_i`.

So here's what we do: view $`\mathbb{C}` as a $`\mathbb{R}`-vector space (with basis $`\{1, i\}`, say) and consider the *complexification* $$`V_\mathbb{C} \coloneqq \mathbb{C} \otimes_\mathbb{R} V.`
Then you can check that our elements are actually of the form $$`z_1 \otimes e_1 + z_2 \otimes e_2 + z_3 \otimes e_3.`
Here, the tensor product is over $`\mathbb{R}`, so we have $`z \otimes re_i = (zr) \otimes e_i` for $`r : \mathbb{R}`.
Then $`V_\mathbb{C}` can be thought of as a three-dimensional vector space over $`\mathbb{C}`, with basis $`1 \otimes e_i` for $`i \in \{1, 2, 3\}`.
In this way, the tensor product lets us formalize the idea that we "fuse on" complex coefficients.

If $`T \colon V \to W` is a map, then $`T_\mathbb{C} \colon V_\mathbb{C} \to W_\mathbb{C}` is just the map $`z \otimes v \mapsto z \otimes T(v)`.
You'll see this written sometimes as $`T_\mathbb{C} = \mathrm{id} \otimes T`.
One can then apply theorems to $`T_\mathbb{C}` and try to deduce the corresponding results on $`T`.
:::

# Problems

:::PROBLEM "Column operations"
Show that for any real numbers $`x_{ij}` (here $`1 \leq i, j \leq n`) we have $$`\det \begin{bmatrix} x_{11} & x_{12} & \dots & x_{1n} \\ \vdots & \vdots & \ddots & \vdots \\ x_{n1} & x_{n2} & \dots & x_{nn} \end{bmatrix} = \det \begin{bmatrix} x_{11} + cx_{12} & x_{12} & \dots & x_{1n} \\ \vdots & \vdots & \ddots & \vdots \\ x_{n1} + cx_{n2} & x_{n2} & \dots & x_{nn} \end{bmatrix}.`
:::

:::PROBLEM "Determinant is product of eigenvalues"
Let $`V` be an $`n`-dimensional vector space over an algebraically closed field $`k`.
Let $`T \colon V \to V` be a linear map with eigenvalues $`\lambda_1, \lambda_2, \dots, \lambda_n` (counted with algebraic multiplicity).
Show that $`\det T = \lambda_1 \dots \lambda_n`.
:::

:::PROBLEM "Exponential matrix"
Let $`X` be an $`n \times n` matrix with complex coefficients.
We define the exponential map by $$`\exp(X) = 1 + X + \frac{X^2}{2!} + \frac{X^3}{3!} + \cdots` (take it for granted that this converges to some $`n \times n` matrix).
Prove that $$`\det(\exp(X)) = e^{\operatorname{Tr} X}.`
:::

:::PROBLEM "Determinant detects isomorphism"
Let $`T \colon V \to V` be a map of finite-dimensional vector spaces.
Prove that $`T` is an isomorphism if and only if $`\det T \neq 0`.
:::

:::PROBLEM "Based on Sweden 2010" (chili := 1)
A herd of $`1000` cows of nonzero weight is given.
Prove that we can remove one cow such that the remaining $`999` cows cannot be partitioned into two sets with equal sum of weights.
:::

:::PROBLEM "Putnam 2015" (chili := 2)
Define $`S` to be the set of real matrices $`\begin{pmatrix} a & b \\ c & d \end{pmatrix}` such that $`a, b, c, d` form an arithmetic progression in that order.
Find all $`M \in S` such that for some integer $`k > 1`, $`M^k \in S`.
:::

:::PROBLEM (chili := 2)
Let $`V` be a finite-dimensional vector space over $`k` and $`T \colon V \to V`.
Show that $$`\det(a \cdot \mathrm{id}_V - T) = \sum_{n=0}^{\dim V} a^{\dim V - n} \cdot (-1)^n \operatorname{Tr}\left( \bigwedge^n(T) \right)` where the trace is taken by viewing $`\bigwedge^n(T) \colon \bigwedge^n(V) \to \bigwedge^n(V)`.
:::

:::PROBLEM "Cauchy-Binet formula" (chili := 1)
Let $`n \geq s \geq 1` be integers, and let $`A` and $`B` be an $`s \times n` matrix and $`n \times s` matrix, respectively.
(Hence $`AB` is an $`s \times s` matrix.)
For any subset $`S \subseteq \{1, 2, \dots, n\}` with $`|S| = s`, we let $`A_S` be the $`s \times s` submatrix of $`A` of the rows with indices in $`S` and let $`B_S` be the $`s \times s` submatrix of $`B` of the columns with indices in $`S`.
Prove that $$`\det(AB) = \sum_{|S| = s} \det A_S \det B_S.`
:::

# Formalization

:::LEANCOMPANION
:::

## Wedge product

Mathlib packages the wedge product of a $`k`-module $`M` inside the `ExteriorAlgebra R M`, where the injection `ExteriorAlgebra.ι R : M → ExteriorAlgebra R M` sends a vector to its degree-one image and multiplication plays the role of $`\wedge`.
The single defining relation of the wishlist, $`v \wedge v = 0`, is `ExteriorAlgebra.ι_sq_zero`.

```lean
example (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] (m : M) :
    ExteriorAlgebra.ι R m * ExteriorAlgebra.ι R m = 0 :=
  ExteriorAlgebra.ι_sq_zero m
```

The exercise asked you to derive the anticommutativity $`v \wedge w = -(w \wedge v)` from $`v \wedge v = 0` alone.
Prove it: the sum `ExteriorAlgebra.ι_add_mul_swap` of the two orders vanishes, so each is the negation of the other.

```lean
example (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] (x y : M) :
    ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y
      = -(ExteriorAlgebra.ι R y * ExteriorAlgebra.ι R x) := by
  sorry
```

:::solution
```lean
example (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] (x y : M) :
    ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y
      = -(ExteriorAlgebra.ι R y * ExteriorAlgebra.ι R x) :=
  eq_neg_of_add_eq_zero_left (ExteriorAlgebra.ι_add_mul_swap x y)
```
:::

## The determinant

`Matrix.det` computes the determinant on square matrices, accessible via `M.det` once a `Fintype` and `DecidableEq` for the index type are in scope.

```lean
example {n : Type*} [Fintype n] [DecidableEq n] {k : Type*}
    [CommRing k] (M : Matrix n n k) : k := M.det
```

For a $`2 \times 2` matrix this unfolds to the $`ad - bc` of the worked wedge computation, recorded as `Matrix.det_fin_two`.

```lean
example {k : Type*} [CommRing k] (M : Matrix (Fin 2) (Fin 2) k) :
    M.det = M 0 0 * M 1 1 - M 0 1 * M 1 0 :=
  Matrix.det_fin_two M
```

The basis-free definition makes multiplicativity, $`\det(S \circ T) = \det(S)\det(T)`, fall out for free.
Show that the determinant of a product of matrices is the product of the determinants.

```lean
example {n : Type*} [Fintype n] [DecidableEq n] {k : Type*}
    [CommRing k] (M N : Matrix n n k) : (M * N).det = M.det * N.det := by
  sorry
```

:::solution
```lean
example {n : Type*} [Fintype n] [DecidableEq n] {k : Type*}
    [CommRing k] (M N : Matrix n n k) : (M * N).det = M.det * N.det :=
  Matrix.det_mul M N
```
:::

The problem "determinant detects isomorphism" says $`T` is invertible exactly when $`\det T \neq 0`.
Over a field the invertible elements are the nonzero ones, and Mathlib phrases the general statement with `IsUnit`: a matrix is invertible exactly when its determinant is.

```lean
example {n : Type*} [Fintype n] [DecidableEq n] {k : Type*}
    [CommRing k] (M : Matrix n n k) : IsUnit M ↔ IsUnit M.det := by
  sorry
```

:::solution
```lean
example {n : Type*} [Fintype n] [DecidableEq n] {k : Type*}
    [CommRing k] (M : Matrix n n k) : IsUnit M ↔ IsUnit M.det :=
  Matrix.isUnit_iff_isUnit_det M
```
:::

## Characteristic polynomials, and Cayley-Hamilton

The characteristic polynomial $`p_T(X) = \det(X \cdot \mathrm{id} - T)` of a matrix is `Matrix.charpoly`; it lives in the polynomial ring `Polynomial k`.

```lean
noncomputable example {n : Type*} [DecidableEq n] [Fintype n]
    {k : Type*} [CommRing k] (M : Matrix n n k) : Polynomial k :=
  M.charpoly
```

The Cayley-Hamilton theorem says $`p_T(T)` is the zero map.
Substituting the matrix into its own characteristic polynomial — through the algebra evaluation `Polynomial.aeval` — yields zero, and Mathlib records this as `Matrix.aeval_self_charpoly`.

```lean
example {n : Type*} [DecidableEq n] [Fintype n] {k : Type*} [CommRing k]
    (M : Matrix n n k) : Polynomial.aeval M M.charpoly = 0 := by
  sorry
```

:::solution
```lean
example {n : Type*} [DecidableEq n] [Fintype n] {k : Type*} [CommRing k]
    (M : Matrix n n k) : Polynomial.aeval M M.charpoly = 0 :=
  Matrix.aeval_self_charpoly M
```
:::
