import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.LinearAlgebra.Dual.Defs
import Mathlib.LinearAlgebra.Dual.Basis
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Contraction
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Trace

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

open scoped TensorProduct

set_option pp.rawOnError true

#doc (Manual) "Dual space and trace" =>

%%%
file := "Dual-space-and-trace"
%%%


You may have learned in high school that given a matrix $$`\begin{bmatrix} a & c \\ b & d \end{bmatrix}` the trace is the sum along the diagonals $`a + d` and the determinant is $`ad - bc`.
But we know that a matrix is somehow just encoding a linear map using a choice of basis.
Why would these random formulas somehow not depend on the choice of a basis?

In this chapter, we are going to give an intrinsic definition of $`\operatorname{Tr} T`, where $`T \colon V \to V` and $`\dim V < \infty`.
This will give a coordinate-free definition which will in particular imply the trace $`a + d` doesn't change if we take a different basis.

In doing so, we will introduce two new constructions: the _tensor product_ $`V \otimes W` (which is a sort of product of two spaces, with dimension $`\dim V \cdot \dim W`) and the _dual space_ $`V^\vee`, which is the set of linear maps $`V \to k` (a $`k`-vector space).
Later on, when we upgrade from a vector space $`V` to an inner product space, we will see that the dual space $`V^\vee` gives a nice interpretation of the "transpose" of a matrix.
You'll already see some of that come through here.

The trace is only defined for finite-dimensional vector spaces, so if you want you can restrict your attention to finite-dimensional vector spaces for this chapter.
(On the other hand we do not need the ground field to be algebraically closed.)

The next chapter will then do the same for the determinant.

# Tensor product

:::PROTOTYPE
$`\mathbb{R}[x] \otimes \mathbb{R}[y] = \mathbb{R}[x, y]`.
:::

We know that $`\dim(V \oplus W) = \dim V + \dim W`, even though as sets $`V \oplus W` looks like $`V \times W`.
What if we wanted a real "product" of spaces, with multiplication of dimensions?

For example, let's pull out my favorite example of a real vector space, namely $$`V = \{ax^2 + bx + c \mid a, b, c : \mathbb{R}\}.`
Here's another space, a little smaller: $$`W = \{dy + e \mid d, e : \mathbb{R}\}.`
If we take the direct sum, then we would get some rather unnatural vector space of dimension five (whose elements can be thought of as pairs $`(ax^2 + bx + c, dy + e)`).
But suppose we want a vector space whose elements are _products_ of polynomials in $`V` and $`W`; it would contain elements like $`4x^2 y + 5xy + y + 3`.
In particular, the basis would be $$`\{x^2 y, x^2, xy, x, y, 1\}` and thus have dimension six.

For this we resort to the _tensor product_.
It does exactly this, except that the "multiplication" is done by a scary{margin}[Seriously, $`\otimes` looks _terrifying_ to non-mathematicians, and even to many math undergraduates.] symbol $`\otimes`: think of it as a "wall" that separates the elements between the two vector spaces.
For example, the above example might be written as $$`4x^2 \otimes y + 5x \otimes y + 1 \otimes y + 3 \otimes 1.` (This should be read as $`(4x^2 \otimes y) + (5x \otimes y) + \dots`; addition comes after $`\otimes`.)
Of course there should be no distinction between writing $`4x^2 \otimes y` and $`x^2 \otimes 4y` or even $`2x^2 \otimes 2y`.
While we want to keep the $`x` and $`y` separate, the scalars should be free to float around.

Of course, there's no need to do everything in terms of just the monomials.
We are free to write $$`(x + 1) \otimes (y + 1).`
If you like, you can expand this as $$`x \otimes y + 1 \otimes y + x \otimes 1 + 1 \otimes 1.`
Same thing.
The point is that we can take any two of our polynomials and artificially "tensor" them together.

The definition of the tensor product does exactly this, and nothing else.{margin}[I'll only define this for vector spaces for simplicity. The definition for modules over a commutative ring $`R` is exactly the same.]

:::DEFINITION
Let $`V` and $`W` be vector spaces over the same field $`k`.
The *tensor product* $`V \otimes_k W` is the abelian group generated by elements of the form $`v \otimes w`, subject to relations $$`(v_1 + v_2) \otimes w = v_1 \otimes w + v_2 \otimes w` $$`v \otimes (w_1 + w_2) = v \otimes w_1 + v \otimes w_2` $$`(c \cdot v) \otimes w = v \otimes (c \cdot w).`
As a vector space, its action is given by $`c \cdot (v \otimes w) = (c \cdot v) \otimes w = v \otimes (c \cdot w)`.
:::

Here's another way to phrase the same idea.
We define a *pure tensor* as an element of the form $`v \otimes w` for $`v : V` and $`w : W`.
But we let the $`\otimes` wall be "permeable" in the sense that $$`(c \cdot v) \otimes w = v \otimes (c \cdot w) = c \cdot (v \otimes w)` and we let multiplication and addition distribute as we expect.
Then $`V \otimes W` consists of sums of pure tensors.

:::EXAMPLE "Infinite-dimensional example: two-variable polynomials"
Although it's not relevant to this chapter, this definition works equally well with infinite-dimensional vector spaces.
The best example might be $$`\mathbb{R}[x] \otimes_\mathbb{R} \mathbb{R}[y] = \mathbb{R}[x, y].`
That is, the tensor product of polynomials in $`x` with real polynomials in $`y` turns out to just be two-variable polynomials $`\mathbb{R}[x, y]`.
:::

:::REMARK "Warning on sums of pure tensors"
Remember the elements of $`V \otimes_k W` really are _sums_ of these pure tensors!
If you liked the previous example, this fact has a nice interpretation — not every polynomial in $`\mathbb{R}[x, y] = \mathbb{R}[x] \otimes_\mathbb{R} \mathbb{R}[y]` factors as a polynomial in $`x` times a polynomial in $`y` (i.e. as pure tensors $`f(x) \otimes g(y)`).
But they all can be written as sums of pure tensors $`x^a \otimes y^b`.
:::

As the example we gave suggested, the basis of $`V \otimes_k W` is literally the "product" of the bases of $`V` and $`W`.
In particular, this fulfills our desire that $`\dim(V \otimes_k W) = \dim V \cdot \dim W`.

:::PROPOSITION "Basis of V ⊗ W"
Let $`V` and $`W` be finite-dimensional $`k`-vector spaces.
If $`e_1, \dots, e_m` is a basis of $`V` and $`f_1, \dots, f_n` is a basis of $`W`, then the basis of $`V \otimes_k W` is precisely $`e_i \otimes f_j`, where $`i = 1, \dots, m` and $`j = 1, \dots, n`.
:::

:::PROOF
Omitted; it's easy at least to see that this basis is spanning.
:::

:::EXAMPLE "Explicit computation"
Let $`V` have basis $`e_1, e_2` and $`W` have basis $`f_1, f_2`.
Let $`v = 3e_1 + 4e_2 : V` and $`w = 5f_1 + 6f_2 : W`.
Let's write $`v \otimes w` in this basis for $`V \otimes_k W`: $$`v \otimes w = (3e_1 + 4e_2) \otimes (5f_1 + 6f_2)` $$`= 15(e_1 \otimes f_1) + 20(e_2 \otimes f_1) + 18(e_1 \otimes f_2) + 24(e_2 \otimes f_2).`
So you can see why tensor products are a nice "product" to consider if we're really interested in $`V \times W` in a way that's more intimate than just a direct sum.
:::

:::ABUSE
Moving forward, we'll almost always abbreviate $`\otimes_k` to just $`\otimes`, since $`k` is usually clear.
:::

:::REMARK
Observe that to define a linear map $`V \otimes W \to X`, I only have to say what happens to each pure tensor $`v \otimes w`, since the pure tensors _generate_ $`V \otimes W`.
But again, keep in mind that $`V \otimes W` consists of _sums_ of these pure tensors!
In other words, $`V \otimes W` is generated by pure tensors.
:::

:::REMARK
Much like the Cartesian product $`A \times B` of sets, you can tensor together any two vector spaces $`V` and $`W` over the same field $`k`; the relationship between $`V` and $`W` is completely irrelevant.
One can think of the $`\otimes` as a "wall" through which one can pass scalars in $`k`, but otherwise keeps the elements of $`V` and $`W` separated.
Thus, $`\otimes` is *content-agnostic*.

This also means that even if $`V` and $`W` have some relation to each other, the tensor product doesn't remember this.
So for example $`v \otimes 1 \neq 1 \otimes v`, just like $`(g, 1_G) \neq (1_G, g)` in the group $`G \times G`.
:::

# Dual space

:::PROTOTYPE
Rotate a column matrix by $`90` degrees.
:::

Consider the following vector space:

:::EXAMPLE "Functions from ℝ³ → ℝ"
The set of real functions $`f(x, y, z)` is an infinite-dimensional real vector space.
Indeed, we can add two functions to get $`f + g`, and we can think of functions like $`2f`.
:::

This is a terrifyingly large vector space, but you can do some reasonable reductions.
For example, you can restrict your attention to just the _linear maps_ from $`\mathbb{R}^3` to $`\mathbb{R}`.

That's exactly what we're about to do.
This definition might seem strange at first, but bear with me.

:::DEFINITION
Let $`V` be a $`k`-vector space.
Then $`V^\vee`, the *dual space* of $`V`, is defined as the vector space whose elements are _linear maps from $`V` to $`k`_.
:::

The addition and multiplication are pointwise: it's the same notation we use when we write $`cf + g` to mean $`c \cdot f(x) + g(x)`.
The dual space itself is less easy to think about.

Let's try to find a basis for $`V^\vee`.
First, here is a very concrete interpretation of the vector space.
Suppose for example $`V = \mathbb{R}^3`.
We can think of elements of $`V` as column matrices, like $$`v = \begin{bmatrix} 2 \\ 5 \\ 9 \end{bmatrix} : V.`
Then a linear map $`f \colon V \to k` can be interpreted as a _row matrix_: $$`f = \begin{bmatrix} 3 & 4 & 5 \end{bmatrix} : V^\vee.`
Then $$`f(v) = \begin{bmatrix} 3 & 4 & 5 \end{bmatrix} \begin{bmatrix} 2 \\ 5 \\ 9 \end{bmatrix} = 71.`

More precisely: *to specify a linear map $`V \to k`, I only have to tell you where each basis element of $`V` goes*.
In the above example, $`f` sends $`e_1` to $`3`, $`e_2` to $`4`, and $`e_3` to $`5`.
So $`f` sends $$`2e_1 + 5e_2 + 9e_3 \mapsto 2 \cdot 3 + 5 \cdot 4 + 9 \cdot 5 = 71.`

Let's make all this precise.

:::PROPOSITION "The dual basis for V∨"
Let $`V` be a finite-dimensional vector space with basis $`e_1, \dots, e_n`.
For each $`i` consider the function $`e_i^\vee \colon V \to k` defined by $$`e_i^\vee(e_j) = \begin{cases} 1 & i = j \\ 0 & i \neq j. \end{cases}`
In more humane terms, $`e_i^\vee(v)` gives the coefficient of $`e_i` in $`v`.

Then $`e_1^\vee, e_2^\vee, \dots, e_n^\vee` is a basis of $`V^\vee`.
:::

:::EXAMPLE "Explicit example of element in V∨"
In this notation, $`f = 3e_1^\vee + 4e_2^\vee + 5e_3^\vee`.
Do you see why the "sum" notation works as expected here?
Indeed $$`f(e_1) = (3e_1^\vee + 4e_2^\vee + 5e_3^\vee)(e_1) = 3 \cdot 1 + 4 \cdot 0 + 5 \cdot 0 = 3.`
That's exactly what we wanted.
:::

You might be inclined to point out that $`V \cong V^\vee` at this point, with an isomorphism given by $`e_i \mapsto e_i^\vee`.
You might call it "rotating the column matrix by $`90°`".

This statement is technically true, but for a generic vector space $`V` without any extra information, you can just think of this as an artifact of the $`\dim V = \dim V^\vee` (as _any_ two vector spaces of equal dimension are isomorphic).
Most importantly, the isomorphism given above depends on what basis you picked.

:::REMARK "Explicit example of unnatural V → V∨"
Alice or Bob are looking at the same two-dimensional real vector space $$`V = \{(x, y, z) \mid x + y + z = 0\}.`
Also, let $`v_{\text{example}} = (3, 5, -8)` be an example of an arbitrary element of $`V` for concreteness.

Suppose Alice chooses the following basis vectors for $`V`. $$`e_1 = (1, 0, -1), \qquad e_2 = (0, 1, -1).`
Alice uses this to construct an isomorphism $`A \colon V \to V^\vee` as described above, and considers $`e_1^\vee = A(e_1)`.
The element $`e_1^\vee : V^\vee` is a function $`e_1^\vee \colon V \to \mathbb{R}`, meaning Alice can plug any vector in $`V` into it.
As an example, for $`v_{\text{example}}` $$`e_1^\vee(v_{\text{example}}) = e_1^\vee((3, 5, -8)) = e_1^\vee(3e_1 + 5e_2) = 3.`
Meanwhile, Bob chooses the different basis vectors $$`f_1 = (1, 0, -1), \qquad f_2 = (1, -1, 0).`
This gives Bob an isomorphism $`B \colon V \to V^\vee`, and a corresponding $`f_1^\vee = B(f_1)`.
Bob can also evaluate it anywhere, e.g. $$`f_1^\vee(v_{\text{example}}) = f_1^\vee((3, 5, -8)) = f_1^\vee(8f_1 - 5f_2) = 8.`

It follows that $`e_1^\vee = A((1, 0, -1))` and $`f_1^\vee = B((1, 0, -1))` are different elements of $`V^\vee`.
In other words Alice and Bob got different isomorphisms because they picked different bases.
:::

# V∨ ⊗ W gives matrices from V to W

Goal of this section:

:::MORAL
If $`V` and $`W` are finite-dimensional $`k`-vector spaces then $`V^\vee \otimes W` represents linear maps $`V \to W`.
:::

Here's the intuition.
If $`V` is three-dimensional and $`W` is five-dimensional, then we can think of the maps $`V \to W` as a $`5 \times 3` array of numbers.
We want to think of these maps as a vector space (since one can add or scale matrices).
So it had better be a vector space with dimension $`15`, but just saying "$`k^{\oplus 15}`" is not really that satisfying (what is the basis?).

To do better, we consider the tensor product $$`V^\vee \otimes W` which somehow is a product of maps out of $`V` and the target space $`W`.
We claim that this is in fact the space we want: i.e. *there is a natural bijection between elements of $`V^\vee \otimes W` and linear maps from $`V` to $`W`*.

First, how do we interpret an element of $`V^\vee \otimes W` as a map $`V \to W`?
For concreteness, suppose $`V` has a basis $`e_1, e_2, e_3`, and $`W` has a basis $`f_1, f_2, f_3, f_4, f_5`.
Consider an element of $`V^\vee \otimes W`, say $$`e_1^\vee \otimes (f_2 + 2f_4) + 4e_2^\vee \otimes f_5.`
We want to interpret this element as a function $`V \to W`: so given a $`v : V`, we want to output an element of $`W`.
There's really only one way to do this: feed $`v : V` into the $`V^\vee` guys on the left.
That is, take the map $$`v \mapsto e_1^\vee(v) \cdot (f_2 + 2f_4) + 4e_2^\vee(v) \cdot f_5 : W.`
So, there's a natural way to interpret any element $`\xi_1 \otimes w_1 + \dots + \xi_m \otimes w_m : V^\vee \otimes W` as a linear map $`V \to W`.
The claim is that in fact, every linear map $`V \to W` has such an interpretation.

First, for notational convenience,

:::DEFINITION
Let $`\operatorname{Hom}(V, W)` denote the set of linear maps from $`V` to $`W` (which one can interpret as matrices which send $`V` to $`W`), viewed as a vector space over $`k`.
(The "$`\operatorname{Hom}`" stands for homomorphism.)
:::

:::QUESTION
Identify $`\operatorname{Hom}(V, k)` by name.
:::

We can now write down something that's more true generally.

:::THEOREM "V∨ ⊗ W ⟺ linear maps V → W"
Let $`V` and $`W` be finite-dimensional vector spaces.
We described a map $$`\Psi \colon V^\vee \otimes W \to \operatorname{Hom}(V, W)` by sending $`\xi_1 \otimes w_1 + \dots + \xi_m \otimes w_m` to the linear map $$`v \mapsto \xi_1(v) w_1 + \dots + \xi_m(v) w_m.`
Then $`\Psi` is an isomorphism of vector spaces, i.e. every linear map $`V \to W` can be uniquely represented as an element of $`V^\vee \otimes W` in this way.
:::

The above is perhaps a bit dense, so here is a concrete example.

:::EXAMPLE "Explicit example"
Let $`V = \mathbb{R}^2` and take a basis $`e_1, e_2` of $`V`.
Then define $`T \colon V \to V` by $$`T = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}.`
Then we have $$`\Psi(e_1^\vee \otimes e_1 + 2e_2^\vee \otimes e_1 + 3e_1^\vee \otimes e_2 + 4e_2^\vee \otimes e_2) = T.`
The beauty is that the $`\Psi` definition is basis-free; thus even if we change the basis, although the above expression will look completely different, the _actual element_ in $`V^\vee \otimes V` doesn't change.
:::

Despite this, we'll indulge ourselves in using coordinates for the proof.

:::PROOF
This looks intimidating, but it's actually not difficult.
We proceed in two steps:

1. First, we check that $`\Psi` is _surjective_; every linear map has at least one representation in $`V^\vee \otimes W`.
   To see this, take any $`T \colon V \to W`.
   Suppose $`V` has basis $`e_1, e_2, e_3` and that $`T(e_1) = w_1`, $`T(e_2) = w_2` and $`T(e_3) = w_3`.
   Then the element $`e_1^\vee \otimes w_1 + e_2^\vee \otimes w_2 + e_3^\vee \otimes w_3` works, as it is contrived to agree with $`T` on the basis elements $`e_i`.
2. So it suffices to check now that $`\dim V^\vee \otimes W = \dim \operatorname{Hom}(V, W)`.
   Certainly, $`V^\vee \otimes W` has dimension $`\dim V \cdot \dim W`.
   But by viewing $`\operatorname{Hom}(V, W)` as $`\dim V \cdot \dim W` matrices, we see that it too has dimension $`\dim V \cdot \dim W`.
:::

So there is a *natural isomorphism* $`V^\vee \otimes W \cong \operatorname{Hom}(V, W)`.
While we did use a basis liberally in the _proof that it works_, this doesn't change the fact that the isomorphism is "God-given", depending only on the spirit of $`V` and $`W` itself and not which basis we choose to express the vector spaces in.

# The trace

We are now ready to give the definition of a trace.
Recall that a square matrix $`T` can be thought of as a map $`T \colon V \to V`.
According to the above theorem, $$`\operatorname{Hom}(V, V) \cong V^\vee \otimes V` so every map $`V \to V` can be thought of as an element of $`V^\vee \otimes V`.
But we can also define an _evaluation map_ $`\operatorname{ev} \colon V^\vee \otimes V \to k` by "collapsing" each pure tensor: $`f \otimes v \mapsto f(v)`.
So this gives us a composed map $$`\operatorname{Hom}(V, V) \xrightarrow{\cong} V^\vee \otimes V \xrightarrow{\operatorname{ev}} k.`
This result is called the *trace* of a matrix $`T`.

:::EXAMPLE "Example of a trace"
Continuing the previous example, $$`\operatorname{Tr} T = e_1^\vee(e_1) + 2e_2^\vee(e_1) + 3e_1^\vee(e_2) + 4e_2^\vee(e_2) = 1 + 0 + 0 + 4 = 5.`
And that is why the trace is the sum of the diagonal entries.
:::

# Problems

:::PROBLEM "Trace is sum of eigenvalues"
Let $`V` be an $`n`-dimensional vector space over an algebraically closed field $`k`.
Let $`T \colon V \to V` be a linear map with eigenvalues $`\lambda_1, \lambda_2, \dots, \lambda_n` (counted with algebraic multiplicity).
Show that $`\operatorname{Tr} T = \lambda_1 + \dots + \lambda_n`.
:::

:::PROBLEM "Product of traces"
Let $`T \colon V \to V` and $`S \colon W \to W` be linear maps of finite-dimensional vector spaces $`V` and $`W`.
Define $`T \otimes S \colon V \otimes W \to V \otimes W` by $`v \otimes w \mapsto T(v) \otimes S(w)`.
Prove that $$`\operatorname{Tr}(T \otimes S) = \operatorname{Tr}(T) \operatorname{Tr}(S).`
:::

:::PROBLEM "Traces kind of commute" (chili := 1)
Let $`T \colon V \to W` and $`S \colon W \to V` be linear maps between finite-dimensional vector spaces $`V` and $`W`.
Show that $$`\operatorname{Tr}(T \circ S) = \operatorname{Tr}(S \circ T).`
:::

:::PROBLEM "Putnam 1988" (chili := 1)
Let $`V` be an $`n`-dimensional vector space.
Let $`T \colon V \to V` be a linear map and suppose there exist $`n + 1` eigenvectors, any $`n` of which are linearly independent.
Does it follow that $`T` is a scalar multiple of the identity?
:::

# Formalization

:::LEANCOMPANION
:::

## Tensor product

`TensorProduct k V W`, written `V ⊗[k] W`, is this tensor product of `k`-modules; a pure tensor $`v \otimes w` is written `v ⊗ₜ[k] w`.

```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V]
    [AddCommGroup W] [Module k W] : Type _ := TensorProduct k V W
```

The permeable "wall" — scalars pass through $`\otimes` freely — and the distributivity of pure tensors over addition are the defining relations, available as `smul_tmul` and `add_tmul`.

```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (c : k) (v : V) (w : W) : (c • v) ⊗ₜ[k] w = v ⊗ₜ[k] (c • w) :=
  TensorProduct.smul_tmul c v w

example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (v₁ v₂ : V) (w : W) : (v₁ + v₂) ⊗ₜ[k] w = v₁ ⊗ₜ[k] w + v₂ ⊗ₜ[k] w :=
  TensorProduct.add_tmul v₁ v₂ w
```

Those relations really are *all* you get: every other identity between pure tensors has to be squeezed out of them.
Squeeze out the first one, that $`0 \otimes w = 0`.
The trick is the usual one for showing something is an additive identity: use distributivity on $`0 = 0 + 0` to get $`0 \otimes w = 0 \otimes w + 0 \otimes w`, then cancel (`add_eq_left` turns `a + b = a` into `b = 0`).

```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (w : W) : (0 : V) ⊗ₜ[k] w = 0 := by
  sorry
```

:::solution
```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (w : W) : (0 : V) ⊗ₜ[k] w = 0 := by
  -- Distributivity applied to `0 = 0 + 0` makes the element absorb itself.
  have h : (0 : V) ⊗ₜ[k] w = (0 : V) ⊗ₜ[k] w + (0 : V) ⊗ₜ[k] w := by
    rw [← TensorProduct.add_tmul, add_zero]
  exact add_eq_left.mp h.symm
```
:::

A warning that the notation hides: a general element of $`V \otimes_k W` is *not* a pure tensor $`v \otimes w`, only a finite sum of them.
That "only a finite sum" is a theorem, and it is the single most useful fact about tensor products: the pure tensors span.
Prove it.
The statement is that the span of $`\{v \otimes w\}` is everything, and the proof is the recursion principle `TensorProduct.induction_on`, which builds an arbitrary tensor out of `zero`, `tmul`, and `add` — exactly the three cases you must supply.
(Start from `Submodule.eq_top_iff'`, which reduces `= ⊤` to membership of an arbitrary element.)

```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W] :
    Submodule.span k {t : V ⊗[k] W | ∃ v w, v ⊗ₜ[k] w = t} = ⊤ := by
  sorry
```

:::solution
```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W] :
    Submodule.span k {t : V ⊗[k] W | ∃ v w, v ⊗ₜ[k] w = t} = ⊤ := by
  refine Submodule.eq_top_iff'.mpr fun t => ?_
  induction t using TensorProduct.induction_on with
  | zero => exact Submodule.zero_mem _
  | tmul v w => exact Submodule.subset_span ⟨v, w, rfl⟩
  | add x y hx hy => exact Submodule.add_mem _ hx hy
```
:::

Mathlib knows this as `TensorProduct.span_tmul_eq_top`, and it is what makes the induction principle above so effective: to prove *anything* about all tensors, it is enough to handle pure ones and check that the property survives addition.
The dimension count $`\dim(V \otimes_k W) = \dim V \cdot \dim W` is `Module.finrank_tensorProduct`.

```lean
example (k V W : Type*) [Field k]
    [AddCommGroup V] [Module k V] [FiniteDimensional k V]
    [AddCommGroup W] [Module k W] [FiniteDimensional k W] :
    Module.finrank k (V ⊗[k] W) = Module.finrank k V * Module.finrank k W :=
  Module.finrank_tensorProduct
```

## Dual space

`Module.Dual k V` is the type of linear maps `V → k`, viewed as a $`k`-module.

```lean
example (k V : Type*) [Field k] [AddCommGroup V] [Module k V] :
    Type _ := Module.Dual k V
```

Since $`\dim V^\vee = \dim V`, the two spaces are isomorphic (though not naturally so); the equality of dimensions is `Subspace.dual_finrank_eq`.

```lean
example (k V : Type*) [Field k] [AddCommGroup V] [Module k V] :
    Module.finrank k (Module.Dual k V) = Module.finrank k V :=
  Subspace.dual_finrank_eq
```

Given a basis $`e_1, \dots, e_n` of $`V`, its dual basis `Module.Basis.dualBasis` consists of the coordinate functions $`e_i^\vee`, characterized by $`e_i^\vee(e_j) = 1` when $`i = j` and $`0` otherwise — that defining property is `Module.Basis.dualBasis_apply_self`.

```lean
example (k V ι : Type*) [Field k] [AddCommGroup V] [Module k V]
    [DecidableEq ι] [Fintype ι] (b : Module.Basis ι k V) (i j : ι) :
    b.dualBasis i (b j) = if j = i then 1 else 0 :=
  b.dualBasis_apply_self i j
```

Calling $`e_i^\vee` a *basis* of $`V^\vee` means every functional is a combination of them, and the coefficients are forced: expanding $`f` in the dual basis must reproduce the values $`f(e_i)`.
Prove that expansion, $`f = \sum_i f(e_i) \, e_i^\vee`.
Any basis expansion starts from `Module.Basis.sum_repr`, which rebuilds a vector — here the vector is $`f` and the basis is `b.dualBasis` — from its coordinates; rewriting *backwards* with it turns the bare `f` on the left into a sum.
What identifies those coordinates as the values $`f(e_i)` is `Module.Basis.dualBasis_repr`.

```lean
example (k V ι : Type*) [Field k] [AddCommGroup V] [Module k V]
    [DecidableEq ι] [Fintype ι] (b : Module.Basis ι k V) (f : Module.Dual k V) :
    f = ∑ i, f (b i) • b.dualBasis i := by
  sorry
```

:::solution
```lean
example (k V ι : Type*) [Field k] [AddCommGroup V] [Module k V]
    [DecidableEq ι] [Fintype ι] (b : Module.Basis ι k V) (f : Module.Dual k V) :
    f = ∑ i, f (b i) • b.dualBasis i := by
  -- Only the left side is rewritten, or the rewrite would loop on the sum.
  conv_lhs => rw [← b.dualBasis.sum_repr f]
  simp [Module.Basis.dualBasis_repr]
```
:::

## V∨ ⊗ W gives matrices from V to W

The question asked us to name $`\operatorname{Hom}(V, k)`: it is exactly the dual space $`V^\vee`, true by definition.

```lean
example (k V : Type*) [Field k] [AddCommGroup V] [Module k V] :
    Module.Dual k V = (V →ₗ[k] k) := rfl
```

The map $`\Psi \colon V^\vee \otimes W \to \operatorname{Hom}(V, W)` is `dualTensorHom`, and when $`V` and $`W` are finite-dimensional it upgrades to the isomorphism `dualTensorHomEquiv`.

```lean
noncomputable example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W] :
    Module.Dual k V ⊗[k] W →ₗ[k] V →ₗ[k] W := dualTensorHom k V W

noncomputable example (k V W : Type*) [Field k]
    [AddCommGroup V] [Module k V] [FiniteDimensional k V]
    [AddCommGroup W] [Module k W] [FiniteDimensional k W] :
    Module.Dual k V ⊗[k] W ≃ₗ[k] (V →ₗ[k] W) := dualTensorHomEquiv k V W
```

Interpreting a pure tensor $`f \otimes w` as a map sends $`v` to $`f(v) \cdot w`, which is `dualTensorHom_apply`.

```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (f : Module.Dual k V) (w : W) (v : V) :
    dualTensorHom k V W (f ⊗ₜ[k] w) v = f v • w :=
  dualTensorHom_apply f v w
```

Read that formula again: whatever $`v` is fed in, the output is a *multiple of the single vector* $`w`.
So a pure tensor corresponds to a matrix of rank at most one, which is why the pure tensors are so far from being all of $`V^\vee \otimes W`, and why a general matrix needs a sum of them.
Make that precise: show the image of $`\Psi(f \otimes w)` lies in the line spanned by $`w`.
Take an arbitrary element of the range apart with `rintro _ ⟨v, rfl⟩` — a range membership is a witness $`v` together with the equation naming the output — then rewrite with the formula above and note that a span is closed under scaling (`Submodule.smul_mem`, applied to `Submodule.mem_span_singleton_self`).

```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (f : Module.Dual k V) (w : W) :
    LinearMap.range (dualTensorHom k V W (f ⊗ₜ[k] w))
      ≤ Submodule.span k {w} := by
  sorry
```

:::solution
```lean
example (k V W : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    (f : Module.Dual k V) (w : W) :
    LinearMap.range (dualTensorHom k V W (f ⊗ₜ[k] w))
      ≤ Submodule.span k {w} := by
  rintro _ ⟨v, rfl⟩
  rw [dualTensorHom_apply]
  exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self w)
```
:::

## The trace

`LinearMap.trace k V` is the basis-free trace on `End k V` (for finite-dimensional `V`).

```lean
noncomputable example (k V : Type*)
    [CommRing k] [AddCommGroup V] [Module k V] :
    (V →ₗ[k] V) →ₗ[k] k := LinearMap.trace k V
```

Along the composition $`\operatorname{Hom}(V, V) \xrightarrow{\cong} V^\vee \otimes V \xrightarrow{\operatorname{ev}} k`, the trace of the map coming from a pure tensor $`f \otimes v` is the evaluation $`f(v)`, since the evaluation map `contractLeft` collapses $`f \otimes v \mapsto f(v)`.

```lean
example (k V : Type*) [Field k] [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] (f : Module.Dual k V) (v : V) :
    LinearMap.trace k V (dualTensorHom k V V (f ⊗ₜ[k] v)) = f v := by
  rw [LinearMap.trace_eq_contract_apply, contractLeft_apply]
```

The problem "Traces kind of commute" asks that $`\operatorname{Tr}(T \circ S) = \operatorname{Tr}(S \circ T)` for $`T \colon V \to W` and $`S \colon W \to V`; this is `LinearMap.trace_comp_comm'`.

```lean
example (k V W : Type*) [Field k]
    [AddCommGroup V] [Module k V] [FiniteDimensional k V]
    [AddCommGroup W] [Module k W] [FiniteDimensional k W]
    (f : V →ₗ[k] W) (g : W →ₗ[k] V) :
    LinearMap.trace k V (g ∘ₗ f) = LinearMap.trace k W (f ∘ₗ g) :=
  LinearMap.trace_comp_comm' f g
```

That innocuous-looking commutation is the workhorse of the whole theory, because it is what makes the trace *basis-independent*: changing basis replaces $`T` by $`u T u^{-1}`, and cycling $`u^{-1}` around to the front cancels it.
Prove that invariance.
Reassociate first — `LinearMap.comp_assoc` regroups $`u \circ (T \circ u^{-1})` as $`(u \circ T) \circ u^{-1}` — and then a single application of the commutation above moves $`u^{-1}` to the front, where `simp` can cancel it against $`u`.

```lean
example (k V : Type*) [Field k] [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] (f : V →ₗ[k] V) (u : V ≃ₗ[k] V) :
    LinearMap.trace k V ((u : V →ₗ[k] V) ∘ₗ f ∘ₗ (u.symm : V →ₗ[k] V))
      = LinearMap.trace k V f := by
  sorry
```

:::solution
```lean
example (k V : Type*) [Field k] [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] (f : V →ₗ[k] V) (u : V ≃ₗ[k] V) :
    LinearMap.trace k V ((u : V →ₗ[k] V) ∘ₗ f ∘ₗ (u.symm : V →ₗ[k] V))
      = LinearMap.trace k V f := by
  -- Regroup as `(u ∘ f) ∘ u⁻¹`, then cycle `u⁻¹` to the front.
  rw [← LinearMap.comp_assoc, LinearMap.trace_comp_comm']
  simp
```
:::

(Mathlib has this packaged as `LinearMap.trace_conj'`, but the two-line derivation is the point: everything the trace knows is a consequence of linearity plus cycling.)

Here is a famous payoff, and a good test of both.
On a finite-dimensional space there is *no* pair of operators with $`AB - BA = 1`; equivalently, the canonical commutation relation of quantum mechanics has no finite-dimensional model.
The argument is three lines of trace bookkeeping: the trace of the left side is $`0` because the trace is linear (`map_sub`) and cycles, while the trace of the identity is $`\dim V` (`LinearMap.trace_one`), which is nonzero in characteristic $`0` whenever $`V \neq 0`.
Finish it: from `(finrank k V : k) = 0` get `finrank k V = 0` by `Nat.cast_eq_zero` (this is where `CharZero k` is used), and contradict `Module.finrank_pos`.

```lean
example (k V : Type*) [Field k] [CharZero k] [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] [Nontrivial V] (A B : V →ₗ[k] V) :
    A ∘ₗ B - B ∘ₗ A ≠ 1 := by
  sorry
```

:::solution
```lean
example (k V : Type*) [Field k] [CharZero k] [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] [Nontrivial V] (A B : V →ₗ[k] V) :
    A ∘ₗ B - B ∘ₗ A ≠ 1 := by
  intro h
  -- Linearity plus cycling kill the commutator's trace.
  have h1 : LinearMap.trace k V (A ∘ₗ B - B ∘ₗ A) = 0 := by
    rw [map_sub, LinearMap.trace_comp_comm' A B, sub_self]
  -- But the supposed value `1` has trace `dim V ≠ 0`.
  rw [h, LinearMap.trace_one] at h1
  exact (Module.finrank_pos (R := k) (M := V)).ne' (Nat.cast_eq_zero.mp h1)
```
:::
