import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Recall
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.MeasureTheory.OuterMeasure.Basic
import Mathlib.MeasureTheory.OuterMeasure.Caratheodory
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.MeasureTheory.Measure.Hausdorff

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Constructing the Borel and Lebesgue measure" =>

%%%
file := "Constructing-the-Borel-and-Lebesgue-measure"
%%%

It's very difficult to define in one breath a measure on the Borel space $`\mathcal{B}(\mathbb{R}^n)`.
It is easier if we define a weaker notion first.
There are two such weaker notions that we will define:

- A *pre-measure*: satisfies the axioms of a measure, but defined on *fewer* sets than a measure: they'll be defined on an "algebra" rather than the full-fledged "$`\sigma`-algebra".
- An *outer measure*: defined on $`2^\Omega` but satisfies weaker axioms.

It will turn out that pre-measures yield outer measures, and outer measures yield measures.

# Pre-measures

:::PROTOTYPE
Let $`\Omega = \mathbb{R}^2`.
Then we take $`\mathcal{A}_0` generated by rectangles, with $`\mu_0` the usual area.
:::

The way to define a pre-measure is to weaken the $`\sigma`-algebra to an algebra.

:::DEFINITION
Let $`\Omega` be a set.
We define notions of an *algebra*, which is the same as $`\sigma`-algebra except with "countable" replaced by finite everywhere.

That is: an algebra $`\mathcal{A}_0` on $`\Omega` is a nonempty subset of $`2^\Omega`, which is closed under complement and *finite* union.
The smallest algebra containing a subset $`\mathcal{F} \subseteq 2^\Omega` is the *algebra generated by $`\mathcal{F}`*.
:::

`MeasureTheory.IsSetAlgebra` is the Mathlib predicate, and `MeasureTheory.AddContent` (the content built on a set algebra) is the closest thing Mathlib carries to a "pre-measure on an algebra"; the Carathéodory machinery in `Mathlib.MeasureTheory.OuterMeasure.OfFunction` and `MeasureTheory.OuterMeasure.toMeasure` then turns this into a Mathlib `Measure`.

In practice, we will basically always use generation for algebras.

::::EXAMPLE
When $`\Omega = \mathbb{R}^n`, we can let $`\mathcal{L}_0` be the algebra generated by $`[a_1, b_1] \times \dots \times [a_n, b_n]`.
A typical element might look like:

:::figure "figures/measure-theory/algebra-element.svg"
:::

Unsurprisingly, since we have *finitely* many rectangles and their complements involved, in this case we actually *can* unambiguously assign an area, and will do so soon.
::::

:::DEFINITION
A *pre-measure* $`\mu_0` on a algebra $`\mathcal{A}_0` is a function $`\mu_0 \colon \mathcal{A}_0 \to [0, +\infty]` which satisfies the axioms

- $`\mu_0(\varnothing) = 0`, and
- *Countable additivity*: if $`A_1`, $`A_2`, … are disjoint sets in $`\mathcal{A}_0` and *moreover* the disjoint union $`\bigsqcup A_i` is contained in $`\mathcal{A}_0` (not guaranteed by algebra axioms!), then
  $$`\mu_0\left(\bigsqcup_n A_n\right) = \sum_n \mu_0(A_n).`
:::

:::EXAMPLE "The pre-measure on $`\\mathbb{R}^n`"
Let $`\Omega = \mathbb{R}^2`.
Then, let $`\mathcal{L}_0` be the algebra generated by rectangles $`[a_1, a_2] \times [b_1, b_2]`.
We then let
$$`\mu_0([a_1, a_2] \times [b_1, b_2]) = (a_2 - a_1)(b_2 - b_1)`
the area of the rectangle.
As elements of $`\mathcal{L}_0` are simply *finite* unions of rectangles and their complements (picture drawn earlier), it's not difficult to extend this to a pre-measure $`\lambda_0` which behaves as you expect — although we won't do this.
:::

Since we are sweeping something under the rug that turns out to be conceptually important, I'll go ahead and blue-box it.

:::PROPOSITION "Geometry sanity check that we won't prove"
For $`\Omega = \mathbb{R}^n` and $`\mathcal{L}_0` the algebra generated by rectangular prisms, one can define a pre-measure $`\lambda_0` on $`\mathcal{L}_0`.
:::

From this point forwards, we will basically do almost no geometry whatsoever in defining the measure $`\mathcal{B}(\mathbb{R}^n)`, and only use set theory to extend our measure.
So, the proposition above is the only sentry which checks to make sure that our "initial definition" is sane.

To put the point another way, suppose an *insane scientist* tried to define a notion of area in which every rectangle had area $`1`.
Intuitively, this shouldn't be possible: every rectangle can be dissected into two halves and we ought to have $`1 + 1 \neq 1`.
However, the only thing that would stop them is that they couldn't extend their pre-measure on the algebra $`\mathcal{L}_0`.
If they somehow got past that barrier and got a pre-measure, nothing in the rest of the section would prevent them from getting an entire *bona fide* measure with this property.
Thus, in our construction of the Lebesgue measure, most of the geometric work is captured in the (omitted) proof of that proposition.

# Outer measures

:::PROTOTYPE
Keep taking $`\Omega = \mathbb{R}^2`; see the picture to follow.
:::

The other way to weaken a measure is to relax the countable additivity, and this yields the following:

:::DEFINITION
An *outer measure* $`\mu^*` on a set $`\Omega` is a function $`\mu^* \colon 2^\Omega \to [0, +\infty]` satisfying the following axioms:

- $`\mu^*(\varnothing) = 0`;
- if $`E \subseteq F` and $`E, F \in 2^\Omega` then $`\mu^*(E) \leq \mu^*(F)`;
- for any subsets $`E_1`, $`E_2`, … of $`\Omega` we have
  $$`\mu^*\left(\bigcup_n E_n\right) \leq \sum_n \mu^*(E_n).`

(I don't really like the word "outer measure", since I think it is a bit of a misnomer: I would rather call it "fake measure", since it's not a measure either.)
:::

`MeasureTheory.OuterMeasure Ω` is Mathlib's outer measure structure: a function `Set Ω → ℝ≥0∞` carrying exactly these three axioms (`empty`, `mono`, and `iUnion_nat` for countable subadditivity) as fields.

```lean
example (Ω : Type*) : Type _ := MeasureTheory.OuterMeasure Ω
```

The reason for the name "outer measure" is that you almost always obtain outer measures by approximating them from "outside" sets.
Officially, the result is often stated as follows:

> For a set $`\Omega`, let $`\mathcal{E}` be *any* subset of $`2^\Omega` and let $`\rho \colon \mathcal{E} \to [0, +\infty]` be *any* function.
> Then
> $$`\mu^*(E) = \inf\left\{\sum_{n=1}^\infty \rho(E_n) \mid E_n \in \mathcal{E}, \; E \subseteq \bigcup_{n=1}^\infty E_n\right\}`
> is an outer measure.

However, I think the above theorem is basically always wrong to use in practice, because it is *way too general*.
As I warned with the insane scientist, we really do want some sort of sanity conditions on $`\rho`: otherwise, if we apply the above result as stated, there is no guarantee that $`\mu^*` will be compatible with $`\rho` in any way.

So, I think it is really better to apply the theorem to pre-measures $`\mu_0` for which one *does* have some sort of guarantee that the resulting $`\mu^*` is compatible with $`\mu_0`.
In practice, this is always how we will want to construct our outer measures.

:::THEOREM "Constructing outer measures from pre-measures"
Let $`\mu_0` be a pre-measure on an algebra $`\mathcal{A}_0` on a set $`\Omega`.

- The map $`\mu^* \colon 2^\Omega \to [0, +\infty]` defined by
  $$`\mu^*(E) = \inf\left\{\sum_{n=1}^\infty \mu_0(A_n) \mid A_n \in \mathcal{A}_0, \; E \subseteq \bigcup_{n=1}^\infty A_n\right\}`
  is an outer measure.
- Moreover, this measure agrees with $`\mu_0` on sets in $`\mathcal{A}_0`.
:::

`MeasureTheory.OuterMeasure.ofFunction` packages exactly this construction in Mathlib: given a function `m : Set Ω → ℝ≥0∞` with `m ∅ = 0`, it produces the inf-of-coverings outer measure.
The compatibility statement in part (b) is `MeasureTheory.OuterMeasure.ofFunction_eq` (specialized to the case where the input function is a pre-measure on an algebra).

Intuitively, what is going on is that $`\mu^*(A)` is the infimum of coverings of $`A` by countable unions of elements in $`\mathcal{A}_0`.
Part (b) is the first half of the compatibility condition I promised; the other half appears later.

::::PROOF
As alluded to already, part (a) is a special case of the more general "construction from arbitrary $`\rho`" theorem stated above (and proving it in this generality is actually easier, because you won't be distracted by unnecessary properties).

We now check (b), that $`\mu^*(A) = \mu_0(A)` for $`A \in \mathcal{A}_0`.
One bound is quick:

:::QUESTION
Show that $`\mu^*(A) \leq \mu_0(A)`.
:::

For the reverse, suppose that $`A \subseteq \bigcup_n A_n`.
Then, define the sets
$$`\begin{aligned} B_1 &= A \cap A_1 \\ B_2 &= (A \cap A_2) \setminus B_1 \\ B_3 &= (A \cap A_3) \setminus (B_1 \cup B_2) \\ &\vdots \end{aligned}`
and so on.
Then the $`B_n` are disjoint elements of $`\mathcal{A}_0` with $`B_n \subset A_n`, and we have rigged the definition so that $`\bigsqcup_n B_n = A`.
Thus by definition of pre-measure,
$$`\mu_0(A) = \sum_n \mu_0(B_n) \leq \sum_n \mu_0(A_n)`
as desired.
::::

:::EXAMPLE
Let $`\Omega = \mathbb{R}^2` and $`\lambda_0` the pre-measure from before.
Then $`\lambda^*(A)` is, intuitively, the infimum of coverings of the set $`A` by rectangles.
:::

# Carathéodory extension for outer measures

We will now take any outer measure and turn it into a proper measure.
To do this, we first need to specify the $`\sigma`-algebra on which we will define the measure.

:::DEFINITION
Let $`\mu^*` be an outer measure.
We say a set $`A` is *Carathéodory measurable with respect to $`\mu^*`*, or just *$`\mu^*`-measurable*, if the following condition holds: for any set $`E \in 2^\Omega`,
$$`\mu^*(E) = \mu^*(E \cap A) + \mu^*(E \setminus A).`
:::

`MeasureTheory.OuterMeasure.IsCaratheodory μ A` is Mathlib's predicate for exactly this condition; the resulting `σ`-algebra is `MeasureTheory.OuterMeasure.caratheodory μ : MeasurableSpace Ω`.

```lean
example {Ω : Type*} (μ : MeasureTheory.OuterMeasure Ω) :
    MeasurableSpace Ω :=
  μ.caratheodory
```

This definition is hard to motivate, but turns out to be the right one.
One way to motivate is this: it turns out that in $`\mathbb{R}^n`, it will be equivalent to a reasonable geometric condition (which I will state in a moment), but since that geometric definition requires information about $`\mathbb{R}^n` itself, this is the "right" generalization for general measure spaces.

Since our goal was to extend our $`\mathcal{A}_0`, we had better make sure this definition lets us measure the initial sets that we started with!

:::PROPOSITION "Carathéodory measurability is compatible with the initial $`\\mathcal{A}_0`"
Suppose $`\mu^*` was obtained from a pre-measure $`\mu_0` on an algebra $`\mathcal{A}_0`, as in the construction above.
Then every set in $`\mathcal{A}_0` is $`\mu^*`-measurable.
:::

This is the second half of the compatibility condition that we get if we make sure our initial $`\mu_0` at least satisfies the pre-measure axioms.

:::PROOF
Let $`A \in \mathcal{A}_0` and $`E \in 2^\Omega`; we wish to prove $`\mu^*(E) = \mu^*(E \cap A) + \mu^*(E \setminus A)`.
The definition of outer measure already requires $`\mu^*(E) \leq \mu^*(E \cap A) + \mu^*(E \setminus A)` and so it's enough to prove the reverse inequality.

By definition of infimum, for any $`\varepsilon > 0`, there is a covering $`E \subset \bigcup_n A_n` with $`\mu^*(E) + \varepsilon \geq \sum_n \mu_0(A_n)`.
But
$$`\sum_n \mu_0(A_n) = \sum_n (\mu_0(A_n \cap A) + \mu_0(A_n \setminus A)) \geq \mu^*(E \cap A) + \mu^*(E \setminus A)`
with the first equality being the definition of pre-measure on $`\mathcal{A}_0`, the second just being by definition of $`\mu^*` (since $`A_n \cap A` certainly covers $`E \cap A`, for example).
Thus $`\mu^*(E) + \varepsilon \geq \mu^*(E \cap A) + \mu^*(E \setminus A)`.
Since the inequality holds for any $`\varepsilon > 0`, we're done.
:::

To add extra icing onto the cake, here is one more niceness condition which our constructed measure will happen to satisfy.

:::DEFINITION
A *null set* of a measure space $`(\Omega, \mathcal{A}, \mu)` is a set $`A \in \mathcal{A}` with $`\mu(A) = 0`.
A measure space $`(\Omega, \mathcal{A}, \mu)` is *complete* if whenever $`A` is a null set, then all subsets of $`A` are in $`\mathcal{A}` as well (and hence null sets).
:::

`MeasureTheory.Measure.IsComplete μ` and the `[CompleteMeasure μ]` typeclass package this in Mathlib.

This is a nice property to have, for obvious reasons.
Visually, if I have a bunch of dust which I *already* assigned weight zero, and I blow away some of the dust, then the remainder should still have an assigned weight — zero.
The extension theorem will give us $`\sigma`-algebras with this property.

:::THEOREM "Carathéodory extension theorem for outer measures"
If $`\mu^*` is an outer measure, and $`\mathcal{A}^{\text{cm}}` is the set of $`\mu^*`-measurable sets with respect to $`\mu^*`, then $`\mathcal{A}^{\text{cm}}` is a $`\sigma`-algebra on $`\Omega`, and the restriction $`\mu^{\text{cm}}` of $`\mu^*` to $`\mathcal{A}^{\text{cm}}` gives a *complete* measure space.
:::

(Phonetic remark: you can think of the superscript $`{}^{\text{cm}}` as standing for either "Carathéodory measurable" or "complete".
Both are helpful for remembering what this represents.
This notation is not standard but the pun was too good to resist.)

`MeasureTheory.OuterMeasure.toMeasure` realizes exactly this in Mathlib: given an outer measure `μ` and a `MeasurableSpace` instance with `m ≤ μ.caratheodory` (the σ-algebra is contained in the Carathéodory-measurable sets), it produces the proper `Measure`.

Thus, if we compose the outer-measure construction with Carathéodory's theorem, we find that every pre-measure $`\mu_0` on an algebra $`\mathcal{A}_0` naturally gives a $`\sigma`-algebra $`\mathcal{A}^{\text{cm}}` with a complete measure $`\mu^{\text{cm}}`, and our two compatibility results mean that $`\mathcal{A}^{\text{cm}} \supset \mathcal{A}_0` and $`\mu^{\text{cm}}` agrees with $`\mu`.

Here is a table showing the process, where going down each row of the table corresponds to restriction process.

$$`\begin{array}{lll} \text{Sets} & \text{Function} & \text{Notes} \\ \hline 2^\Omega & \mu^* & \mu^* \text{ outer measure obtained from } \mu_0 \\ \mathcal{A}^{\text{cm}} & \mu^{\text{cm}} & \mathcal{A}^{\text{cm}} = \mu^*\text{-measurable sets},\ (\mathcal{A}^{\text{cm}}, \mu^{\text{cm}}) \text{ complete} \\ \mathcal{A}_0 & \mu_0 & \mu_0 \text{ is a pre-measure} \end{array}`

# Defining the Lebesgue measure

This lets us finally define the Lebesgue measure on $`\mathbb{R}^n`.
We wrap everything together at once now.

:::DEFINITION
We create a measure on $`\mathbb{R}^n` by the following procedure.

- Start with the algebra $`\mathcal{L}_0` generated by rectangular prisms, and define a *pre-measure* $`\lambda_0` on this $`\mathcal{L}_0` (this was glossed over in the example).
- By the construction theorem, this gives the *Lebesgue outer measure* $`\lambda^*` on $`2^{\mathbb{R}^n}`, which is compatible on all the rectangular prisms.
- By Carathéodory, this restricts to a complete measure $`\lambda` on the $`\sigma`-algebra $`\mathcal{L}(\mathbb{R}^n)` of $`\lambda^*`-measurable sets (which as promised contains all rectangular prisms).

The resulting complete measure, denoted $`\lambda`, is called the *Lebesgue measure*.

The algebra $`\mathcal{L}(\mathbb{R}^n)` we obtained will be called the *Lebesgue $`\sigma`-algebra*; sets in it are said to be *Lebesgue measurable*.
:::

Mathlib short-circuits all of this for the user.
The Lebesgue measure on `ℝ` (and `ℝ^n`) is `MeasureTheory.volume`, registered as the canonical `[MeasureSpace ℝ]` instance via `Real.measureSpace`; under the hood it's exactly the Carathéodory completion of the rectangular pre-measure.
You don't have to assemble it yourself — `volume` and the `∫ x, f x` notation Just Work, and the compatibility lemmas like `Real.volume_Icc : volume (Set.Icc a b) = ENNReal.ofReal (b - a)` make computations a one-liner.

```lean
example : MeasureTheory.volume (Set.Icc (0 : ℝ) 1) = 1 := by
  rw [Real.volume_Icc]; simp
```

Of course, now that we've gotten all the way here, if we actually want to *compute* any measures, we can mostly gleefully forget about how we actually constructed the measure and just use the properties.
The hard part was to showing that there *is* a way to assign measures consistently; actually figuring out what that measure's value is *given that it exists* is often much easier.
Here is an example.

::::EXAMPLE "The Cantor set has measure zero"
The standard *middle-thirds Cantor set* is the subset $`[0, 1]` obtained as follows: we first delete the open interval $`(1/3, 2/3)`.
This leaves two intervals $`[0, 1/3]` and $`[2/3, 1]` from which we delete the middle thirds again from both, i.e. deleting $`(1/9, 2/9)` and $`(7/9, 8/9)`.
We repeat this procedure indefinitely and let $`C` denote the result.
An illustration is shown below.

:::figure "cantor-thirds.png"
Image from {cite}`img:cantor`.
:::

It is a classic fact that $`C` is uncountable (it consists of ternary expansions omitting the digit $`1`).
But it is measurable (it is an intersection of closed sets!) and we contend it has measure zero.
Indeed, at the $`n`th step, the result has measure $`(2/3)^n` leftover.
So $`\mu(C) \leq (2/3)^n` for every $`n`, forcing $`\mu(C) = 0`.
::::

This is fantastic, but there is one elephant in the room: how are the Lebesgue $`\sigma`-algebra and the Borel $`\sigma`-algebra related?
To answer this question briefly, I will state two results (but another answer is given in the next section).
The first is a geometric interpretation of the strange Carathéodory measurable hypothesis.

:::PROPOSITION "A geometric interpretation of Lebesgue measurability"
A set $`A \subseteq \mathbb{R}^n` is Lebesgue measurable if and only if for every $`\varepsilon > 0`, there is an open set $`U \supset A` such that
$$`\lambda^*(U \setminus A) < \varepsilon`
where $`\lambda^*` is the Lebesgue outer measure.
:::

I want to say that this was Lebesgue's original formulation of "measurable", but I'm not sure about that.
In any case, we won't need to use this, but it's good to see that our definition of Lebesgue measurable has a down-to-earth geometric interpretation.

:::QUESTION
Deduce that every open set is Lebesgue measurable.
Conclude that the Lebesgue $`\sigma`-algebra contains the Borel $`\sigma`-algebra.
(A different proof is given later on.)
:::

However, the containment is proper: there are more Lebesgue measurable sets than Borel ones.
Indeed, it can actually be proven using transfinite induction (though we won't) that $`|\mathcal{B}(\mathbb{R})| = |\mathbb{R}|`.
Using this, one obtains:

:::EXERCISE
Show the Borel $`\sigma`-algebra is not complete.
(Hint: consider the Cantor set.
You won't be able to write down an example of a non-measurable set, but you can use cardinality arguments.)
Thus the Lebesgue $`\sigma`-algebra strictly contains the Borel one.
:::

Nonetheless, there is a great way to describe the Lebesgue $`\sigma`-algebra, using the idea of completeness.

:::DEFINITION
Let $`(\Omega, \mathcal{A}, \mu)` be a measure space.
The *completion* $`(\Omega, \overline{\mathcal{A}}, \overline{\mu})` is defined as follows: we let
$$`\overline{\mathcal{A}} = \{A \cup N \mid A \in \mathcal{A}, \; N \text{ subset of null set}\}.`
and $`\overline{\mu}(A \cup N) = \mu(A)`.
One can check this is well-defined, and in fact $`\overline{\mu}` is the unique extension of $`\mu` from $`\mathcal{A}` to $`\overline{\mathcal{A}}`.

This looks more complicated than it is.
Intuitively, all we are doing is "completing" the measure by telling $`\overline{\mu}` to regard any subset of a null set as having measure zero, too.
:::

`MeasureTheory.Measure.completion μ` (in `Mathlib.MeasureTheory.Measure.Completion`) does exactly this.
The resulting measure is `Measure.IsComplete` and agrees with `μ` on the original σ-algebra.

Then, the saving grace:

:::THEOREM "Lebesgue is completion of Borel"
For $`\mathbb{R}^n`, the Lebesgue measure is the completion of the Borel measure.
:::

# A fourth row: Carathéodory for pre-measures

:::PROTOTYPE
The fourth row for the Lebesgue measure is $`\mathcal{B}(\mathbb{R}^n)`.
:::

In many cases, $`\mathcal{A}^{\text{cm}}` is actually bigger than our original goal, and instead we only need to extend $`\mu_0` on $`\mathcal{A}_0` to $`\mu` on $`\mathcal{A}`, where $`\mathcal{A}` is the $`\sigma`-algebra generated by $`\mathcal{A}_0`.
Indeed, our original goal was to get $`\mathcal{B}(\mathbb{R}^n)`, and in fact:

:::EXERCISE
Show that $`\mathcal{B}(\mathbb{R}^n)` is the $`\sigma`-algebra generated by the $`\mathcal{L}_0` we defined earlier.
:::

Fortunately, this restriction is trivial to do.

:::QUESTION
Show that $`\mathcal{A}^{\text{cm}} \supset \mathcal{A}`, so we can just restrict $`\mu^{\text{cm}}` to $`\mathcal{A}`.
:::

We will in a moment add this as the fourth row in our table.

However, if this is the end goal, than a somewhat different Carathéodory theorem can be stated because often one more niceness condition holds:

:::DEFINITION
A pre-measure or measure $`\mu` on $`\Omega` is *$`\sigma`-finite* if $`\Omega` can be written as a countable union $`\Omega = \bigcup_n A_n` with $`\mu(A_n) < \infty` for each $`n`.
:::

`MeasureTheory.SigmaFinite μ` is the Mathlib typeclass; `volume` on `ℝ` and `ℝ^n` carries it as a registered instance, since you can cover the line by `Set.Ico (-n) n` for `n : ℕ`.

:::QUESTION
Show that the pre-measure $`\lambda_0` we had, as well as the Borel measure $`\mathcal{B}(\mathbb{R}^n)`, are both $`\sigma`-finite.
:::

Actually, for us, $`\sigma`-finite is basically always going to be true, so you can more or less just take it for granted.

:::THEOREM "Carathéodory extension theorem for pre-measures"
Let $`\mu_0` be a pre-measure on an algebra $`\mathcal{A}_0` of $`\Omega`, and let $`\mathcal{A}` denote the $`\sigma`-algebra generated by $`\mathcal{A}_0`.
Let $`\mathcal{A}^{\text{cm}}`, $`\mu^{\text{cm}}` be as in the previous theorem.
Then:

- The restriction of $`\mu^{\text{cm}}` to $`\mathcal{A}` gives a measure $`\mu` extending $`\mu_0`.
- If $`\mu_0` was $`\sigma`-finite, then $`\mu` is the unique extension of $`\mu_0` to $`\mathcal{A}`.
- If $`\mu_0` was $`\sigma`-finite, then $`\mu^{\text{cm}}` is the completion of $`\mu`, hence the unique extension of $`\mu_0` to $`\mathcal{A}^{\text{cm}}`.
:::

The Mathlib uniqueness statement for σ-finite extensions is `MeasureTheory.Measure.ext_of_generateFrom_of_iUnion` (and friends): two σ-finite measures agreeing on a generating π-system agree everywhere.

Here is the updated table, with comments if $`\mu_0` was indeed $`\sigma`-finite.

$$`\begin{array}{llcl} \text{Sets} & \text{Function} & \text{Construct order} & \text{Notes} \\ \hline 2^\Omega & \mu^* & \text{Step 2} & \mu^* \text{ is outer measure obtained from } \mu_0 \\ \mathcal{A}^{\text{cm}} & \mu^{\text{cm}} & \text{Step 3} & (\mathcal{A}^{\text{cm}}, \mu^{\text{cm}}) \text{ is completion of } (\mathcal{A}, \mu), \\ & & & \mathcal{A}^{\text{cm}} \text{ defined as } \mu^*\text{-measurable sets} \\ \mathcal{A} & \mu & \text{Step 4} & \mathcal{A} \text{ defined as } \sigma\text{-alg. generated by } \mathcal{A}_0 \\ \mathcal{A}_0 & \mu_0 & \text{Step 1} & \mu_0 \text{ is a pre-measure} \end{array}`

And here is the table for $`\Omega = \mathbb{R}^n`, with Borel and Lebesgue in it.

$$`\begin{array}{llcl} \text{Sets} & \text{Function} & \text{Construct order} & \text{Notes} \\ \hline 2^{\mathbb{R}^n} & \lambda^* & \text{Step 2} & \lambda^* \text{ is Lebesgue outer measure} \\ \mathcal{L}(\mathbb{R}^n) & \lambda & \text{Step 3} & \text{Lebesgue } \sigma\text{-algebra, completion of Borel one} \\ \mathcal{B}(\mathbb{R}^n) & \mu & \text{Step 4} & \text{Borel } \sigma\text{-algebra, generated by } \mathcal{L}_0 \\ \mathcal{L}_0 & \lambda_0 & \text{Step 1} & \text{Define pre-measure on rectangles} \end{array}`

Going down one row of the table corresponds to restriction, while each of $`\mu_0 \to \mu \to \mu^{\text{cm}}` is a unique extension when $`\mu_0` is $`\sigma`-finite.

# Problems

:::PROBLEM "Constructing outer measures from arbitrary $`\\rho`"
For a set $`\Omega`, let $`\mathcal{E}` be *any* subset of $`2^\Omega` and let $`\rho \colon \mathcal{E} \to [0, +\infty]` be *any* function.
Prove that
$$`\mu^*(E) = \inf\left\{\sum_{n=1}^\infty \rho(E_n) \mid E_n \in \mathcal{E}, \; E \subseteq \bigcup_{n=1}^\infty E_n\right\}`
is an outer measure.
:::

This is exactly `MeasureTheory.OuterMeasure.ofFunction` — `OuterMeasure.ofFunction m h` takes any `m : Set Ω → ℝ≥0∞` with `m ∅ = 0` and produces the inf-of-coverings outer measure.
The Mathlib proof is the obvious one and lives directly in the definition's body.

:::PROBLEM "The insane scientist"
Let $`\Omega = \mathbb{R}^2`, and let $`\mathcal{E}` be the set of (non-degenerate) rectangles.
Let $`\rho(E) = 1` for every rectangle $`E \in \mathcal{E}`.
Ignoring my advice, the insane scientist uses $`\rho` to construct an outer measure $`\mu^*`, as in the previous problem.

- Find $`\mu^*(S)` for each subset $`S` of $`\mathbb{R}^2`.
- Which sets are $`\mu^*`-measurable?

You should find that no rectangle is $`\mu^*`-measurable, unsurprisingly foiling the scientist.
:::

:::PROBLEM (chili := 1)
A function $`f \colon \mathbb{R} \to \mathbb{R}` is continuous.
Must $`f` be measurable with respect to the Lebesgue measure on $`\mathbb{R}`?
:::

The answer is yes — `Continuous.measurable` from the previous chapter, plus the fact that the Lebesgue measure is built on top of the Borel σ-algebra.
The subtle point (and a common source of folklore confusion) is that "Borel-measurable" and "Lebesgue-measurable" in the *codomain* are the same for `ℝ → ℝ` continuous functions, but the question of pulling Lebesgue-measurable subsets *back* through a continuous function is genuinely different — see the Cantor function example from the previous chapter.
