/-
The book's bibliography. Each entry is a `NapkinRef` value indexed by
its citation key. Inline citations elsewhere in the book go through
the `{cite}` role and the `:::bibliography` directive renders the full
list — both defined in `Napkin.Meta.Citations`.

Translated from Napkin's `book/references.bib`.
-/

namespace Napkin

structure NapkinRef where
  /-- Citation key, e.g. "ref:vakil". -/
  key : String
  /-- Authors as a single human-readable string. -/
  authors : String
  /-- Year as a string (allows "n.d." or other non-numeric values). -/
  year : String
  /-- Title of the work. -/
  title : String
  /-- Publisher, journal, institution, or other source attribution. -/
  source : String
  /-- Optional URL to the work. -/
  url : Option String := none
  /-- Short label used in inline citations (e.g. "Vakil"). -/
  short : String

/-- All references currently used in the book. Order doesn't matter; the
    bibliography directive sorts by short label. -/
def references : Array NapkinRef := #[
  ⟨"ref:55a",
   "Dennis Gaitsgory (notes by Evan Chen)", "2014",
   "Math 55a: Honors Abstract and Linear Algebra",
   "Harvard College, course notes",
   some "https://web.evanchen.cc/coursework.html",
   "Gaitsgory, Math 55a"⟩,
  ⟨"ref:145a",
   "Peter Koellner (notes by Evan Chen)", "2014",
   "Math 145a: Set Theory I",
   "Harvard College, course notes",
   some "https://web.evanchen.cc/coursework.html",
   "Koellner, Math 145a"⟩,
  ⟨"ref:18-435",
   "Seth Lloyd (notes by Evan Chen)", "2015",
   "18.435J: Quantum Computation",
   "MIT, course notes",
   some "https://web.evanchen.cc/coursework.html",
   "Lloyd, 18.435J"⟩,
  ⟨"ref:pugh",
   "C. C. Pugh", "2002",
   "Real mathematical analysis",
   "Springer",
   none,
   "Pugh"⟩,
  ⟨"ref:hatcher",
   "Allen Hatcher", "2002",
   "Algebraic topology",
   "Cambridge University Press",
   some "https://pi.math.cornell.edu/~hatcher/AT/ATpage.html",
   "Hatcher"⟩,
  ⟨"ref:msci",
   "Tom Leinster", "2014",
   "Basic category theory",
   "Cambridge University Press",
   some "https://arxiv.org/abs/1612.09375",
   "Leinster"⟩,
  ⟨"ref:manifolds",
   "Reyer Sjamaar", "2005",
   "Manifolds and Differential Forms",
   "Cornell University, lecture notes",
   some "https://pi.math.cornell.edu/~sjamaar/manifolds/manifold.pdf",
   "Sjamaar"⟩,
  ⟨"ref:vakil",
   "Ravi Vakil", "2017",
   "The Rising Sea: Foundations of Algebraic Geometry",
   "Stanford University, draft textbook",
   some "https://math.stanford.edu/~vakil/216blog/",
   "Vakil"⟩,
  ⟨"ref:gathmann",
   "Andreas Gathmann", "2003",
   "Algebraic Geometry",
   "TU Kaiserslautern, lecture notes",
   some "https://www.mathematik.uni-kl.de/~gathmann/de/alggeom.php",
   "Gathmann"⟩,
  ⟨"ref:etingof",
   "Pavel Etingof", "2011",
   "Introduction to Representation Theory",
   "MIT, lecture notes",
   some "https://math.mit.edu/~etingof/replect.pdf",
   "Etingof"⟩,
  ⟨"ref:gorin",
   "Vadim Gorin (notes by Tony Zhang)", "2018",
   "18.175: Theory of Probability",
   "MIT, course notes",
   some "https://web.archive.org/web/20190617235844/http://web.mit.edu/txz/www/links.html",
   "Gorin, 18.175"⟩,
  ⟨"ref:gowers",
   "Timothy Gowers", "2011",
   "Normal subgroups and quotient groups",
   "Gowers's Weblog",
   some "https://gowers.wordpress.com/2011/11/20/normal-subgroups-and-quotient-groups/",
   "Gowers"⟩,
  ⟨"ref:axler",
   "Sheldon Axler", "1997",
   "Linear algebra done right",
   "Springer, New York",
   none,
   "Axler"⟩,
  ⟨"ref:55b",
   "Dennis Gaitsgory (notes by Evan Chen)", "2015",
   "Math 55b: Honors Real and Complex Analysis",
   "Harvard College, course notes",
   some "https://web.evanchen.cc/coursework.html",
   "Gaitsgory, Math 55b"⟩,
  ⟨"ref:lebesgue",
   "Steve Cheng", "2008",
   "A Crash Course on the Lebesgue Integral and Measure Theory",
   "course notes",
   some "https://www.gold-saucer.org/math/lebesgue/lebesgue-new.pdf",
   "Cheng"⟩,
  ⟨"ref:dartmouth",
   "Andrew Yang", "2012",
   "Math 43: Complex Analysis",
   "Dartmouth College, course notes",
   some "https://math.dartmouth.edu/~m43s12/syllabus.html",
   "Yang, Math 43"⟩,
  ⟨"ref:miquel",
   "Alexandre Miquel", "2014",
   "An Axiomatic Presentation of the Method of Forcing",
   "Universidad de la República, Uruguay",
   some "https://www.fing.edu.uy/~amiquel/forcing/",
   "Miquel"⟩,
  ⟨"ref:munkres",
   "James Munkres", "2000",
   "Topology",
   "Prentice-Hall, Inc., 2nd edition",
   none,
   "Munkres"⟩,
  ⟨"ref:maxim752",
   "Laurentiu Maxim", "2013",
   "Math 752 Topology Lecture Notes",
   "University of Wisconsin-Madison, lecture notes",
   some "https://www.math.wisc.edu/~maxim/752notes.pdf",
   "Maxim"⟩,
  ⟨"ref:oggier_NT",
   "Frederique Oggier", "2010",
   "Algebraic Number Theory",
   "Nanyang Technological University, lecture notes",
   some "https://feog.github.io/ANT10.pdf",
   "Oggier"⟩,
  ⟨"ref:lenstra_chebotarev",
   "Hendrik Lenstra", "2002",
   "The Chebotarev Density Theorem",
   "Leiden University, lecture notes",
   some "https://websites.math.leidenuniv.nl/algebra/",
   "Lenstra"⟩,
  ⟨"ref:miranda",
   "R. Miranda", "1995",
   "Algebraic Curves and Riemann Surfaces",
   "American Mathematical Society",
   none,
   "Miranda"⟩,
  ⟨"ref:analytic_NT",
   "A. J. Hildebrand", "2013",
   "Introduction to Analytic Number Theory",
   "University of Illinois, lecture notes",
   some "https://web.archive.org/web/20230326025121/https://faculty.math.illinois.edu/~hildebr/ant/main.pdf",
   "Hildebrand"⟩,
  ⟨"img:exercise",
   "Abstruse Goose", "2008",
   "Math Text",
   "abstrusegoose.com (CC 3.0)",
   some "https://abstrusegoose.com/12",
   "Abstruse Goose"⟩,
  ⟨"img:read_with_pencil",
   "Ben Orlin", "2015",
   "The Math Major Who Never Reads Math",
   "Math with Bad Drawings",
   some "https://mathwithbaddrawings.com/2015/03/17/the-math-major-who-never-reads-math/",
   "Orlin"⟩,
  ⟨"img:snsd",
   "Topological Girl's Generation", "n.d.",
   "Topological Girl's Generation",
   "tumblr (dead link)",
   some "https://topologicalgirlsgeneration.tumblr.com/",
   "Topological Girl's Generation"⟩,
  ⟨"img:matrixmult",
   "MathMathsMathematics", "2012",
   "How to Multiply Matrices — A 2x2 Matrix by various sizes",
   "YouTube",
   some "https://youtu.be/pJwslaulUMU",
   "MathMathsMathematics"⟩,
  ⟨"img:apples",
   "George Hodan", "n.d.",
   "Apple",
   "publicdomainpictures.net (Public domain)",
   some "https://www.publicdomainpictures.net/view-image.php?image=20117",
   "Hodan"⟩,
  ⟨"img:velociraptor",
   "Petr Kratochvil", "n.d.",
   "Velociraptor",
   "publicdomainpictures.net (Public domain)",
   some "https://www.publicdomainpictures.net/view-image.php?image=93881",
   "Kratochvil"⟩,
  ⟨"img:omega500",
   "Pop-up casket", "n.d.",
   "Omega exp",
   "Wikimedia Commons (Public domain)",
   some "https://commons.wikimedia.org/wiki/File:Omega-exp-omega-labeled.svg",
   "Pop-up casket"⟩,
  ⟨"img:zornaholic",
   "Abstruse Goose", "2009",
   "Zornaholic",
   "abstrusegoose.com (CC 3.0)",
   some "https://abstrusegoose.com/133",
   "Abstruse Goose"⟩,
  ⟨"img:calvin_hobbes_fly",
   "Bill Watterson", "n.d.",
   "Calvin and Hobbes",
   "(fair use)",
   none,
   "Watterson"⟩,
  ⟨"img:cantor",
   "127“rect”", "2007",
   "Cantor set in seven iterations",
   "Wikipedia (Public domain)",
   some "https://en.wikipedia.org/wiki/File:Cantor_set_in_seven_iterations.svg",
   "127 rect"⟩,
  ⟨"img:weierstrass",
   "Eeyore22", "n.d.",
   "Weierstrass function",
   "Wikimedia Commons (Public domain)",
   some "https://commons.wikimedia.org/wiki/File:WeierstrassFunction.svg",
   "Eeyore22"⟩,
  ⟨"img:even_covering",
   "Wordslaugh", "n.d.",
   "Covering space diagram",
   "Wikimedia Commons (CC 3.0)",
   some "https://commons.wikimedia.org/wiki/File:Covering_space_diagram.svg",
   "Wordslaugh"⟩,
  ⟨"img:torus",
   "Toahigherlevel", "n.d.",
   "Projection color torus",
   "Wikipedia (Public domain)",
   some "https://en.wikipedia.org/wiki/File:Projection_color_torus.jpg",
   "Toahigherlevel"⟩,
  ⟨"img:kleinfold",
   "Inductiveload", "n.d.",
   "Klein Bottle Folding",
   "Wikimedia Commons (Public domain)",
   some "https://commons.wikimedia.org/wiki/File:Klein_Bottle_Folding_1.svg",
   "Inductiveload"⟩,
  ⟨"img:kleinbottle",
   "Fropuff", "n.d.",
   "Klein bottle",
   "Wikipedia (Public domain)",
   some "https://en.wikipedia.org/wiki/File:KleinBottle-01.png",
   "Fropuff"⟩,
  ⟨"img:stokes",
   "Krish Navedala", "n.d.",
   "Stokes patch",
   "Wikipedia (Public domain)",
   some "https://en.wikipedia.org/wiki/File:Stokes_patch.svg",
   "Navedala"⟩,
  ⟨"img:xkcd_rolles",
   "Randall Munroe", "n.d.",
   "Rolle's theorem",
   "xkcd (CC 2.5)",
   some "https://xkcd.com/2042/",
   "Munroe"⟩,
  ⟨"img:tangentplane",
   "g.kov", "n.d.",
   "Normal surface vector",
   "TeX StackExchange",
   some "https://tex.stackexchange.com/a/235142/76888",
   "g.kov"⟩,
  ⟨"ref:aops_burnside",
   "Maxima", "2013",
   "Burnside's Lemma, post 6",
   "Art of Problem Solving",
   some "https://www.aops.com/Forum/viewtopic.php?p=3089768#p3089768",
   "Maxima, AoPS"⟩
]

/-- Look up a reference by key. -/
def lookupRef (key : String) : Option NapkinRef :=
  references.find? (·.key == key)

end Napkin
