import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.Algebra.Module.PID
import Mathlib.GroupTheory.FiniteAbelian.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Data.ZMod.Basic
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Basis.Defs

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

open scoped DirectSum

set_option pp.rawOnError true

#doc (Manual) "The PID structure theorem" =>

%%%
file := "PID-structure-theorem"
%%%


The main point of this chapter is to discuss a classification theorem for finitely generated abelian groups.
This won't take long to do, and if you like, you can read just the first section and then move on.

However, since I'm here, I will go ahead and state the result as a special case of the much more general _structure theorem_.
Its corollaries include

- All finite-dimensional vector spaces are $`k^{\oplus n}`.
- The classification theorem for finitely generated abelian groups,
- The Jordan decomposition of a matrix from before,
- Another canonical form for a matrix: "Frobenius normal form".

# Finitely generated abelian groups

:::REMARK
We talk about abelian groups in what follows, but really the morally correct way to think about these structures is as $`\mathbb{Z}`-modules.
:::

:::DEFINITION
An abelian group $`G = (G, +)` is *finitely generated* if it is finitely generated as a $`\mathbb{Z}`-module.
(That is, there exists a finite collection $`b_1, \dots, b_m : G`, such that every $`x : G` can be written in the form $`c_1 b_1 + \dots + c_m b_m` for some $`c_1, \dots, c_m : \mathbb{Z}`.)
:::

:::EXAMPLE "Examples of finitely generated abelian groups"
1. $`\mathbb{Z}` is finitely generated (by $`1`).
2. $`\mathbb{Z}/n\mathbb{Z}` is finitely generated (by $`1`).
3. $`\mathbb{Z}^{\oplus 2}` is finitely generated (by two elements $`(1, 0)` and $`(0, 1)`).
4. $`\mathbb{Z}^{\oplus 3} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \mathbb{Z}/2016\mathbb{Z}` is finitely generated by five elements.
5. $`\mathbb{Z}/3\mathbb{Z} \oplus \mathbb{Z}/5\mathbb{Z}` is finitely generated by two elements.
:::

:::EXERCISE
In fact $`\mathbb{Z}/3\mathbb{Z} \oplus \mathbb{Z}/5\mathbb{Z}` is generated by _one_ element.
What is it?
:::

You might notice that these examples are not very diverse.
That's because they are actually the only examples:

:::THEOREM "Fundamental theorem of finitely generated abelian groups"
Let $`G` be a finitely generated abelian group.
Then there exists an integer $`r`, prime powers $`q_1, \dots, q_m` (not necessarily distinct) such that $$`G \cong \mathbb{Z}^{\oplus r} \oplus \mathbb{Z}/q_1\mathbb{Z} \oplus \mathbb{Z}/q_2\mathbb{Z} \oplus \dots \oplus \mathbb{Z}/q_m\mathbb{Z}.` This decomposition is unique up to permutation of the $`\mathbb{Z}/q_i\mathbb{Z}`.
:::

:::DEFINITION
The *rank* of a finitely generated abelian group $`G` is the integer $`r` above.
:::

Now, we could prove this theorem, but it is more interesting to go for the gold and state and prove the entire structure theorem.

# Some ring theory prerequisites

:::PROTOTYPE
$`R = \mathbb{Z}`.
:::

Before I can state the main theorem, I need to define a few terms for UFD's, which behave much like $`\mathbb{Z}`:

:::MORAL
Our intuition from the case $`R = \mathbb{Z}` basically carries over verbatim.
:::

We don't even need to deal with prime ideals and can factor elements instead.

:::DEFINITION
If $`R` is a UFD, then $`p : R` is a *prime element* if $`(p)` is a prime ideal and $`p \neq 0`.
For UFD's this is equivalent to: if $`p = xy` then either $`x` or $`y` is a unit.
:::

So for example in $`\mathbb{Z}` the set of prime elements is $`\{\pm 2, \pm 3, \pm 5, \dots\}`.
Now, since $`R` is a UFD, every element $`r` factors into a product of prime elements $$`r = u p_1^{e_1} p_2^{e_2} \dots p_m^{e_m}.`

:::DEFINITION
We say $`r` *divides* $`s` if $`s = r' r` for some $`r' : R`.
This is written $`r \mid s`.
:::

:::EXAMPLE "Divisibility in ℤ"
The number $`0` is divisible by every element of $`\mathbb{Z}`.
All other divisibility as expected.
:::

:::QUESTION
Show that $`r \mid s` if and only if the exponent of each prime in $`r` is less than or equal to the corresponding exponent in $`s`.
:::

Now, the case of interest is the even stronger case when $`R` is a PID:

:::PROPOSITION "PID's are Noetherian UFD's"
If $`R` is a PID, then it is Noetherian and also a UFD.
:::

:::PROOF
The fact that $`R` is Noetherian is obvious.
For $`R` to be a UFD we essentially repeat the proof for $`\mathbb{Z}`, using the fact that $`(a, b)` is principal in order to extract $`\gcd(a, b)`.
:::

In this case, we have a Chinese remainder theorem for elements.

:::THEOREM "Chinese remainder theorem for rings"
Let $`m` and $`n` be relatively prime elements, meaning $`(m) + (n) = (1)`.
Then $$`R / (mn) \cong R/(m) \times R/(n).`
:::

:::PROOF
This is the same as the proof of the usual Chinese remainder theorem.
First, since $`(m, n) = (1)` we have $`am + bn = 1` for some $`a` and $`b`.
Then we have a map $$`R/(m) \times R/(n) \to R/(mn) \quad \text{by} \quad (r, s) \mapsto r \cdot bn + s \cdot am.` One can check that this map is well-defined and an isomorphism of rings.
(Diligent readers invited to do so.)
:::

Finally, we need to introduce the concept of a Noetherian $`R`-module.

:::DEFINITION
An $`R`-module $`M` is *Noetherian* if it satisfies one of the two equivalent conditions:

- Its submodules obey the ascending chain condition: there is no infinite sequence of modules $`M_1 \subsetneq M_2 \subsetneq \dots`.
- All submodules of $`M` (including $`M` itself) are finitely generated.
:::

This generalizes the notion of a Noetherian ring: a Noetherian ring $`R` is one for which $`R` is Noetherian as an $`R`-module.

:::QUESTION
Check these two conditions are equivalent.
(Copy the proof for rings.)
:::

# The structure theorem

Our structure theorem takes two forms:

:::THEOREM "Structure theorem, invariant form"
Let $`R` be a PID and let $`M` be any finitely generated $`R`-module.
Then $$`M \cong \bigoplus_{i=1}^m R/(s_i)` for some $`s_i` (possibly zero) satisfying $`s_1 \mid s_2 \mid \dots \mid s_m`.
:::

:::COROLLARY "Structure theorem, primary form"
Let $`R` be a PID and let $`M` be any finitely generated $`R`-module.
Then $$`M \cong R^{\oplus r} \oplus R/(q_1) \oplus R/(q_2) \oplus \dots \oplus R/(q_m)` where $`q_i = p_i^{e_i}` for some prime element $`p_i` and integer $`e_i \geq 1`.
:::

:::PROOF
Factor each $`s_i` into prime factors (since $`R` is a UFD), then use the Chinese remainder theorem.
:::

:::REMARK
In both theorems the decomposition is unique up to permutations of the summands.
:::

# Reduction to maps of free R-modules

:::DEFINITION
A *free $`R`-module* is a module of the form $`R^{\oplus n}` (or more generally, $`\bigoplus_I R` for some indexing set $`I`, just to allow an infinite basis).
:::

The proof of the structure theorem proceeds in two main steps.
First, we reduce the problem to a _linear algebra_ problem involving free $`R`-modules $`R^{\oplus d}`.
Once that's done, we just have to play with matrices; this is done in the next section.

Suppose $`M` is finitely generated by $`d` elements.
Then there is a surjective map of $`R`-modules $$`R^{\oplus d} \twoheadrightarrow M` whose image on the basis of $`R^{\oplus d}` are the generators of $`M`.
Let $`K` denote the kernel.

We claim that $`K` is finitely generated as well.
To this end we prove that

:::LEMMA "Direct sum of Noetherian modules is Noetherian"
Let $`M` and $`N` be two Noetherian $`R`-modules.
Then the direct sum $`M \oplus N` is also a Noetherian $`R`-module.
:::

:::PROOF
It suffices to show that if $`L \subseteq M \oplus N`, then $`L` is finitely generated.
One guess is that $`L = P \oplus Q`, where $`P` and $`Q` are the projections of $`L` onto $`M` and $`N`.
Unfortunately this is false (take $`M = N = \mathbb{Z}` and $`L = \{(n, n) \mid n : \mathbb{Z}\}`) so we will have to be more careful.

Consider the submodules $$`A = \{x : M \mid (x, 0) \in L\} \subseteq M` $$`B = \{y : N \mid \exists x : M, (x, y) \in L\} \subseteq N.`
(Note the asymmetry for $`A` and $`B`: the proof doesn't work otherwise.)
Then $`A` is finitely generated by $`a_1, \dots, a_k`, and $`B` is finitely generated by $`b_1, \dots, b_\ell`.
Let $`x_i = (a_i, 0)` and let $`y_i = (*, b_i)` be elements of $`L` (where the $`*`'s are arbitrary things we don't care about).
Then $`x_i` and $`y_i` together generate $`L`.
:::

:::QUESTION
Deduce that for $`R` a PID, $`R^{\oplus d}` is Noetherian.
:::

Hence $`K \subseteq R^{\oplus d}` is finitely generated as claimed.
So we can find another surjective map $`R^{\oplus f} \twoheadrightarrow K`.
Consequently, we have a composition $$`R^{\oplus f} \xrightarrow{T} R^{\oplus d} \twoheadrightarrow M` where $`T` factors through $`K`.

:::figure "figures/more-on-groups/cokernel-diagram.svg"
The map $`T` factors through the submodule $`K`, exhibiting $`M` as the cokernel of $`T`.
:::
Observe that $`M` is the *cokernel* of the linear map $`T`, i.e. we have that $$`M \cong R^{\oplus d} / \operatorname{img}(T).` So it suffices to understand the map $`T` well.

# Uniqueness of primary form

In this section, we will prove that if $`M \cong R^{\oplus r} \oplus R/(q_1) \oplus \cdots \oplus R/(q_m)`, then the integer $`r` and the prime powers $`q_i` are unique, up to permutations.

First, we consider the case where $`M` is free.

:::THEOREM "Uniqueness of free module's rank"
For a commutative integral domain $`R`, if a free module $`M` has a finite basis, then every other basis has the same number of elements.
:::

The strategy of the proof is to pass to the field case.
Indeed, we're going to pass to the field $`F` being the fraction field of $`R`, then directly apply the dimension theorem for vector spaces.

:::PROOF
As before, but we prove by contradiction this time.
Assume $`v_1, \dots, v_n` is a basis for the free module $`M` of rank $`n`, while $`w_1, \dots, w_m` are any elements of $`M` such that $`m > n`.

Let $`F` be the fraction field of $`R`, and embed the $`R`-module $`M \cong R^n` into the $`F`-vector space $`V \cong F^n`.

Then, because $`m > n`, as elements of $`V`, the elements $`w_1, \dots, w_m` are linearly dependent, which means there are some elements $`f_1, \dots, f_m : F` not all zero, such that $`f_1 w_1 + \cdots + f_m w_m = 0`.

By clearing denominators, we can obtain ring elements $`r_1, \dots, r_m : R` not all zero such that $`r_1 w_1 + \cdots + r_m w_m = 0`.
This means $`w_1, \dots, w_m` cannot be a basis for $`M`.
:::

Next, we prove the case where the rank $`r` is $`0`.
This case needs a different strategy, but it still boils down to applying the dimension theorem for appropriately constructed vector spaces.

:::THEOREM "Uniqueness for one-prime torsion modules"
Let $`R` be a PID, let $`p` be a prime element of $`R`, and let $`M \cong R/(p^{e_1}) \oplus R/(p^{e_2}) \oplus \cdots \oplus R/(p^{e_m})` for positive integers $`e_1, \dots, e_m`.
Then the $`e_i` are unique, up to permutations.
:::

Intuitively, what the proof is trying to do is:

:::MORAL
If we can compute the exponents $`e_i` from intrinsic properties of $`M`, then the exponents must be unique.
:::

Let us consider a simple case --- consider $`R = \mathbb{Z}` and $`M = \mathbb{Z}/4\mathbb{Z}`.
This module has $`4` elements, but it's not the same as $`\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mathbb{Z}`.
In this case, the difference between the two modules can be detected by the fact that in $`M`, the element $`1 \pmod 4` is not zero when multiplied by $`2`, on the other hand, multiplying by $`2` makes every element in $`\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mathbb{Z}` zero.

For notational convenience,

:::DEFINITION
For $`r : R` and an $`R`-module $`M`, define $`rM = \{rm \mid m : M\}`.
(Check that this is still an $`R`-module.)
:::

Then, what the paragraph above says is that $`M \not\cong \mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mathbb{Z}` because $`|2M| = 2 \neq 1 = |2(\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mathbb{Z})|`.
In other words, in this case, counting the number of elements of $`2M` suffices to distinguish the two modules.

For modules of the form $`M \cong R/(p^{e_1}) \oplus R/(p^{e_2}) \oplus \cdots \oplus R/(p^{e_m})` where $`R = \mathbb{Z}`, this almost works in general --- except we also need to consider the number of elements in $`pM`, $`p^2 M`, $`p^3 M`, etc.

Equivalently, we may also consider the number of elements in the successive quotients: $`M/pM`, $`pM/p^2 M`, $`p^2 M/p^3 M`, etc.

:::EXAMPLE
Let $`R = \mathbb{Z}`, $`p = 3`, and $`M = \mathbb{Z}/3^2\mathbb{Z} \oplus \mathbb{Z}/3^5\mathbb{Z}`.
Then:

- $`|M/3M| = 9`,
- $`|3M/3^2 M| = 9`,
- $`|3^2 M/3^3 M| = 3`,
- $`|3^3 M/3^4 M| = 3`,
- $`|3^4 M/3^5 M| = 3`,
- $`|3^e M/3^{e+1} M| = 1` for all integer $`e \geq 5`.

You can already see where this is going --- each decrement of the size of the quotient corresponds to a prime power $`p^{e_i}`.
:::

When the quotient is infinite however, we can no longer do this.
However, note that:

:::LEMMA
For each integer $`e \geq 0`, then $`p^e M/p^{e+1} M` is an $`R/(p)`-vector space.
:::

Thus, instead of counting the number of elements in $`p^e M/p^{e+1} M`, we count the *dimension* of the $`p^e M/p^{e+1} M` as an $`R/(p)`-vector space --- by the dimension theorem, this is indeed intrinsic to the module $`M`.

:::PROOF
Note that, since $`M \cong R/(p^{e_1}) \oplus R/(p^{e_2}) \oplus \cdots \oplus R/(p^{e_m})`, we have $$`\pi(M) \cong \pi(R/(p^{e_1})) \oplus \pi(R/(p^{e_2})) \oplus \cdots \oplus \pi(R/(p^{e_m}))`
where $`\pi(M) = p^e M/p^{e+1} M` for any integer $`e \geq 0`.

This means, as $`R/(p)`-vector space, $$`\dim \pi(M) = \dim \pi(R/(p^{e_1})) + \dim \pi(R/(p^{e_2})) + \cdots + \dim \pi(R/(p^{e_m})).`

Note that, for each term $`R/(p^{e_i})`, then $$`\dim p^e (R/(p^{e_i})) / p^{e+1} (R/(p^{e_i})) = \begin{cases} 1 & e < e_i \\ 0 & \text{otherwise}. \end{cases}`
With some arithmetic, you can see that the values $`e_i` are indeed uniquely determined by $`\dim p^e M/p^{e+1} M`, up to permutation.
:::

Note that this can be easily generalized to the case where the primes in the denominator may be different --- because for different primes $`p` and $`q` of $`R`, then $`p^e (R/(q))/p^{e+1} (R/(q))` is a $`0`-dimensional $`R/(p)`-vector space.

Finally, we handle the general case.

:::THEOREM
If $`M \cong R^{\oplus r} \oplus R/(q_1) \oplus R/(q_2) \oplus \cdots \oplus R/(q_m)`, then the integer $`r` and the prime powers $`q_i` are unique, up to permutations.
:::

:::PROOF
From the two theorems above, it suffices if we can prove that the $`R^{\oplus r}` part and the $`R/(q_1) \oplus R/(q_2) \oplus \cdots \oplus R/(q_m)` part are uniquely determined from $`M`.

For notational convenience, we call an element $`a : M` a *torsion element* if there is $`r : R`, $`r \neq 0` such that $`r a = 0`.

Then,

- If an element $`a : M` has the $`R^{\oplus r}` component zero, then $`q_1 q_2 \cdots q_m \cdot a = 0`, thus $`a` is a torsion element.
- If an element $`a : M` has the $`R^{\oplus r}` component nonzero, then $`a` is not a torsion element.

In other words, the submodule consisting of all torsion elements is identical to the submodule of the elements with $`R^{\oplus r}` component zero, thus is isomorphic to $`R/(q_1) \oplus R/(q_2) \oplus \cdots \oplus R/(q_m)`.

For notation convenience, let $`\operatorname{Tor}(M)` be the submodule of $`M` consisting of all torsion elements.
Then $`\operatorname{Tor}(M) \cong R/(q_1) \oplus R/(q_2) \oplus \cdots \oplus R/(q_m)` and $`M/\operatorname{Tor}(M) \cong R^{\oplus r}`, in other words, the $`R^{\oplus r}` part and the $`R/(q_1) \oplus R/(q_2) \oplus \cdots \oplus R/(q_m)` part are uniquely determined from $`M`, so we're done.
:::

# Smith normal form

The idea is now that we have reduced our problem to studying linear maps $`T \colon R^{\oplus m} \to R^{\oplus n}`, which can be thought of as a generic matrix $$`T = \begin{bmatrix} a_{11} & \dots & a_{1m} \\ \vdots & \ddots & \vdots \\ a_{n1} & \dots & a_{nm} \end{bmatrix}` for a basis $`e_1, \dots, e_m` of $`R^{\oplus m}` and $`f_1, \dots, f_n` of $`R^{\oplus n}`.

Of course, as you might expect it ought to be possible to change the given basis of $`T` such that $`T` has a nicer matrix form.
We already saw this in *Jordan form*, where we had a map $`T \colon V \to V` and changed the basis so that $`T` was "almost diagonal".
This time, we have _two_ sets of bases we can change, so we would hope to get a diagonal basis, or even better.

Before proceeding let's think about how we might edit the matrix: what operations are permitted?
Here are some examples:

- Swapping rows and columns, which just corresponds to re-ordering the basis.
- Adding a multiple of a column to another column.
  For example, if we add $`3` times the first column to the second column, this is equivalent to replacing the basis $$`(e_1, e_2, e_3, \dots, e_m) \mapsto (e_1, e_2 + 3e_1, e_3, \dots, e_m).`
- Adding a multiple of a row to another row.
  One can see that adding $`3` times the first row to the second row is equivalent to replacing the basis $$`(f_1, f_2, f_3, \dots, f_n) \mapsto (f_1 - 3f_2, f_2, f_3, \dots, f_n).`

More generally,

:::MORAL
If $`A` is an invertible $`n \times n` matrix we can replace $`T` with $`AT`.
:::

This corresponds to replacing $$`(f_1, \dots, f_n) \mapsto ((F A^{-1})_1, \dots, (F A^{-1})_n)`
(the "invertible" condition just guarantees the latter is a basis).
Here, $`F` is the $`n \times n` matrix with columns being $`f_1, \dots, f_n`, and $`(F A^{-1})_1` denotes the first column of $`F A^{-1}`.

Of course similarly we can replace $`T` with $`TB` where $`B` is an invertible $`m \times m` matrix; this corresponds to $$`(e_1, \dots, e_m) \mapsto ((E B)_1, \dots, (E B)_m)`
where $`E` is the $`m \times m` matrix with columns being $`e_1, \dots, e_m`.

Armed with this knowledge, we can now approach:

:::THEOREM "Smith normal form"
Let $`R` be a PID.
Let $`M = R^{\oplus m}` and $`N = R^{\oplus n}` be free $`R`-modules and let $`T \colon M \to N` be a linear map.
Set $`k = \min\{m, n\}`.

Then we can select a pair of new bases for $`M` and $`N` such that $`T` has only diagonal entries $`s_1, s_2, \dots, s_k` and $`s_1 \mid s_2 \mid \dots \mid s_k`.
:::

So if $`m > n`, the matrix should take the form $$`\begin{bmatrix} s_1 & 0 & 0 & 0 & \dots & 0 \\ 0 & s_2 & 0 & 0 & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots & \dots & \vdots \\ 0 & 0 & 0 & s_n & \dots & 0 \end{bmatrix}`
and similarly when $`m \leq n`.

:::QUESTION
Show that Smith normal form implies the structure theorem.
:::

:::REMARK
Note that this is not a generalization of Jordan form.

- In Jordan form we consider maps $`T \colon V \to V`; note that the source and target space are the _same_, and we are considering one basis for the space $`V`.
- In Smith form the maps $`T \colon M \to N` are between _different_ modules, and we pick _two_ sets of bases (one for $`M` and one for $`N`).
:::

:::EXAMPLE "Example of Smith normal form"
To give a flavor of the idea of the proof, let's work through a concrete example with the $`\mathbb{Z}`-matrix $$`\begin{bmatrix} 18 & 38 & 48 \\ 14 & 30 & 32 \end{bmatrix}.` The GCD of all the entries is $`2`, and so motivated by this, we perform the *Euclidean algorithm on the left column*: subtract the second row from the first row, then three times the first row from the second: $$`\begin{bmatrix} 18 & 38 & 48 \\ 14 & 30 & 32 \end{bmatrix} \mapsto \begin{bmatrix} 4 & 8 & 16 \\ 14 & 30 & 32 \end{bmatrix} \mapsto \begin{bmatrix} 4 & 8 & 16 \\ 2 & 6 & -16 \end{bmatrix}.`
Now that the GCD of $`2` is present, we move it to the upper-left by switching the two rows, and then kill off all the entries in the same row/column; since $`2` was the GCD all along, we isolate $`2` completely: $$`\begin{bmatrix} 4 & 8 & 16 \\ 2 & 6 & -16 \end{bmatrix} \mapsto \begin{bmatrix} 2 & 6 & -16 \\ 4 & 8 & 16 \end{bmatrix} \mapsto \begin{bmatrix} 2 & 6 & -16 \\ 0 & -4 & 48 \end{bmatrix} \mapsto \begin{bmatrix} 2 & 0 & 0 \\ 0 & -4 & 48 \end{bmatrix}.`
This reduces the problem to a $`1 \times 2` matrix.
So we just apply the Euclidean algorithm again there: $$`\begin{bmatrix} 2 & 0 & 0 \\ 0 & -4 & 0 \end{bmatrix} \mapsto \begin{bmatrix} 2 & 0 & 0 \\ 0 & 4 & 0 \end{bmatrix}.`
:::

Now all we have to do is generalize this proof to work with any PID.
It's intuitively clear how to do this: the PID condition more or less lets you perform a Euclidean algorithm.

:::PROOF
Begin with a generic matrix $`T`.
We want to show, by a series of operations (gradually changing the given basis), that we can rearrange the matrix into Smith normal form.

Define $`\gcd(x, y)` to be any generator of the principal ideal $`(x, y)`.
The key step is a "Euclidean algorithm" claim: if $`a` and $`b` are entries in the same row or column, we can change bases to replace $`a` with $`\gcd(a, b)` and $`b` with something else.
We do just the case of columns.
By hypothesis, $`\gcd(a, b) = xa + yb` for some $`x, y : R`.
We must have $`(x, y) = (1)` now (we're in a UFD).
So there are $`u` and $`v` such that $`xu + yv = 1`.
Then $$`\begin{bmatrix} x & y \\ -v & u \end{bmatrix} \begin{bmatrix} a \\ b \end{bmatrix} = \begin{bmatrix} \gcd(a, b) \\ \text{something} \end{bmatrix}`
and the first matrix is invertible (check this!), as desired.

Let $`s_1 = \gcd_{i,j} a_{ij}` be the GCD of all entries.
Now by repeatedly applying this algorithm, we can cause $`s` to appear in the upper left hand corner.
Then, we use it to kill off all the entries in the first row and the first column, thus arriving at a block-diagonal form.
We then repeat the same procedure with the lower-right $`(m-1) \times (n-1)` matrix, and so on.
This gives the Smith normal form.
:::

With the Smith normal form, we have in the original situation that $`M \cong R^{\oplus d} / \operatorname{img} T` and applying the theorem to $`T` completes the proof of the structure theorem.

# Problems

Now, we can apply our structure theorem!

:::PROBLEM "Finite-dimensional vector spaces are all isomorphic"
A vector space $`V` over a field $`k` has a finite spanning set of vectors.
Show that $`V \cong k^{\oplus n}` for some $`n`.
:::

:::PROBLEM "Frobenius normal form"
Let $`T \colon V \to V` where $`V` is a finite-dimensional vector space over an arbitrary field $`k` (not necessarily algebraically closed).
Show that one can write $`T` as a block-diagonal matrix whose blocks are all of the form $$`\begin{bmatrix} 0 & 0 & 0 & \dots & 0 & * \\ 1 & 0 & 0 & \dots & 0 & * \\ 0 & 1 & 0 & \dots & 0 & * \\ \vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\ 0 & 0 & 0 & \dots & 1 & * \end{bmatrix}.` (View $`V` as a $`k[x]`-module with action $`x \cdot v = T(v)`.)
:::

:::PROBLEM "Jordan normal form"
Let $`T \colon V \to V` where $`V` is a finite-dimensional vector space over an arbitrary field $`k` which is algebraically closed.
Prove that $`T` can be written in Jordan form.
:::

:::PROBLEM (chili := 1)
Find two abelian groups $`G` and $`H` which are not isomorphic, but for which there are injective homomorphisms $`G \hookrightarrow H` and $`H \hookrightarrow G`.
:::

:::PROBLEM (chili := 2)
Let $`A \subseteq B \subseteq C` be rings.
Suppose $`C` is a finitely generated $`A`-module.
Does it follow that $`B` is a finitely generated $`A`-module?
:::

# Formalization

:::LEANCOMPANION
:::

## Finitely generated abelian groups

The fundamental theorem is exactly `AddCommGroup.equiv_free_prod_directSum_zmod`: a finitely generated abelian group (the finite-generation hypothesis is `AddGroup.FG`) splits as a power of $`\mathbb{Z}` times a direct sum of cyclic groups `ZMod (p i ^ e i)` of prime-power order.
Two pieces of notation appear in its statement.
The free part is `Fin n →₀ ℤ`, where `→₀` is *finitely-supported functions*: a function `Fin n → ℤ` that is zero outside a finite set, which for the finite domain `Fin n` is just $`\mathbb{Z}^{\oplus n}`.
The torsion part is `⨁ i, ZMod (p i ^ e i)`, where `⨁` is the *direct sum* (elements with finitely many nonzero coordinates) — for a finite index it agrees with the iterated product.

```lean
example (G : Type*) [AddCommGroup G] [AddGroup.FG G] :
    ∃ (n : ℕ) (ι : Type) (_ : Fintype ι) (p : ι → ℕ) (_ : ∀ i, (p i).Prime) (e : ι → ℕ),
      Nonempty (G ≃+ (Fin n →₀ ℤ) × ⨁ i : ι, ZMod (p i ^ e i)) :=
  AddCommGroup.equiv_free_prod_directSum_zmod G
```

The exercise asked which single element generates $`\mathbb{Z}/3\mathbb{Z} \oplus \mathbb{Z}/5\mathbb{Z}`.
Being generated by one element is precisely `IsAddCyclic`; show that this product is cyclic.
The route in is the Chinese remainder isomorphism `ZMod.chineseRemainder`, giving `ZMod 15 ≃+* ZMod 3 × ZMod 5` (feed it the coprimality proof, `by decide`).
Transport cyclicity across it with `AddEquiv.isAddCyclic` — turn the ring isomorphism into an `AddEquiv` first with `.toAddEquiv` — and note that `ZMod 15` is cyclic by `inferInstance` (`ZMod.instIsAddCyclic`).

```lean
example : IsAddCyclic (ZMod 3 × ZMod 5) := by
  sorry
```

:::solution
```lean
example : IsAddCyclic (ZMod 3 × ZMod 5) :=
  (AddEquiv.isAddCyclic
    (ZMod.chineseRemainder (m := 3) (n := 5) (by decide)).toAddEquiv).mp
    inferInstance
```
:::

## Some ring theory prerequisites

Both halves of the proposition that a PID is a Noetherian UFD are available by instance search from `IsPrincipalIdealRing`: the Noetherian half is `PrincipalIdealRing.isNoetherianRing`, and the unique-factorization half is the `UniqueFactorizationMonoid` instance on a principal ideal domain.

```lean
example (R : Type*) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R] :
    IsNoetherianRing R := inferInstance

example (R : Type*) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R] :
    UniqueFactorizationMonoid R := inferInstance
```

For the integers, the coprime splitting of the Chinese remainder theorem is `ZMod.chineseRemainder`, packaged as a ring isomorphism; the general statement for coprime ideals in any commutative ring is `Ideal.quotientInfRingEquivPiQuotient`.

```lean
example (m n : ℕ) (h : m.Coprime n) : ZMod (m * n) ≃+* ZMod m × ZMod n :=
  ZMod.chineseRemainder h
```

`IsNoetherian R M` is the Mathlib predicate for a Noetherian module; `isNoetherian_def` is the equivalence to the "every submodule is finitely generated" condition, and `isNoetherian_iff_fg_wellFounded` is the equivalence to the ascending chain condition.

```lean
example (R : Type*) [Semiring R] (M : Type*) [AddCommMonoid M] [Module R M] :
    IsNoetherian R M ↔ ∀ s : Submodule R M, s.FG :=
  isNoetherian_def
```

The chapter asked you to check that the two conditions defining a Noetherian module agree.
Alongside `isNoetherian_def` above, show that `IsNoetherian` is equivalent to the ascending chain condition, phrased as well-foundedness of `>` on the submodules.
This is `isNoetherian_iff'`, which states exactly this equivalence; the proof is that one name.

```lean
example (R : Type*) [Semiring R] (M : Type*) [AddCommMonoid M] [Module R M] :
    IsNoetherian R M ↔ WellFoundedGT (Submodule R M) := by
  sorry
```

:::solution
```lean
example (R : Type*) [Semiring R] (M : Type*) [AddCommMonoid M] [Module R M] :
    IsNoetherian R M ↔ WellFoundedGT (Submodule R M) :=
  isNoetherian_iff'
```
:::

## The structure theorem

The primary form is `Module.equiv_free_prod_directSum`: a finitely generated module (`Module.Finite R M`) over a PID is isomorphic to a free part `Fin n →₀ R` times a direct sum of quotients `R ⧸ R ∙ p i ^ e i` by prime-power ideals.
Here `R ∙ x` is `Submodule.span R {x}`, the ideal generated by the single element `x` — so `R ∙ p i ^ e i` is the ideal $`(p_i^{e_i})` and the quotient `R ⧸ R ∙ p i ^ e i` is the module $`R/(q_i)`.
Reading the full conclusion off the signature is the point: the isomorphism `M ≃ₗ[R] (Fin n →₀ R) × ⨁ i : ι, R ⧸ R ∙ p i ^ e i` is precisely the primary decomposition, with the `Irreducible (p i)` hypothesis making each `p i ^ e i` a prime power.

```lean
recall Module.equiv_free_prod_directSum (R : Type u) [CommRing R]
    [IsPrincipalIdealRing R] (M : Type v) [AddCommGroup M] [Module R M]
    [IsDomain R] [Module.Finite R M] :
    ∃ (n : ℕ) (ι : Type u) (_ : Fintype ι) (p : ι → R)
      (_ : ∀ i, Irreducible (p i)) (e : ι → ℕ),
      Nonempty (M ≃ₗ[R] (Fin n →₀ R) × ⨁ i : ι, R ⧸ R ∙ p i ^ e i)
```

Its torsion-only special case is `Module.equiv_directSum_of_isTorsion`, which drops the free `Fin n →₀ R` factor.

## Reduction to maps of free R-modules

The reduction step asks you to deduce that $`R^{\oplus d}` is Noetherian when $`R` is a PID.
This one is pure instance search: a PID is a Noetherian ring (`IsPrincipalIdealRing R` gives `IsNoetherianRing R`), and a finite free module over a Noetherian ring is Noetherian, so Mathlib already has the instance.
The whole proof is the single term `inferInstance`; confirm it, using `Fin d → R` as the model of $`R^{\oplus d}`.

```lean
example (R : Type*) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R] (d : ℕ) :
    IsNoetherian R (Fin d → R) := by
  sorry
```

:::solution
```lean
example (R : Type*) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R] (d : ℕ) :
    IsNoetherian R (Fin d → R) := inferInstance
```
:::

## Uniqueness of primary form

Mathlib records the rank of a free module as `Module.finrank R M`, defined without reference to any particular basis; `Module.finrank_eq_card_basis` then says any finite basis has exactly that many elements.

```lean
example (R : Type*) [CommRing R] [Nontrivial R] (M : Type*) [AddCommGroup M] [Module R M]
    {ι : Type*} [Fintype ι] (b : Module.Basis ι R M) :
    Module.finrank R M = Fintype.card ι :=
  Module.finrank_eq_card_basis b
```

The uniqueness of a free module's rank says any two finite bases have the same number of elements.
Prove it for bases indexed by $`\iota` and $`\kappa`.
Both counts equal the basis-free `Module.finrank R M`: apply `Module.finrank_eq_card_basis` to each of `b` and `c` and chain the two equalities (`rw [← Module.finrank_eq_card_basis b, ← Module.finrank_eq_card_basis c]` closes it).

```lean
example (R : Type*) [CommRing R] [Nontrivial R] (M : Type*) [AddCommGroup M] [Module R M]
    {ι κ : Type*} [Fintype ι] [Fintype κ]
    (b : Module.Basis ι R M) (c : Module.Basis κ R M) :
    Fintype.card ι = Fintype.card κ := by
  sorry
```

:::solution
```lean
example (R : Type*) [CommRing R] [Nontrivial R] (M : Type*) [AddCommGroup M] [Module R M]
    {ι κ : Type*} [Fintype ι] [Fintype κ]
    (b : Module.Basis ι R M) (c : Module.Basis κ R M) :
    Fintype.card ι = Fintype.card κ := by
  rw [← Module.finrank_eq_card_basis b, ← Module.finrank_eq_card_basis c]
```
:::

## Smith normal form

Mathlib phrases Smith normal form for the inclusion of a submodule $`N` into a finite free module $`M`: `Submodule.smithNormalForm` produces a basis of $`M` and a basis of $`N` that are *aligned*, related entry-by-entry by diagonal coefficients $`a_i` (the packaged data is a `Module.Basis.SmithNormalForm`).
Applying this to the image submodule is exactly how the diagonalization is obtained.

```lean
noncomputable example (R : Type*) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
    (M : Type*) [AddCommGroup M] [Module R M] {ι : Type*} [Finite ι]
    (b : Module.Basis ι R M) (N : Submodule R M) :
    Σ n : ℕ, Module.Basis.SmithNormalForm N ι n :=
  N.smithNormalForm b
```

The Euclidean-algorithm step multiplied a column by the matrix $`\begin{bmatrix} x & y \\ -v & u \end{bmatrix}`, asking you to check that it is invertible.
When $`xu + yv = 1`, its determinant is $`1`; verify this.
The literal `!![x, y; -v, u]` is Mathlib's notation for a matrix given entrywise (rows separated by `;`).
Expand the determinant with `Matrix.det_fin_two_of`, which rewrites `Matrix.det !![a, b; c, d]` to `a * d - b * c`; the remaining ring identity follows from `h` (e.g. `linear_combination h`).

```lean
example (R : Type*) [CommRing R] (x y u v : R) (h : x * u + y * v = 1) :
    Matrix.det !![x, y; -v, u] = 1 := by
  sorry
```

:::solution
```lean
example (R : Type*) [CommRing R] (x y u v : R) (h : x * u + y * v = 1) :
    Matrix.det !![x, y; -v, u] = 1 := by
  rw [Matrix.det_fin_two_of]
  linear_combination h
```
:::

## Problems

The first problem asks you to show that a vector space with a finite spanning set is $`k^{\oplus n}`.
Using the finite basis that Mathlib extracts, produce the linear isomorphism $`V \cong k^n`.
Take `n` to be `Module.finrank k V`, and get a basis indexed by `Fin n` from `Module.finBasis k V`.
Any basis `b` yields the coordinate isomorphism `b.equivFun : V ≃ₗ[k] (ι → k)`, which is exactly the map you need.

```lean
example (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] : ∃ n : ℕ, Nonempty (V ≃ₗ[k] (Fin n → k)) := by
  sorry
```

:::solution
```lean
example (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V]
    [FiniteDimensional k V] : ∃ n : ℕ, Nonempty (V ≃ₗ[k] (Fin n → k)) :=
  ⟨Module.finrank k V, ⟨(Module.finBasis k V).equivFun⟩⟩
```
:::
