import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Napkin.Meta.Recall
import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import Mathlib.NumberTheory.NumberField.Basic
import Mathlib.NumberTheory.KummerDedekind

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Unique factorization (finally!)" =>

%%%
file := "Unique-factorization"
%%%

Took long enough.

# Motivation

Suppose we're interested in solutions to the Diophantine equation $`n = x^2 + 5y^2` for a given $`n`.
The idea is to try and "factor" $`n` in $`\mathbb{Z}[\sqrt{-5}]`, for example $$`6 = (1+\sqrt{-5})(1-\sqrt{-5}).`
Unfortunately, this is not so simple, because as I've said before we don't have unique factorization of elements: $$`6 = 2 \cdot 3 = \left( 1+\sqrt{-5} \right)\left( 1-\sqrt{-5} \right).`
One reason this doesn't work is that we don't have a notion of a _greatest common divisor_.
We can write $`(35, 77) = 7`, but what do we make of $`(3, 1+\sqrt{-5})`?

The trick is to use ideals as a "generalized GCD".
Recall that by $`(a,b)` I mean the ideal $`\{ax + by \mid x,y \in \mathbb{Z}[\sqrt{-5}] \}`.
You can see that $`(35, 77) = (7)`, but $`(3, 1+\sqrt{-5})` will be left "unsimplified" because it doesn't represent an actual value in the ring.
Using these _sets_ (ideals) as elements, it turns out that we can develop a full theory of prime factorization, and we do so in this chapter.

In other words, we use the ideal $`(a_1, \dots, a_m)` to interpret a "generalized GCD" of $`a_1`, …, $`a_m`.
In particular, if we have a number $`x` we want to represent, we encode it as just $`(x)`.

Going back to our example of $`6`, $$`(6) = (2) \cdot (3) = \left( 1+\sqrt{-5} \right) \cdot \left( 1-\sqrt{-5} \right).`
Please take my word for it that in fact, the complete prime factorization of $`(6)` into prime ideals is
$$`(6) = (2,1-\sqrt{-5})^2 (3,1+\sqrt{-5})(3,1-\sqrt{-5}) = \mathfrak{p}^2 \mathfrak{q}_1 \mathfrak{q}_2.`
In fact, $`(2) = \mathfrak{p}^2`, $`(3) = \mathfrak{q}_1 \mathfrak{q}_2`, $`(1+\sqrt{-5}) = \mathfrak{p} \mathfrak{q}_1`, $`(1-\sqrt{-5}) = \mathfrak{p} \mathfrak{q}_2`.
So $`6` indeed factorizes uniquely into ideals, even though it doesn't factor into elements.

As one can see above, ideal factorization is more refined than element factorization.
Once you have the factorization into _ideals_, you can from there recover all the factorizations into _elements_.
The upshot of this is that if we want to write $`n` as $`x^2+5y^2`, we just have to factor $`n` into ideals, and from there we can recover all factorizations into elements, and finally all ways to write $`n` as $`x^2+5y^2`.
Since we can already break $`n` into rational prime factors (for example $`6 = 2 \cdot 3` above) we just have to figure out how each rational prime $`p \mid n` breaks down.
There's a recipe for this, the factoring algorithm later in this chapter!
In fact, I'll even tell you what is says in this special case:

- If $`t^2+5` factors as $`(t+c)(t-c) \pmod p`, then $`(p) = (p, c+\sqrt{-5})(p, c-\sqrt{-5})`.
- Otherwise, $`(p)` is a prime ideal.

In this chapter we'll develop this theory of unique factorization in full generality.

:::REMARK
In this chapter, I'll be using the letters $`\mathfrak{a}`, $`\mathfrak{b}`, $`\mathfrak{p}`, $`\mathfrak{q}` for ideals of $`\mathcal{O}_K`.
When fractional ideals arise, I'll use $`I` and $`J` for them.
:::

# Ideal arithmetic

:::PROTOTYPE
$`(x)(y) = (xy)`, and $`(x)+(y)=(\gcd(x, y))`.
In any case, think in terms of generators.
:::

First, I have to tell you how to add and multiply two ideals $`\mathfrak{a}` and $`\mathfrak{b}`.

:::DEFINITION
Given two ideals $`\mathfrak{a}` and $`\mathfrak{b}` of a ring $`R`, we define
$$`\mathfrak{a} + \mathfrak{b} \coloneqq \left\{ a+b \mid a \in \mathfrak{a}, b \in \mathfrak{b} \right\}`
$$`\mathfrak{a} \cdot \mathfrak{b} \coloneqq \left\{ a_1b_1 + \dots + a_n b_n \mid a_i \in \mathfrak{a}, b_i \in \mathfrak{b} \right\}.`
:::

(Note that infinite sums don't make sense in general rings, which is why in $`\mathfrak{a} \cdot \mathfrak{b}` we cut off the sum after some finite number of terms.)
You can readily check these are actually ideals.
This definition is more natural if you think about it in terms of the generators of $`\mathfrak{a}` and $`\mathfrak{b}`.

:::PROPOSITION "Ideal arithmetic via generators"
Suppose $`\mathfrak{a} = \left( a_1, a_2, \dots, a_n \right)` and $`\mathfrak{b} = \left( b_1, \dots, b_m \right)` are ideals in a ring $`R`.
Then

1. $`\mathfrak{a} + \mathfrak{b}` is the ideal generated by $`a_1, \dots, a_n, b_1, \dots, b_m`.
2. $`\mathfrak{a} \cdot \mathfrak{b}` is the ideal generated by $`a_i b_j`, for $`1 \le i \le n` and $`1 \le j \le m`.
:::

:::PROOF
Pretty straightforward; just convince yourself that this result is correct.
:::

In other words, for sums you append the two sets of generators together, and for products you take products of the generators.
Note that for principal ideals, this coincides with "normal" multiplication, for example $$`(3) \cdot (5) = (15)` in $`\mathbb{Z}`.

Both operations already exist on `Ideal R`: the sum is the lattice join (`Ideal.add_eq_sup : I + J = I ⊔ J` — "smallest ideal containing both", which is the generator description), the product is the `*` from the `Mul (Ideal R)` instance, and the generator descriptions are `Ideal.span_union` and `Ideal.span_mul_span`.
Principal-times-principal is `Ideal.span_singleton_mul_span_singleton`.

:::REMARK
Note that for an ideal $`\mathfrak{a}` and an element $`c`, the set $$`c \mathfrak{a} = \left\{ ca \mid a \in \mathfrak{a} \right\}` is equal to $`(c) \cdot \mathfrak{a}`.
So "scaling" and "multiplying by principal ideals" are the same thing.
This is important, since we'll be using the two notions interchangeably.
:::

:::REMARK
The addition of two ideals does not correspond to the addition of elements — for example, $`(4)+(6)=(4, 6)=(2)`, but $`4+6=10`.

This is the best we can hope for — addition of elements does not make sense for ideals — for example, $`1+1=2` and $`1+(-1)=0`, but as ideals, $`(1)=(-1)`.

In fact, addition of ideal is the straightforward generalization of $`\gcd` of elements — as you can check in the example above, $`\gcd(4, 6)=2`.

Nevertheless, I hope you agree that $`\mathfrak{a}+\mathfrak{b}` is a natural notation, compared to something like $`(\mathfrak{a}, \mathfrak{b})`.

Because factorization involves _multiplying_, instead of adding, the ideals together, we will not need to use the notation $`\mathfrak{a}+\mathfrak{b}` any time soon.
:::

Finally, since we want to do factorization we better have some notion of divisibility.
So we define:

:::DEFINITION
We say $`\mathfrak{a}` divides $`\mathfrak{b}` and write $`\mathfrak{a} \mid \mathfrak{b}` if $`\mathfrak{a} \supseteq \mathfrak{b}`.
:::

Note the reversal of inclusions!
So $`(3)` divides $`(15)`, because $`(15)` is contained in $`(3)`; every multiple of $`15` is a multiple of $`3`.
And from the example in the previous section: In $`\mathbb{Z}[\sqrt{-5}]`, $`(3,1-\sqrt{-5})` divides $`(3)` and $`(1 - \sqrt{-5})`.

"To divide is to contain" is a genuine theorem rather than a definition: divisibility `I ∣ J` means literally `∃ K, J = I * K`, and in a Dedekind domain (below) the two agree:

```lean
recall Ideal.dvd_iff_le {A : Type*} [CommRing A] [IsDedekindDomain A]
    {I J : Ideal A} :
    I ∣ J ↔ J ≤ I
```

(In an arbitrary commutative ring only the forward direction `Ideal.le_of_dvd` survives; the reverse is one of the many superpowers Dedekind domains are about to grant us.
Note also that `≤` on ideals is inclusion, so the reversal of inclusions is right there in the statement.)

Finally, the *prime ideals* are defined as in the rings chapter: $`\mathfrak{p}` is prime if $`xy \in \mathfrak{p}` implies $`x \in \mathfrak{p}` or $`y \in \mathfrak{p}`.
This is compatible with the definition of divisibility:

:::EXERCISE
A nonzero proper ideal $`\mathfrak{p}` is prime if and only if whenever $`\mathfrak{p}` divides $`\mathfrak{a} \mathfrak{b}`, $`\mathfrak{p}` divides one of $`\mathfrak{a}` or $`\mathfrak{b}`.
:::

The exercise is exactly the compatibility between `Ideal.IsPrime` and the general algebra predicate `Prime` (in the divisibility sense of the flavors-of-rings chapter), recorded as `Ideal.prime_iff_isPrime`.
As mentioned in the rings chapter, this also lets us ignore multiplication by units: $`(-3) = (3)`.

# Dedekind domains

:::PROTOTYPE
Any $`\mathcal{O}_K` is a Dedekind domain.
:::

We now define a Dedekind domain as follows.

:::DEFINITION
An integral domain $`\mathcal A` is a *Dedekind domain* if it is Noetherian, integrally closed, and _every nonzero prime ideal of $`\mathcal A` is in fact maximal_.
(The last condition is the important one.)
:::

:::REMARK
We'll prove momentarily that $`\mathcal{O}_K` is a Dedekind domain for any number field $`K`.
This is really the only case we'll use in this book.
So, introducing the term "Dedekind domain" is mainly here to highlight which properties of $`\mathcal{O}_K` are used for unique factorization, not because we will actually encounter other kinds of Dedekind domains.
:::

Here there's one new word I have to define for you, but we won't make much use of it.

:::DEFINITION
Let $`R` be an integral domain and let $`K` be its field of fractions.
We say $`R` is *integrally closed* if the only elements $`a \in K` which are roots of _monic_ polynomials in $`R` are the elements of $`R` (which are roots of the trivial $`x-r` polynomial).
:::

The _interesting_ condition in the definition of a Dedekind domain is the last one: prime ideals and maximal ideals are the same thing.
The other conditions are just technicalities, but "primes are maximal" has real substance.

The class is assembled from the same three conditions:

```lean
recall IsDedekindDomain (A : Type*) [CommRing A] : Prop
```

extends `IsDomain A` together with `IsDedekindRing A`, which packages `IsNoetherian A A`, `IsIntegrallyClosed A`, and — for the interesting condition — `Ring.DimensionLEOne A`: every nonzero prime ideal is maximal, phrased as "Krull dimension at most one".
(Each ingredient is its own typeclass, so partial credit like "Noetherian and integrally closed but dimension two" remains expressible.)

:::EXAMPLE "ℤ is a Dedekind domain"
The ring $`\mathbb{Z}` is a Dedekind domain.
Note that

- $`\mathbb{Z}` is Noetherian (for obvious reasons).
- $`\mathbb{Z}` has field of fractions $`\mathbb{Q}`.
  If $`f(x) \in \mathbb{Z}[x]` is monic, then by the rational root theorem any rational roots are integers (this is the same as the proof that $`\overline{\mathbb{Z}} \cap \mathbb{Q} = \mathbb{Z}`).
  Hence $`\mathbb{Z}` is integrally closed.
- The nonzero prime ideals of $`\mathbb{Z}` are $`(p)`, which also happen to be maximal.
:::

The case of interest is a ring $`\mathcal{O}_K` in which we wish to do factorizing.
We're now going to show that for any number field $`K`, the ring $`\mathcal{O}_K` is a Dedekind domain.
First, the boring part.

:::PROPOSITION "The ring of integers is integrally closed and Noetherian"
For any number field $`K`, the ring $`\mathcal{O}_K` is integrally closed and Noetherian.
:::

:::PROOF
Boring, but here it is anyways for completeness.

Since $`\mathcal{O}_K \cong \mathbb{Z}^{\oplus n}`,{margin}[By the free-module theorem from the previous chapter.] we get that it's Noetherian.

Now we show that $`\mathcal{O}_K` is integrally closed.
Suppose that $`\eta \in K` is the root of some polynomial with coefficients in $`\mathcal{O}_K`.
Thus $$`\eta^n = \alpha_{n-1} \cdot \eta^{n-1} + \alpha_{n-2} \cdot \eta^{n-2} + \dots + \alpha_0` where $`\alpha_i \in \mathcal{O}_K`.
We want to show that $`\eta \in \mathcal{O}_K` as well.

Well, from the above, $`\mathcal{O}_K[\eta]` is finitely generated… thus $`\mathbb{Z}[\eta] \subseteq \mathcal{O}_K[\eta]` is finitely generated.
So $`\eta \in \overline{\mathbb{Z}}`, and hence $`\eta \in K \cap \overline{\mathbb{Z}} = \mathcal{O}_K`.
:::

Now let's do the fun part.
We'll prove a stronger result, which will re-appear repeatedly.

:::THEOREM "Important: prime ideals divide rational primes"
Let $`\mathcal{O}_K` be a ring of integers and $`\mathfrak{p}` a nonzero prime ideal inside it.
Then $`\mathfrak{p}` contains a rational prime $`p`.
Moreover, $`\mathfrak{p}` is maximal.
:::

For a concrete example, consider $`(2+i) \subseteq \mathbb{Z}[i]`.
In this case, $`p = 5`, and because $`p \in (2+i)`, we get that the lattice is periodic in both dimensions with period $`5`, which implies finitely many points in $`\{a+bi \mid 0 \le a, b \le 4, a, b \in \mathbb{Z}\}` suffices to cover all cosets modulo the ideal.

The proof of the finiteness of the quotient here is closely related to the statement that the mesh of the lattice is finite, which will be covered in the next chapter.

:::PROOF
Take any $`\alpha \neq 0` in $`\mathfrak{p}`.
Its Galois conjugates are algebraic integers so their product $`\operatorname{N}(\alpha)/\alpha` is in $`\mathcal{O}_K` (even though each individual conjugate need not be in $`K`).
Consequently, $`\operatorname{N}(\alpha) \in \mathfrak{p}`, and we conclude $`\mathfrak{p}` contains some integer.

Then take the smallest positive integer in $`\mathfrak{p}`, say $`p`.
We must have that $`p` is a rational prime, since otherwise $`\mathfrak{p} \ni p = xy` implies one of $`x,y \in \mathfrak{p}`.
This shows the first part.

We now do something pretty tricky to show $`\mathfrak{p}` is maximal.
Look at $`\mathcal{O}_K / \mathfrak{p}`; since $`\mathfrak{p}` is prime it's supposed to be an integral domain… but we claim that it's actually finite!
To do this, we forget that we can multiply on $`\mathcal{O}_K`.
Recalling that $`\mathcal{O}_K \cong \mathbb{Z}^{\oplus n}` as an abelian group, we obtain a map $$`{\mathbb{F}_p}^{\oplus n} \cong \mathcal{O}_K / (p) \twoheadrightarrow \mathcal{O}_K / \mathfrak{p}.`
Hence $`\left\lvert \mathcal{O}_K / \mathfrak{p} \right\rvert \le p^n` is _finite_.
Since finite integral domains are fields (a problem from the flavors-of-rings chapter) we are done.
:::

Since every nonzero prime $`\mathfrak{p}` is maximal, we now know that $`\mathcal{O}_K` is a Dedekind domain.
And so does Mathlib, as an instance available whenever `[NumberField K]` is:

```lean
recall (K : Type*) [Field K] [NumberField K] :
    IsDedekindDomain (NumberField.RingOfIntegers K)
```

:::REMARK
An alternative proof for the first part is: because $`\mathfrak{p}` is an ideal, $`\alpha \cdot \mathcal{O}_K \subseteq \mathfrak{p}`, but $`\alpha \cdot \mathcal{O}_K` is a free $`\mathbb{Z}`-module of rank $`n`, so $`\mathfrak{p}` is squeezed between two free $`\mathbb{Z}`-modules of rank $`n`, by the structure theorem we must have $`\mathfrak{p}` is also free of rank $`n`.
So the quotient is finite, then use the lemma that an ideal divides its norm (from the end of this chapter).
:::

# Unique factorization works

Okay, I'll just say it now!

:::MORAL
Unique factorization works perfectly in Dedekind domains!
:::

:::REMARK "Comparison between Dedekind domain and UFD"
If we temporarily forget about the Noetherian and integrally closed condition, we have:

- An integral domain admits unique factorization of elements if the prime elements and the irreducible elements are the same.
- An integral domain admits unique factorization of ideals if the prime ideals and the maximal ideals are the same.

Notice the similarity — in either case, the Noetherian condition is "merely" to ensure that, if you keep extracting prime factors, you will terminate in a finite time.
:::

:::EXAMPLE "What went wrong if $`\\mathcal A` is not integrally closed?"
Consider $`\mathcal A = 2\mathbb{Z}`, which is an ideal of $`\mathbb{Z}`.
Clearly, every nonzero prime ideal is maximal.

Nevertheless, in $`\mathcal A`, $`(2 \cdot 3 \cdot 5)=(60)` is not a prime ideal (so of course it isn't a maximal ideal), but we cannot break it down into, for example, $`(2 \cdot 3) \cdot (5)`.
:::

:::THEOREM "Prime factorization works"
Let $`\mathfrak{a}` be a nonzero proper ideal of a Dedekind domain $`\mathcal A`.
Then $`\mathfrak{a}` can be written as a finite product of nonzero prime ideals $`\mathfrak{p}_i`, say $$`\mathfrak{a} = \mathfrak{p}_1^{e_1} \mathfrak{p}_2^{e_2} \dots \mathfrak{p}_g^{e_g}` and this factorization is unique up to the order of the $`\mathfrak{p}_i`.

Moreover, $`\mathfrak{a}` divides $`\mathfrak{b}` if and only if for every prime ideal $`\mathfrak{p}`, the exponent of $`\mathfrak{p}` in $`\mathfrak{a}` is less than or equal to the corresponding exponent in $`\mathfrak{b}`.
:::

The theorem is delivered as an instance: in a Dedekind domain, the ideals — with the multiplication defined above — form a `UniqueFactorizationMonoid`, the same abstraction that expressed unique factorization of _elements_ in the flavors-of-rings chapter, now applied one level up:

```lean
recall (A : Type*) [CommRing A] [IsDedekindDomain A] :
    UniqueFactorizationMonoid (Ideal A)
```

So everything proved about UFDs — existence and essential uniqueness of factorizations into `Prime` elements, `∣`-comparison by exponents — specializes to ideals for free, with "unit" degenerating to the single ideal $`(1)`.

I won't write out the proof, but I'll describe the basic method of attack.
Section 3 of Ullery's _Minkowski Theory and the Class Number_ does a nice job of explaining it.
When we proved the fundamental theorem of arithmetic, the basic plot was:

1. Show that if $`p` is a rational prime{margin}[Note that the kindergarten definition of a prime is that "$`p` isn't the product of two smaller integers". This isn't the correct definition of a prime: the definition of a prime is that $`p \mid bc` means $`p \mid b` or $`p \mid c`. The kindergarten definition is something called "irreducible". Fortunately, in $`\mathbb{Z}`, primes and irreducibles are the same thing, so no one ever told you that your definition of "prime" was wrong.] then $`p \mid bc` means $`p \mid b` or $`p \mid c`.
   (This is called Euclid's Lemma.)
2. Use strong induction to show that every $`N > 1` can be written as the product of primes (easy).
3. Show that if $`p_1 \dots p_m = q_1 \dots q_n` for some primes (not necessarily unique), then $`p_1 = q_i` for some $`i`, say $`q_1`.
4. Divide both sides by $`p_1` and use induction.

What happens if we try to repeat the proof here?
We get step 1 for free, because we're using a better definition of "prime".
We can also do step 3, since it follows from step 1.
But step 2 doesn't work, because for abstract Dedekind domains we don't really have a notion of size.
And step 4 doesn't work because we don't yet have a notion of what the inverse of a prime ideal is.

Well, it turns out that we _can_ define the inverse $`\mathfrak{a}^{-1}` of an ideal, and I'll do so by the end of this chapter.
You then need to check that $`\mathfrak{a} \cdot \mathfrak{a}^{-1} = (1) = \mathcal A`.
In fact, even this isn't easy.
You have to check it's true for prime ideals $`\mathfrak{p}`, _then_ prove prime factorization, and then prove that this is true.
Moreover, $`\mathfrak{a}^{-1}` is not actually an ideal, so you need to work in the field of fractions $`K` instead of $`\mathcal A`.

So the main steps in the new situation are as follows:

1. First, show that every ideal $`\mathfrak{a}` divides $`\mathfrak{p}_1 \dots \mathfrak{p}_g` for some finite collection of primes.
   (This is an application of Zorn's Lemma.)
2. Define $`\mathfrak{p}^{-1}` and show that $`\mathfrak{p} \mathfrak{p}^{-1} = (1)`.
3. Show that a factorization exists (again using Zorn's Lemma).
4. Show that it's unique, using the new inverse we've defined.

Finally, let me comment on how nice this is if $`\mathcal A` is a PID (like $`\mathbb{Z}`).
Thus every element $`a \in \mathcal A` is in direct correspondence with an ideal $`(a)`.
Now suppose $`(a)` factors as a product of ideals $`\mathfrak{p}_i = (p_i)`, say, $$`(a) = (p_1)^{e_1} (p_2)^{e_2} \dots (p_n)^{e_n}.`
This verbatim reads $$`a = u p_1^{e_1} p_2^{e_2} \dots p_n^{e_n}` where $`u` is some unit (recall the definition from the rings chapter).
Hence, Dedekind domains which are PID's satisfy unique factorization for _elements_, just like in $`\mathbb{Z}`.
(In fact, the converse of this is true.)

# The factoring algorithm

Let's look at some examples from quadratic fields.
Recall that if $`K = \mathbb{Q}(\sqrt{d})`, then
$$`\mathcal{O}_K = \begin{cases} \mathbb{Z}[\sqrt d] & d \equiv 2,3 \pmod 4 \\ \mathbb{Z}\left[ \frac{1+\sqrt d}{2} \right] & d \equiv 1 \pmod 4. \end{cases}`
Also, recall that the norm of $`a+b\sqrt{-d}` is given by $`a^2+db^2`.

:::EXAMPLE "Factoring 6 in the integers of ℚ(√−5)"
Let $`\mathcal{O}_K = \mathbb{Z}[\sqrt{-5}]` arise from $`K = \mathbb{Q}(\sqrt{-5})`.
We've already seen that $$`(6) = (2) \cdot (3) = \left( 1+\sqrt{-5} \right)\left( 1-\sqrt{-5} \right)` and you can't get any further with these principal ideals.
But let $$`\mathfrak{p} = \left( 1+\sqrt{-5}, 2 \right) = \left( 1-\sqrt{-5}, 2 \right) \quad\text{and}\quad \mathfrak{q}_1 = (1+\sqrt{-5},3), \; \mathfrak{q}_2 = (1-\sqrt{-5},3).`
Then it turns out $`(6) = \mathfrak{p}^2\mathfrak{q}_1\mathfrak{q}_2`.
More specifically, $`(2) = \mathfrak{p}^2`, $`(3) = \mathfrak{q}_1\mathfrak{q}_2`, and $`(1+\sqrt{-5}) = \mathfrak{p}\mathfrak{q}_1` and $`(1-\sqrt{-5}) = \mathfrak{p}\mathfrak{q}_2`.
(Proof in just a moment.)
:::

I want to stress that all our ideals are computed relative to $`\mathcal{O}_K`.
So for example, $$`(2) = \left\{ 2x \mid x \in \mathcal{O}_K \right\}.`

How do we know in this example that $`\mathfrak{p}` is prime/maximal?
(Again, these are the same since we're in a Dedekind domain.)
Answer: look at $`\mathcal{O}_K / \mathfrak{p}` and see if it's a field.
There is a trick to this: we can express $$`\mathcal{O}_K = \mathbb{Z}[\sqrt{-5}] \cong \mathbb{Z}[x] / (x^2+5).`
So when we take _that_ mod $`\mathfrak{p}`, we get that $$`\mathcal{O}_K / \mathfrak{p} = \mathbb{Z}[x] / (x^2+5, 2, 1+x) \cong \mathbb{F}_2[x] / (x^2+5,x+1)` as rings.

:::QUESTION
Conclude that $`\mathcal{O}_K / \mathfrak{p} \cong \mathbb{F}_2`, and satisfy yourself that $`\mathfrak{q}_1` and $`\mathfrak{q}_2` are also maximal.
:::

I should give an explicit example of an ideal multiplication: let's compute
$$`\mathfrak{q}_1\mathfrak{q}_2 = \left( (1+\sqrt{-5})(1-\sqrt{-5}), 3(1+\sqrt{-5}), 3(1-\sqrt{-5}), 9 \right) = \left( 6, 3+3\sqrt{-5}, 3-3\sqrt{-5}, 9 \right) = \left( 6, 3+3\sqrt{-5}, 3-3\sqrt{-5}, 3 \right) = (3)`
where we first did $`9-6=3` (think Euclidean algorithm!), then noted that all the other generators don't contribute anything we don't already have with the $`3` (again these are ideals computed in $`\mathcal{O}_K`).
You can do the computation for $`\mathfrak{p}^2`, $`\mathfrak{p}\mathfrak{q}_1`, $`\mathfrak{p}\mathfrak{q}_2` in the same way.

Finally, it's worth pointing out that we should quickly verify that $`\mathfrak{p} \neq (x)` for some $`x`; in other words, that $`\mathfrak{p}` is not principal.
Assume for contradiction that it is.
Then $`x` divides both $`1+\sqrt{-5}` and $`2`, in the sense that $`1+\sqrt{-5} = \alpha_1 x` and $`2 = \alpha_2 x` for some $`\alpha_1, \alpha_2 \in \mathcal{O}_K`.
(Principal ideals are exactly the "multiples" of $`x`, so $`(x) = x \mathcal{O}_K`.)
Taking the norms, we find that $`\operatorname{N}_{K/\mathbb{Q}}(x)` divides both $$`\operatorname{N}_{K/\mathbb{Q}}(1+\sqrt{-5}) = 6 \quad\text{and}\quad \operatorname{N}_{K/\mathbb{Q}}(2) = 4.`
Since $`\mathfrak{p} \neq (1)`, $`x` cannot be a unit, so its norm must be $`2`.
But there are no elements of norm $`2 = a^2+5b^2` in $`\mathcal{O}_K`.

:::EXAMPLE "Factoring 3 in the integers of ℚ(√−17)"
Let $`\mathcal{O}_K = \mathbb{Z}[\sqrt{-17}]` arise from $`K = \mathbb{Q}(\sqrt{-17})`.
We know $`\mathcal{O}_K \cong \mathbb{Z}[x] / (x^2+17)`.
Now $$`\mathcal{O}_K / 3\mathcal{O}_K \cong \mathbb{Z}[x] / (3,x^2+17) \cong \mathbb{F}_3[x] / (x^2-1).`
This already shows that $`(3)` cannot be a prime (i.e. maximal) ideal, since otherwise our result should be a field.
Anyways, we have a projection $$`\mathcal{O}_K \twoheadrightarrow \mathbb{F}_3[x] / \left( (x-1)(x+1) \right).`
Let $`\mathfrak{q}_1` be the pre-image of $`(x-1)` in the image, that is, $$`\mathfrak{q}_1 = (3, \sqrt{-17}-1).`
Similarly, $$`\mathfrak{q}_2 = (3, \sqrt{-17}+1).`
We have $`\mathcal{O}_K / \mathfrak{q}_1 \cong \mathbb{F}_3`, so $`\mathfrak{q}_1` is maximal (prime).
Similarly $`\mathfrak{q}_2` is prime.
Magically, you can check explicitly that $$`\mathfrak{q}_1 \mathfrak{q}_2 = (3).`
Hence this is the factorization of $`(3)` into prime ideals.
:::

The fact that $`\mathfrak{q}_1 \mathfrak{q}_2 = (3)` looks magical, but it's really true:
$$`\mathfrak{q}_1\mathfrak{q}_2 = (3, \sqrt{-17}-1) (3, \sqrt{-17}+1) = (9, 3\sqrt{-17}+3, 3\sqrt{-17}-3, 18) = (9, 3\sqrt{-17}+3, 6) = (3, 3\sqrt{-17}+3, 6) = (3).`
In fact, it turns out this always works in general: given a rational prime $`p`, there is an algorithm to factor $`p` in any $`\mathcal{O}_K` of the form $`\mathbb{Z}[\theta]`.

::::THEOREM "Factoring algorithm / Dedekind-Kummer theorem"
Let $`K` be a number field.
Let $`\theta \in \mathcal{O}_K` with $`|\mathcal{O}_K / \mathbb{Z}[\theta]| = j < \infty`, and let $`p` be a prime not dividing $`j`.
Then $`(p) = p \mathcal{O}_K` is factored as follows:

:::quote
Let $`f` be the minimal polynomial of $`\theta` and factor $`\overline{f}` mod $`p` as $$`\overline{f} \equiv \prod_{i=1}^g (\overline{f}_i)^{e_i} \pmod p.`
Then $`\mathfrak{p}_i = (f_i(\theta), p)` is prime for each $`i` and the factorization of $`(p)` is $$`\mathcal{O}_K \supseteq (p) = \prod_{i=1}^g \mathfrak{p}_i^{e_i}.`
:::

In particular, if $`K` is monogenic with $`\mathcal{O}_K = \mathbb{Z}[\theta]` then $`j=1` and the theorem applies for all primes $`p`.
::::

In almost all our applications in this book, $`K` will be monogenic; i.e. $`j=1`.
Here $`\overline{\psi}` denotes the image in $`\mathbb{F}_p[x]` of a polynomial $`\psi \in \mathbb{Z}[x]`.

The theorem lives in `Mathlib.NumberTheory.KummerDedekind`, in maximum generality (any Dedekind domain downstairs, any prime not dividing the _conductor_ — the ideal-theoretic version of our $`j`): `KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk` is the bijection between the prime factors of $`(p)` upstairs and the irreducible factors of $`f` mod $`p`, and `multiplicity_factors_map_eq_multiplicity` matches up the exponents $`e_i`.

:::QUESTION
There are many possible pre-images $`f_i` we could have chosen (for example if $`\overline{f_i} = x^2+1 \pmod 3`, we could pick $`f_i = x^2 + 3x + 7`.)
Why does this not affect the value of $`\mathfrak{p}_i`?
:::

Note that earlier, we could check the factorization worked for any particular case.
The proof that this works is much the same, but we need one extra tool, the ideal norm.
After that we leave the proposition as a problem at the end of this chapter.

This algorithm gives us a concrete way to compute prime factorizations of $`(p)` in any monogenic number field with $`\mathcal{O}_K = \mathbb{Z}[\theta]`.
To summarize the recipe:

1. Find the minimal polynomial of $`\theta`, say $`f \in \mathbb{Z}[x]`.
2. Factor $`f` mod $`p` into irreducible polynomials $`{\overline{f}_1}^{e_1} {\overline{f}_2}^{e_2} \dots {\overline{f}_g}^{e_g}`.
3. Compute $`\mathfrak{p}_i = (f_i(\theta), p)` for each $`i`.

Then your $`(p) = \mathfrak{p}_1^{e_1} \dots \mathfrak{p}_g^{e_g}`.

Or even shorter:

:::MORAL
In order to factorize $`p` in $`\mathbb{Z}[x]/(f(x))`, we can factorize $`f(x)` in $`\mathbb{Z}[x]/(p)` instead.
:::

Both are equivalent to factorizing $`0` in $`\mathbb{Z}[x]/(f(x), p)` — in other words, writing $`\mathbb{Z}[x]/(f(x), p)` as a direct sum of $`\mathbb{Z}[x]`-modules.

:::EXERCISE
Factor $`(29)` in $`\mathbb{Z}[i]` using the above algorithm.
:::

# Fractional ideals

:::PROTOTYPE
Analog to $`\mathbb{Q}` for $`\mathbb{Z}`, allowing us to take inverses of ideals.
Prime factorization works in the nicest way possible.
:::

We now have a neat theory of factoring ideals of $`\mathcal A`, just like factoring the integers.
Now note that our factorization of $`\mathbb{Z}` naturally gives a way to factor elements of $`\mathbb{Q}`; just factor the numerator and denominator separately.

Let's make the analogy clearer.
The analogue of a rational number is as follows.

:::DEFINITION
Let $`\mathcal A` be a Dedekind domain with field of fractions $`K`.
A *fractional ideal* $`J` of $`K` is a set of the form $$`J = \frac{1}{x} \cdot \mathfrak{a} \quad \text{where } x \in \mathcal A \text{, and } \mathfrak{a} \text{ is an integral ideal.}`
For emphasis, ideals of $`\mathcal A` will be sometimes referred to as *integral ideals*.
:::

You might be a little surprised by this definition: one would expect that a fractional ideal should be of the form $`\frac{\mathfrak{a}}{\mathfrak{b}}` for some integral ideals $`\mathfrak{a}`, $`\mathfrak{b}`.
But in fact, it suffices to just take $`x \in \mathcal A` in the denominator.
The analogy is that when we looked at $`\mathcal{O}_K`, we found that we only needed integer denominators: $`\frac{1}{4-\sqrt3} = \frac{1}{13}(4+\sqrt3)`.
Similarly here, it will turn out that we only need to look at $`\frac1x \cdot \mathfrak{a}` rather than $`\frac{\mathfrak{a}}{\mathfrak{b}}`, and so we define it this way from the beginning.
See the problems for a different equivalent definition.

:::EXAMPLE "$`\\tfrac52\\mathbb{Z}` is a fractional ideal"
The set $$`\frac52 \mathbb{Z} = \left\{ \frac52n \mid n \in \mathbb{Z} \right\} = \frac{1}{2} (5)` is a fractional ideal of $`\mathbb{Z}`.
:::

Now, as we prescribed, the fractional ideals form a multiplicative group:

:::THEOREM "Fractional ideals form a group"
Let $`\mathcal A` be a Dedekind domain and $`K` its field of fractions.
For any integral ideal $`\mathfrak{a}`, the set $$`\mathfrak{a}^{-1} = \left\{ x \in K \mid x\mathfrak{a} \subseteq (1) = \mathcal A \right\}` is a fractional ideal with $`\mathfrak{a} \mathfrak{a}^{-1} = (1)`.
:::

(This result is nontrivial.
To prove $`\mathfrak{a} \mathfrak{a}^{-1} = (1)`, one approach is to prove it first for prime $`\mathfrak{a}`, then consider the factorization of $`\mathfrak{a}` into prime ideals.)

:::DEFINITION
Thus nonzero fractional ideals of $`K` form a group under multiplication with identity $`(1) = \mathcal A`.
This *ideal group* is denoted $`J_K`.
:::

The type is `FractionalIdeal A⁰ K` — the `A⁰` records that denominators are taken from the nonzero elements of `A` (the "non-zero-divisors") — defined for any domain, with the equivalent finitely-generated-submodule description from the problems as the actual underlying definition.
The theorem is then the instance `FractionalIdeal.semifield`, available exactly when `A` is a Dedekind domain: nonzero fractional ideals are invertible, so `J⁻¹` and division notation just work, and $`J_K` is the unit group `(FractionalIdeal A⁰ K)ˣ`.

:::EXAMPLE "$`(3)^{-1}` in $`\\mathbb{Z}`"
Please check that in $`\mathbb{Z}` we have $$`(3)^{-1} = \left\{ \frac 13 n \mid n \in \mathbb{Z} \right\} = \frac 13 \mathbb{Z}.`
:::

It follows that every fractional ideal $`J` can be uniquely written as $$`J = \prod_i \mathfrak{p}_i^{n_i} \cdot \prod_i \mathfrak{q}_i^{-m_i}` where $`n_i` and $`m_i` are positive integers.
In fact, $`\mathfrak{a}` is an integral ideal if and only if all its exponents are nonnegative, just like the case with integers.
So, a perhaps better way to think about fractional ideals is as products of prime ideals, possibly with negative exponents.

# The ideal norm

One last tool is the ideal norm, which gives us a notion of the "size" of an ideal.

:::DEFINITION
The *ideal norm* (or absolute norm) of a nonzero ideal $`\mathfrak{a} \subseteq \mathcal{O}_K` is defined as $`|\mathcal{O}_K / \mathfrak{a}|` and denoted $`\operatorname{N}(\mathfrak{a})`.
:::

:::EXAMPLE "Ideal norm of (5) in the Gaussian integers"
Let $`K = \mathbb{Q}(i)`, $`\mathcal{O}_K = \mathbb{Z}[i]`.
Consider the ideal $`(5)` in $`\mathcal{O}_K`.
We have that $$`\mathcal{O}_K / (5) \cong \{ a+bi \mid a,b \in \mathbb{Z}/5\mathbb{Z} \}` so $`(5)` has ideal norm $`25`, corresponding to the fact that $`\mathcal{O}_K/(5)` has $`5^2=25` elements.
:::

:::EXAMPLE "Ideal norm of (2+i) in the Gaussian integers"
You'll notice that $$`\mathcal{O}_K / (2+i) \cong \mathbb{F}_5` since mod $`2+i` we have both $`5 \equiv 0` and $`i \equiv -2`.
(Indeed, since $`(2+i)` is prime we had better get a field!)
Thus $`\operatorname{N}\left( (2+i) \right) = 5`; similarly $`\operatorname{N}\left( (2-i) \right) = 5`.
:::

Thus the ideal norm measures how "roomy" the ideal is: that is, $`(5)` is a lot more spaced out in $`\mathbb{Z}[i]` than it is in $`\mathbb{Z}`.
(This intuition will be important when we will actually view $`\mathcal{O}_K` as a lattice.)

:::QUESTION
What are the ideals with ideal norm one?
:::

Our example with $`(5)` suggests several properties of the ideal norm which turn out to be true:

:::LEMMA "Properties of the absolute norm"
Let $`\mathfrak{a}` be a nonzero ideal of $`\mathcal{O}_K`.

1. $`\operatorname{N}(\mathfrak{a})` is finite.
2. For any other nonzero ideal $`\mathfrak{b}`, $`\operatorname{N}(\mathfrak{a}\mathfrak{b}) = \operatorname{N}(\mathfrak{a})\operatorname{N}(\mathfrak{b})`.
3. If $`\mathfrak{a} = (a)` is principal, then $`\operatorname{N}(\mathfrak{a}) = |\operatorname{N}_{K/\mathbb{Q}}(a)|`.
:::

I unfortunately won't prove these properties, though we already did (a) in our proof that $`\mathcal{O}_K` was a Dedekind domain.

The ideal norm is `Ideal.absNorm`, and its bundling repeats the trick we saw for the element norm — it is a homomorphism by construction, so property (b) is again just `map_mul`:

```lean
recall Ideal.absNorm {S : Type*} [CommRing S] [IsDedekindDomain S]
    [Module.Free ℤ S] :
    Ideal S →*₀ ℕ
```

Property (c) is `Ideal.absNorm_span_singleton`, connecting the two norms of this chapter and the last: $`\operatorname{N}((a))` equals the absolute value of `Algebra.norm ℤ a`.

As with the case of the norm of an element, the ideal norm also has a geometrical interpretation: Recall that if $`\mathfrak{a} = (a)`, let $`\mu_a` be the multiplication-by-$`a` map, then $`\operatorname{N}_{K/\mathbb{Q}}(a) = |\det \mu_a|` measures how much $`K` is stretched under $`\mu_a` when viewed as a $`\mathbb{Q}`-vector space.

:::EXERCISE
Convince yourself that if $`\mu_a(\mathcal{O}_K) \subseteq \mathcal{O}_K`, then $`|\mathcal{O}_K / a \mathcal{O}_K|` is exactly equal to $`|\det \mu_a|`.
:::

This explains why $`\operatorname{N}(\mathfrak{a}) = |\operatorname{N}_{K/\mathbb{Q}}(a)|`, although note that $`\mathfrak{a} = (a) = (-a)`, so there need not be an unique multiplication-by-$`\mathfrak{a}` map.

The fact that $`\operatorname{N}` is completely multiplicative lets us also consider the norm of a fractional ideal $`J` by the natural extension
$$`J = \prod_i \mathfrak{p}_i^{n_i} \cdot \prod_i \mathfrak{q}_i^{-m_i} \quad \implies \quad \operatorname{N}(J) \coloneqq \frac{\prod_i \operatorname{N}(\mathfrak{p}_i)^{n_i}}{\prod_i \operatorname{N}(\mathfrak{q}_i)^{m_i}}.`
Thus $`\operatorname{N}` is a natural group homomorphism $`J_K \to \mathbb{Q}^\times`.

# Problems

:::PROBLEM
Show that there are three different factorizations of $`77` in $`\mathcal{O}_K`, where $`K = \mathbb{Q}(\sqrt{-13})`.
:::

:::PROBLEM
Let $`K = \mathbb{Q}(\sqrt[3] 2)`; take for granted that $`\mathcal{O}_K = \mathbb{Z}[\sqrt[3] 2]`.
Find the factorization of $`(5)` in $`\mathcal{O}_K`.
:::

:::PROBLEM "Fermat's little theorem"
Let $`\mathfrak{p}` be a prime ideal in some ring of integers $`\mathcal{O}_K`.
Show that for $`\alpha \in \mathcal{O}_K`, $$`\alpha^{\operatorname{N}(\mathfrak{p})} \equiv \alpha \pmod{\mathfrak{p}}.`
(Hint: copy the proof of the usual Fermat's little theorem.)
:::

:::PROBLEM
Let $`\mathcal A` be a Dedekind domain with field of fractions $`K`, and pick $`J \subseteq K`.
Show that $`J` is a fractional ideal if and only if

1. $`J` is closed under addition and multiplication by elements of $`\mathcal A`, and
2. $`J` is finitely generated as an abelian group.

More succinctly: $`J` is a fractional ideal $`\iff` $`J` is a finitely generated $`\mathcal A`-module.
(Hint: clear denominators!)
:::

:::PROBLEM
In the notation of the factoring algorithm, let $`I = \prod_{i=1}^g \mathfrak{p}_i^{e_i}`.
Assume for simplicity that $`K` is monogenic, hence $`\mathcal{O}_K = \mathbb{Z}[\theta]`.

1. Prove that each $`\mathfrak{p}_i` is prime.
2. Show that $`(p)` divides $`I`.
3. Use the norm to show that $`(p) = I`.

(Hint: (a) is straightforward.
For (b) work mod $`p`.
For (c) use norms.)
:::

:::PROBLEM "USEMO 2025" (chili := 1)
Let $`k` be a positive integer not divisible by $`6`.
Suppose that there exists a prime $`p` such that $`p` divides both $`2025^k-1` and $`2026^k-1`.
Prove that $`p<3^k`.
(Hint: let $`\omega` be a $`k`'th root of unity.
Let $`\mathfrak{p}` be any prime ideal above $`p` in the ring of integers of $`K = \mathbb{Q}(\omega)`.
Show that there exist indices $`i` and $`j` such that $`2025-\omega^i` and $`2026-\omega^j` are in $`\mathfrak{p}`.
Then show that $`1+\omega^i-\omega^j` is nonzero with norm at most $`3^k`.)
:::
