import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Napkin.Meta.Recall
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.FieldTheory.Finite.GaloisField

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Finite fields" =>

%%%
file := "Finite-fields"
%%%

In this short chapter, we classify all fields with finitely many elements and compute the Galois groups.
Nothing in here is very hard, and so most of the proofs are just sketches; if you like, you should check the details yourself.

The whole point of this chapter is to prove:

- A finite field $`F` must have order $`p^n`, with $`p` prime and $`n` an integer.
- In this case, $`F` has characteristic $`p`.
- All such fields are isomorphic, so it's customary to use the notation $`\mathbb{F}_{p^n}` for "the" finite field of order $`p^n` if we only care up to isomorphism.
- The extension $`F/\mathbb{F}_p` is Galois, and $`\operatorname{Gal}(F/\mathbb{F}_p)` is a cyclic group of order $`n`.
  The generator is the automorphism $$`\sigma \colon F \to F \quad\text{by}\quad x \mapsto x^p.`

If you're in a hurry you can just remember these results and skip to the next chapter.

# Example of a finite field

Before diving in, we give some examples.

Recall that the _characteristic_ of a field $`F` is the smallest positive integer $`p` such that $$`\underbrace{1_F + \dots + 1_F}_{p \text{ times}} = 0` or $`0` if no such integer $`p` exists.

:::EXAMPLE "Base field"
Let $`\mathbb{F}_p` denote the field of integers modulo $`p`.
This is a field with $`p` elements, with characteristic $`p`.
:::

:::EXAMPLE "The finite field of nine elements"
Let $$`F \cong \mathbb{F}_3[X]/(X^2+1) \cong \mathbb{Z}[i] / (3).`
We can think of its elements as $$`\left\{ a + bi \mid 0 \le a,b \le 2 \right\}.`
Since $`(3)` is prime in $`\mathbb{Z}[i]`, the ring of integers of $`\mathbb{Q}(i)`, we see $`F` is a field with $`3^2 = 9` elements inside it.
Note that, although this field has $`9` elements, every element $`x` has the property that $$`3x = \underbrace{x + \dots + x}_{3 \text{ times}} = 0.`
In particular, $`F` has characteristic $`3`.
:::

# Finite fields have prime power order

:::LEMMA
If the characteristic of a field $`F` isn't zero, it must be a prime number.
:::

:::PROOF
Assume not, so $`n = ab` for $`a,b < n`.
Then let $$`A = \underbrace{1_F + \dots + 1_F}_{a \text{ times}} \neq 0` and $$`B = \underbrace{1_F + \dots + 1_F}_{b \text{ times}} \neq 0.`
Then $`AB = 0`, contradicting the fact that $`F` is a field.
:::

We like fields of characteristic zero, but unfortunately for finite fields we are doomed to have nonzero characteristic.

:::LEMMA "Finite fields have prime power orders"
Let $`F` be a finite field.
Then

1. Its characteristic is nonzero, and hence some prime $`p`.
2. The field $`F` is a finite extension of $`\mathbb{F}_p`, and in particular it is an $`\mathbb{F}_p`-vector space.
3. We have $`\left\lvert F \right\rvert = p^n` for some prime $`p`, integer $`n`.
:::

:::PROOF
Very briefly, since this is easy:

1. Apply Lagrange's theorem (or pigeonhole principle!) to $`(F, +)` to get the characteristic isn't zero.
2. The additive subgroup of $`(F,+)` generated by $`1_F` is an isomorphic copy of $`\mathbb{F}_p`.
3. Since it's a field extension, $`F` is a finite-dimensional vector space over $`\mathbb{F}_p`, with some basis $`e_1, \dots, e_n`.
   It follows that there are $`p^n` elements of $`F`.
:::

:::REMARK
An amusing alternate proof of (c) by contradiction: if a prime $`q \neq p` divides $`\left\lvert F \right\rvert`, then by Cauchy's theorem (from the group actions chapter) on $`(F, +)` there's a (nonzero) element $`x` of order $`q`.
Evidently $$`x \cdot ( \underbrace{1_F + \dots + 1_F}_{q \text{ times}} ) = 0` then, but $`x \neq 0`, and hence the characteristic of $`F` also divides $`q`, which is impossible.
:::

An important point in the above proof is that

:::LEMMA "Finite fields are field extensions of 𝔽ₚ"
If $`\left\lvert F \right\rvert = p^n` is a finite field, then there is an isomorphic copy of $`\mathbb{F}_p` sitting inside $`F`.
Thus $`F` is a field extension of $`\mathbb{F}_p`.
:::

We want to refer a lot to this copy of $`\mathbb{F}_p`, so in what follows:

:::ABUSE
Every integer $`n` can be identified as an element of $`F`, namely $$`n \coloneqq \underbrace{1_F + \dots + 1_F}_{n \text{ times}}.`
Note that (as expected) this depends only on $`n \pmod p`.
:::

This notation makes it easier to think about statements like the following.

:::THEOREM "Freshman's dream"
For any $`a,b : F` we have $$`(a+b)^p = a^p + b^p.`
:::

:::PROOF
Use the Binomial theorem, and the fact that $`\binom pi` is divisible by $`p` for $`0 < i < p`.
:::

:::EXERCISE
Convince yourself that this proof works.
:::

# All finite fields are isomorphic

We next proceed to prove "Fermat's little theorem":

:::THEOREM "Fermat's little theorem in finite fields"
Let $`F` be a finite field of order $`p^n`.
Then every element $`x : F` satisfies $$`x^{p^n} - x = 0.`
:::

:::PROOF
If $`x = 0` it's true; otherwise, use Lagrange's theorem on the abelian group $`(F, \times)` to get $`x^{p^n-1} = 1_F`.
:::

We can now prove the following result, which is the "main surprise" about finite fields: that there is a unique one up to isomorphism for each size.

:::THEOREM "Complete classification of finite fields"
A field $`F` is a finite field with $`p^n` elements if and only if it is a splitting field of $`x^{p^n}-x` over $`\mathbb{F}_p`.
:::

:::PROOF
By "Fermat's little theorem", all the elements of $`F` satisfy this polynomial.
So we just have to show that the roots of this polynomial are distinct (i.e. that it is separable).

To do this, we use the derivative trick again: the derivative of this polynomial is $$`p^n \cdot x^{p^n-1} - 1 = -1` which has no roots at all, so the polynomial cannot have any double roots.
:::

:::DEFINITION
For this reason, it's customary to denote _the_ field with $`p^n` elements by $`\mathbb{F}_{p^n}`.
:::

Note that the polynomial $`x^{p^n}-x \pmod p` is far from irreducible, but the computation above shows that it's separable.

:::EXAMPLE "The finite field of order nine again"
The polynomial $`x^9-x` is separable modulo $`3` and has factorization $$`x(x+1)(x+2)(x^2+1)(x^2+x+2)(x^2+2x+2) \pmod 3.`

So if $`F` has order $`9`, then we intuitively expect it to be the field generated by adjoining all the roots: $`0`, $`1`, $`2`, as well as $`\pm i`, $`1 \pm i`, $`2 \pm i`.
Indeed, that's the example we had at the beginning of this chapter.

(Here $`i` denotes _an_ element of $`\mathbb{F}_9` satisfying $`i^2=-1`.
The notation is deliberately similar to the usual imaginary unit.)
:::

# The Galois theory of finite fields

Retain the notation $`\mathbb{F}_{p^n}` now (instead of $`F` like before).
By the above theorem, it's the splitting field of a separable polynomial, hence we know that $`\mathbb{F}_{p^n} /\mathbb{F}_p` is a Galois extension.
We would like to find the Galois group.

In fact, we are very lucky: it is cyclic.
First, we exhibit one such element $`\sigma_p \in \operatorname{Gal}(\mathbb{F}_{p^n} /\mathbb{F}_p)`:

:::THEOREM "The pth power automorphism"
The map $`\sigma_p \colon \mathbb{F}_{p^n} \to \mathbb{F}_{p^n}` defined by $$`\sigma_p(x) = x^p` is an automorphism, and moreover fixes $`\mathbb{F}_p`.
:::

This is called the Frobenius automorphism, and will re-appear later on in the chapter on the Frobenius element.

::::PROOF
It's a homomorphism since it fixes $`1`, respects multiplication, and respects addition.

:::QUESTION
Why does it respect addition?
:::

Next, we claim that it is injective.
To see this, note that $$`x^p = y^p \iff x^p - y^p = 0 \iff (x-y)^p = 0 \iff x=y.`
Here we have again used the Freshman's Dream.
Since $`\mathbb{F}_{p^n}` is finite, this injective map is automatically bijective.
The fact that it fixes $`\mathbb{F}_p` is Fermat's little theorem.
::::

Now we're done:

:::THEOREM "Galois group of the extension 𝔽ₚⁿ/𝔽ₚ"
We have $`\operatorname{Gal}(\mathbb{F}_{p^n}/\mathbb{F}_p) \cong \mathbb{Z}/n\mathbb{Z}` with generator $`\sigma_p`.
:::

:::PROOF
Since $`[\mathbb{F}_{p^n}:\mathbb{F}_p] = n`, the Galois group $`G` has order $`n`.
So we just need to show $`\sigma_p \in G` has order $`n`.

Note that $`\sigma_p` applied $`k` times gives $`x \mapsto x^{p^k}`.
Hence, $`\sigma_p` applied $`n` times is the identity, as all elements of $`\mathbb{F}_{p^n}` satisfy $`x^{p^n}=x`.
But if $`k < n`, then $`\sigma_p` applied $`k` times cannot be the identity or $`x^{p^k}-x` would have too many roots.
:::

We can see an example of this again with the finite field of order $`9`.

::::EXAMPLE "Galois group of finite field of order 9"
Let $`\mathbb{F}_9` be the finite field of order $`9`, and represent it concretely by $`\mathbb{F}_9 = \mathbb{Z}[i]/(3)`.
Let $`\sigma_3 \colon \mathbb{F}_9 \to \mathbb{F}_9` be $`x \mapsto x^3`.
We can witness the fate of all nine elements:

:::figure "figures/algebraic-nt/ff9-frobenius.svg"
:::

(As claimed, $`0`, $`1`, $`2` are the fixed points, so I haven't drawn arrows for them.)
As predicted, the Galois group has order two: $$`\operatorname{Gal}(\mathbb{F}_9/\mathbb{F}_3) = \left\{ \operatorname{id}, \sigma_3 \right\} \cong \mathbb{Z}/2\mathbb{Z}.`
::::

This concludes the proof of all results stated at the beginning of this chapter.

# Extra: The multiplicative group of a finite field

In this section we prove a result which is interesting by its own right, even though it is not used in the following chapters.

Consider the field $`F` of order $`p = 17`.
We may want to ask the following questions about $`F`:

- How many nonzero elements in $`F` is a quadratic residue (can be written as a square of another element in $`F`)?
- Is there any element $`x` in $`p` such that $`x^2 = -1`?

With the following proposition, the questions above become easy.

:::PROPOSITION
Let $`F` be a finite field, then the multiplicative group $`F^\times` is a cyclic group.
:::

Essentially, it says that the multiplicative group $`F^\times` is as nice as possible — the cyclic group is the simplest Abelian group!

If we look back at the examples above, we can see how this knowledge can help us.

::::EXAMPLE "The multiplicative group of 𝔽₁₇"
The group $`F^\times` is cyclic of order $`16`, so there is some element $`g \in F^\times` such that all of the elements in $`F` are $$`0, g^0 = 1, g^1, g^2, \dots, g^{15}.`
Using this knowledge, if we square the nonzero elements, we can easily see that the result are the following (note that $`g^{16} = g^0 = 1`): $$`g^0, g^2, g^4, \dots, g^{14}, g^0, g^2, \dots, g^{14}.`
As such, exactly half of the elements — 8 elements — in $`F^\times` are quadratic residues!

Checking whether there is an element $`x` such that $`x^2 = -1` isn't much harder.
First, where may $`-1` appear in the sequence $`\{g^0, g^1, \dots, g^{15} \}`?
If you find an explicit value of $`g` (you can pick $`g = 3` for instance), you will see that $`g^8 = -1`.
But, even without an explicit calculation, you can still see that, because:

:::QUESTION
Note that the equation $`x^2 = 1` has only $`2` roots, $`1` and $`-1`.
Using group operations in the group $`F^\times`, what does the equation say?
:::

We have $`g^8 = -1`, so $`(g^4)^2 = (g^{12})^2 = -1`, so we're done.
::::

So, why is the proposition true?
Consider a finite field $`F` of order a prime power $`q`.

First, using an idea similar to the above, we have:

:::QUESTION
Show that, for any positive $`d < |F^\times| = q-1`, then there are at most $`d` elements $`x` such that $`x^d = 1`.
:::

The rest is easily handled using group theory.
Recall, because $`F^\times` is a finite Abelian group, it is in particular finitely generated, and by the fundamental theorem of finitely generated abelian groups can be written in the form $$`F^\times \cong \mathbb{Z}^{\oplus r} \oplus \mathbb{Z}/q_1\mathbb{Z} \oplus \mathbb{Z}/q_2\mathbb{Z} \oplus \dots \oplus \mathbb{Z}/q_m\mathbb{Z}.`
Of course, $`r = 0` here.

Now, assume $`F^\times` is not cyclic, so the lowest common denominator of all the $`q_i` values are less than $`|F^\times|`.
Then, for all $`x \in F^\times`, $`x^{\operatorname{lcm}(q_1, \dots, q_m)} = 1`, which gives a contradiction.

:::REMARK
If you look up an elementary proof of why there are exactly $`\frac{p-1}{2}` quadratic residues modulo $`p`, most of the time, you will get some argument using "$`x^d-1` has at most $`d` roots" similar to the proof above, but by not going all the way and show the structure of the multiplicative group, it hides the spirit of what is really going on.

The proposition above takes a step further — now, without any calculation, you know for instance the finite field $`\mathbb{F}_{17^2}` has exactly $`\frac{17^2-1}{2} = 144` nonzero quadratic residues.
:::

# Problems

:::PROBLEM "HMMT 2017" (chili := 1)
What is the period of the Fibonacci sequence modulo $`127`?
(Hint: the Fibonacci sequence is given by $`F_n = \frac{\alpha^n - \beta^n}{\alpha - \beta}` where $`\alpha = \frac{1 + \sqrt5}{2}` and $`\beta = \frac{1 - \sqrt5}{2}` are the two roots of $`P(X) \coloneqq X^2-X-1`.
Show the polynomial $`P(X)` is irreducible modulo $`127`; then work in the splitting field of $`P`, namely $`\mathbb{F}_{p^2}`.
Show that $`F_p=-1`, $`F_{p+1}=0`, $`F_{2p+1}=1`, $`F_{2p+2}=0`.
(Look at the action of $`\operatorname{Gal}(\mathbb{F}_{p^2}/\mathbb{F}_p)` on the roots of $`P`.))
:::

# Formalization

:::LEANCOMPANION
:::

```lean -show
open Module Polynomial
```

## Example of a finite field

The base field $`\mathbb{F}_p` is `ZMod p`, whose field structure fires as soon as a `[Fact p.Prime]` hypothesis is around — the same convention we saw for the $`p`-adics.
"Finite field" needs no bundled type: it is just a `Field F` together with `Finite F` (or `Fintype F` when we want to actually count).

The base field really is a field with $`p` elements.
Confirm that `ZMod p` has cardinality $`p`.

```lean
example (p : ℕ) [Fact p.Prime] : Fintype.card (ZMod p) = p := by
  sorry
```

:::solution
```lean
example (p : ℕ) [Fact p.Prime] : Fintype.card (ZMod p) = p :=
  ZMod.card p
```
:::

## Finite fields have prime power order

This is `CharP.char_is_prime`, which needs only that $`F` is a nontrivial ring without zero divisors — the proof above never used inverses.

The lemma is `FiniteField.card'`:

```lean
recall FiniteField.card' (K : Type*) [Field K] [Fintype K] :
    ∃ (p : ℕ), CharP K p ∧ ∃ (n : ℕ+),
      Nat.Prime p ∧ Fintype.card K = p ^ (n : ℕ)
```

(The embedded copy of $`\mathbb{F}_p` is the `Algebra (ZMod p) F` instance `ZMod.algebra`, available whenever `CharP F p` holds.)

The freshman's dream is `add_pow_char`, and it holds in any commutative semiring of characteristic $`p`, not just fields.
The exercise was to convince yourself this proof really goes through; prove it from `add_pow_char`.

```lean
example (F : Type*) [CommRing F] (p : ℕ) [Fact p.Prime] [CharP F p]
    (a b : F) : (a + b) ^ p = a ^ p + b ^ p := by
  sorry
```

:::solution
```lean
example (F : Type*) [CommRing F] (p : ℕ) [Fact p.Prime] [CharP F p]
    (a b : F) : (a + b) ^ p = a ^ p + b ^ p := by
  rw [add_pow_char]
```
:::

## All finite fields are isomorphic

This is `FiniteField.pow_card` (with `FiniteField.pow_card_sub_one_eq_one` as the intermediate step, and `ZMod.pow_card` as the special case that number theorists call Fermat's little theorem):

```lean
recall FiniteField.pow_card {K : Type*} [GroupWithZero K] [Fintype K]
    (a : K) : a ^ Fintype.card K = a
```

Mathlib's $`\mathbb{F}_{p^n}` is `GaloisField p n`, and its definition _is_ the classification theorem: it is literally defined as the splitting field of $`x^{p^n} - x` over `ZMod p`.
The "only one up to isomorphism" half is `GaloisField.algEquivGaloisField`:

```lean
recall GaloisField.algEquivGaloisField (p : ℕ) [Fact p.Prime] (n : ℕ)
    {K : Type*} [Field K] [Algebra (ZMod p) K]
    (h : Nat.card K = p ^ n) :
    K ≃ₐ[ZMod p] GaloisField p n
```

The special case number theorists call Fermat's little theorem is `ZMod.pow_card`.
Prove that every $`x : \mathbb{F}_p` satisfies $`x^p = x`.

```lean
example (p : ℕ) [Fact p.Prime] (x : ZMod p) : x ^ p = x := by
  sorry
```

:::solution
```lean
example (p : ℕ) [Fact p.Prime] (x : ZMod p) : x ^ p = x :=
  ZMod.pow_card x
```
:::

## The Galois theory of finite fields

As a ring homomorphism the Frobenius is `frobenius F p` (defined on any commutative semiring of characteristic $`p` — there it need not be surjective!); upgraded to an element of the Galois group of an extension of finite fields it is `FiniteField.frobeniusAlgEquivOfAlgebraic`, whose underlying function is `(· ^ q)` with $`q` the cardinality of the base field.

The order computation in this proof is `FiniteField.orderOf_frobeniusAlgHom`: the Frobenius has order exactly $`[\mathbb{F}_{p^n} : \mathbb{F}_p]` in the Galois group, which by the counting theorem has that same order — so the group is cyclic with the Frobenius as a generator, exactly as claimed.

The question "Why does it respect addition?" is answered by the Frobenius being a ring homomorphism.
Show directly that $`\sigma_p` sends $`a + b` to $`\sigma_p(a) + \sigma_p(b)`.

```lean
example (F : Type*) [CommRing F] (p : ℕ) [Fact p.Prime] [CharP F p]
    (a b : F) :
    frobenius F p (a + b) = frobenius F p a + frobenius F p b := by
  sorry
```

:::solution
```lean
example (F : Type*) [CommRing F] (p : ℕ) [Fact p.Prime] [CharP F p]
    (a b : F) :
    frobenius F p (a + b) = frobenius F p a + frobenius F p b :=
  map_add (frobenius F p) a b
```
:::

## Extra: The multiplicative group of a finite field

The proposition is an instance: `IsCyclic Fˣ` is inferred for any finite field (indeed for the units of any finite division ring or any finite subgroup of the units of a domain, via `subgroup_units_cyclic`), so a generator is always available as `IsCyclic.exists_generator`.

The counting question asked how many $`x` solve $`x^d = 1`.
Prove the sharper statement `FiniteField.forall_pow_eq_one_iff`: every unit satisfies $`x^i = 1` exactly when $`\left\lvert F \right\rvert - 1` divides $`i`.

```lean
example (K : Type*) [Field K] [Fintype K] (i : ℕ) :
    (∀ x : Kˣ, x ^ i = 1) ↔ Fintype.card K - 1 ∣ i := by
  sorry
```

:::solution
```lean
example (K : Type*) [Field K] [Fintype K] (i : ℕ) :
    (∀ x : Kˣ, x ^ i = 1) ↔ Fintype.card K - 1 ∣ i :=
  FiniteField.forall_pow_eq_one_iff (K := K) i
```
:::
