import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Napkin.Meta.Recall
import Mathlib.Probability.Notation
import Mathlib.Probability.Martingale.Basic
import Mathlib.Probability.Martingale.Convergence
import Mathlib.Probability.Martingale.OptionalStopping
import Mathlib.Probability.ConditionalExpectation

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Stopped martingales" =>

%%%
file := "Stopped-martingales"
%%%

```lean -show
open MeasureTheory ProbabilityTheory
open scoped ProbabilityTheory
```

# How to make money almost surely

We now take our newfound knowledge of measure theory to a casino.

Here's the most classical example that shows up: a casino lets us play a game where we can bet any amount of on a fair coin flip, but with bad odds: we win $`\$n` if the coin is heads, but lose $`\$2n` if the coin is tails, for a value of $`n` of our choice.
This seems like a game that no one in their right mind would want to play.

Well, if we have unbounded time and money, we actually can almost surely make a profit.

:::EXAMPLE "Being even greedier than 18th century France"
In the game above, we start by betting $`\$1`.

- If we win, we leave having made $`\$1`.
- If we lose, we then bet $`\$10` instead, and
  - If we win, then we leave having made $`\$10-\$2=\$8`, and
  - If we lose then we bet $`\$100` instead, and
    - If we win, we leave having made $`\$1000-\$20-\$2=\$978`, and
    - If we lose then we bet $`\$1000` instead, and so on…

Since the coin will almost surely show heads eventually, we make money whenever that happens.
In fact, the expected amount of time until a coin shows heads is only $`2` flips!
What could go wrong?
:::

This chapter will show that under sane conditions such as "finite time" or "finite money", one cannot actually make money in this way — the _optional stopping theorem_.
This will give us an excuse to define conditional probabilities, and then talk about martingales (which generalize the fair casino).

Once we realize that trying to extract money from Las Vegas is a lost cause, we will stop gambling and then return to solving math problems, by showing some tricky surprises, where problems that look like they have nothing to do with gambling can be solved by considering a suitable martingale.

In everything that follows, $`\Omega = (\Omega, \mathcal{A}, \mu)` is a probability space.

# Sub-σ-algebras and filtrations

:::PROTOTYPE
$`\sigma`-algebra generated by a random variable, and coin flip filtration.
:::

We considered our $`\Omega` as a space of worlds, equipped with a $`\sigma`-algebra $`\mathcal{A}` that lets us integrate over $`\Omega`.
However, it is a sad fact of life that at any given time, you only know partial information about the world.
For example, at the time of writing, we know that the world did not end in 2012 (see the [2012 phenomenon](https://en.wikipedia.org/wiki/2012_phenomenon)), but the fate of humanity in future years remains at slightly uncertain.

Let's write this measure-theoretically: we could consider
$$`\Omega = A \sqcup B`
$$`A = \left\{ \omega \text{ for which world ends in } 2012 \right\}`
$$`B = \left\{ \omega \text{ for which world does not end in } 2012 \right\}.`
We will assume that $`A` and $`B` are measurable sets, that is, $`A,B \in \mathcal{A}`.
That means we could have good fun arguing about what the values of $`\mu(A)` and $`\mu(B)` should be ("a priori probability that the world ends in $`2012`"), but let's move on to a different silly example.

We will now introduce a new notion that we will need when we define conditional probabilities later.

:::DEFINITION
Let $`\Omega = (\Omega, \mathcal{A}, \mu)` be a probability space.
A *sub-$`\sigma`-algebra* $`\mathcal{F}` on $`\Omega` is exactly what it sounds like: a $`\sigma`-algebra $`\mathcal{F}` on the type $`\Omega` such that each $`A \in \mathcal{F}` is measurable (i.e., $`\mathcal{F} \subseteq \mathcal{A}`).
:::

The motivation is that $`\mathcal{F}` is the $`\sigma`-algebra of sets which let us ask questions about some piece of information.
For example, in the 2012 example we gave above, we might take $`\mathcal{F} = \{\varnothing, A, B, \Omega\}`, which are the sets we care about if we are thinking only about 2012.

Here are some more serious examples.

:::EXAMPLE "Examples of sub-σ-algebras"
1. Let $`X \colon \Omega \to \{0,1,2\}` be a random variable taking on one of three values.
   If we're interested in $`X` then we could define
   $$`A = \{\omega \mid X(\omega) = 1\}`
   $$`B = \{\omega \mid X(\omega) = 2\}`
   $$`C = \{\omega \mid X(\omega) = 3\}`
   then we could write $$`\mathcal{F} = \left\{ \varnothing, \; A, \; B, \; C, \; A \cup B, \; B \cup C, \; C \cup A, \; \Omega \right\}.`
   This is a sub-$`\sigma`-algebra on $`\mathcal{F}` that lets us ask questions about $`X` like "what is the probability $`X \neq 3`", say.

2. Now suppose $`Y \colon \Omega \to [0,1]` is another random variable.
   If we are interested in $`Y`, the $`\mathcal{F}` that captures our curiosity is $$`\mathcal{F} = \left\{ Y^{\mathrm{pre}}(B) \mid B \subseteq [0,1] \text{ is measurable } \right\}.`
:::

You might notice a trend here which we formalize now:

:::DEFINITION
Let $`X \colon \Omega \to \mathbb{R}` be a random variable.
The *sub-$`\sigma`-algebra generated by $`X`* is defined by $$`\sigma(X) \coloneqq \left\{ X^{\mathrm{pre}}(B) \mid B \subseteq \mathbb{R} \text{ is measurable } \right\}.`
If $`X_1`, … is a sequence (finite or infinite) of random variables, the sub-$`\sigma`-algebra generated by them is the smallest $`\sigma`-algebra which contains $`\sigma(X_i)` for each $`i`.
:::

Finally, we can put a lot of these together — since we're talking about time, we learn more as we grow older, and this can be formalized.

:::DEFINITION
A *filtration* on $`\Omega = (\Omega, \mathcal{A}, \mu)` is a nested sequence{margin}[For convenience, we will restrict ourselves to $`\mathbb{Z}_{\ge0}`-indexed filtrations, though really any index set is okay.] $$`\mathcal{F}_0 \subseteq \mathcal{F}_1 \subseteq \mathcal{F}_2 \subseteq \dots` of sub-$`\sigma`-algebras on $`\Omega`.
:::

:::EXAMPLE "Filtration"
Suppose you're bored in an infinitely long class and start flipping a fair coin to pass the time.
(Accordingly, we could let $`\Omega = \{H,T\}^\infty` consist of infinite sequences of heads $`H` and tails $`T`.)
We could let $`\mathcal{F}_n` denote the sub-$`\sigma`-algebra generated by the values of the first $`n` coin flips.
So:

- $`\mathcal{F}_0 = \{\varnothing, \Omega\}`,
- $`\mathcal{F}_1 = \{\varnothing, \text{first flip } H, \text{first flip } T, \Omega\}`,
- $`\mathcal{F}_2 = \{\varnothing, \text{first flips } HH, \text{second flip } T, \Omega, \text{first flip and second flip differ}, \dots\}`.
- and so on, with $`\mathcal{F}_n` being the measurable sets "determined" only by the first $`n` coin flips.
:::

:::EXERCISE
In the previous example, compute the cardinality $`|\mathcal{F}_n|` for each integer $`n`.
:::

More importantly,

:::MORAL
$`X` is $`\mathcal{F}`-measurable if $`X` is determined only by the information given in $`\mathcal{F}`.
:::

:::EXAMPLE
In the example above, let $`X_3` be the value of the third coin flip.
Then:

- $`X_3` is not $`\mathcal{F}_2`-measurable.
  (That is, we don't know $`X_3` from the knowledge of the first $`2` coin flips.)
- But it is $`\mathcal{F}_3`-measurable.
:::

:::EXERCISE
Check this!
(Recall that a function is measurable if it lifts open sets to measurable sets.
So you need to show e.g. $`X_3^{\mathrm{pre}}(\{H\}) \notin \mathcal{F}_2`.)
:::

So, not only can we formalize partial information about the world, we can also formalize what it means for something to only depend on that partial information.

# Conditional expectation

:::PROTOTYPE
$`\mathbb{E}(X \mid X+Y)` for $`X` and $`Y` distributed over $`[0,1]`.
:::

We'll need the definition of conditional probability to define a martingale, but this turns out to be surprisingly tricky.
Let's consider the following simple example to see why.

::::EXAMPLE "Why high-school methods aren't enough here"
Suppose we have two independent random variables $`X`, $`Y` distributed uniformly over $`[0,1]` (so we may as well take $`\Omega = [0,1]^2`).
We might try to ask the question:

:::quote
_"what is the expected value of $`X` given that $`X+Y = 0.6`"?_
:::

Intuitively, we know the answer has to be $`0.3`.
However, if we try to write down a definition, we quickly run into trouble.
Ideally we want to say something like $$`\mathbb{E}[X \text{ given } X+Y=0.6] = \frac{\int_{S} X}{\int_{S} 1} \text{ where } S = \left\{ \omega : \Omega \mid X(\omega)+Y(\omega)=0.6 \right\}.`
The problem is that $`S` is a set of measure zero, so we quickly run into $`\frac 00`, meaning a definition of this shape will not work out.
::::

The way that this is typically handled in measure theory is to use the notion of sub-$`\sigma`-algebra that we defined.

But first, we should explain what $`\mathbb{E}(X \mid X+Y)` means first — why are we conditioning on another random variable instead of an event?

To motivate conditioning on a random variable, consider the following situation.
Suppose that the weather tomorrow depends on the weather today and the random fluctuations.
So we may have statements such as:
$$`\Pr(\text{it rains tomorrow}\mid \text{it rains today}) = 0.6,`
$$`\Pr(\text{it rains tomorrow}\mid \text{it doesn't rain today}) = 0.3.`
This is the standard conditional probability: $`\Pr(A \mid B) = \frac{\Pr(A \wedge B)}{\Pr(B)}`.

Note that "the weather today" is itself a random variable.

Let $`Z` be the weather forecast tonight's prediction of the probability, suppose it works as above.
Then $`Z` is a random real variable, defined by:
$$`Z \colon \Omega \to \mathbb{R}`
$$`Z(\omega) = \Pr(\text{it rains tomorrow} \mid \text{weather today} = \text{weather today}(\omega))`

It would only be reasonable to write $$`Z = \Pr(\text{it rains tomorrow}\mid \text{weather today}).`
We're conditioning on a random variable, and $`\Pr(\cdots \mid \cdots)` is itself a random variable instead of a single value in $`\mathbb{R}`, but that's perfectly okay.

Similarly, if $`\Omega` is finite and every subset of it is measurable, for random real variables $`X` and $`Y` it would be sensible for us to define random real variable $`Z = \mathbb{E}(X \mid Y)` by
$$`Z \colon \Omega \to \mathbb{R}`
$$`Z(\omega) = \mathbb{E}[X \mid Y = Y(\omega)].`

:::EXAMPLE
Let $`X` and $`Y` be the result of rolling two dices.
Then:

- $`\mathbb{E}[X \mid X+Y = 3] = 1.5`, as you can easily calculate.
- $`\mathbb{E}(X \mid X+Y)` is a random variable, which would takes the value $`1.5` in any world whether $`X+Y = 3`.
- More generally, we have in fact $$`\mathbb{E}(X \mid X+Y) = \frac{X+Y}{2}.`

Notice how the random variable $`\mathbb{E}(X \mid X+Y)` depends only on the value of $`X+Y` — by definition.
:::

Of course, as we explained earlier, this naive attempts will give us division-by-zero everywhere for the continuous case — so, enters the sub-$`\sigma`-algebra.

:::PROPOSITION "Conditional expectation definition"
Let $`X \colon \Omega \to \mathbb{R}` be an _absolutely integrable_ random variable (meaning $`\mathbb{E}[|X|] < \infty`) over a probability space $`\Omega`, and let $`\mathcal{F}` be a sub-$`\sigma`-algebra on it.

Then there exists a function $`\eta \colon \Omega \to \mathbb{R}` satisfying the following two properties:

- $`\eta` is $`\mathcal{F}`-measurable (that is, measurable as a function $`(\Omega, \mathcal{F}, \mu) \to \mathbb{R}`); and
- for any set $`A \in \mathcal{F}` we have $`\mathbb{E}[\eta \cdot \mathbf{1}_A] = \mathbb{E}[X \cdot \mathbf{1}_A]`.

Moreover, this random variable is unique up to almost sureness.
:::

:::PROOF
Omitted, but relevant buzzword used is "Radon-Nikodym derivative".
:::

:::DEFINITION
Let $`\eta` be as in the previous proposition.

- We denote $`\eta` by $`\mathbb{E}(X \mid \mathcal{F})` and call it the *conditional expectation* of $`X` with respect to $`\mathcal{F}`.
- If $`Y` is a random variable then $`\mathbb{E}(X \mid Y)` denotes $`\mathbb{E}(X \mid \sigma(Y))`, i.e. the conditional expectation of $`X` with respect to the $`\sigma`-algebra generated by $`Y`.
:::

:::EXAMPLE
As we can expect, $`\eta = \frac{X+Y}{2}` satisfies the condition of $`\mathbb{E}(X \mid X+Y)` above.

The way to motivate doing all this is the following.
We want to be able to say something like: $$`\mathbb{E}[X \mid X+Y=0.6] = \lim_{\varepsilon \to 0} \mathbb{E}[X \mid 0.6-\varepsilon < X+Y < 0.6+\varepsilon]`
Unfortunately, this setup does not work in general where $`\mathcal{F}` might not be generated by just one random real variable.
Let's see how the definition above helps us.

- Let $`A = \{\omega : \Omega \mid 0.6-\varepsilon < X(\omega)+Y(\omega) < 0.6+\varepsilon\}`, this set certainly belongs to the sub-$`\sigma`-algebra generated by $`X+Y` (because it is $`(X+Y)^{\mathrm{pre}}((0.6-\varepsilon, 0.6+\varepsilon))`).
- Recall that $`\eta` is $`\mathcal{F}`-measurable means $`\eta` only depends on the information in $`\mathcal{F} = \sigma(X+Y)`, that is, on $`X+Y`.
  This makes sense.
- Look at the right hand side: $$`\mathbb{E}[X \mid 0.6-\varepsilon < X+Y < 0.6+\varepsilon] = \mathbb{E}[X \cdot \mathbf{1}_A].`

  The law of total expectation says that $`\mathbb{E}[\mathbb{E}(X \mid Y)] = \mathbb{E}[X]`.
  So, intuitively, the second property above simply requires this law to hold over all set $`A \in \mathcal{F}`.

  In our case, we have the following: $$`\mathbb{E}[\eta \mid 0.6-\varepsilon < X+Y < 0.6+\varepsilon] = \mathbb{E}[X \mid 0.6-\varepsilon < X+Y < 0.6+\varepsilon].`
:::

More fine print:

:::REMARK "This notation is terrible"
The notation $`\mathbb{E}(X \mid \mathcal{F})` is admittedly confusing, since it is actually an entire function $`\Omega \to \mathbb{R}`, rather than just a real number like $`\mathbb{E}[X]` — though, as you can see, it has its merits.
For this reason I try to be careful to remember to use parentheses rather than square brackets for conditional expectations; not everyone does this.
:::

:::ABUSE
In addition, when we write $`Y = \mathbb{E}(X \mid \mathcal{F})`, there is some abuse of notation happening here since $`\mathbb{E}(X \mid \mathcal{F})` is defined only up to some reasonable uniqueness (i.e. up to measure zero changes).
So this really means that "$`Y` satisfies the hypothesis of the conditional expectation proposition", but this is so pedantic that no one bothers.

For example, in the example above, if we change $`\eta` to be
$$`\eta(\omega) = \begin{cases} 0 & \text{if } X(\omega)+Y(\omega)=0.6 \\ \frac{X(\omega)+Y(\omega)}{2} & \text{otherwise} \end{cases}`
then $`\mathbb{E}[\eta \cdot \mathbf{1}_A] = \mathbb{E}[X \cdot \mathbf{1}_A]` still holds for every set $`A`, but now it seems to be saying $`\mathbb{E}[X \mid X+Y=0.6] = 0`?

Nevertheless, we must agree that we must sacrifice a measure zero set, since otherwise if we have
$$`T(\omega) = \begin{cases} 1&\text{if } Y(\omega) > 0.5 \text{ or } (Y(\omega)=0.5 \text{ and } X(\omega) \in \mathbb{Q}) \\ 0&\text{otherwise} \end{cases}`
then it is certainly measurable (i.e. a random variable), $`\mathbb{E}[T \mid Y = 0.4] = 0` and $`\mathbb{E}[T \mid Y = 0.6] = 1`, but what is $`\mathbb{E}[T \mid Y = 0.5]`?
(You may argue it should be $`0`, but what if $`\mathbb{Q}` is changed to something more non-measurable?
Besides, why should the conditional expectation change when we only modify $`T` on a probability-zero set anyway?)
:::

Before moving on, let us collect the properties of conditional expectation that get used constantly; each follows from the defining property plus the uniqueness.

:::PROPOSITION "Properties of conditional expectation"
Let $`X`, $`Y` be absolutely integrable random variables on $`\Omega` and $`\mathcal{F}` a sub-$`\sigma`-algebra.
All equalities below are almost-sure.

- *Linearity*: $`\mathbb{E}(aX + Y \mid \mathcal{F}) = a\,\mathbb{E}(X \mid \mathcal{F}) + \mathbb{E}(Y \mid \mathcal{F})` for $`a : \mathbb{R}`.
- *Positivity*: if $`X \ge 0` then $`\mathbb{E}(X \mid \mathcal{F}) \ge 0`.
- *Taking out what is known*: if $`X` is already $`\mathcal{F}`-measurable, then $`\mathbb{E}(X \mid \mathcal{F}) = X`; more generally $`\mathbb{E}(XY \mid \mathcal{F}) = X \cdot \mathbb{E}(Y \mid \mathcal{F})` for bounded $`\mathcal{F}`-measurable $`X`.
- *Independence*: if $`\sigma(X)` is independent from $`\mathcal{F}`, then $`\mathbb{E}(X \mid \mathcal{F})` is the constant $`\mathbb{E}[X]`.
- *Tower property*: if $`\mathcal{F} \subseteq \mathcal{G}` then $$`\mathbb{E}\left( \mathbb{E}(X \mid \mathcal{G}) \mid \mathcal{F} \right) = \mathbb{E}(X \mid \mathcal{F}).`
  Taking $`\mathcal{F} = \{\varnothing, \Omega\}` gives the *law of total expectation* $`\mathbb{E}[\mathbb{E}(X \mid \mathcal{G})] = \mathbb{E}[X]`.
:::

:::EXERCISE
Prove as many of these as you have patience for, by checking the two defining properties against the uniqueness statement.
(The independence property is the one that requires an actual computation.)
:::

# Supermartingales

:::PROTOTYPE
Visiting a casino is a supermartingale, assuming house odds.
:::

:::DEFINITION
Let $`X_0`, $`X_1`, … be a sequence of random variables on a probability space $`\Omega`, and let $`\mathcal{F}_0 \subseteq \mathcal{F}_1 \subseteq \cdots` be a filtration.

Then $`(X_n)_{n \ge 0}` is a *supermartingale* with respect to $`(\mathcal{F}_n)_{n \ge 0}` if the following conditions hold:

- $`X_n` is absolutely integrable for every $`n`;
- $`X_n` is measurable with respect to $`\mathcal{F}_n`; and
- for each $`n = 1, 2, \dots` the inequality $$`\mathbb{E}(X_n \mid \mathcal{F}_{n-1}) \le X_{n-1}` holds for all $`\omega \in \Omega`.

In a *submartingale* the inequality $`\le` is replaced with $`\ge`, and in a *martingale* it is replaced by $`=`.
:::

:::aside "Where did the name come from?"
Not from mathematics: _martingale_ was the name of the double-your-bet-until-you-win gambling strategy — essentially the scheme from the start of this chapter — reportedly from the Provençal expression _jouga a la martengalo_, "to play in an absurd way", after the village of Martigue.
(The same word also names a piece of horse harness; the connection between the two is murky.)
The betting term was borrowed into probability by Ville, and popularized by Doob, whose name is now on half the theorems of the subject.
:::

:::ABUSE "No one uses that filtration thing anyways"
We will always take $`\mathcal{F}_n` to be the $`\sigma`-algebra generated by the previous variables $`X_0`, $`X_1`, …, $`X_{n-1}`, and do so without further comment.
Nonetheless, all the results that follow hold in the more general setting of a supermartingale with respect to some filtration.
:::

We will prove all our theorems for supermartingales; the analogous versions for submartingales can be obtained by replacing $`\le` with $`\ge` everywhere (since $`X_n` is a martingale iff $`-X_n` is a supermartingale) and for martingales by replacing $`\le` with $`=` everywhere (since $`X_n` is a martingale iff it is both a supermartingale and a submartingale).

Let's give examples.

:::EXAMPLE "Supermartingales"
1. *Random walks*: an ant starts at the position $`0` on the number line.
   Every minute, it flips a fair coin and either walks one step left or one step right.
   If $`X_t` is the position at the $`t`th time, then $`X_t` is a martingale, because $$`\mathbb{E}(X_t \mid X_0, \dots, X_{t-1}) = \frac{(X_{t-1}+1) + (X_{t-1}-1)}{2} = X_{t-1}.`
2. *Casino game*: Consider a gambler using the strategy described at the beginning of the chapter.
   This is a martingale, since every bet the gambler makes has expected value $`0`.
3. *Multiplying independent variables*: Let $`X_1`, $`X_2`, …, be independent (not necessarily identically distributed) integrable random variables with mean $`1`.
   Then the sequence $`Y_1`, $`Y_2`, … defined by $$`Y_n \coloneqq X_1 X_2 \cdots X_n` is a martingale; as $`\mathbb{E}(Y_n \mid Y_1, \dots, Y_{n-1}) = \mathbb{E}[Y_n] \cdot Y_{n-1} = Y_{n-1}`.
4. *Iterated blackjack*: Suppose one shows up to a casino and plays infinitely many games of blackjack.
   If $`X_t` is their wealth at time $`t`, then $`X_t` is a supermartingale.
   This is because each game has negative expected value (house edge).
:::

:::EXAMPLE "Frivolous/inflamamtory example — real life is a supermartingale"
Let $`X_t` be your happiness on day $`t` of your life.
Life has its ups and downs, so it is not the case that $`X_t \le X_{t-1}` for every $`t`.
For example, you might win the lottery one day.

However, on any given day, many things can go wrong (e.g. zombie apocalypse), and by Murphy's Law this is more likely than things going well.
Also, as you get older, you have an increasing number of responsibilities and your health gradually begins to deteriorate.

Thus it seems that $$`\mathbb{E}(X_t \mid X_0, \dots, X_{t-1}) \le X_{t-1}` is a reasonable description of the future — _in expectation_, each successive day is slightly worse than the previous one.
(In particular, if we set $`X_t = -\infty` on death, then as long as you have a positive probability of dying, the displayed inequality is obviously true.)
:::

Before going on, we will state without proof one useful result: if a martingale is bounded, then it will almost certainly converge.

:::THEOREM "Doob's martingale convergence theorem"
Let $`X_0`, … be a supermartingale on a probability space $`\Omega` such that $$`\sup_{n \in \mathbb{Z}_{\ge 0}} \mathbb{E} \left[ \left\lvert X_n \right\rvert \right] < \infty.`
Then, there exists a random variable $`X_\infty \colon \Omega \to \mathbb{R}` such that $$`X_n \xrightarrow{\text{a.s.}} X_\infty.`
:::

# Optional stopping

:::PROTOTYPE
Las Vegas.
:::

In the first section we described how to make money almost surely.
The key advantage the gambler had was the ability to quit whenever he wanted (equivalently, an ability to control the size of the bets; betting \$0 forever is the same as quitting.)
Let's formalize a notion of stopping time.

The idea is we want to define a function $`\tau \colon \Omega \to \{0, 1, 2, \dots\} \cup \{\infty\}` such that

- $`\tau(\omega)` specifies the index after which we _stop_ the martingale.
  Note that the decisions to stop after time $`n` must be made with only the information available at that time — i.e., with respect to $`\mathcal{F}_n` of the filtration.
- $`X_{\tau \wedge n}` is the random value representing the value at time $`n` of the stopped martingale, where if $`n` is _after_ the stopping time, we just take it to be the our currently value after we leave.

  So for example in a world $`\omega` where we stopped at time $`3`, then $`X_{\tau \wedge 0}(\omega) = X_0(\omega)`, $`X_{\tau \wedge 1}(\omega) = X_1(\omega)`, $`X_{\tau \wedge 2}(\omega) = X_2(\omega)`, $`X_{\tau \wedge 3}(\omega) = X_3(\omega)`, but then $$`X_3(\omega) = X_{\tau \wedge 4}(\omega) = X_{\tau \wedge 5}(\omega) = X_{\tau \wedge 6}(\omega) = \dots` since we have stopped — the value stops changing.
- $`X_{\tau}` denotes the eventual value after we stop (or the limit $`X_\infty` if we never stop).

Here's the compiled machine code.

:::DEFINITION
Let $`\mathcal{F}_0 \subseteq \mathcal{F}_1 \subseteq \cdots` be a filtration on a probability space $`\Omega`.

- A *stopping time* is a function $$`\tau \colon \Omega \to \{0, 1, 2, \dots\} \cup \{\infty\}` with the property that for each integer $`n`, the set $$`\left\{ \omega : \Omega \mid \tau(\omega) = n \right\}` is $`\mathcal{F}_n`-measurable (i.e., is in $`\mathcal{F}_n`).
- For each $`n \ge 0` we define $`X_{\tau \wedge n} \colon \Omega \to \mathbb{R}` by $$`X_{\tau \wedge n}(\omega) = X_{\min \left\{ \tau(\omega), n \right\}}(\omega)`
- Finally, we let the eventual outcome be denoted by
  $$`X_\tau(\omega) = \begin{cases} X_{\tau(\omega)}(\omega) & \tau(\omega) \neq \infty \\ \lim_{n \to \infty} X_n(\omega) & \tau(\omega) = \infty \text{ and } \lim_{n \to \infty} X_n(\omega) \text{ exists } \\ \text{undefined} & \text{otherwise}. \end{cases}`
  We require that the "undefined" case occurs only for a set of measure zero (for example, if Doob's martingale convergence theorem applies).
  Otherwise we don't allow $`X_\tau` to be defined.
:::

:::PROPOSITION "Stopped supermartingales are still supermartingales"
Let $`X_0`, $`X_1`, … be a supermartingale.
Then the sequence $$`X_{\tau \wedge 0}, \; X_{\tau \wedge 1}, \; \dots` is itself a supermartingale.
:::

:::PROOF
We have almost everywhere the inequalities
$$`\mathbb{E}\left( X_{\tau \wedge n} \mid \mathcal{F}_{n-1} \right) = \mathbb{E} \left( X_{n-1} + \mathbf 1_{\tau(\omega) = n-1} (X_n - X_{n-1}) \mid \mathcal{F}_{n-1} \right) = \mathbb{E} \left( X_{n-1} \mid \mathcal{F}_{n-1} \right) + \mathbb{E} \left( \mathbf 1_{\tau(\omega) = n-1} \cdot (X_n - X_{n-1}) \mid \mathcal{F}_{n-1} \right) = X_{n-1} + \mathbf 1_{\tau(\omega) = n-1} \cdot \mathbb{E} \left( X_n - X_{n-1} \mid \mathcal{F}_{n-1} \right) \le X_{n-1}`
as functions from $`\Omega \to \mathbb{R}`.
:::

(Which properties of conditional expectation did each step use?
The middle equality is linearity, and pulling the indicator out is "taking out what is known" — the event $`\tau = n-1` is $`\mathcal{F}_{n-1}`-measurable precisely because $`\tau` is a stopping time.)

:::THEOREM "Doob's optional stopping theorem"
Let $`X_0`, $`X_1`, … be a supermartingale on a probability space $`\Omega`, with respect to a filtration $`\mathcal{F}_0 \subseteq \mathcal{F}_1 \subseteq \cdots`.
Let $`\tau` be a stopping time with respect to this filtration.
Suppose that _any_ of the following hypotheses are true, for some constant $`C`:

1. *Finite time*: $`\tau(\omega) \le C` for almost all $`\omega`.
2. *Finite money*: for each $`n \ge 1`, $`\left\lvert X_{\tau \wedge n}(\omega) \right\rvert \le C` for almost all $`\omega`.
3. *Finite bets*: we have $`\mathbb{E}[\tau] < \infty`, and for each $`n \ge 1`, the conditional expectation $$`\mathbb{E}\left( \left\lvert X_n-X_{n-1} \right\rvert \mid \mathcal{F}_n \right)` takes on values at most $`C` for almost all $`\omega \in \Omega` satisfying $`\tau(\omega) \ge n`.

Then $`X_\tau` is well-defined almost everywhere, and more importantly, $$`\mathbb{E}[X_\tau] \le \mathbb{E}[X_0].`
:::

The last equation can be cheekily expressed as "the only winning move is not to play".

:::PROOF
The previous proposition already did the heavy lifting: since the stopped process $`X_{\tau \wedge n}` is a supermartingale, taking expectations of $`\mathbb{E}(X_{\tau \wedge n} \mid \mathcal{F}_{n-1}) \le X_{\tau \wedge (n-1)}` and chaining gives $$`\mathbb{E}[X_{\tau \wedge n}] \le \mathbb{E}[X_{\tau \wedge 0}] = \mathbb{E}[X_0] \qquad \text{for every } n.`
So everything comes down to passing to the limit: we need $`X_\tau` to be defined almost everywhere and $$`\mathbb{E}[X_\tau] = \lim_{n \to \infty} \mathbb{E}[X_{\tau \wedge n}],` and this is where the three hypotheses come in.

1. If $`\tau \le C` almost surely, there is no limit to take: $`X_{\tau \wedge n} = X_\tau` on almost all of $`\Omega` once $`n \ge C`.
2. Suppose $`|X_{\tau \wedge n}| \le C` almost surely for every $`n`.
   Then in particular $`\sup_n \mathbb{E}[|X_{\tau \wedge n}|] \le C` is finite, so Doob's martingale convergence theorem applies to the stopped process: $`X_{\tau \wedge n}` converges almost surely, which is exactly the statement that $`X_\tau` is defined almost everywhere (on $`\tau < \infty` the sequence is eventually constant anyway; on $`\tau = \infty` the limit exists almost surely).
   Now $`X_{\tau \wedge n} \to X_\tau` almost surely with $`|X_{\tau \wedge n}| \le C` and constants are integrable on a probability space, so the dominated convergence theorem gives $`\mathbb{E}[X_{\tau \wedge n}] \to \mathbb{E}[X_\tau]`.
3. Suppose $`\mathbb{E}[\tau] < \infty` and the bets are bounded as stated.
   First, $`\tau < \infty` almost surely, so $`X_\tau` is defined almost everywhere.
   The plan is again dominated convergence, and the dominating function is the total distance traveled: $$`Y \coloneqq |X_0| + \sum_{k=1}^{\tau} \left\lvert X_k - X_{k-1} \right\rvert,` which dominates every $`|X_{\tau \wedge n}|` at once by the triangle inequality.
   Its expectation is finite by the finite-bets hypothesis: writing the sum with indicators and using the tower property,
   $$`\mathbb{E}\left[ \sum_{k \ge 1} \mathbf{1}_{\tau \ge k} |X_k - X_{k-1}| \right] = \sum_{k \ge 1} \mathbb{E}\left[ \mathbf{1}_{\tau \ge k} \cdot \mathbb{E}\left( |X_k - X_{k-1}| \mid \mathcal{F}_{k-1} \right) \right] \le C \sum_{k \ge 1} \Pr[\tau \ge k] = C \cdot \mathbb{E}[\tau] < \infty,`
   where the indicator could be moved inside the conditional expectation because $`\{\tau \ge k\} = \Omega \setminus \{\tau \le k-1\}` is $`\mathcal{F}_{k-1}`-measurable.
   So $`\mathbb{E}[Y] < \infty`, dominated convergence applies, and we conclude as before.
:::

:::EXERCISE
Conclude that going to Las Vegas with the strategy described in the first section is a really bad idea.
What goes wrong?
:::

While this is useful to make us stop gambling, it doesn't allow us to compute anything — we don't know anything about $`\mathbb{E}[X_\tau]` other than it's $`\leq \mathbb{E}[X_0]`.
However:

:::COROLLARY
With the same hypothesis as above:

- If $`X_0`, $`X_1`, … is a submartingale, then $`\mathbb{E}[X_\tau] \geq \mathbb{E}[X_0]`.
- If it is a martingale, then $`\mathbb{E}[X_\tau] = \mathbb{E}[X_0]`.
:::

:::PROOF
If $`X_0`, $`X_1`, … is a submartingale, then $`Y_0`, $`Y_1`, … defined by $`Y_i = -X_i` is a supermartingale, and the hypothesis is still satisfied.
Apply the theorem to $`Y_\tau` we get the result.

If $`X_0`, $`X_1`, … is a martingale, then it is both a supermartingale and a submartingale, the result follows immediately.
:::

This finally let us calculate something — if we can compute $`\mathbb{E}[X_0]` and write the result as $`\mathbb{E}[X_\tau]` for some martingale, then we can solve the problem!

# Fun applications of optional stopping

We now give three problems which showcase some of the power of the results we have developed so far.

## The ballot problem

Suppose Alice and Bob are racing in an election; Alice received $`a` votes total while Bob received $`b` votes total, and $`a > b`.
If the votes are chosen in random order, one could ask: what is the probability that Alice remains strictly ahead of Bob in the election?

:::figure "figures/probability/ballot-path.svg"
One possible count for $`a = 5` and $`b = 3`, where Alice stays strictly ahead.
:::

:::PROPOSITION "Ballot problem"
This occurs with probability $`\frac{a-b}{a+b}`.
:::

We should try to model this as a martingale.
A natural way to do it is the random walk, as in the supermartingale examples:
$$`X_0 = 0`
$$`X_i = X_{i-1} + \begin{cases} 1\text{ with probability }\frac{1}{2} \\ -1\text{ otherwise.} \end{cases}`
Here, each $`1` represents Alice getting a vote, and each $`-1` represents Bob getting a vote.

Then, we need to compute $$`\Pr[X_i > 0\text{ for all }1 \leq i \leq a+b \mid X_{a+b} = a-b].`

While this is natural, the fact that the probability is conditioned on $`X_{a+b}=a-b` makes us unable to apply the optional stopping theorem.

Instead, the following will work: We start with all the votes, and _remove_ them in random order.
$$`(A_0, B_0) = (a, b),`
$$`(A_i, B_i) = \begin{cases} (A_{i-1}-1, B_{i-1})\text{ with probability }\frac{A_{i-1}}{A_{i-1}+B_{i-1}} \\ (A_{i-1}, B_{i-1}-1)\text{ otherwise} \end{cases} \text{ for } 1 \leq i \leq a+b.`
Of course, here $`A_i` represents the number of votes Alice has left, and $`B_i` represents the number of votes Bob has left.

Now we just need to compute $$`\Pr[A_i>B_i\text{ for all }0 \leq i \leq a+b-1].`
There's no longer any conditional expectation!

Next, we need to construct a martingale.
We could try to define $`X_i = A_i-B_i` similar to above, but that will not be a martingale.

Here is the trick: we _modify_ $`X_i` to make it a martingale.
(More examples where a sequence of random variables is modified to create a martingale can be found in the "Examples of martingales" problem below.)

:::EXAMPLE
Suppose $`a=2` and $`b=1`.
Then:
$$`(A_0, B_0) = (2, 1),`
$$`(A_1, B_1) = \begin{cases} (1, 1)\text{ with probability }\frac{2}{3} \\ (2, 0)\text{ otherwise.} \end{cases}`
So $`\mathbb{E}[A_0-B_0]=1` while $`\mathbb{E}[A_1-B_1]=\frac{2}{3}\cdot 0+\frac{1}{3}\cdot 2=\frac{2}{3}`, if we define $`X_i` as above of course it wouldn't be a martingale.

However, it's not difficult to find ways to modify it to form a martingale.
For example:

- If we define $`X_1 = A_1-B_1+\frac{1}{3}`, then $`\mathbb{E}[X_1]=1`, so we're fine.
- Similarly, we can also define $`X_1 = \frac{3}{2}\cdot(A_1-B_1)`.
- Or $`X_1 = \frac{9}{4}\cdot (A_1-B_1)^2`.
- … et cetera…
:::

We need to make $`\mathbb{E}[X_i \mid X_0=x_0, X_1=x_1, \dots, X_{i-1}=x_{i-1}]=x_{i-1}` for _every_ $`i` and every $`(x_0, x_1, \dots, x_{i-1})`.
(You can try to find out yourself what modification will work yourself before continue reading.)

Turns out, the following will work: $$`X_i = \frac{A_i-B_i}{a+b-i}\text{ for }0 \leq i \leq a+b-1.`
We cannot extend it to $`i \geq a+b`, but it is fine.
(If you're worried, just define $`X_i = X_{a+b-1}` for $`i \geq a+b`.)

:::EXERCISE
Check that it works.
(The math is very similar to the problem about Pólya's urn below.)
:::

For the stopping time, there is only one natural way to define it: $`\tau` is $`a+b-1` if Alice remains ahead of Bob i.e. $`X_i>0` for every $`0 \leq i \leq a+b-1`, otherwise $`\tau` is the smallest $`i` such that $`X_i=0`.

Then, the optional stopping theorem states: $$`\mathbb{E}[X_\tau] = \mathbb{E}[X_0].`
$`\mathbb{E}[X_0]` is easy to calculate, it is $`\frac{A_0-B_0}{a+b}=\frac{a-b}{a+b}`.
What is $`\mathbb{E}[X_\tau]`?

- If Alice remains ahead of Bob, $`X_\tau = X_{a+b-1} = 1`.
- Otherwise, $`X_\tau = 0`.

Therefore $`\mathbb{E}[X_\tau]` is exactly the probability we need to calculate, so we're done.

:::REMARK "This is cheating a little"
Note that you can equivalently write $$`X_i = \frac{A_i-B_i}{A_i+B_i}.`
Which is exactly the form of the answer.

That is to say, if you already know the form of the answer, martingale theory can help you to check it.
But if you don't…
:::

## ABRACADABRA

A monkey sits at a typewriter with $`26` keys and hits one uniformly random key per second, forever.
How long, on average, until the monkey types the string

$$`\texttt{ABRACADABRA}?`

Since any particular string of $`11` letters appears at a given position with probability $`26^{-11}`, one expects the answer to be roughly $`26^{11}`.
The surprise is that the answer is not exactly $`26^{11}`, and that the correction depends on the string: $`\texttt{ABRACADABRA}` takes longer, on average, than a "typical" string of the same length!

:::PROPOSITION "ABRACADABRA"
The expected number of seconds is exactly $$`26^{11} + 26^4 + 26.`
:::

The proof sets up a casino so absurd it loops back around to being a proof technique.

:::PROOF
Just before each second $`n = 1, 2, \dots`, a new gambler walks into the casino with $`\$1` and bets it on the event "the $`n`th keystroke is $`\texttt{A}`", at fair odds ($`\times 26` payout).
If they win, they bet their whole balance of $`\$26` on "the $`(n+1)`st keystroke is $`\texttt{B}`", then their $`\$26^2` on $`\texttt{R}`, and so on through the string $`\texttt{ABRACADABRA}`; if they ever lose a bet they walk out with nothing, and if they survive the whole string they walk out with $`\$26^{11}`.

Every individual bet in this casino is fair, so the casino's net profit $`X_n` after $`n` seconds is a martingale (with $`X_0 = 0`), regardless of the gamblers' behavior.
Let $`\tau` be the first time the string $`\texttt{ABRACADABRA}` has just been completed.
Since $`\mathbb{E}[\tau] < \infty` (some string of $`11` letters completes in every disjoint block of $`11` seconds, with probability $`26^{-11}` each) and each second changes the casino's balance by a bounded amount, the "finite bets" case of the optional stopping theorem applies: $$`\mathbb{E}[X_\tau] = \mathbb{E}[X_0] = 0.`

Now audit the books at time $`\tau`.
The casino has collected $`\$1` from each of the $`\tau` gamblers.
Which gamblers still hold money?
A gambler who entered at time $`\tau - k + 1` (so has bet on the last $`k` keystrokes) holds $`\$26^k` exactly when the last $`k` letters typed match the first $`k` letters of $`\texttt{ABRACADABRA}` — that is, when a length-$`k` suffix of the string equals a length-$`k` prefix.
For $`\texttt{ABRACADABRA}` this happens for $`k = 11` (the whole string), $`k = 4` ($`\texttt{ABRA}`), and $`k = 1` ($`\texttt{A}`), and no other $`k`.
So $$`0 = \mathbb{E}[X_\tau] = \mathbb{E}[\tau] - \left( 26^{11} + 26^4 + 26 \right),` which is the claim.
:::

:::QUESTION
What is the expected time until the monkey types $`\texttt{ABCDEFGHIJK}`, and why is it smaller?
:::

## USA TST 2018

The following problem was proposed by Michael Kural and Yang Liu for the USA Team Selection Test in 2018.

:::PROBLEM "USA TST 2018/2"
Find all functions $`f \colon \mathbb{Z}^2 \to [0, 1]` such that for any integers $`x` and $`y`, $$`f(x, y) = \frac{f(x - 1, y) + f(x, y - 1)}{2}.`
:::

The answer is that $`f` must be constant — and the fun part is that the given equation is begging to be read as a martingale.

:::PROOF
Fix a starting point and walk _backwards_: from $`(x, y)`, move to $`(x-1, y)` or $`(x, y-1)` with probability $`\frac12` each, independently forever, and let $`Z_n` be the position after $`n` steps.
The functional equation says precisely that $$`\mathbb{E}\left( f(Z_n) \mid Z_0, \dots, Z_{n-1} \right) = f(Z_{n-1}),` i.e. $`X_n = f(Z_n)` is a martingale; it takes values in $`[0,1]`, so it even converges almost surely by Doob's convergence theorem.

Rather than stopping this martingale, we exploit the fairness identity it gives at each fixed time: $$`f(x, y) = \mathbb{E}[f(Z_n)] = \sum_{k=0}^{n} \binom nk 2^{-n} f(x - k, \; y - (n-k)),` since after $`n` steps we have moved left a $`\operatorname{Binomial}(n, \frac12)` number $`k` of times.
Doing the same at the neighboring starting point $`(x-1, y)` gives the same sum with $`k` shifted by one, so subtracting,
$$`\left\lvert f(x,y) - f(x-1,y) \right\rvert = \left\lvert \sum_{k} \left( \binom nk - \binom{n}{k-1} \right) 2^{-n} f(x-k, y-(n-k)) \right\rvert \le 2^{-n} \sum_k \left\lvert \binom nk - \binom{n}{k-1} \right\rvert = 2^{-n} \cdot 2\binom{n}{\lfloor n/2 \rfloor},`
where the last sum telescopes in the two halves and we used $`0 \le f \le 1` — this is the only place the codomain matters.
By our estimates on the central binomial coefficient, $`2^{-n} \binom{n}{\lfloor n/2 \rfloor} = O\left( \frac{1}{\sqrt n} \right) \to 0`, and the left-hand side doesn't depend on $`n`; hence $`f(x, y) = f(x-1, y)`.
By symmetry also $`f(x,y) = f(x, y-1)`, so $`f` is constant (and any constant works).
:::

:::REMARK
The bound $`0 \le f \le 1` cannot be discarded: $`f(x, y) = x - y` satisfies the equation.
The proof shows any _bounded_ solution is constant, which is a discrete analogue of Liouville's theorem from complex analysis.
:::

# Problems

:::PROBLEM "Examples of martingales"
We give some more examples of martingales.

1. *(Simple random walk)* Let $`X_1`, $`X_2`, … be i.i.d. random variables which equal $`+1` with probability $`1/2`, and $`-1` with probability $`1/2`.
   Prove that $$`Y_n = \left( X_1 + \dots + X_n \right)^2 - n` is a martingale.
2. *(de Moivre's martingale)* Fix real numbers $`p` and $`q` such that $`p,q > 0` and $`p+q=1`.
   Let $`X_1`, $`X_2`, … be i.i.d. random variables which equal $`+1` with probability $`p`, and $`-1` with probability $`q`.
   Show that $$`Y_n = \left(qp^{-1}\right)^{X_1 + X_2 + \dots + X_n}` is a martingale.
3. *(Pólya's urn)* An urn contains one red and one blue marble initially.
   Every minute, a marble is randomly removed from the urn, and two more marbles of the same color are added to the urn.
   Thus after $`n` minutes, the urn will have $`n+2` marbles.

   Let $`r_n` denote the fraction of marbles which are red.
   Show that $`r_n` is a martingale.
:::

:::PROBLEM
A deck has $`52` cards; of them $`26` are red and $`26` are black.
The cards are drawn and revealed one at a time.
At any point, if there is at least one card remaining in the deck, you may stop the dealer; you win if (and only if) the next card in the deck is red.
If all cards are dealt, then you lose.
Across all possible strategies, determine the maximal probability of winning.
(Hint: there is a cute elementary solution.
For the martingale-based solution, show that the fraction of red cards in the deck at time $`n` is a martingale.)
:::

:::PROBLEM "Wald's identity"
Let $`\mu` be a real number.
Let $`X_1`, $`X_2`, … be independent random variables on a probability space $`\Omega` with mean $`\mu`.
Finally let $`\tau \colon \Omega \to \{1, 2, \dots\}` be a stopping time such that $`\mathbb{E}[\tau] < \infty`, and the event $`\tau = n` depends only on $`X_1`, …, $`X_n`.

Prove that $$`\mathbb{E}[X_1 + X_2 + \dots + X_\tau] = \mu \mathbb{E}[\tau].`
:::

:::PROBLEM "Unbiased drunkard's walk"
An ant starts at $`0` on a number line, and walks left or right one unit with probability $`1/2`.
It stops once it reaches either $`-17` or $`+8`.

1. Find the probability it reaches $`+8` before $`-17`.
2. Find the expected value of the amount of time it takes to reach either endpoint.
:::

:::PROBLEM "Biased drunkard's walk"
Let $`0 < p < 1` be a real number.
An ant starts at $`0` on a number line, and walks left or right one unit with probability $`p`.
It stops once it reaches either $`-17` or $`+8`.
Find the probability it reaches $`+8` first.
(Hint: use the "Examples of martingales" problem.)
:::

:::PROBLEM
The number $`1` is written on a blackboard.
Every minute, if the number $`a` is written on the board, it's erased and replaced by a real number in the interval $`[0, 2.01a]` selected uniformly at random.
What is the probability that the resulting sequence of numbers approaches $`0`?
(Hint: it occurs with probability $`1`.
If $`X_n` is the number on the board at step $`n`, and $`\mu = \frac{1}{2.01} \int_0^{2.01} \log t \; dt`, show that $`\log(X_n) - n \mu` is a martingale.
(Incidentally, using the law of large numbers could work too.))
:::

# Formalization

:::LEANCOMPANION
:::

## Sub-σ-algebras and filtrations

Sub-$`\sigma`-algebras need no new structure: `MeasurableSpace Ω` is an ordinary type, measurable spaces on a fixed carrier are partially ordered by inclusion of their measurable sets, and a sub-$`\sigma`-algebra of `m₀` is just an `m : MeasurableSpace Ω` with `m ≤ m₀`.
(This is one place the "carriers are types, structures are instances" design gets stress-tested: here the carrier stays fixed and the *structure* varies, so the σ-algebras are passed around as explicit values rather than instances.)

$`\sigma(X)` is the pullback `MeasurableSpace.comap X inferInstance`, and the "smallest $`\sigma`-algebra containing each" is a supremum `⨆ i, MeasurableSpace.comap (X i) _` in the complete lattice of measurable-space structures.

`MeasureTheory.Filtration ι m` bundles exactly this: a monotone family of `MeasurableSpace Ω` values, all bounded above by `m`, indexed by any preorder `ι` (so the margin note's generality comes for free).
The filtration generated by a sequence of random variables is `MeasureTheory.Filtration.natural`.

The definition asks a filtration to be a nested sequence $`\mathcal{F}_0 \subseteq \mathcal{F}_1 \subseteq \cdots`.
Recover that monotonicity from the bundled structure: a filtration's $`\sigma`-algebras only grow with time.

```lean
example {Ω : Type*} {m : MeasurableSpace Ω} (ℱ : Filtration ℕ m) (i j : ℕ)
    (h : i ≤ j) : ℱ i ≤ ℱ j := by
  sorry
```

:::solution
```lean
example {Ω : Type*} {m : MeasurableSpace Ω} (ℱ : Filtration ℕ m) (i j : ℕ)
    (h : i ≤ j) : ℱ i ≤ ℱ j :=
  ℱ.mono h
```
:::

## Conditional expectation

The conditional expectation is `MeasureTheory.condExp m μ X`, written `μ[X|m]` — the function $`\eta`, defined via exactly the Radon-Nikodym route the proof gestures at.
Its defining property is `MeasureTheory.setIntegral_condExp`, the second bullet of the proposition with $`\mathbf{1}_A` folded into a set-restricted integral:

```lean
recall MeasureTheory.setIntegral_condExp {α : Type*} {E : Type*}
    {m m₀ : MeasurableSpace α} {μ : Measure α} {f : α → E} {s : Set α}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (hm : m ≤ m₀) [SigmaFinite (μ.trim hm)] (hf : Integrable f μ)
    (hs : MeasurableSet[m] s) :
    ∫ x in s, (μ[f|m]) x ∂μ = ∫ x in s, f x ∂μ
```

Since the proposition only pins $`\eta` down up to almost-sure equality, `condExp` has to *choose* a representative; and it makes total junk-value choices everywhere outside the proposition's hypotheses ($`X` not integrable, or $`\mathcal{F}` not a sub-$`\sigma`-algebra: `μ[X|m] = 0`).
Conditioning on a random variable is conditioning on its generated $`\sigma`-algebra, `μ[X | MeasurableSpace.comap Y inferInstance]`.

Each bullet is a lemma: linearity is `MeasureTheory.condExp_add` (with `condExp_smul` for the scalar), positivity is `condExp_nonneg`, taking out what is known is `condExp_of_stronglyMeasurable` (and `condExp_mul_of_stronglyMeasurable_left` for the product form), independence is `MeasureTheory.condExp_indep_eq`, and the tower property is `condExp_condExp_of_le`, with the law of total expectation as `integral_condExp`:

```lean
recall MeasureTheory.condExp_condExp_of_le {α : Type*} {E : Type*}
    {f : α → E}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    {m₁ m₂ m₀ : MeasurableSpace α} {μ : Measure α}
    (hm₁₂ : m₁ ≤ m₂) (hm₂ : m₂ ≤ m₀) [SigmaFinite (μ.trim hm₂)] :
    μ[μ[f|m₂]|m₁] =ᵐ[μ] μ[f|m₁]

recall MeasureTheory.integral_condExp {α : Type*} {E : Type*}
    {m m₀ : MeasurableSpace α} {μ : Measure α} {f : α → E}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (hm : m ≤ m₀) [hμm : SigmaFinite (μ.trim hm)] :
    ∫ x, (μ[f|m]) x ∂μ = ∫ x, f x ∂μ
```

The "taking out what is known" bullet says that a random variable already measurable with respect to $`\mathcal{F}` is its own conditional expectation.
Prove it for an integrable, $`\mathcal{F}`-measurable $`f`.

```lean
example {α E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    {m m₀ : MeasurableSpace α} {μ : Measure α} (hm : m ≤ m₀)
    [SigmaFinite (μ.trim hm)] {f : α → E}
    (hf : StronglyMeasurable[m] f) (hfi : Integrable f μ) :
    μ[f | m] = f := by
  sorry
```

:::solution
```lean
example {α E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    {m m₀ : MeasurableSpace α} {μ : Measure α} (hm : m ≤ m₀)
    [SigmaFinite (μ.trim hm)] {f : α → E}
    (hf : StronglyMeasurable[m] f) (hfi : Integrable f μ) :
    μ[f | m] = f :=
  condExp_of_stronglyMeasurable hm hf hfi
```
:::

## Supermartingales

The three definitions are `MeasureTheory.Supermartingale`, `Submartingale`, and `Martingale`, each taking the process, the filtration, and the measure:

```lean
recall MeasureTheory.Supermartingale {Ω E ι : Type*} [Preorder ι]
    {m0 : MeasurableSpace Ω} [NormedAddCommGroup E]
    [NormedSpace ℝ E] [LE E]
    (f : ι → Ω → E) (ℱ : Filtration ι m0) (μ : Measure Ω) : Prop
```

Two packaging notes.
The measurability bullet is the predicate `StronglyAdapted ℱ f` inside the definition.
And where the definition above compares consecutive times, Mathlib quantifies over all pairs `i ≤ j` — `μ[f j | ℱ i] ≤ᵐ[μ] f i` — which is the equivalent "no lookahead at any distance" form (the consecutive version recovers it by the tower property, exercise!).

The convergence theorem is `MeasureTheory.Submartingale.ae_tendsto_limitProcess`; the supermartingale statement follows by negation, since $`-X_n` is then a submartingale.
Given the uniform $`L^1` bound, the process converges almost everywhere to `ℱ.limitProcess f μ`, Mathlib's name for a choice of the limiting random variable $`X_\infty`.
The proof formalized there is the classic upcrossing argument, whose combinatorial heart lives in `Mathlib.Probability.Martingale.Upcrossing`.

We prove our theorems for supermartingales and read off the martingale case from the fact that a martingale is exactly a process that is at once a supermartingale and a submartingale.
Verify that characterization.

```lean
example {Ω E ι : Type*} [Preorder ι] {m0 : MeasurableSpace Ω} {μ : Measure Ω}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E] [PartialOrder E]
    (f : ι → Ω → E) (ℱ : Filtration ι m0) :
    Martingale f ℱ μ ↔ Supermartingale f ℱ μ ∧ Submartingale f ℱ μ := by
  sorry
```

:::solution
```lean
example {Ω E ι : Type*} [Preorder ι] {m0 : MeasurableSpace Ω} {μ : Measure Ω}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E] [PartialOrder E]
    (f : ι → Ω → E) (ℱ : Filtration ι m0) :
    Martingale f ℱ μ ↔ Supermartingale f ℱ μ ∧ Submartingale f ℱ μ :=
  martingale_iff
```
:::

## Optional stopping

All three bullets have Mathlib names.
A stopping time is `MeasureTheory.IsStoppingTime ℱ τ` for `τ : Ω → WithTop ι` — with `WithTop` supplying the $`\cup \{\infty\}` — phrased via the (equivalent, for integer times) condition that $`\{\tau \le n\}` is $`\mathcal{F}_n`-measurable:

```lean
recall MeasureTheory.IsStoppingTime {Ω ι : Type*}
    {m : MeasurableSpace Ω} [Preorder ι]
    (f : Filtration ι m) (τ : Ω → WithTop ι) : Prop :=
  ∀ i, MeasurableSet[f i] {ω | τ ω ≤ i}
```

The stopped process $`n \mapsto X_{\tau \wedge n}` is `MeasureTheory.stoppedProcess X τ`, and the eventual value $`X_\tau` is `MeasureTheory.stoppedValue X τ` — with one honesty caveat: `stoppedValue` extracts the value at time `τ ω` via a junk-value fallback rather than a limit, so it only means the chapter's $`X_\tau` on worlds where $`\tau` is finite; the $`\tau = \infty` branch has to be handled by combining with `limitProcess`.

The stopped-supermartingale proposition is `MeasureTheory.Submartingale.stoppedProcess` (submartingale form; negate for the supermartingale statement).

Mathlib formalizes the finite-time case, in a two-stopping-times form: `MeasureTheory.Submartingale.expected_stoppedValue_mono` states that for bounded stopping times $`\tau \le \pi`, $$`\mathbb{E}[X_\tau] \le \mathbb{E}[X_\pi],` and remarkably this property *characterizes* submartingales among adapted integrable processes (`MeasureTheory.submartingale_iff_expected_stoppedValue_mono`) — optional stopping is not just a consequence of the definition but an equivalent reformulation.
The unbounded cases (finite money, finite bets) are the dominated-convergence epilogue above and are done by hand when needed.

The simplest stopping rule is "always stop at a fixed time $`i`" — deciding whether to stop needs no information at all.
Confirm that a constant is a stopping time.

```lean
example {Ω ι : Type*} {m : MeasurableSpace Ω} [Preorder ι]
    (ℱ : Filtration ι m) (i : ι) :
    IsStoppingTime ℱ (fun _ => (i : WithTop ι)) := by
  sorry
```

:::solution
```lean
example {Ω ι : Type*} {m : MeasurableSpace Ω} [Preorder ι]
    (ℱ : Filtration ι m) (i : ι) :
    IsStoppingTime ℱ (fun _ => (i : WithTop ι)) :=
  isStoppingTime_const ℱ i
```
:::
