import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations
import Mathlib.RepresentationTheory.Character

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

open CategoryTheory
open CategoryTheory.MonoidalCategory
open scoped Classical

set_option pp.rawOnError true

#doc (Manual) "Characters" =>

%%%
file := "Characters"
%%%


Characters are basically the best thing ever.
To every representation $`V` of $`A` we will attach a so-called character $`\chi_V \colon A \to k`.
It will turn out that the characters of finite-dimensional irreps of $`V` will determine the representation $`V` completely.
Thus a finite-dimensional irrep is just specified by a set of $`\dim A` numbers.

# Definitions

:::DEFINITION
Let $`V = (V, \rho)` be a finite-dimensional representation of $`A`.
The *character* $`\chi_V \colon A \to k` attached to $`V` is defined by $`\chi_V = \operatorname{Tr} \circ \rho`, i.e. $$`\chi_V(a) := \operatorname{Tr}(\rho(a) \colon V \to V).`
:::

Since $`\operatorname{Tr}` and $`\rho` are additive, this is a $`k`-linear map (but it is not multiplicative).
Note also that $`\chi_{V \oplus W} = \chi_V + \chi_W` for any representations $`V` and $`W`.

We are especially interested in the case $`A = k[G]`, of course.
As usual, we just have to specify $`\chi_V(g)` for each $`g : G` to get the whole map $`k[G] \to k`.
Thus we often think of $`\chi_V` as a function $`G \to k`, called a character of the group $`G`.
Here is the case $`G = S_3`:

:::EXAMPLE "Character table of $`S_3`"
Let's consider the three irreps of $`G = S_3` from before.
For $`\mathbb{C}_{\text{triv}}` all traces are $`1`; for $`\mathbb{C}_{\text{sign}}` the traces are $`\pm 1` depending on sign (obviously, for one-dimensional maps $`k \to k` the trace "is" just the map itself).
For $`\operatorname{refl}_0` we take a basis $`(1, 0, -1)` and $`(0, 1, -1)`, say, and compute the traces directly in this basis.

$$`\begin{array}{|r|rrrrrr|} \hline \chi_V(g) & \operatorname{id} & (1\;2) & (2\;3) & (3\;1) & (1\;2\;3) & (3\;2\;1) \\ \hline \mathbb{C}_{\text{triv}} & 1 & 1 & 1 & 1 & 1 & 1 \\ \mathbb{C}_{\text{sign}} & 1 & -1 & -1 & -1 & 1 & 1 \\ \operatorname{refl}_0 & 2 & 0 & 0 & 0 & -1 & -1 \\ \hline \end{array}`
:::

The above table is called the *character table* of the group $`G`.
The table above has certain mysterious properties, which we will prove as the chapter progresses.

1. The value of $`\chi_V(g)` only depends on the conjugacy class of $`g`.
2. The number of rows equals the number of conjugacy classes.
3. The sum of the squares of any row is $`6` again!
4. The "dot product" of any two rows is zero.

:::ABUSE
The name "character" for $`\chi_V \colon G \to k` is a bit of a misnomer.
This $`\chi_V` is not multiplicative in any way, as the above example shows: one can almost think of it as an element of $`k^{\oplus |G|}`.
:::

:::QUESTION
Show that $`\chi_V(1_A) = \dim V`, so one can read the dimensions of the representations from the leftmost column of a character table.
:::

# The dual space modulo the commutator

For any algebra, we first observe that since $`\operatorname{Tr}(TS) = \operatorname{Tr}(ST)`, we have for any $`V` that $$`\chi_V(ab) = \chi_V(ba).`
This explains observation (1) from earlier:

:::QUESTION
Deduce that if $`g` and $`h` are in the same conjugacy class of a group $`G`, and $`V` is a representation of $`k[G]`, then $`\chi(g) = \chi(h)`.
:::

Now, given our algebra $`A` we define the *commutator* $`[A, A]` to be the $`k`-vector subspace spanned by $`xy - yx` for $`x, y : A`.
Thus $`[A, A]` is contained in the kernel of each $`\chi_V`.

:::DEFINITION
The space $`A^{\text{ab}} := A / [A, A]` is called the *abelianization* of $`A`.
Each character of $`A` can be viewed as a map $`A^{\text{ab}} \to k`, i.e. an element of $`(A^{\text{ab}})^\vee`.
:::

:::EXAMPLE "Examples of abelianizations"
1. If $`A` is commutative, then $`[A, A] = \{0\}` and $`A^{\text{ab}} = A`.
2. If $`A = \operatorname{Mat}_d(k)`, then $`[A, A]` consists exactly of the $`d \times d` matrices of trace zero.
   (Proof: harmless exercise.)
   Consequently, $`A^{\text{ab}}` is one-dimensional.
3. Suppose $`A = k[G]`.
   Then in $`A^{\text{ab}}`, we identify $`gh` and $`hg` for each $`g, h : G`; equivalently $`g h g^{-1} = h`.
   So in other words, $`A^{\text{ab}}` is isomorphic to the space of $`k`-linear combinations of the _conjugacy classes_ of $`G`.
:::

:::REMARK "Warning"
For a group $`G`, the abelianization of $`G` is defined to be $`G / [G, G]`, where $`[G, G]` is the subgroup generated by all the commutators.

When $`A = k[G]`, the space $`A^{\text{ab}}` is not isomorphic to the group algebra $`k[G / [G, G]]`!
This is because, in the abelianization of the group $`G`, we identify $`g h g^{-1} h^{-1} = 1` for all $`g, h : G`, which is not the same as $`gh - hg`.

In fact, in the general case, $`A^{\text{ab}}` does not even inherit the structure of a $`k`-algebra from $`A`, it can only get a $`k`-vector space structure.
:::

:::THEOREM "Character of representations of algebras"
Let $`A` be an algebra over an algebraically closed field.
Then

1. Characters of pairwise non-isomorphic finite-dimensional irreps are linearly independent in $`(A^{\text{ab}})^\vee`.
2. If $`A` is finite-dimensional and semisimple, then the characters attached to irreps form a basis of $`(A^{\text{ab}})^\vee`.

In particular, in (2) the number of irreps of $`A` equals $`\dim A^{\text{ab}}`.
:::

::::PROOF
Part (1) is more or less obvious by the density theorem: suppose there is a linear dependence, so that for every $`a` we have $$`c_1 \chi_{V_1}(a) + c_2 \chi_{V_2}(a) + \dots + c_r \chi_{V_r}(a) = 0` for some integer $`r`.

:::EXERCISE
Deduce that $`c_1 = \dots = c_r = 0` from the density theorem.
:::

For part (2), assume there are $`r` irreps.
We may assume that $$`A = \bigoplus_{i=1}^r \operatorname{Mat}(V_i)` where $`V_1`, \dots, $`V_r` are the irreps of $`A`.
Since we have already showed the characters are linearly independent we need only show that $`\dim(A / [A, A]) = r`, which follows from the observation earlier that each $`\operatorname{Mat}(V_i)` has a one-dimensional abelianization.
::::

Since $`G` has $`\dim k[G]^{\text{ab}}` conjugacy classes, this completes the proof of (2).

# Orthogonality of characters

Now we specialize to the case of finite groups $`G`, represented over $`\mathbb{C}`.

:::DEFINITION
Let $`\operatorname{Classes}(G)` denote the set of conjugacy classes of $`G`.
:::

If $`G` has $`r` conjugacy classes, then it has $`r` irreps.
Each (finite-dimensional) representation $`V`, irreducible or not, gives a character $`\chi_V`.

:::ABUSE
From now on, we will often regard $`\chi_V` as a function $`G \to \mathbb{C}` or as a function $`\operatorname{Classes}(G) \to \mathbb{C}`.
So for example, we will write both $`\chi_V(g)` (for $`g : G`) and $`\chi_V(C)` (for a conjugacy class $`C`); the latter just means $`\chi_V(g_C)` for any representative $`g_C \in C`.
:::

:::DEFINITION
Let $`\operatorname{FunCl}(G)` denote the set of functions $`\operatorname{Classes}(G) \to \mathbb{C}` viewed as a vector space over $`\mathbb{C}`.
We endow it with the inner form $$`\langle f_1, f_2 \rangle = \frac{1}{|G|} \sum_{g : G} f_1(g) \overline{f_2(g)}.`
:::

This is the same "dot product" that we mentioned at the beginning, when we looked at the character table of $`S_3`.
We now aim to prove the following orthogonality theorem, which will imply (3) and (4) from earlier.

:::THEOREM "Orthogonality"
For any finite-dimensional complex representations $`V` and $`W` of $`G` we have $$`\langle \chi_V, \chi_W \rangle = \dim \operatorname{Hom}_{\text{rep}}(W, V).`
In particular, if $`V` and $`W` are irreps then $$`\langle \chi_V, \chi_W \rangle = \begin{cases} 1 & V \cong W \\ 0 & \text{otherwise}. \end{cases}`
:::

:::COROLLARY "Irreps give an orthonormal basis"
The characters associated to irreps form an *orthonormal* basis of $`\operatorname{FunCl}(G)`.
:::

In order to prove this theorem, we have to define the dual representation and the tensor representation, which give a natural way to deal with the quantity $`\chi_V(g) \overline{\chi_W(g)}`.

:::DEFINITION
Let $`V = (V, \rho)` be a representation of $`G`.
The *dual representation* $`V^\vee` is the representation on $`V^\vee` with the action of $`G` given as follows: for each $`\xi : V^\vee`, the action of $`g` gives a $`g \cdot \xi : V^\vee` specified by $$`(g \cdot \xi)(v) = \xi(\rho(g^{-1})(v)).`
:::

:::DEFINITION
Let $`V = (V, \rho_V)` and $`W = (W, \rho_W)` be _group_ representations of $`G`.
The *tensor product* of $`V` and $`W` is the group representation on $`V \otimes W` with the action of $`G` given on pure tensors by $$`g \cdot (v \otimes w) = (\rho_V(g)(v)) \otimes (\rho_W(g)(w))` which extends linearly to define the action of $`G` on all of $`V \otimes W`.
:::

:::REMARK
Warning: the definition for tensors does *not* extend to algebras.
We might hope that $`a \cdot (v \otimes w) = (a \cdot v) \otimes (a \cdot w)` would work, but this is not even linear in $`a : A` (what happens if we take $`a = 2`, for example?).
:::

:::THEOREM "Character traces"
If $`V` and $`W` are finite-dimensional representations of $`G`, then for any $`g : G`.

1. $`\chi_{V \oplus W}(g) = \chi_V(g) + \chi_W(g)`.
2. $`\chi_{V \otimes W}(g) = \chi_V(g) \cdot \chi_W(g)`.
3. $`\chi_{V^\vee}(g) = \overline{\chi_V(g)}`.
:::

:::PROOF
Parts (1) and (2) follow from the identities $`\operatorname{Tr}(S \oplus T) = \operatorname{Tr}(S) + \operatorname{Tr}(T)` and $`\operatorname{Tr}(S \otimes T) = \operatorname{Tr}(S) \operatorname{Tr}(T)`.
However, part (3) is trickier.
As $`(\rho(g))^{|G|} = \rho(g^{|G|}) = \rho(1_G) = \operatorname{id}_V` by Lagrange's theorem, we can diagonalize $`\rho(g)`, say with eigenvalues $`\lambda_1`, \dots, $`\lambda_n` which are $`|G|`th roots of unity, corresponding to eigenvectors $`e_1`, \dots, $`e_n`.
Then we see that in the basis $`e_1^\vee`, \dots, $`e_n^\vee`, the action of $`g` on $`V^\vee` has eigenvalues $`\lambda_1^{-1}`, $`\lambda_2^{-1}`, \dots, $`\lambda_n^{-1}`.
So $$`\chi_V(g) = \sum_{i=1}^n \lambda_i \quad \text{and} \quad \chi_{V^\vee}(g) = \sum_{i=1}^n \lambda_i^{-1} = \sum_{i=1}^n \overline{\lambda_i}` where the last step follows from the identity $`|z| = 1 \iff z^{-1} = \overline{z}`.
:::

:::REMARK "Warning"
The identities (2) and (3) do not extend linearly to $`\mathbb{C}[G]`, i.e. it is not true for example that $`\chi_{V^\vee}(a) = \overline{\chi_V(a)}` if we think of $`\chi_V` as a map $`\mathbb{C}[G] \to \mathbb{C}`.
:::

*Proof of orthogonality relation.*

::::PROOF
The key point is that we can now reduce the sums of products to just a single character by $$`\chi_V(g) \overline{\chi_W(g)} = \chi_{V \otimes W^\vee}(g).`
So we can rewrite the sum in question as just $$`\langle \chi_V, \chi_W \rangle = \frac{1}{|G|} \sum_{g : G} \chi_{V \otimes W^\vee}(g) = \chi_{V \otimes W^\vee}\left( \frac{1}{|G|} \sum_{g : G} g \right).`
Let $`P \colon V \otimes W^\vee \to V \otimes W^\vee` be the action of $`\frac{1}{|G|} \sum_{g : G} g`, so we wish to find $`\operatorname{Tr} P`.

:::EXERCISE
Show that $`P` is idempotent.
(Compute $`P \circ P` directly.)
:::

Hence $`V \otimes W^\vee = \ker P \oplus \operatorname{img} P` and $`\operatorname{img} P` is the subspace of elements which are fixed under $`G`.
From this we deduce that $$`\operatorname{Tr} P = \dim \operatorname{img} P = \dim \left\{ x : V \otimes W^\vee \mid g \cdot x = x \; \forall g : G \right\}.`
Now, consider the natural isomorphism $`V \otimes W^\vee \to \operatorname{Hom}(W, V)`.

:::EXERCISE
Let $`g : G`.
Show that under this isomorphism, $`T : \operatorname{Hom}(W, V)` satisfies $`g \cdot T = T` if and only if $`T(g \cdot w) = g \cdot T(w)` for each $`w : W`.
(This is just unwinding three or four definitions.)
:::

Consequently, $`\chi_{V \otimes W^\vee}(P) = \operatorname{Tr} P = \dim \operatorname{Hom}_{\text{rep}}(W, V)` as desired.
::::

The orthogonality relation gives us a fast and mechanical way to check whether a finite-dimensional representation $`V` is irreducible.
Namely, compute the traces $`\chi_V(g)` for each $`g : G`, and then check whether $`\langle \chi_V, \chi_V \rangle = 1`.
So, for example, we could have seen the three representations of $`S_3` that we found were irreps directly from the character table.
Thus, we can now efficiently verify any time we have a complete set of irreps.

# Examples of character tables

:::EXAMPLE "Dihedral group on 10 elements"
Let $`D_{10} = \langle r, s \mid r^5 = s^2 = 1, rs = s r^{-1} \rangle`.
Let $`\omega = \exp(\frac{2 \pi i}{5})`.
We write four representations of $`D_{10}`:

- $`\mathbb{C}_{\text{triv}}`, all elements of $`D_{10}` act as the identity.
- $`\mathbb{C}_{\text{sign}}`, $`r` acts as the identity while $`s` acts by negation.
- $`V_1`, which is two-dimensional and given by $`r \mapsto \begin{bmatrix} \omega & 0 \\ 0 & \omega^4 \end{bmatrix}` and $`s \mapsto \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}`.
- $`V_2`, which is two-dimensional and given by $`r \mapsto \begin{bmatrix} \omega^2 & 0 \\ 0 & \omega^3 \end{bmatrix}` and $`s \mapsto \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}`.

We claim that these four representations are irreducible and pairwise non-isomorphic.
We do so by writing the character table: $$`\begin{array}{|c|rccr|} \hline D_{10} & 1 & r, r^4 & r^2, r^3 & s r^k \\ \hline \mathbb{C}_{\text{triv}} & 1 & 1 & 1 & 1 \\ \mathbb{C}_{\text{sign}} & 1 & 1 & 1 & -1 \\ V_1 & 2 & \omega + \omega^4 & \omega^2 + \omega^3 & 0 \\ V_2 & 2 & \omega^2 + \omega^3 & \omega + \omega^4 & 0 \\ \hline \end{array}`
Then a direct computation shows the orthogonality relations, hence we indeed have an orthonormal basis.
For example, $`\langle \mathbb{C}_{\text{triv}}, \mathbb{C}_{\text{sign}} \rangle = 1 + 2 \cdot 1 + 2 \cdot 1 + 5 \cdot (-1) = 0`.
:::

:::EXAMPLE "Character table of $`S_4`"
We now have enough machinery to compute the character table of $`S_4`, which has five conjugacy classes (corresponding to cycle types $`\operatorname{id}`, $`2`, $`3`, $`4` and $`2 + 2`).
First of all, we note that it has two one-dimensional representations, $`\mathbb{C}_{\text{triv}}` and $`\mathbb{C}_{\text{sign}}`, and these are the only ones (because there are only two homomorphisms $`S_4 \to \mathbb{C}^\times`).
So thus far we have the table $$`\begin{array}{|c|rrrrr|} \hline S_4 & 1 & (\bullet\;\bullet) & (\bullet\;\bullet\;\bullet) & (\bullet\;\bullet\;\bullet\;\bullet) & (\bullet\;\bullet)(\bullet\;\bullet) \\ \hline \mathbb{C}_{\text{triv}} & 1 & 1 & 1 & 1 & 1 \\ \mathbb{C}_{\text{sign}} & 1 & -1 & 1 & -1 & 1 \\ \vdots & & & & & \end{array}`
Note the columns represent $`1 + 6 + 8 + 6 + 3 = 24` elements.

Now, the remaining three representations have dimensions $`d_1`, $`d_2`, $`d_3` with $$`d_1^2 + d_2^2 + d_3^2 = 4! - 2 = 22` which has only $`(d_1, d_2, d_3) = (2, 3, 3)` and permutations.
Now, we can take the $`\operatorname{refl}_0` representation $$`\left\{ (w, x, y, z) \mid w + x + y + z = 0 \right\}` with basis $`(1, 0, 0, -1)`, $`(0, 1, 0, -1)` and $`(0, 0, 1, -1)`.
This can be geometrically checked to be irreducible, but we can also do this numerically by computing the character directly (this is tedious): it comes out to have $`3`, $`1`, $`0`, $`-1`, $`-1` which indeed gives norm $$`\langle \chi_{\operatorname{refl}_0}, \chi_{\operatorname{refl}_0} \rangle = \frac{1}{4!}\left( 3^2 + 6 \cdot 1^2 + 8 \cdot 0^2 + 6 \cdot (-1)^2 + 3 \cdot (-1)^2 \right) = 1.`
Note that we can also tensor this with the sign representation, to get another irreducible representation (since $`\mathbb{C}_{\text{sign}}` has all traces $`\pm 1`, the norm doesn't change).
Finally, we recover the final row using orthogonality (which we name $`\mathbb{C}^2`, for lack of a better name); hence the completed table is as follows. $$`\begin{array}{|c|rrrrr|} \hline S_4 & 1 & (\bullet\;\bullet) & (\bullet\;\bullet\;\bullet) & (\bullet\;\bullet\;\bullet\;\bullet) & (\bullet\;\bullet)(\bullet\;\bullet) \\ \hline \mathbb{C}_{\text{triv}} & 1 & 1 & 1 & 1 & 1 \\ \mathbb{C}_{\text{sign}} & 1 & -1 & 1 & -1 & 1 \\ \mathbb{C}^2 & 2 & 0 & -1 & 0 & 2 \\ \operatorname{refl}_0 & 3 & 1 & 0 & -1 & -1 \\ \operatorname{refl}_0 \otimes \mathbb{C}_{\text{sign}} & 3 & -1 & 0 & 1 & -1 \\ \hline \end{array}`
:::

# Problems

:::PROBLEM "Reading decompositions from characters"
Let $`W` be a complex representation of a finite group $`G`.
Let $`V_1`, \dots, $`V_r` be the complex irreps of $`G` and set $`n_i = \langle \chi_W, \chi_{V_i} \rangle`.
Prove that each $`n_i` is a non-negative integer and $$`W = \bigoplus_{i=1}^r V_i^{\oplus n_i}.`
:::

:::PROBLEM
Consider complex representations of $`G = S_4`.
The representation $`\operatorname{refl}_0 \otimes \operatorname{refl}_0` is $`9`-dimensional, so it is clearly reducible.
Compute its decomposition in terms of the five irreducible representations.
:::

:::PROBLEM "Tensoring by one-dimensional irreps"
Let $`V` and $`W` be irreps of $`G`, with $`\dim W = 1`.
Show that $`V \otimes W` is irreducible.
:::

:::PROBLEM "Quaternions"
Compute the character table of the quaternion group $`Q_8`.
:::

:::PROBLEM "Second orthogonality formula" (chili := 1)
Let $`g` and $`h` be elements of a finite group $`G`, and let $`V_1`, \dots, $`V_r` be the irreps of $`G`.
Prove that $$`\sum_{i=1}^r \chi_{V_i}(g) \overline{\chi_{V_i}(h)} = \begin{cases} |C_G(g)| & \text{if } g \text{ and } h \text{ are conjugates} \\ 0 & \text{otherwise}. \end{cases}`
Here, $`C_G(g) = \{ x : G \mid xg = gx \}` is the centralizer of $`g`.
:::

# Formalization

:::LEANCOMPANION
:::

## Definitions

The character $`\chi_V` of a finite-dimensional representation $`V` is `FDRep.character`, sending each $`g` to the trace of $`\rho(g) \colon V \to V`.

```lean
example {k G : Type*} [Field k] [Monoid G] (V : FDRep k G) (g : G) :
    V.character g = LinearMap.trace k V (V.ρ g) := rfl
```

Evaluating the character at the identity recovers the dimension, $`\chi_V(1) = \dim V`, which is `FDRep.char_one`.

```lean
example {k G : Type*} [Field k] [Monoid G] (V : FDRep k G) :
    V.character 1 = Module.finrank k V := FDRep.char_one V
```

Characters were promised to determine a representation up to isomorphism; the easy half of that is `FDRep.char_iso`, that isomorphic representations already share a character.

```lean
example {k G : Type*} [Field k] [Monoid G] (V W : FDRep k G) (i : V ≅ W) :
    V.character = W.character := by
  sorry
```

## The dual space modulo the commutator

The commutation identity $`\chi_V(hg) = \chi_V(gh)` is `FDRep.char_mul_comm`, and its consequence that the character is constant on conjugacy classes, $`\chi_V(hgh^{-1}) = \chi_V(g)`, is `FDRep.char_conj`.

```lean
example {k G : Type*} [Field k] [Monoid G] (V : FDRep k G) (g h : G) :
    V.character (h * g) = V.character (g * h) := FDRep.char_mul_comm V g h

example {k G : Type*} [Field k] [Group G] (V : FDRep k G) (g h : G) :
    V.character (h * g * h⁻¹) = V.character g := FDRep.char_conj V g h
```

The question asked you to deduce that a character takes the same value on conjugate elements.
Mathlib's `IsConj g h` is exactly the statement that $`g` and $`h` are conjugate; show that the character then agrees on them.

```lean
example {k G : Type*} [Field k] [Group G] (V : FDRep k G) (g h : G)
    (hc : IsConj g h) : V.character g = V.character h := by
  sorry
```

## Orthogonality of characters

Multiplicativity under tensor product, $`\chi_{V \otimes W} = \chi_V \cdot \chi_W`, is `FDRep.char_tensor`, while the dual character is computed by `FDRep.char_dual` as $`\chi_{V^\vee}(g) = \chi_V(g^{-1})`.

```lean
example {k G : Type*} [Field k] [Monoid G] (V W : FDRep k G) :
    (V ⊗ W).character = V.character * W.character := FDRep.char_tensor V W

example {k G : Type*} [Field k] [Group G] (V : FDRep k G) (g : G) :
    (FDRep.of (Representation.dual V.ρ)).character g = V.character g⁻¹ :=
  FDRep.char_dual V g
```

The scalar product of two characters equals the dimension of the space of equivariant maps $`V \to W`, which is `FDRep.scalar_product_char_eq_finrank_equivariant`.
Over an algebraically closed field this specializes to orthonormality of irreducible characters, `FDRep.char_orthonormal`, taking the value $`1` when $`V \cong W` and $`0` otherwise.

```lean
example {k G : Type*} [Field k] [Group G] [Fintype G]
    [Invertible (Fintype.card G : k)] (V W : FDRep k G) :
    ⅟(Fintype.card G : k) • ∑ g : G, W.character g * V.character g⁻¹ =
      Module.finrank k (V ⟶ W) :=
  FDRep.scalar_product_char_eq_finrank_equivariant V W

example {k G : Type*} [Field k] [IsAlgClosed k] [Group G] [Fintype G]
    [Invertible (Fintype.card G : k)] (V W : FDRep k G) [Simple V] [Simple W] :
    ⅟(Fintype.card G : k) • ∑ g : G, V.character g * W.character g⁻¹ =
      if Nonempty (V ≅ W) then (1 : k) else 0 := FDRep.char_orthonormal V W
```

The orthogonality relation gives a mechanical irreducibility test: an irrep has norm $`1`, i.e. $`\langle \chi_V, \chi_V \rangle = 1`.
Specialize `FDRep.char_orthonormal` to $`W = V` to confirm it.

```lean
example {k G : Type*} [Field k] [IsAlgClosed k] [Group G] [Fintype G]
    [Invertible (Fintype.card G : k)] (V : FDRep k G) [Simple V] :
    ⅟(Fintype.card G : k) • ∑ g : G, V.character g * V.character g⁻¹ =
      (1 : k) := by
  sorry
```
