/-
# `Napkin.Missing` — objects the book defines but Mathlib does not (yet)

The chapters' Lean companions try to rebuild the text in Mathlib.  Where a
chapter introduces a mathematical object that Mathlib has **no** definition
for, the companion used to stop at a prose note.  Instead, the missing object
is defined here — as faithfully to the text's definition as Lean allows — so
the companion's worked models and exercises have something concrete to bite
on.

Everything in this directory is a *stopgap*.  Each definition is tagged, in
its doc-string, with a line beginning

    Not in Mathlib.

together with the upstream name to watch for.  When Mathlib gains the real
object, retire the stopgap: delete the definition here, and repoint the
chapters that `open Napkin.Missing` at the Mathlib name.  To enumerate every
outstanding stopgap:

    grep -rn "Not in Mathlib." Napkin/Missing
-/
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.GroupTheory.Index

namespace Napkin.Missing

section ArtinMap

variable {I G : Type*} [CommGroup I] [CommGroup G]

/-- The data of the **Artin map** of an abelian extension `L/K` relative to a
fixed modulus `𝔪`.  It bundles the abelian Galois group `G = Gal(L/K)`, the
group `I = I_K(𝔪)` of fractional ideals coprime to `𝔪`, the Artin map
`artin : I →* G` sending each prime to its Artin symbol, and the two halves of
Artin reciprocity that Mathlib cannot prove: that the Artin map is
*surjective* (`surjective`, e.g. by Chebotarev density), and that the ray of
principal ideals `ray = P_K(𝔪)` lies in its kernel (`ray_le_ker`), so that the
map factors through the ray class group `C_K(𝔪) = I ⧸ P_K(𝔪)`.

Not in Mathlib.  The Artin map, ray class groups, and moduli of class field
theory have no counterpart; the special case `𝔪 = 1` of `I` is `ClassGroup`.
Retire this whenever class field theory arrives. -/
structure ArtinMapData (I G : Type*) [CommGroup I] [CommGroup G] where
  /-- The Artin map `(L/K / •) : I_K(𝔪) → Gal(L/K)`, the multiplicative
  extension of the Artin symbol. -/
  artin : I →* G
  /-- The Artin map is surjective (for example by Chebotarev density). -/
  surjective : Function.Surjective artin
  /-- The ray of principal ideals `P_K(𝔪)`, generated by the `α 𝒪_K` with
  `α ≡ 1 (mod 𝔪)`. -/
  ray : Subgroup I
  /-- Artin reciprocity's lower bound: `P_K(𝔪) ⊆ H(L/K, 𝔪)`, i.e. the ray
  lies in the kernel of the Artin map. -/
  ray_le_ker : ray ≤ artin.ker

namespace ArtinMapData

variable (D : ArtinMapData I G)

/-- The **ray class group** `C_K(𝔪) = I_K(𝔪) / P_K(𝔪)` through which the Artin
map factors.

Not in Mathlib for general `𝔪`; only `𝔪 = 1`, the ideal `ClassGroup`, is
there. -/
abbrev RayClassGroup := I ⧸ D.ray

/-- The Artin map descended to the ray class group `C_K(𝔪) ↠ Gal(L/K)`.  It
exists precisely because reciprocity puts the ray `P_K(𝔪)` inside the kernel,
which is the content of the factoring `I_K(𝔪) ↠ C_K(𝔪) ↠ Gal(L/K)`.

Not in Mathlib.  Retire alongside `ArtinMapData`. -/
noncomputable def rayArtin : I ⧸ D.ray →* G :=
  QuotientGroup.lift D.ray D.artin D.ray_le_ker

/-- On the class of an ideal, the descended map is the Artin symbol of the
ideal. -/
@[simp] theorem rayArtin_mk (x : I) :
    D.rayArtin (x : I ⧸ D.ray) = D.artin x := rfl

/-- The Artin map on the ray class group is still surjective: `C_K(𝔪)` maps
onto the whole Galois group. -/
theorem rayArtin_surjective : Function.Surjective D.rayArtin := by
  intro g
  obtain ⟨x, hx⟩ := D.surjective g
  exact ⟨(x : I ⧸ D.ray), by rw [rayArtin_mk]; exact hx⟩

/-- **Abelian reciprocity**: the Galois group is a quotient of the ray class
group.  Noether's first isomorphism theorem applied to the surjection
`C_K(𝔪) ↠ Gal(L/K)` exhibits `Gal(L/K)` as `C_K(𝔪)` modulo the kernel
`H(L/K, 𝔪) / P_K(𝔪)`. -/
noncomputable def quotientEquiv :
    (I ⧸ D.ray) ⧸ D.rayArtin.ker ≃* G :=
  QuotientGroup.quotientKerEquivOfSurjective D.rayArtin D.rayArtin_surjective

/-- The order of the Galois group divides the ray class number: `|Gal(L/K)|`
divides `|C_K(𝔪)|`, since the Galois group is a quotient of the ray class
group. -/
theorem card_dvd_rayClassNumber :
    Nat.card G ∣ Nat.card (I ⧸ D.ray) :=
  Subgroup.card_dvd_of_surjective D.rayArtin D.rayArtin_surjective

/-- The identity of `Gal(L/K)` collects the principal ideals: every ideal in
the ray `P_K(𝔪)` has trivial Artin symbol, since the ray lies in the kernel.
This is the reciprocity direction "`α ≡ 1 (mod 𝔪)` ⟹ `(L/K / α𝒪_K) = id`". -/
theorem artin_eq_one_of_mem_ray {x : I} (hx : x ∈ D.ray) :
    D.artin x = 1 := by
  have := D.ray_le_ker hx
  rwa [MonoidHom.mem_ker] at this

/-- The **lower-bound** case, `H(L/K, 𝔪) = P_K(𝔪)`: when the kernel is exactly
the ray — as happens for the cyclotomic tower `ℚ(ζ_m)/ℚ` at `𝔪 = m∞`, the
Kronecker–Weber prototype — the ray class group *is* the Galois group, giving
the canonical isomorphism `C_K(𝔪) ≅ Gal(L/K)`.

Not in Mathlib.  Retire alongside `ArtinMapData`. -/
noncomputable def rayClassEquiv (h : D.artin.ker = D.ray) :
    (I ⧸ D.ray) ≃* G :=
  (QuotientGroup.quotientMulEquivOfEq h.symm).trans
    (QuotientGroup.quotientKerEquivOfSurjective D.artin D.surjective)

end ArtinMapData

end ArtinMap

section Conductor

variable {M : Type*} [CommMonoid M]

/-- The data of the **conductor** `𝔣 = 𝔣(L/K)` of an abelian extension.  With
`M` a commutative monoid of moduli under multiplication and divisibility, it
bundles the conductor `conductor : M` and the predicate `IsAdmissible 𝔪`
recording that `P_K(𝔪) ⊆ H(L/K, 𝔪)` (equivalently, that `H(L/K, 𝔪)` is a
congruence subgroup).  The reciprocity field states the defining property of
the conductor: admissibility holds for exactly the multiples of `𝔣`, so `𝔣` is
the *smallest* modulus (in divisibility) whose ray class group surjects onto
`Gal(L/K)`.

Not in Mathlib.  The conductor of class field theory has no counterpart;
retire this whenever it arrives. -/
structure ConductorData (M : Type*) [CommMonoid M] where
  /-- The conductor `𝔣(L/K)`. -/
  conductor : M
  /-- `IsAdmissible 𝔪` says `P_K(𝔪) ⊆ H(L/K, 𝔪) ⊆ I_K(𝔪)`, i.e. the kernel of
  the Artin map is a congruence subgroup of `𝔪`. -/
  IsAdmissible : M → Prop
  /-- Artin reciprocity: `P_K(𝔪) ⊆ H(L/K, 𝔪)` holds iff the conductor divides
  the modulus, `𝔣 ∣ 𝔪`. -/
  reciprocity : ∀ m : M, IsAdmissible m ↔ conductor ∣ m

namespace ConductorData

variable (C : ConductorData M)

/-- The conductor is itself admissible: taking `𝔪 = 𝔣` in reciprocity, the ray
already lies in the kernel at the conductor. -/
theorem isAdmissible_conductor : C.IsAdmissible C.conductor :=
  (C.reciprocity C.conductor).2 dvd_rfl

/-- The conductor is the smallest admissible modulus: it divides every modulus
at which reciprocity's lower bound holds. -/
theorem conductor_dvd {m : M} (h : C.IsAdmissible m) : C.conductor ∣ m :=
  (C.reciprocity m).1 h

/-- Admissibility is upward closed in divisibility: if `𝔪` is admissible and
`𝔪 ∣ 𝔫`, then `𝔫` is admissible.  So enlarging a modulus past the conductor
never breaks reciprocity. -/
theorem isAdmissible_of_dvd {m n : M} (h : C.IsAdmissible m) (hmn : m ∣ n) :
    C.IsAdmissible n :=
  (C.reciprocity n).2 (dvd_trans (C.conductor_dvd h) hmn)

end ConductorData

end Conductor

end Napkin.Missing
