import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Glossary of notations" =>

%%%
file := "Glossary-of-notations"
%%%

# General

- $`\forall`: for all
- $`\exists`: there exists
- $`\operatorname{sign}(\sigma)`: sign of permutation $`\sigma`
- $`X \implies Y`: $`X` implies $`Y`

# Functions and sets

- $`f(S)` is the image of $`f \colon X \to Y` for $`S \subseteq X`.
- $`f^{-1}(y)` is the inverse for $`f \colon X \to Y` when $`y \in Y`.
- $`f^{-1}(T)` is the pre-image for $`f \colon X \to Y` when $`T \subseteq Y`.
- $`f\restriction_{S}` is the restriction of $`f \colon X \to Y` to $`S \subseteq X`.
- $`f^n` is the function $`f` applied $`n` times

Below are some common sets.
These may also be thought of as groups, rings, fields etc. in the obvious way.

- $`\mathbb{C}`: set of complex numbers
- $`\mathbb{R}`: set of real numbers
- $`\mathbb{N}`: set of positive integers
- $`\mathbb{Q}`: set of rational numbers
- $`\mathbb{Z}`: set of integers
- $`\varnothing`: empty set

Some common notation with sets:

- $`A \subset B`: $`A` is any subset of $`B`
- $`A \subseteq B`: $`A` is any subset of $`B`
- $`A \subsetneq B`: $`A` is a _proper_ subset of $`B`
- $`S \times T`: Cartesian product of sets $`S` and $`T`
- $`S \setminus T`: difference of sets $`S` and $`T`
- $`S \cup T`: set union of $`S` and $`T`
- $`S \cap T`: set intersection of $`S` and $`T`
- $`S \sqcup T`: disjoint union of $`S` and $`T`
- $`\left\lvert S \right\rvert`: cardinality of $`S`
- $`S / {\sim}`: if $`\sim` is an equivalence relation on $`S`, this is the set of equivalence classes
- $`x + S`: denotes the set $`\{x + s \mid s \in S\}`.
- $`xS`: denotes the set $`\{xs \mid s \in S\}`.

# Abstract and linear algebra

Some common groups/rings/fields:

- $`\mathbb{Z}/n\mathbb{Z}`: cyclic group of order $`n`
- $`(\mathbb{Z}/n\mathbb{Z})^\times`: set of units of $`\mathbb{Z}/n\mathbb{Z}`.
- $`S_n`: symmetric group on $`\{1, \dots, n\}`
- $`D_{2n}`: dihedral group of order $`2n`.
- $`0`, $`1`: trivial group (depending on context)
- $`\mathbb{F}_p`: integers modulo $`p`

Notation with groups:

- $`1_G`: identity element of the group $`G`
- $`N \trianglelefteq G`: subgroup $`N` is normal in $`G`.
- $`G/N`: quotient group of $`G` by the normal subgroup $`N`
- $`Z(G)`: center of group $`G`
- $`N_G(H)`: normalizer of the subgroup $`H` of $`G`
- $`G \times H`: product group of $`G` and $`H`
- $`G \oplus H`: also product group, but often used when $`G` and $`H` are abelian (and hence we can think of them as $`\mathbb{Z}`-modules)
- $`\operatorname{Stab}_G(x)`: the stabilizer of $`x \in X`, if $`X` is acted on by $`G`
- $`\operatorname{Fix}(g)`, the set of fixed points by $`g \in G` (under a group action)

Notation with rings:

- $`R/I`: quotient of ring $`R` by ideal $`I`
- $`(a_1, \dots, a_n)`: ideal generated by the $`a_i`
- $`R^\times`: the group of units of $`R`
- $`R[x_1, \dots, x_n]`: polynomial ring in $`x_i`, or ring obtained by adjoining the $`x_i` to $`R`
- $`F(x_1, \dots, x_n)`: field obtained by adjoining $`x_i` to $`F`
- $`R^d`: $`d`th graded part of a graded (pseudo)ring $`R`

Linear algebra:

- $`\operatorname{id}`: the identity matrix
- $`V \oplus W`: direct sum
- $`V^{\oplus n}`: direct sum of $`V`, $`n` times
- $`V \otimes W`: tensor product
- $`V^{\otimes n}`: tensor product of $`V`, $`n` times
- $`V^\vee`: dual space
- $`T^\vee`: dual map (for $`T` a vector space)
- $`T^\dagger`: conjugate transpose (for $`T` a vector space)
- $`\left< -, - \right>`: a bilinear form
- $`\operatorname{Mat}(V)`: endomorphisms of $`V`, i.e. $`\operatorname{Hom}_k(V, V)`
- $`e_1, \dots, e_n`: the "standard basis" of $`k^{\oplus n}`

# Quantum computation

- $`|\psi\rangle`: a vector in some vector space $`H`
- $`\langle\psi|`: a vector in some vector space $`H^\vee`, dual to $`|\psi\rangle`.
- $`\langle\phi|\psi\rangle`: evaluation of an element $`\langle\phi| \in H^\vee` at $`|\phi\rangle \in H`.
- $`|{\uparrow_z}\rangle`, $`|{\downarrow_z}\rangle`: spin $`z`-up, spin $`z`-down
- $`|{\uparrow_x}\rangle`, $`|{\downarrow_x}\rangle`: spin $`x`-up, spin $`x`-down
- $`|{\uparrow_y}\rangle`, $`|{\downarrow_y}\rangle`: spin $`y`-up, spin $`y`-down

# Topology and real/complex analysis

Common topological spaces:

- $`S^1`: the unit circle
- $`S^n`: surface of an $`n`-sphere (in $`\mathbb{R}^{n+1}`)
- $`D^{n+1}`: closed $`n+1` dimensional ball (in $`\mathbb{R}^{n+1}`)
- $`\mathbb{RP}^n`: real projective $`n`-space
- $`\mathbb{CP}^n`: complex projective $`n`-space

Some topological notation:

- $`\partial Y`: boundary of a set $`Y` (in some topological space)
- $`X/S`: quotient topology of $`X` by $`S \subseteq X`
- $`X \times Y`: product topology of spaces $`X` and $`Y`
- $`X \amalg Y`: disjoint union of spaces $`X` and $`Y`
- $`X \vee Y`: wedge product of (pointed) spaces $`X` and $`Y`

Real analysis (calculus 101):

- $`\liminf`: limit infimum
- $`\limsup`: limit supremum
- $`\inf`: infimum
- $`\sup`: supremum
- $`\mathbb{Z}_p`: $`p`-adic integers
- $`\mathbb{Q}_p`: $`p`-adic numbers
- $`f'`: derivative of $`f`
- $`\int_a^b f(x) \, dx`: Riemann integral of $`f` on $`[a, b]`

Complex analysis:

- $`\int_\alpha f \, dz`: contour integral of $`f` along path $`\alpha`
- $`\operatorname{Res}(f; p)`: the residue of a meromorphic function $`f` at point $`p`
- $`\operatorname{Wind}(\gamma, p)`: winding number of $`\gamma` around $`p`.

# Measure theory and probability

- $`\mathcal{A}^\ast`: the $`\sigma`-algebra of Carathéodory-measurable sets
- $`\mathcal{B}(X)`: the Borel space for $`X`
- $`\mu^\ast`: the induced measure on $`\mathcal{A}^\ast`.
- $`\lambda`: Lebesgue measure
- $`\mathbf{1}_A`: the indicator function for $`A`
- $`\int_\Omega f \, d\mu`: the Lebesgue integral of $`f`
- $`\lim_{n \to \infty} f_n`: pointwise limit of $`f_n`
- $`\widehat G`: Pontryagin dual for $`G`

# Algebraic topology

- $`\alpha \simeq \beta`: for paths, this indicates path homotopy
- $`\ast`: path concatenation
- $`\pi_1(X) = \pi_1(X, x_0)`: the fundamental group of (pointed) space $`X`
- $`\pi_n(X) = \pi_n(X, x_0)`: the $`n`th homotopy group of (pointed) space $`X`
- $`f_\sharp`: the induced map $`\pi_1(X) \to \pi_1(Y)` of $`f \colon X \to Y`
- $`\Delta^n`: the standard $`n`-simplex
- $`\partial\sigma`: the boundary of a singular $`n`-simplex $`\sigma`
- $`H_n(A_\bullet)`: the $`n`th homology group of the chain complex $`A_\bullet`
- $`H_n(X)`: the $`n`th homology group of a space $`X`
- $`\widetilde H_n(X)`: the $`n`th reduced homology group of $`X`
- $`H_n(X, A)`: the $`n`th relative homology group of $`X` and $`A \subseteq X`
- $`f_\ast`: the induced map on $`H_n(A_\bullet) \to H_n(B_\bullet)` of $`f \colon A_\bullet \to B_\bullet`, or $`H_n(X) \to H_n(Y)` for $`f \colon X \to Y`
- $`\chi(X)`: Euler characteristic of a space $`X`
- $`H^n(A^\bullet)`: the $`n`th cohomology group of a cochain complex $`A^\bullet`
- $`H^n(A_\bullet; G)`: the $`n`th cohomology group of the cochain complex obtained by applying $`\operatorname{Hom}(-, G)` to $`A_\bullet`
- $`H^n(X; G)`: the $`n`th cohomology group/ring of $`X` with $`G`-coefficients
- $`\widetilde H^n(X; G)`: the $`n`th reduced cohomology group/ring of $`X` with $`G`-coefficients
- $`H^n(X, A; G)`: the $`n`th relative cohomology group/ring of $`X` and $`A \subset X` with $`G`-coefficients
- $`f^\sharp`: the induced map on $`H^n(A^\bullet) \to H^n(B^\bullet)` of $`f \colon A^\bullet \to B^\bullet`, or $`H^n(X) \to H^n(Y)` for $`f \colon X \to Y`
- $`\operatorname{Ext}(-, -)`: the Ext functor
- $`\phi \smile \psi`: cup product of cochains $`\phi` and $`\psi`

# Category theory

Some common categories (in alphabetical order):

- $`\mathbf{Grp}`: category of groups
- $`\mathbf{CRing}`: category of commutative rings
- $`\mathbf{Top}`: category of topological spaces
- $`\mathbf{Top}_\ast`: category of pointed topological spaces
- $`\mathbf{Vect}_k`: category of $`k`-vector spaces
- $`\mathbf{FDVect}_k`: category of finite-dimensional vector spaces
- $`\mathbf{Set}`: category of sets
- $`\mathbf{hTop}`: category of topological spaces, whose morphisms are homotopy classes of maps
- $`\mathbf{hTop}_\ast`: pointed version of $`\mathbf{hTop}`
- $`\mathbf{hPairTop}`: category of pairs $`(X, A)` with morphisms being pair-homotopy equivalence classes
- $`\operatorname{Opens}(X)`: the category of open sets of $`X`, as a poset

Operations with categories:

- $`\operatorname{obj} \mathcal{A}`: objects of the category $`\mathcal{A}`
- $`\mathcal{A}^{\operatorname{op}}`: opposite category
- $`\mathcal{A} \times \mathcal{B}`: product category
- $`[\mathcal{A}, \mathcal{B}]`: category of functors from $`\mathcal{A}` to $`\mathcal{B}`
- $`\ker f \colon \operatorname{Ker} f \to B`: for $`f \colon A \to B`, categorical kernel
- $`\operatorname{coker} f \colon A \to \operatorname{Coker} f`: for $`f \colon A \to B`, categorical cokernel
- $`\operatorname{img} f \colon A \to \operatorname{Img} f`: for $`f \colon A \to B`, categorical image

# Differential geometry

- $`Df`: total derivative of $`f`
- $`(Df)_p`: total derivate of $`f` at point $`p`
- $`\frac{\partial f}{\partial e_i}`: $`i`th partial derivative
- $`\alpha_p`: evaluating a $`k`-form $`\alpha` at $`p`
- $`\int_c \alpha`: integration of the differential form $`\alpha` over a cell $`c`
- $`d\alpha`: exterior derivative of a $`k`-form $`\alpha`
- $`\phi^\ast \alpha`: pullback of $`k`-form $`\alpha` by $`\phi`

# Algebraic number theory

- $`\overline{\mathbb{Q}}`: ring of algebraic numbers
- $`\overline{\mathbb{Z}}`: ring of algebraic integers
- $`\overline{F}`: algebraic closure of a field $`F`
- $`N_{K/\mathbb{Q}}(\alpha)`: the norm of $`\alpha` in extension $`K/\mathbb{Q}`
- $`\operatorname{Tr}_{K/\mathbb{Q}}(\alpha)`: the trace of $`\alpha` in extension $`K/\mathbb{Q}`
- $`\mathcal{O}_K`: ring of integers in $`K`
- $`\mathfrak{a} + \mathfrak{b}`: sum of two ideals $`\mathfrak{a}` and $`\mathfrak{b}`
- $`\mathfrak{a}\mathfrak{b}`: ideal generated by products of elements in ideals $`\mathfrak{a}` and $`\mathfrak{b}`
- $`\mathfrak{a} \mid \mathfrak{b}`: ideal $`\mathfrak{a}` divides ideal $`\mathfrak{b}`
- $`\mathfrak{a}^{-1}`: the inverse of $`\mathfrak{a}` in the ideal group
- $`\operatorname{Norm}(I)`: ideal norm
- $`\operatorname{Cl}_K`: class group of $`K`
- $`\Delta_K`: discriminant of number field $`K`
- $`\mu(\mathcal{O}_K)`: set of roots of unity contained in $`\mathcal{O}_K`
- $`[K : F]`: degree of a field extension
- $`\operatorname{Aut}(K/F)`: set of field automorphisms of $`K` fixing $`F`
- $`\operatorname{Gal}(K/F)`: Galois group of $`K/F`
- $`D_\mathfrak{p}`: decomposition group of prime ideal $`\mathfrak{p}`
- $`I_\mathfrak{p}`: inertia group of prime ideal $`\mathfrak{p}`
- $`\operatorname{Frob}_\mathfrak{p}`: Frobenius element of $`\mathfrak{p}` (element of $`\operatorname{Gal}(K/\mathbb{Q})`)
- $`P_K(\mathfrak{m})`: ray of principal ideals of a modulus $`\mathfrak{m}`
- $`I_K(\mathfrak{m})`: fractional ideals of a modulus $`\mathfrak{m}`
- $`C_K(\mathfrak{m})`: ray class group of a modulus $`\mathfrak{m}`
- $`\left( \frac{L/K}{\bullet} \right)`: the Artin symbol
- $`\operatorname{Ram}(L/K)`: primes of $`K` ramifying in $`L`
- $`\mathfrak{f}(L/K)`: the conductor of $`L/K`

# Representation theory

- $`k[G]`: group algebra
- $`V \oplus W`: direct sum of representations $`V = (V, \rho_V)` and $`W = (W, \rho_W)` of an algebra $`A`
- $`V^\vee`: dual representation of a representation $`V = (V, \rho_V)`
- $`\operatorname{Reg}(A)`: regular representation of an algebra $`A`
- $`\operatorname{Hom}_{\operatorname{rep}}(V, W)`: algebra of morphisms $`V \to W` of representations
- $`\chi_V`: the character $`A \to k` attached to an $`A`-representation $`V`
- $`\operatorname{Classes}(G)`: set of conjugacy classes of $`G`
- $`\operatorname{FunCl}(G)`: the complex vector space of functions $`\operatorname{Classes}(G) \to \mathbb{C}`
- $`V \otimes W`: tensor product of representations $`V = (V, \rho_V)` and $`W = (W, \rho_W)` of a _group_ $`G` (rather than an algebra)
- $`\mathbb{C}_{\operatorname{triv}}`: the trivial representation
- $`\mathbb{C}_{\operatorname{sign}}`: the sign representation

# Algebraic geometry

- $`\mathbb{V}(-)`: vanishing locus of a set or ideal
- $`\mathbb{A}^n`: $`n`-dimensional (complex) affine space
- $`\sqrt I`: radical of an ideal $`I`
- $`\mathbb{C}[V]`: coordinate ring of an affine variety $`V`
- $`\mathcal{O}_V(U)`: ring of rational functions on $`U`
- $`D(f)`: distinguished open set
- $`\mathbb{CP}^n`: complex projective $`n`-space (ambient space for projective varieties)
- $`(x_0 : \dots : x_n)`: coordinates of projective space
- $`U_i`: standard affine charts
- $`\mathbb{V}_+(-)`: projective vanishing locus.
- $`h_I`, $`h_V`: Hilbert function of an ideal $`I` or projective variety $`V`
- $`\pi^\sharp` or $`\pi^\sharp_U`: the pullback $`\mathcal{O}_Y \to \mathcal{O}_X(\pi^{-1}(U))` obtained from $`\pi \colon X \to Y`
- $`\mathcal{F}_p`: the stalk of a (pre-)sheaf $`\mathcal{F}` at a point $`p`
- $`[s]_p`: the germ of $`s \in \mathcal{F}(U)` at the point $`p`
- $`\mathcal{O}_{X, p}`: shorthand for $`(\mathcal{O}_X)_p`.
- $`\mathcal{F}^{\operatorname{sh}}`: sheafification of pre-sheaf $`\mathcal{F}`
- $`\alpha_p \colon \mathcal{F}_p \to \mathcal{G}_p`: morphism of stalks obtained from $`\alpha \colon \mathcal{F} \to \mathcal{G}`
- $`\mathfrak{m}_{X, p}`: the maximal ideal of $`\mathcal{O}_{X, p}`
- $`\operatorname{Spec} A`: the spectrum of a ring $`A`
- $`S^{-1} A`: localization of ring $`A` at a set $`S`
- $`A[1/f]`: localization of ring $`A` away from element $`f`
- $`A_\mathfrak{p}`: localization of ring $`A` at prime ideal $`\mathfrak{p}`
- $`f(\mathfrak{p})`: the value of $`f` at $`\mathfrak{p}`, i.e. $`f \pmod{\mathfrak{p}}`
- $`\kappa(\mathfrak{p})`: the residue field of $`\operatorname{Spec} A` at the element $`\mathfrak{p}`.
- $`\pi^\sharp_{\mathfrak{p}}`: the induced map of stalks in $`\pi^\sharp`.

# Set theory

- $`\mathsf{ZFC}`: standard theory of ZFC
- $`\mathsf{ZFC}^+`: standard theory of ZFC, plus the sentence "there exists a strongly inaccessible cardinal"
- $`2^S` or $`\mathcal{P}(S)`: power set of $`S`
- $`A \land B`: $`A` and $`B`
- $`A \lor B`: $`A` or $`B`
- $`\neg A`: not $`A`
- $`V`: class of all sets (von Neumann universe)
- $`\omega`: the first infinite ordinal, also the set of nonnegative integers
- $`V_\alpha`: level of the von Neumann universe
- $`\operatorname{On}`: class of ordinals
- $`\bigcup A`: the union of elements inside $`A`
- $`A \approx B`: sets $`A` and $`B` are equinumerous
- $`\aleph_\alpha`: the aleph numbers
- $`\operatorname{cof} \lambda`: the cofinality of $`\lambda`
- $`\mathcal{M} \vDash \phi[b_1, \dots, b_n]`: model $`\mathcal{M}` satisfies sentence $`\phi` with parameters $`b_1, \dots, b_n`
- $`\Delta_n`, $`\Sigma_n`, $`\Pi_n`: levels of the Levy hierarchy
- $`\mathcal{M}_1 \subseteq \mathcal{M}_2`: $`\mathcal{M}_1` is a substructure of $`\mathcal{M}_2`
- $`\mathcal{M}_1 \prec \mathcal{M}_2`: $`\mathcal{M}_1` is an elementary substructure of $`\mathcal{M}_2`
- $`p \parallel q`: elements $`p` and $`q` of a poset $`\mathbb{P}` are compatible
- $`p \perp q`: elements $`p` and $`q` of a poset $`\mathbb{P}` are incompatible
- $`\operatorname{Name}_\alpha`: the hierarchy of $`\mathbb{P}`-names
- $`\tau^G`: interpretation of a name $`\tau` by filter $`G`
- $`M[G]`: the model obtained from a forcing poset $`G \subseteq \mathbb{P}`
- $`p \Vdash \varphi(\sigma_1, \dots, \sigma_n)`: $`p \in \mathbb{P}` forces the sentence $`\varphi`
- $`\check x`: the name giving an $`x \in M` when interpreted
- $`\dot G`: the name giving $`G` when interpreted
