import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Hints and solutions: Algebra, Topology, and Linear Algebra" =>

%%%
file := "Hints-and-solutions-Algebra-Topology-Linear-Algebra"
%%%

This appendix collects the hints and solution sketches for the problems in the algebra, topology, and linear algebra chapters.
Each entry names its problem and gives whichever of a hint and a solution the source provides.



# Groups

*What is the joke in the following figure?*
(Source: {cite}`img:snsd`.)

:::figure "love-proper-isomorphic-subgroup.jpg"
:::

_Hint._ Orders.

_Solution._ The point is that $`\heartsuit` is a group, $`G \subsetneq \heartsuit` a subgroup and $`G \cong \heartsuit`.
This can only occur if $`\left\lvert \heartsuit \right\rvert = \infty`;
otherwise, a proper subgroup would have strictly smaller size than the original.

*Prove Lagrange's theorem for orders in the special case that $`G` is a finite abelian group.*

_Hint._ Copy the proof of Fermat's little theorem, using
an earlier result.

_Solution._ Let $`\{g_1, g_2, \dots, g_n\}` denote the elements of $`G`.
For any $`g \in G`, this is the same as the set $`\{gg_1, \dots, gg_n\}`.
Taking the entire product and exploiting commutativity gives
$`g^n \cdot g_1g_2 \dots g_n = g_1g_2 \dots g_n`, hence $`g^n=1`.

*Show that $`D_6 \cong S_3` but $`D_{24} \not\cong S_4`.*

_Hint._ For the former,
decide where the isomorphism should send $`r` and $`s`,
and the rest will follow through.
For the latter, look at orders.

_Solution._ One can check manually that $`D_6 \cong S_3`,
using the map $`r \mapsto (1 \; 2 \; 3)` and $`s \mapsto (1 \; 2)`.
(The right-hand sides are in \`\`cycle notation",
as mentioned in an earlier result.)
On the other hand $`D_{24}` contains an element of order $`12`
while $`S_4` does not.

*Let $`p` be a prime.*

_Hint._ Generated groups.

_Solution._ Let $`G` be a group of order $`p`, and $`1 \neq g \in G`.
Look at the group $`H` generated by $`g` and use Lagrange's theorem.

*Let $`G` be a finite group.*

_Hint._ Use $`n = \left\lvert G \right\rvert`.

_Solution._ The idea is that each element $`g \in G` can be thought of as a permutation
$`G \to G` by $`x \mapsto gx`.

*Find the smallest integer $`n` such that the symmetric group $`S_n` has a subgroup isomorphic to the dihedral group $`D_{2018}` of order $`2018`.*

_Hint._ For the lower bound, consider orders (note that $`1009` is prime).
For the upper bound, consider a $`1009`-gon.

_Solution._ The answer is $`n = 1009`.
This solution uses the fact that $`1009` is prime.

To show that no smaller $`m` is possible,
note that $`D_{2018}` has elements of order $`1009`, a prime.
Since $`S_n` has no elements of this order for $`n < 1009`, we need $`n \ge 1009`.

To give a construction from $`n = 1009`,
note that $`D_{2018}` can be thought of the symmetries of a $`1009`-gon.
If one labels the vertices of the $`1009`-gon by $`S \coloneqq \{1,2,\dots,1009\}`,
then elements of $`D_{2018}` induces permutations on $`S`,
and the set of permutations achieved is the desired subgroup.

*IMO SL 2005 C5.*

_Hint._ Draw inspiration from $`D_6`.

_Solution._ We have $`www = bb`, $`bww = wb`, $`wwb = bw`, $`bwb = ww`.
Interpret these as elements of $`D_6`.

*Let $`p` be a prime and $`F_1 = F_2 = 1`, $`F_{n+2} = F_{n+1} + F_n` be the Fibonacci sequence.*

_Hint._ Look at the group of $`2 \times 2` matrices mod $`p`
with determinant $`\pm 1`.

_Solution._ Look at the group $`G` of $`2 \times 2` matrices mod $`p`
with determinant $`\pm 1` (whose entries are the integers mod $`p`).
Let $`g = \begin{bmatrix} 1 & 1 \\ 1 & 0 \end{bmatrix}`
and then use $`g^{\left\lvert G \right\rvert} = 1_G`.


# Metric spaces

*Consider $`\mathbb{Q}` and $`\mathbb{N}` as metric spaces (each with the obvious metric $`d(x,y) = |x-y|`).*

_Hint._ No. There is not even a continuous injective map from $`\mathbb{Q}` to $`\mathbb{N}`.

_Solution._ Two possible approaches, one using metric definition
and one using open sets.

Metric approach: I claim there is no injective map from $`\mathbb{Q}` to $`\mathbb{N}`
that is continuous. Indeed, suppose $`f` was such a map and $`f(x) = n`.
Then, choose $`\varepsilon = 1/2`.
There should be a $`\delta > 0` such that everything with $`\delta` of $`x`
in $`\mathbb{Q}` should land within $`\varepsilon` of $`n \in \mathbb{N}` --- i.e., is equal to $`n`.
This is a blatant contradiction of injectivity.

Open set approach: In $`\mathbb{Q}`, no singleton set is open,
whereas in $`\mathbb{N}`, they all are (in fact $`\mathbb{N}` is discrete).
As you'll see at the start of an earlier result,
with the new and improved definition of \`\`homeomorphism",
we found out that the structure of open sets on $`\mathbb{Q}` and $`\mathbb{N}` are different,
so they are not homeomorphic.

*Continuity of arithmetic continued.*

_Hint._ You can do this with bare hands.
You can also use composition.

_Solution._ For subtraction, the map $`x \mapsto -x` is continuous
so you can view it as a composed map

Similarly, if you are willing to believe $`x \mapsto 1/x`
is a continuous function, then division is composition

If for some reason you are suspicious that $`x \mapsto 1/x` is continuous,
then here is a proof using sequential continuity.
Suppose $`x_n \to x` with $`x_n > 0` and $`x > 0`
(since $`x` needs to be in $`\mathbb{R}_{>0}` too).
Then
$$`\left\lvert \frac{1}{x} - \frac 1{x_n} \right\rvert = \frac{\left\lvert x_n-x \right\rvert}{\left\lvert x x_n \right\rvert}.`

If $`n` is large enough, then $`\left\lvert x_n \right\rvert > x/2`;
so the denominator is at least $`x^2/2`,
and hence the whole fraction is at most
$`\frac{2}{x^2} \left\lvert x_n-x \right\rvert`,
which tends to zero as $`n \to \infty`.

*Exhibit a function $`f \colon \mathbb{R} \to \mathbb{R}` such that $`f` is continuous at $`x \in \mathbb{R}` if and only if $`x=0`.*

_Hint._ $`\pm x` for good choices of $`\pm`.

_Solution._ Let $`f(x) = x` for $`x \in \mathbb{Q}` and $`f(x) = -x` for irrational $`x`.

*Prove that a function $`f \colon \mathbb{R} \to \mathbb{R}` which is strictly increasing must be continuous at some point.*

_Hint._ Project gaps onto the $`y`-axis.
Use the fact that uncountably many positive reals cannot have finite sum.

_Solution._ Assume for contradiction it is completely discontinuous;
by scaling set $`f(0) = 0`, $`f(1) = 1` and focus just on $`f \colon [0,1] \to [0,1]`.
Since it's discontinuous everywhere,
for every $`x \in [0,1]` there's an $`\varepsilon_x > 0`
such that the continuity condition fails.
Since the function is strictly increasing,
that can only happen if the
function misses all $`y`-values in the interval
$`(f(x)-\varepsilon_x, f(x))` or $`(f(x), f(x)+\varepsilon_x)` (or both).

Projecting these missing intervals to the $`y`-axis you find uncountably
many intervals (one for each $`x \in [0,1]`) all of which are disjoint.
In particular, summing the $`\varepsilon_x` you get that a sum of uncountably
many positive reals is $`1`.

But in general it isn't possible for an uncountable family $`\mathcal F`
of positive reals to have finite sum.
Indeed, just classify the reals into buckets $`\frac1k \le x < \frac1{k-1}`.
If the sum is actually finite then each bucket is finite,
so the collection $`\mathcal F` must be countable, contradiction.

*Someone on the Internet posted the question \`\`is $`1/x` a continuous function?", leading to great controversy on Twitter.*

_Hint._ First answer the following question: \`\`is $`1/x` a function?".

_Solution._ Like most Internet \`\`debates" about math,
the question revolves around sloppy definitions.
The original posed question (which is ill-formed) is
\\begin\{quote\}
(1) Is $`1/x` a continuous function?
\\end\{quote\}
To make it well-formed, I want to first bring up the question:
\\begin\{quote\}
(2) Is $`1/x` a function?
\\end\{quote\}
Technically, this question is also ill-formed because it never specifies
the domain of the function, which is part of the data needed to specify a function.
One reasonable guess what the asker meant would be $`\mathbb{R} \setminus \{0\}`,
i.e.\\ the set of nonzero real numbers, in which case we get the question
\\begin\{quote\}
(2') Does $`1/x` define a function from $`\mathbb{R} \setminus \{0\}` to $`\mathbb{R}`?
\\end\{quote\}
which has the firm answer YES.

On the other hand, it does not make sense to try to define $`1/x`
as a function on $`\mathbb{R}`.
The definition a function requires you to specify an output value for every input,
so at least if you want a real-valued function (Those of you
that know what $`\mathbb{RP}^1` is could consider it as a function
$`\mathbb{RP}^1 \to \mathbb{RP}^1` if you insisted;
but it's continuous in that case too.),
there isn't any way to construe $`1/x` as a function on all of $`\mathbb{R}`.

Now, returning to (1), we can now ask a well-formed question
\\begin\{quote\}
(1') Does $`1/x` describe a continuous function from $`\mathbb{R} \setminus \{0\} \to \mathbb{R}`?
\\end\{quote\}
which again has the firm answer YES.

Of course, you could also consider a question like
\`\`does $`1/x` describe a continuous function $`\mathbb{R} \to \mathbb{R}`?".
However, this feels misleading:
it would be like asking \`\`is $`\sqrt{2}` an even integer?".
The question doesn't make sense to begin with because $`\sqrt2` isn't an integer,
and \`\`even" is an adjective used for integers,
so trying to ask whether it applies to $`\sqrt2` is a [type-error](https://qchu.wordpress.com/2013/05/28/the-type-system-of-mathematics/).
Similarly, \`\`continuous" is an adjective used for functions;
it doesn't make sense to ask whether it applies to something that isn't a function.

See [https://twitter.com/davidcpvm/status/1481024944830046209](https://twitter.com/davidcpvm/status/1481024944830046209)
for the Twitter post (in Spanish) and the accompanying Reddit post (one of several)
at [https://www.reddit.com/r/math/comments/s82vf8](https://www.reddit.com/r/math/comments/s82vf8).


# Homomorphisms and quotient groups

*18.701 at MIT.*

_Hint._ Write it out: $`\phi(ab) = \phi(a)\phi(b)`.

_Solution._ Abelian groups: $`abab =a^2b^2 \iff ab= ba`.

*Consider the dihedral group $`G = D_{10}`.*

_Hint._ Yes, no.

_Solution._ Yes to (a): you can check this directly
from the $`ghg^{-1}` definition.
For example, for (a)
it is enough to compute $`(r^a s) r^n (r^a s)^{-1} = r^{-n} \in H`.
The quotient group is $`\mathbb{Z}/2\mathbb{Z}`.

The answer is no for (b) by following
an earlier result.

*Does $`S_4` have a normal subgroup of order $`3`.*

_Hint._ No.

_Solution._ A subgroup of order $`3` must be generated by
an element of order $`3`, since $`3` is prime.
So we may assume WLOG that $`H = \left< (1\; 2 \; 3) \right>`
(by renaming elements appropriately).
But then let $`g = (3 \; 4)`; one can check $`gHg^{-1} \neq H`.

*Let $`G` and $`H` be finite groups, where $`\left\lvert G \right\rvert = 1000` and $`\left\lvert H \right\rvert = 999`.*

_Hint._ $`\gcd(1000,999)=1`.

_Solution._ $`G/\operatorname{ker} G` is isomorphic to a subgroup of $`H`.
The order of the former divides $`1000`;
the order of the latter divides $`999`.
This can only occur if $`G / \operatorname{ker} G = \{1\}`
so $`\operatorname{ker} G = G`.

*Find a non-abelian group $`G` such that every subgroup of $`G` is normal.*

_Hint._ Find an example of order $`8`.

_Solution._ Quaternion group.

*PRIMES entrance exam, 2018.*

_Hint._ Try to show $`G` is the dihedral group of order $`18`.
There is not much group theory content here --- just manipulation.

_Solution._ The answer is $`|G| = 18`.

First, observe that by induction we have

$$`a^n c = ca^{8n}`

for all $`n \ge 1`.
We then note that

$$`\begin{aligned}a(bc) &= (ab)c \\ a \cdot ca^6 &= c^2 a^4 \cdot c \\ c a^8 \cdot a^6 &= c^2 a^4 \cdot c \\ a^{14} &= c(a^4c) = c^2 a^{32}.\end{aligned}`

Hence we conclude $`c^2 = a^{-18}`.
Then $`ab = c^2a^4 \implies b = a^{-15}`.

In that case, since $`c^{2018} = b^{2019}`,
we conclude $`1 = a^{- 1009 \cdot 18 + 2019 \cdot 15} = a^{12123}`.
Finally,

$$`\begin{aligned}bc &= ca^6 \\ a^{-15} c &= ca^6 \\ a^{-15} c^2 &= c(a^6c) = c^2 a^{48} \\ a^{-33} &= a^{30} \\ \implies a^{63} &= 1.\end{aligned}`

Since $`\gcd(12123, 63) = 9`, we find $`a^9 = 1`, hence finally $`c^2 = 1`.
So the presentation above simplifies to

$$`G = \left< a,c \mid a^9=c^2=1, \; ac = ca^{-1} \right>`

which is the presentation of the dihedral group of order $`18`.

This completes the proof.

*Homophony group.*

_Hint._ Get yourself a list of English homophones, I guess.
Don't try too hard.
Letter $`v` is the worst; maybe $`felt = veldt`?

_Solution._ You can find many solutions by searching \`\`homophone group";
one is [https://math.stackexchange.com/q/843966/229197](https://math.stackexchange.com/q/843966/229197).


# Rings and ideals

*The ring $`R = \mathbb{R}[x] / (x^2+1)` is one that you've seen before.*

_Hint._ $`R = \mathbb{R}[i]`.

_Solution._ This is just $`\mathbb{R}[i] = \mathbb{C}`.
The isomorphism is given by $`x \mapsto i`,
which has kernel $`(x^2+1)`.

*Show that $`\mathbb{C}[x] / (x^2-x) \cong \mathbb{C} \times \mathbb{C}`.*

_Hint._ Show that the map

$$`\begin{aligned}\mathbb{C}[x] &\to \mathbb{C} \times \mathbb{C} \\ p &\mapsto \left( p(0), p(1) \right)\end{aligned}`

is surjective and calculate its kernel.

_Solution._ Note that the map

$$`\begin{aligned}\mathbb{C}[x] &\to \mathbb{C} \times \mathbb{C} \\ p &\mapsto \left( p(0), p(1) \right)\end{aligned}`

is indeed a surjective ring homomorphism.
Its kernel consists of those polynomials $`p` such that $`p(0) = p(1) = 0`;
this is the set of polynomials divisible by both $`x` and $`x-1`, so it is $`x(x-1)`.

*Let $`R` be a ring.*

_Hint._ For (b) homomorphism is uniquely determined by the choice of $`\psi(x) \in R`

*.*

_Hint._

_Solution._


# Flavors of rings

*Consider the ring $$`\mathbb{Q}[\sqrt2] = \left\{ a + b\sqrt2 \mid a,b \in \mathbb{Q} \right\}.` Is it a field.*

_Hint._ Yes.

*Homomorphisms from fields are injective.*

_Hint._ The kernel is an ideal of $`K`!

*Pre-image of prime ideals.*

_Hint._ This is just a definition chase.

_Solution._ Consider $`ab \in \phi^{-1}(I)`,
meaning $`\phi(ab) = \phi(a) \phi(b) \in I`.
Since $`I` is prime, either $`\phi(a) \in I` or $`\phi(b) \in I`.
In the former case we get $`a \in \phi^{-1}(I)` as needed;
the latter case we get $`b \in \phi^{-1}(I)`.

*Let $`R` be an integral domain with finitely many elements.*

_Hint._ Fermat's little theorem type argument;
cancellation holds in integral domains.

_Solution._ Let $`x \in R` with $`x \neq 0`.
Look at the powers $`x`, $`x^2`, \….
By pigeonhole, eventually two of them coincide.
So assume $`x^m = x^n` where $`m < n`, or equivalently

$$`0 = x \cdot x \cdot \dots \cdot x \cdot \left( x^{n-m} - 1 \right).`

Since $`x \neq 0`, we get $`x^{n-m} - 1 = 0`,
or $`x^{n-m} = 1`.
So $`x^{n-m-1}` is an inverse for $`x`.

This means every nonzero element has an inverse,
ergo $`R` is a field.

*Krull's theorem.*

_Hint._ Just keep on adding in elements to get an ascending chain.

_Solution._ For part (b), look at the poset of proper ideals.
Apply Zorn's lemma (again using a union trick to verify the condition;
be sure to verify that the union is proper!).
In part (a) we are given no ascending infinite chains,
so no need to use Zorn's lemma.

*$`\operatorname{Spec} k[x]`.*

_Hint._ Use the fact that both are PID's.

_Solution._ The ideal $`(0)` is of course prime in both.
Also, both rings are PID's.

For $`\mathbb{C}[x]` we get a prime ideal $`(x-z)` for each $`z \in \mathbb{C}`.

For $`\mathbb{R}[x]` a prime ideal $`(x-a)` for each $`a \in \mathbb{R}`
and a prime ideal $`(x^2 - ax + b)` for each quadratic
with two conjugate non-real roots.

*How many prime ideals of $`\mathbb{Z}[\sqrt{2017}]` are not maximal ideals.*

_Hint._ Show that the quotient $`\mathbb{Z}[\sqrt{2017}]/I` has finitely many elements
for any nonzero prime ideal $`I`.
Therefore, the quotient is an integral domain, it is also a field,
and thus $`I` was a maximal ideal.

_Solution._ Only one; the ideal $`(0)` which is not maximal.
We contend every other prime ideal is maximal.

Indeed, let $`I` be any ideal (not necessarily prime),
and let $`a + b \sqrt{2017}` be a nonzero element of it.
Then $`I` also contains $`(a^2-2017b^2)`.
That means when taking modulo $`I` we may take modulo the integer
$`n \coloneqq |a^2-2017b^2| \neq 0`.

So every element in $`R` is equivalent modulo $`I`
to an element of the form $`x + y \sqrt{2017}`,
where $`x,y \in \{0, 1, \dots, n-1\}`.
In other words, the quotient $`R/I` has at most finitely many elements.

When $`I` is prime, it follows $`R/I` is an integral domain, too.
An integral domain with finitely many elements must be a field.
Hence, from $`R/I` being a field, we conclude $`I` is maximal.

*Let $`R` denote the set of rational numbers $`q` such that, when $`q` is written in lowest terms, the denominator is not a multiple of $`5`.*

_Solution._ The ideals are $`(0)`, $`(1) = R`, and $`(5^n) = 5^n R` for each $`n \ge 1`.
The ideal $`(0)` is prime and the ideal $`(5)` is maximal
(because the quotient $`R/(5) \cong \mathbb{F}_5` is a field).


# Properties of metric spaces

*Banach fixed point theorem.*

_Hint._ The main task is to show there exists some fixed point.
Start at some point $`x_0` and consider the sequence
$`x_1 = T(x_0)`, $`x_2 = T(x_1)`, $`x_3 = T(x_2)`, \…, and so on.

_Solution._ Uniqueness of the fixed point follows from noting that if $`T(p) = p` and $`T(q) = q`
and $`p \neq q` then we get a direct contradiction by plugging this into the given statement.
Hence the main task is to show there exists some fixed point.

Start with any point $`x_0`.
Let $`x_1 = T(x_0)`, $`x_2 = T(x_1)`, $`x_3 = T(x_2)`, \…, and so on.
We contend that $`(x_0, x_1, x_2, \dots)` is a Cauchy sequence.
Indeed, if we let $`r \coloneqq 0.999 < 1` and $`c \coloneqq d(x_0, x_1)`, then

$$`\begin{aligned}d(x_1, x_2) &< r \cdot c \\ d(x_2, x_3) &< r^2 \cdot c \\ d(x_3, x_4) &< r^3 \cdot c \\ &\;\;\vdots \\\end{aligned}`

and so for large $`M < N` we have

$$`d(x_M, x_N) < \left( r^M + r^{M+1} + \dots + r^N \right) \cdot c < \frac{r^M}{1-r} \cdot c`

which tends to zero once $`M` is large enough.

Hence, because $`M` is complete, the sequence must converge to some limit $`x`.
Because $`T` is continuous, we get

$$`T(x) = T\left( \lim_{n \to \infty} x_n \right) = \lim_{n \to \infty} T(x_n) = \lim_{n \to \infty} x_{n+1} = x`

as desired.

*Henning Makholm, on [math.SE](https://math.stackexchange.com/a/3051746/229197).*

_Hint._ (a): $`M` is complete and bounded
but not totally bounded. $`N` is all no.
For (b) show that $`M \cong \mathbb{R} \cong N`.

_Solution._ Part (a) is essentially by definition.
The space $`M` is bounded since no distances exceed $`1`,
but not totally bounded since we can't cover $`M`
with finitely many $`\tfrac12`-neighborhoods.
The space $`M` is complete since a sequence of real
numbers converges in $`M` if it converges in the usual sense.
As for $`N`, the sequence $`-1`, $`-2`, \…\\ is Cauchy
but fails to converge; and it is obviously not bounded.

To show (b), the identity map (!)\\ is an homeomorphism $`M \cong \mathbb{R}`
and $`\mathbb{R} \cong N`, since it is continuous.

This illustrates that $`M \cong N` despite the fact
that $`M` is both complete and bounded
but $`N` is neither complete nor bounded.
On the other hand, we will later see that complete
and totally bounded implies compact,
which is a very strong property preserved under homeomorphism.

*Completion of a metric space.*

_Hint._ As a set, we let $`\overline{M}` be the set of Cauchy
sequences $`(x_n)` in $`M`, modulo the relation that
$`(x_n) \sim (y_n)` if $`\lim_n d(x_n, y_n) = 0`.

*Show that a metric space is totally bounded if and only if any sequence has a Cauchy subsequence.*

_Solution._ See [https://math.stackexchange.com/q/556150/229197](https://math.stackexchange.com/q/556150/229197).

*Prove that $`\mathbb{Q}` is not homeomorphic to any complete metric space.*

_Hint._ The standard solution seems to be
via the so-called \`\`Baire category theorem".


# Topological spaces

*Pugh, Exercise 2.56.*

_Hint._ Let $`p` be any point.
If there is a real number $`r` such that $`d(p,q) \neq r` for any $`q \in M`,
then the $`r`-neighborhood of $`p` is clopen.

*Let $`X` be a topological space.*

_Hint._ (a) is yes, and (b) is no even for metric spaces.
In fact, a totally disconnected space is one for which
every connected component consists of only a single point,
and there are examples of totally disconnected metric spaces with
non-discrete topologies.

_Solution._ Part (a) is straightforward:
assume for contradiction that the connected component of $`p` is
a disjoint union $`U \sqcup V` of two nonempty sets open in $`X`.
WLOG, assume $`x \in U`
Let $`S` be one of the subspaces containing $`X` that intersects $`V`.
Then $`S = (S \cap U) \sqcup (S \cap V)` rewrites $`S` as the disjoint union
of two sets which are open in $`S`, contradicting the connectedness of $`S`.

(Though note that as $`S` is not necessarily open in $`X`,
the sets $`S \cap U` and $`S \cap V` are not necessarily open in $`X` either.)

For (b), a counterexample is to take any totally disconnected space
like the Cantor set or the $`p`-adic numbers.

*Furstenberg.*

_Hint._ Note that $`p\mathbb{Z}` is closed for each $`p`.
If there were finitely many primes, then
$`\bigcup p\mathbb{Z} = \mathbb{Z} \setminus \{-1,1\}` would have to be closed;
i.e.\\ $`\{-1,1\}` would be open, but all open sets here are infinite.

*Prove that the evenly spaced integer topology on $`\mathbb{Z}` is metrizable.*

_Hint._ The balls at $`0` should be of the form $`n! \cdot \mathbb{Z}`.

_Solution._ Let $`d(x,y) = 2017^{-n}`, where $`n` is the largest integer
such that $`n!` divides $`\left\lvert x-y \right\rvert`.

*We know that any open set $`U \subseteq \mathbb{R}` is a union of open intervals (allowing $`\pm\infty` as endpoints).*

_Hint._ Appeal to $`\mathbb{Q}`.

_Solution._ You can pick a rational number in each interval and
there are only countably many rational numbers. Done!


# Compactness

*Show that the closed interval $`[0,1]` and open interval $`(0,1)` are not homeomorphic.*

_Hint._ $`[0,1]` is compact.

_Solution._ Compactness is preserved under homeomorphism,
but $`[0,1]` is compact while $`(0,1)` is not.

*Let $`X` be a topological space with the discrete topology.*

_Hint._ If and only if it is finite.

*Compact Implies Bounded.*

_Hint._

*Tychonoff's theorem.*

_Hint._ Suppose $`p_i = (x_i, y_i)` is a sequence in $`X \times Y` ($`i=1,2,\dots`).
Take a sub-sequence such that the $`x`-coordinate converges
(throwing out some terms).
Then take a sub-sequence of that sub-sequence
such that $`y`-coordinate converges (throwing out more terms).

_Solution._ Suppose $`p_i = (x_i, y_i)` is a sequence in $`X \times Y` ($`i=1,2,\dots`).
Looking on the $`X` side, some subsequence converges:
for the sake of illustration say it's $`x_1, x_4, x_9, x_{16}, \dots \to x`.
Then look at the corresponding sequence $`y_1, y_4, y_9, y_{16}, \dots`.
Using compactness of $`Y`, it has a convergent subsequence, say
$`y_1, y_{16}, y_{81}, y_{256}, \dots \to y`.
Then $`p_1, p_{16}, p_{81}, \dots` will converge to $`(x,y)`.

One common mistake is to just conclude
that $`(x_n)` has a convergent subsequence
and that $`(y_n)` does too.
But these sequences could be totally unrelated.
For this proof to work,
you do need to apply compactness of $`X` first,
and then compactness of $`Y` on the resulting filtered
sequence like we did here.

*Bolzano-Weierstraß theorem for general metric spaces.*

_Hint._ Mimic the proof of an earlier result.
The totally bounded condition lets you do Pigeonhole.

*Let $`M = (M,d)` be a bounded metric space.*

_Hint._ Assuming $`M` is not compact, construct an
unbounded continuous function $`F \colon M \to \mathbb{R}`.
Once such a function $`F` is defined, the metric

$$`d'(x, y) \coloneqq d(x, y) + \lvert F(x) - F(y) \rvert`

will establish the contrapositive of the problem.

_Solution._ The following solution is due to Royce Yao.
We show the contrapositive:
if $`M` is not compact, then there exists a homeomorphic unbounded metric.

The main step is to construction
an unbounded continuous function $`F \colon M \to \mathbb{R}`.
Once such a function $`F` is defined, the metric

$$`d'(x, y) \coloneqq d(x, y) + \lvert F(x) - F(y) \rvert`

will solve the problem.

So, let $`a_1`, $`a_2`, \…\\ be a sequence in $`M`
with no convergent subsequence.
For each $`a_i`, there exists a radius $`r_i` such that

$$`0 < r_i < \frac{1}{2} \min_{j} d(a_i, a_j)`

Define $`C_i` as an open ball at $`a_i` with radius $`r_i`.
Note that every ball is disjoint.
Then, we define $`F` as follow

$$`F(x) = \begin{cases} 0 & x \not\in C_i \\ \frac{i}{r_1}(r_i - d(x, a_i)) & x \in C_i \end{cases}`

which can be seen to be continuous.
Then, $`F` is unbounded by considering $`F(a_i)` as $`i` goes to infinity.

*In this problem a \`\`circle" refers to the boundary of a disk with nonzero radius.*

_Hint._ The answer to both parts is no.

For (a) use an earlier result.

For (b), color each circle in the partition
based on whether it contains $`p` but not $`q`,
$`q` but not $`p`, or both.

_Solution._ Part (a) follows by the Cantor intersection theorem
(an earlier result).
Assume for contradiction such a partition existed.
Take any of the circles $`C_0`, and let $`K_0` denote the closed disk
with boundary $`C_0`.
Now take the circle $`C_1` passing through the center of $`C_0`,
and let $`K_1` denote the closed disk with boundary $`C_1`.
If we repeat in this way,
we get a nested sequence $`K_0 \supseteq K_1 \supseteq \dots`
and the radii of $`C_i` approach zero
(since each is at most half the previous once).
Thus some point $`p` lies in $`\bigcap_n K_n` which is impossible.

Now for part (b),
again assume for contradiction a partition into circles exists.
Color a circle magenta if it contains $`p` but not $`q`
and color a circle cyan if it contains $`q` but not $`p`.
Color $`p` itself magenta and $`q` itself cyan as well.
Finally, color a circle neon yellow if it contains both $`p` and $`q`.
(When we refer to coloring a circle,
we mean to color all the points on it.)

By repeating the argument in (a) there are no circles
enclosing neither $`p` nor $`q`.
Hence every point is either magenta, cyan, or neon yellow.
Now note that given any magenta circle,
its interior is completely magenta.
Actually, the magenta circles can be totally ordered
by inclusion (since they can't intersect).
So we consider two cases:

- If there is a magenta circle which is maximal by inclusion
(i.e.\\ a magenta circle not contained in any other magenta circle)
then the set of all magenta points is just a closed disk.

- If there is no such magenta circle,
then the set of magenta points can also be expressed
as the union over all magenta circles of their interiors.
This is a union of open sets, so it is itself open.

We conclude the set of magenta points is
either a closed disk or an open set.
Similarly for the set of cyan points.
Moreover, the set of such points is convex.

To finish the problem:

- Suppose there are no neon yellow points.
If the magenta points form a closed disk,
then the cyan points are $`\mathbb R^2` minus a disk which is not convex.
Contradiction. So the magenta points must be open.
Similarly the cyan points must be open.
But $`\mathbb R^2` is connected,
so it can't be written as the union of two open sets.

- Now suppose there are neon yellow points.
We claim there is a neon yellow circle minimal by inclusion.
If not, then repeat the argument of (a) to get a contradiction,
since any neon yellow circle must have diameter the distance from $`p` to $`q`.
So we can find a neon yellow circle $`\mathscr C` whose
interior is all magenta and cyan.
Now repeat the argument of the previous part,
replacing $`\mathbb R^2` by the interior of $`\mathscr C`.


# Vector spaces

*Let $`V` and $`W` be finite-dimensional vector spaces with nonzero dimension, and consider linear maps $`T \colon V \to W`.*

_Hint._ Use the rank-nullity theorem.
Also consider the zero map.

_Solution._ Each \`\`never" is by the rank-nullity theorem.
Each counterexample is obtained by the zero map
sending every element of $`V` to zero;
this map is certainly neither injective or surjective.

*Equal dimension vector spaces are usually isomorphisms.*

_Solution._ It essentially follows by an earlier result.

*Multiplication by $`\sqrt5`.*

_Hint._ $`a + b \sqrt 5 \mapsto \sqrt 5 a + 5b`.

_Solution._ Since $`1 \mapsto \sqrt5` and $`\sqrt5 \mapsto 5`,
the matrix is
$`\begin{bmatrix} 0 & 5 \\ 1 & 0 \end{bmatrix}`.

*Putnam 2003.*

_Hint._ Plug in $`y = -1, 0, 1`. Use dimensions of $`\mathbb{R}[x]`.

*TSTST 2014.*

_Hint._ Interpret as $`V \oplus V \to W` for suitable $`V`, $`W`.

_Solution._ Let $`V` be the space of real polynomials with degree at most $`d/2`
(which has dimension $`1 + \left\lfloor d/2 \right\rfloor`),
and $`W` be the space of real polynomials modulo $`P` (which has dimension $`d`).
Then $`\dim (V \oplus V) > \dim W`.
So the linear map $`V \oplus V \to W` by $`(A,B) \mapsto A + Q \cdot B`
has a kernel of positive dimension
(by rank-nullity, for example).

*Let $`V` be a finite dimensional vector space.*

_Hint._ Use the fact that the infinite chain of subspaces

$$`\operatorname{ker} T \subseteq \operatorname{ker} T^2 \subseteq \operatorname{ker} T^3 \subseteq \dots`

and the similar chain for $`\operatorname{img} T` must eventually stabilize
(for dimension reasons).

_Solution._ Consider

$$`\{0\} \subsetneq \operatorname{ker} S \subseteq \operatorname{ker} S^2 \subseteq \operatorname{ker} S^3 \subseteq \dots and V \supsetneq \operatorname{img} S \supseteq \operatorname{img} S^2 \supseteq \operatorname{img} S^3 \supseteq \dots.`

For dimension reasons, these subspaces must eventually stabilize:
for some large integer $`N`,
$`\operatorname{ker} T^N = \operatorname{ker} T^{N+1} = \dots`
and $`\operatorname{img} T^N = \operatorname{img} T^{N+1} = \operatorname{img} T^{N+2} = \dots`.
When this happens, $`\operatorname{ker} T^N \bigcap \operatorname{img} T^N = \{0\}`,
since $`T^N` is an automorphism of $`\operatorname{img} T^N`.
On the other hand, by Rank-Nullity we also have
$`\dim \operatorname{ker} T^N + \dim \operatorname{img} T^n = \dim V`.
Thus for dimension reasons, $`V = \operatorname{ker} T^N \oplus \operatorname{img} T^N`.


# Eigen-things

*Sum of algebraic multiplicities.*

_Solution._ It's just $`\dim V = 2018`.
After all, you are adding the dimensions of the Jordan blocks\…

*The word \`\`diagonalizable".*

_Solution._ (a): if you express $`T` as a matrix in such a basis,
one gets a diagonal matrix.
(b): this is just saying each Jordan block has dimension $`1`,
which is what we wanted.
(We are implicitly using uniqueness of Jordan form here.)

*Switcharoo.*

_Solution._ The $`+1` eigenspace is spanned by $`e_1+e_2`.
The $`-1` eigenspace is spanned by $`e_1-e_2`.

*Suppose $`T \colon \mathbb{C}^{\oplus 2} \to \mathbb{C}^{\oplus 2}` is a linear map of $`\mathbb{C}`-vector spaces such that….*

_Hint._ The answer is yes.
In fact, the result is true if $`\mathbb{C}^{\oplus 2}` is any finite-dimensional
$`\mathbb{C}`-vector space.

*Writing a polynomial backwards.*

_Solution._ The $`+1` eigenspace is spanned by $`1+x^2` and $`x`.
The $`-1` eigenspace is spanned by $`1-x^2`.

*Differentiation of polynomials.*

_Hint._ Only $`0` is.
Look at degree.

_Solution._ Constant functions differentiate to zero,
and these are the only $`0`-eigenvectors.
There can be no other eigenvectors,
since if $`\operatorname{deg} p > 0` then $`\operatorname{deg} p' = \operatorname{deg} p - 1`,
so if $`p'` is a constant real multiple of $`p`
we must have $`p' = 0`, ergo $`p` is constant.

*Differentiation of functions.*

_Hint._ All of them are!

_Solution._ $`e^{cx}` is an example of a $`c`-eigenvector for every $`c`.
If you know differential equations,
these generate all examples!


# Dual space and trace

*Trace is sum of eigenvalues.*

_Hint._ Follows by writing $`T` in an eigenbasis:
then the diagonal entries are the eigenvalues.

_Solution._ We saw already the trace is always the sum of the eigenvalues, in any basis.
In particular, choosing the Jordan form basis from the previous chapter
gives the result because the Jordan form has the eigenvalues for its diagonal entries.

*Product of traces.*

_Hint._ Again one can just take a basis.

*Traces kind of commute.*

_Hint._ One solution is to just take a basis.
Otherwise, interpret $`T \otimes S \mapsto \operatorname{Tr}(T \circ S)` as a
linear map $`(V^\vee \otimes W) \otimes (W^\vee \otimes V) \to k`,
and verify that it is commutative.

_Solution._ Although we could give a coordinate calculation,
we instead opt to give a cleaner proof.
This amounts to drawing the diagram

It is easy to check that the center rectangle commutes,
by checking it on pure tensors $`\xi_W \otimes v \otimes \xi_V \otimes w`.
So the outer hexagon commutes and we're done.
This is really the same as the proof with bases;
what it amounts to is checking the assertion is true for
matrices that have a $`1` somewhere and $`0` elsewhere,
then extending by linearity.

*Putnam 1988.*

_Hint._ Look at the trace of $`T`.

_Solution._ See [https://mks.mff.cuni.cz/kalva/putnam/psoln/psol886.html](https://mks.mff.cuni.cz/kalva/putnam/psoln/psol886.html).


# Determinant

*Column operations.*

_Hint._ The point is that

$$`(v_1+cv_2) \wedge v_2 \dots \wedge v_n = v_1 \wedge v_2 \dots \wedge v_n + c(v_2 \wedge v_2 \dots \wedge v_n)`

and the latter term is zero.

*Determinant is product of eigenvalues.*

_Hint._ You can either do this by writing $`T` in matrix form,
or you can use the wedge definition of $`\det T`
with the basis given by Jordan form.

*Exponential matrix.*

_Hint._ This is actually immediate by taking any basis
in which $`X` is upper-triangular!

*Extension to the equal-dimension problem.*

_Hint._ You don't need eigenvalues (though they could work also).
In one direction, recall that (by an earlier result)
we can replace \`\`isomorphism" by \`\`injective".
In the other, if $`T` is an isomorphism,
let $`S` be the inverse map and look at $`\det(S \circ T)`.

_Solution._ Recall that (by an earlier result)
we can replace \`\`isomorphism" by \`\`injective".

If $`T(v) = 0` for any nonzero $`v`,
then by taking a basis for which $`e_1 = v`,
we find $`\bigwedge^n(T)` will map $`e_1 \wedge \dots`
to $`0 \wedge T(e_2) \wedge \dots = 0`,
hence is the zero map, so $`\det T = 0`.

Conversely, if $`T` is an isomorphism,
we let $`S` denote the inverse map.
Then $`1 = \det(\operatorname{id}) = \det(S \circ T) = \det S \det T`,
so $`\det T \neq 0`.

*Based on Sweden 2010.*

_Hint._ Consider $`1000 \times 1000` matrix $`M`
with entries $`0` on diagonal and $`\pm 1` off-diagonal.
Mod $`2`.

_Solution._ We proceed by contradiction.
Let $`v` be a vector of length $`1000`
whose entries are weight of cows.
Assume the existence of a matrix $`M` such that $`Mv = 0`,
with entries $`0` on diagonal and $`\pm 1` off-diagonal.
But $`\det M \pmod 2` is equal to the number of derangements
of $`\{1, \dots, 1000\}`, which is odd.
Thus $`\det M` is odd and in particular not zero,
so $`M` is invertible.
Thus $`Mv = 0 \implies v = 0`, contradiction.

*Putnam 2015.*

_Hint._ There is a family of solutions other than just $`a=b=c=d`.

One can solve the problem using Cayley-Hamilton.
A more \`\`bare-hands" approach is to
show the matrix is invertible (unless $`a=b=c=d`)
and then diagonalize the matrix as
$`M = \begin{bmatrix} s & -q \\ -r & p \end{bmatrix} \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix} \begin{bmatrix} p & q \\ r & s \end{bmatrix} = \begin{bmatrix} ps\lambda_1 - qr\lambda_2 & qs(\lambda_1-\lambda_2) \\ pr(\lambda_2-\lambda_1) & ps\lambda_2 - qr\lambda_1 \end{bmatrix}`.

_Solution._ The answer is

$$`\begin{bmatrix} t&t\\t&t \end{bmatrix} \quad\text{and}\quad \begin{bmatrix} -3t&-t\\t&3t \end{bmatrix}`

for $`t \in \mathbb{R}`.
These work by taking $`k=3`.

Now to see these are the only ones, consider an arithmetic matrix

$$`M = \begin{bmatrix} a & a+e \\ a+2e & a+3e \end{bmatrix}.`

with $`e \neq 0`.
Its characteristic polynomial is $`t^2 - (2a+3e)t - 2e^2`,
with discriminant $`(2a+3e)^2 + 8e^2`,
so it has two distinct real roots; moreover, since $`-2e^2 \le 0`
either one of the roots is zero or they are of opposite signs.
Now we can diagonalize $`M` by writing

$$`M = \begin{bmatrix} s & -q \\ -r & p \end{bmatrix} \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix} \begin{bmatrix} p & q \\ r & s \end{bmatrix} = \begin{bmatrix} ps\lambda_1 - qr\lambda_2 & qs(\lambda_1-\lambda_2) \\ pr(\lambda_2-\lambda_1) & ps\lambda_2 - qr\lambda_1 \end{bmatrix}`

where $`ps-qr=1`. By using the fact the diagonal entries have sum equalling
the off-diagonal entries, we obtain that

$$`(ps-qr)(\lambda_1+\lambda_2) = (qs-pr)(\lambda_1-\lambda_2) \implies qs-pr = \frac{\lambda_1+\lambda_2}{\lambda_1-\lambda_2}.`

Now if $`M^k \in S` too then the same calculation gives

$$`qs-pr = \frac{\lambda_1^k+\lambda_2^k}{\lambda_1^k-\lambda_2^k}.`

Let $`x = \lambda_1/\lambda_2 < 0` (since $`-2e^2 < 0`). We appropriately get

$$`\frac{x+1}{x-1} = \frac{x^k+1}{x^k-1} \implies \frac{2}{x-1} = \frac{2}{x^k-1} \implies x = x^k \implies x = -1 or x = 0`

and $`k` odd. If $`x=0` we get $`e=0` and if $`x=-1` we get $`2a+3e=0`,
which gives the curve of solutions that we claimed.

A slicker approach is by Cayley-Hamilton.
Assume that $`e \neq 0`, so $`M` has two distinct real eigenvalues as above.
We have $`M^k = cM + d\operatorname{id}` for some constants $`c` and $`d`
(since $`M` satisfies some quadratic polynomial).
Since $`M \in S`, $`M^k \in S` we obtain $`d=0`.
Thus $`M^k = cM`, so it follows the eigenvalues of $`M` are negatives of each other.
That means $`\operatorname{Tr} M = 0`, and the rest is clear.

*Let $`V` be a finite-dimensional vector space over $`k` and $`T \colon V \to V`.*

_Hint._ Take bases, and do a fairly long calculation.

_Solution._ Pick a basis $`e_1, \dots, e_n` of $`V`.
Let $`T` have matrix $`(x_{ij})`, and let $`m = \dim V`.
Let $`\delta_{ij}` be the Kronecker delta.
Also, let $`\operatorname{Fix}(\sigma)` denote the fixed points of a permutation $`\sigma`
and let $`\operatorname{NoFix}(\sigma)` denote the non-fixed points.

Expanding then gives

$$`\begin{aligned}&\qquad \det (a \cdot \operatorname{id} - T) \\ &= \sum_{\sigma \in S_m} \left( \operatorname{sign}(\sigma) \cdot \prod_{i=1}^m \left( a \cdot \delta_{i \sigma(i)} - x_{i \sigma(i)} \right)\right) \\ &= \sum_{s=0}^m \sum_{1 \le i_1 < \dots < i_s \le m} \sum_{\substack{\sigma \in S_m \\ \sigma \text{ fixes } i_k}} \left( \operatorname{sign}(\sigma) \cdot \prod_{i=1}^m \left( a \cdot \delta_{i \sigma(i)} - x_{i \sigma(i)} \right)\right) \\ &= \sum_{s=0}^m \sum_{1 \le i_1 < \dots < i_s \le m} \sum_{\substack{\sigma \in S_m \\ \sigma \text{ fixes } (i_k)}} \left( \operatorname{sign}(\sigma) \cdot \prod_{i \notin (i_k)} -x_{i \sigma(i)} \prod_{i \in (i_k)}^n \left( a \cdot - x_{ii} \right)\right) \\ &= \sum_{\sigma \in S_m} \left( \operatorname{sign}(\sigma) \cdot \prod_{i \in \operatorname{NoFix}(\sigma)} -x_{i \sigma(i)} \prod_{i \in \operatorname{Fix}(\sigma)} \left( a - x_{ii} \right)\right) \\ &= \sum_{\sigma \in S_m} \left( \operatorname{sign}(\sigma) \cdot \left( \prod_{i \in \operatorname{NoFix}(\sigma)} -x_{i \sigma(i)} \right) \left( \sum_{t=0}^{\left\lvert \operatorname{Fix}(\sigma) \right\rvert} a^{\left\lvert \operatorname{Fix}(\sigma) \right\rvert - t} \cdot \sum_{i_1 < \dots < i_t \in \operatorname{Fix}(\sigma)} \prod_{k=1}^t -x_{i_k i_k} \right) \right) \\ &= \sum_{\sigma \in S_m} \left( \operatorname{sign}(\sigma) \left( \sum_{t=0}^{\left\lvert \operatorname{Fix}(\sigma) \right\rvert} a^{m-t-\left\lvert \operatorname{NoFix}(\sigma) \right\rvert} \sum_{\substack{X \subseteq \{1, \dots, m\} \\ \operatorname{NoFix}(\sigma) \subseteq X \\ X \text{ has exactly } t \text{ fixed}}} \prod_{i \in X} -x_{i \sigma(i)} \right) \right) \\ &= \sum_{n=0}^m a^{m-n} \left( \sum_{\sigma \in S_m} \operatorname{sign}(\sigma) \sum_{\substack{X \subseteq \{1, \dots, m\} \\ \operatorname{NoFix}(\sigma) \subseteq X \\ \left\lvert X \right\rvert = n} } \prod_{i \in X} -x_{i \sigma(i)} \right) \\ &= \sum_{n=0}^m a^{m-n} (-1)^n \left( \sum_{\substack{X \subseteq \{1, \dots, m\} \\ \left\lvert X \right\rvert = n} } \sum_{\substack{\sigma \in S_m \\ \operatorname{NoFix}(\sigma) \subseteq X}} \operatorname{sign}(\sigma) \prod_{i \in X} x_{i \sigma(i)} \right).\end{aligned}`

Hence it's the same to show that

$$`\sum_{\substack{X \subseteq \{1, \dots, m\} \\ \left\lvert X \right\rvert = n} } \sum_{\substack{\sigma \in S_m \\ \operatorname{NoFix}(\sigma) \subseteq X}} \operatorname{sign}(\sigma) \prod_{i \in X} x_{i \sigma(i)} = \operatorname{Tr}_{\bigwedge^n(V)} \left( \bigwedge^n(T) \right)`

holds for every $`n`.

We can expand the definition of trace as using basis elements as

$$`\begin{aligned}\operatorname{Tr}\left( \bigwedge^n(T) \right) &= \sum_{1 \le i_1 < \dots < i_n \le m} \left( \bigwedge_{k=1}^n e_{i_k} \right)^\vee \left( \bigwedge^n(T) \left( \bigwedge_{k=1}^n e_{i_k} \right) \right) \\ &= \sum_{1 \le i_1 < \dots < i_n \le m} \left( \bigwedge_{k=1}^n e_{i_k} \right)^\vee \left( \bigwedge_{k=1}^n T(e_{i_k}) \right) \\ &= \sum_{1 \le i_1 < \dots < i_n \le m} \left( \bigwedge_{k=1}^n e_{i_k} \right)^\vee \left( \bigwedge_{k=1}^n \left( \sum_{j=1}^m x_{i_k j} e_j \right) \right) \\ &= \sum_{1 \le i_1 < \dots < i_n \le m} \sum_{\pi \in S_n} \operatorname{sign}(\pi) \prod_{k=1}^n x_{i_{\pi(k)}k} \\ &= \sum_{\substack{X \subseteq \{1,\dots,m\} \\ \left\lvert X \right\rvert = n}} \sum_{\pi \in S_X} \operatorname{sign}(\pi) \prod_{i \in X} x_{t \pi(t)}\end{aligned}`

Hence it remains to show that the permutations over $`X`
are in bijection with the permutations over $`S_m` which fix $`\{1, \dots, m\} - X`,
which is clear, and moreover, the signs clearly coincide.

*Cauchy-Binet formula.*

_Solution._ See [https://www3.nd.edu/ andyp/notes/CauchyBinet.pdf](https://www3.nd.edu/ andyp/notes/CauchyBinet.pdf).


# Inner product spaces

*Finite-dimensional $`\implies` Hilbert.*

_Hint._ Fix an orthonormal basis $`e_1`, \…, $`e_n`.
Use the fact that $`\mathbb{R}^n` is complete.

*Taiwan IMO camp.*

_Hint._ Dot products in $`\mathbb{F}_2`.

_Solution._ Interpret clubs as vectors in the vector space $`\mathbb F_2^n`.
Consider a \`\`dot product"
to show that all $`k` vectors are linearly independent:
any two different club-vectors have dot product $`0`,
while each club vector has dot product $`1` with itself.
So these vectors are orthonormal and hence linearly independent.
Thus $`k \le \dim \mathbb F_2^n = n`.

*Inner product structure of tensors.*

_Hint._ Define it on simple tensors then extend linearly.

_Solution._ The inner form given by

$$`\left< v_1 \otimes w_1 , v_2 \otimes w_2 \right>_{V \otimes W} = \left< v_1,v_2 \right>_V \left< w_1,w_2\right>_W`

on pure tensors, then extending linearly.
For (b) take $`e_i \otimes f_j` for $`1 \le i \le n`, $`1 \le j \le m`.

*Putnam 2014.*

_Hint._ $`k = n^n`.
Endow tensor products with an inner form.
Note that \`\`zero entry somewhere on its diagonal"
is equivalent to the product of those entries being zero.


# Bonus: Fourier analysis

*For calculus fans.*

_Hint._ Use Parseval again, but this time on $`f(x) = x^2`.

*Let $`f,g,h \colon \{\pm1\}^n \to \{\pm1\}` be any three functions.*

_Hint._ Define the Boolean function $`D \colon \{\pm 1\}^3 \to \mathbb{R}` by
$`D(a,b,c) = ab+bc+ca`.
Write out the value of $`D(a,b,c)` for each $`(a,b,c)`.
Then, evaluate its expected value.

_Solution._ Define the Boolean function $`D \colon \{\pm 1\}^3 \to \mathbb{R}` by

$$`D(a,b,c) = ab + bc + ca = \begin{cases} 3 & a,b,c all equal \\ -1 & a,b,c not all equal. \end{cases}.`

Thus paradoxical outcomes arise when
$`D(f(x_\bullet), g(y_\bullet), h(z_\bullet)) = 3`.
Now, we compute that for randomly selected
$`x_\bullet`, $`y_\bullet`, $`z_\bullet` that

$$`\begin{aligned}\mathbb{E} D(f(x_\bullet), g(y_\bullet), h(z_\bullet)) &= \mathbb{E} \sum_S \sum_T \left( \widehat f(S) \widehat g(T) + \widehat g(S) \widehat h(T) + \widehat h(S) \widehat f(T) \right) \left( \chi_S(x_\bullet)\chi_T(y_\bullet) \right) \\ &= \sum_S \sum_T \left( \widehat f(S) \widehat g(T) + \widehat g(S) \widehat h(T) + \widehat h(S) \widehat f(T) \right) \mathbb{E}\left( \chi_S(x_\bullet)\chi_T(y_\bullet) \right).\end{aligned}`

Now we observe that:

- If $`S \neq T`, then $`\mathbb{E} \chi_S(x_\bullet) \chi_T(y_\bullet) = 0`,
since if say $`s \in S`, $`s \notin T` then $`x_s` affects
the parity of the product with 50\\% either way,
and is independent of any other variables in the product.

- On the other hand, suppose $`S = T`.
Then

$$`\chi_S(x_\bullet) \chi_T(y_\bullet) = \prod_{s \in S} x_sy_s.`

Note that $`x_sy_s` is equal to $`1` with probability $`\frac13`
and $`-1` with probability $`\frac23`
(since $`(x_s, y_s, z_s)` is uniform from $`3!=6` choices,
which we can enumerate).
From this an inductive calculation on $`|S|` gives that

$$`\prod_{s \in S} x_sy_s = \begin{cases} +1 & with probability \tfrac12(1+(-1/3)^{|S|}) \\ -1 & with probability \tfrac12(1-(-1/3)^{|S|}). \end{cases}`

Thus

$$`\mathbb{E} \left( \prod_{s \in S} x_sy_s \right) = \left( -\frac13 \right)^{|S|}.`

Piecing this altogether, we now have that

$$`\mathbb{E} D(f(x_\bullet), g(y_\bullet), h(z_\bullet)) = \left( \widehat f(S) \widehat g(T) + \widehat g(S) \widehat h(T) + \widehat h(S) \widehat f(T) \right) \left( -\frac13 \right)^{|S|}.`

Then, we obtain that

$$`\begin{aligned}&\mathbb{E} \frac14 \left( 1 + D(f(x_\bullet), g(y_\bullet), h(z_\bullet)) \right) \\ =& \frac14 + \frac14\sum_S \left( \widehat f(S) \widehat g(T) + \widehat g(S) \widehat h(T) + \widehat h(S) \widehat f(T) \right) \widehat f(S)^2 \left( -\frac13 \right)^{|S|}.\end{aligned}`

Comparing this with the definition of $`D` gives the desired result.


# Duals, adjoint, and transposes

*Double dual.*

_Hint._ You can prove the result just by taking a basis
$`e_1`, \…, $`e_n` of $`V`
and showing that it is a linear map sending $`e_1`
to the basis $`(e_1^\vee)^\vee`.

*Fundamental theorem of linear algebra.*

_Hint._ Use an earlier result and it will be immediate
(the four quantities equal the $`k` in the theorem).

_Solution._ By an earlier result,
we may select $`e_1`, \…, $`e_n` a basis of $`V`
and $`f_1`, \…, $`f_m` a basis of $`W`
such that $`T(e_i) = f_i` for $`i \le k`
and $`T(e_i) = 0` for $`i > k`.
Then $`T^\vee(f_i^\vee) = e_i^\vee` for $`i \le k`
and $`T^\vee(f_i^\vee) = 0` for $`i > k`.
All four quantities are above are then equal to $`k`.

*Row rank is column rank.*

_Hint._ This actually is just the previous problem in disguise!
The row rank is $`\dim \operatorname{img} T^\vee`
and the column rank is $`\dim \operatorname{img} T`.

*Polynomial criteria for normality.*

_Hint._ If there is a polynomial, check $`TT^\dagger = T^\dagger T` directly.
If $`T` is normal, diagonalize it.

_Solution._ First, suppose $`T^\ast = p(T)`.
Then $`T^\ast T = p(T) \cdot T = T \cdot p(T) = T T^\ast` and we're done.

Conversely, suppose $`T` is diagonalizable
in a way compatible with the inner form
(OK since $`V` is finite dimensional).
Consider the orthonormal basis.
Then $`T` consists of eigenvalues on the main diagonals
and zeros elsewhere, say

$$`T = \left( \begin{array}{cccc} \lambda_1 & 0 & \dots & 0 \\ 0 & \lambda_2 & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \dots & \lambda_n \end{array} \right).`

In that case, we find that for any polynomial $`q` we have

$$`q(T) = \left( \begin{array}{cccc} q(\lambda_1) & 0 & \dots & 0 \\ 0 & q(\lambda_2) & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \dots & q(\lambda_n) \end{array} \right).`

and

$$`T^\ast = \left( \begin{array}{cccc} \overline{\lambda_1} & 0 & \dots & 0 \\ 0 & \overline{\lambda_2} & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \dots & \overline{\lambda_n} \end{array} \right).`

So we simply require a polynomial $`q`
such that $`q(\lambda_i) = \overline{\lambda_i}` for every $`i`.
Since there are finitely many $`\lambda_i`,
we can construct such a polynomial using Lagrange interpolation.

*Let $`M` be an $`m \times n` matrix of complex numbers.*

_Hint._ I do not recommend picking any basis.
Instead, show directly that $`\operatorname{ker}(T^\dagger T) = \operatorname{ker}(T)` for any map $`T`.
(This is better than having the same dimension: the kernels actually match.)


# Group actions overkill AIME problems

*PUMaC 2009 C8.*

_Hint._ Just apply Burnside's lemma directly to get the answer of $`198`
(the relevant group is $`D_{14}`).

*Show that two elements in the same conjugacy class have the same order.*

_Hint._ There are multiple ways to see this.
One is to just do the algebraic manipulation.
Another is to use Cayley's theorem to embed $`G` into a symmetric group.

*Prove Burnside's lemma.*

_Hint._ Double-count pairs $`(g,x)` with $`g \cdot x = x`.

*Classical.*

_Hint._ Let $`H` act on the left cosets $`\{gH \mid g \in G\}`
by left multiplication: $`h \cdot gH = hgH`.
Consider any orbit $`\mathcal{O}`
By the orbit-stabilizer theorem, $`\left\lvert \mathcal{O} \right\rvert`
divides $`\left\lvert H \right\rvert` which divides $`n`, so $`\mathcal{O}`
divides $`n`. But $`\left\lvert \mathcal{O} \right\rvert \le p` since
there are $`p` cosets. So either $`\mathcal{O} = \{H\}` or $`\mathcal{O}` contains
all cosets. Show that the latter is impossible and conclude.

_Solution._ [https://math.stackexchange.com/a/3012179/229197](https://math.stackexchange.com/a/3012179/229197)


# Find all groups

*Let $`G` be a finite simple group.*

_Hint._ Count Sylow $`2` and $`7` groups and let them intersect.

_Solution._ Suppose $`|G|=56` and $`G` is simple.
Consider the Sylow $`7`-subgroups;
if there are $`n_7` of them we assume $`n_7 > 1` (since $`G` is simple)
and $`n_7 \equiv 1 \pmod 7`, so $`n_7 = 8`.
That means there are $`(7-1) \cdot 8 = 48` elements of order $`7` in $`G`.

But consider the Sylow $`2`-subgroups.
These have $`8` elements each, and we conclude therefore
that there is at exactly one Sylow $`2`-subgroup.
That subgroup is normal, contradiction.

*Engel's PSS.*

_Hint._ Construct a non-abelian group such that all elements have order three.

_Solution._ One example is the group of $`3 \times 3`
matrices with entries in $`\mathbb{F}_3` that are of the form
$`\begin{bmatrix} 1 & x & y \\ & 1 & z \\ & & 1 \end{bmatrix}`.

*Let $`p` be a prime and suppose $`G` is a simple group whose order is a power of $`p`.*

_Hint._ First, if $`G` abelian it's trivial.
Otherwise, let $`Z(G)` be the center of the group,
which is always a normal subgroup of $`G`.
Do a mod $`p` argument via conjugation (or use the class equation).

_Solution._ Let $`G` be said group.
If $`G` is abelian then all subgroups are normal,
and since $`G` is simple, $`G` can't have any subgroups at all.
We can clearly find an element of order $`p`, hence $`G` has a subgroup
of order $`p`, which can only happen if $`n=1`, $`G \cong \mathbb{Z}/p\mathbb{Z}`.

Thus it suffices to show $`G` can't be abelian.
For this, we can use the class equation, but let's avoid that and do it directly:

Assume not and let $`Z(G) = \{ g \in G \mid xg = gx \; \forall x \in G \}`
be the center of the group.
Since $`Z(G)` is normal in $`G`, and $`G` is simple, we see $`Z(G) = \{1_G\}`.
But then let $`G` act on itself by conjugation: $`g \cdot x = gxg^{-1}`.
This breaks $`G` into a bunch of orbits $`\mathcal{O}_0 = \{1_G\}`, $`\mathcal{O}_1`, $`\mathcal{O}_2`, \…,
and since $`1_G` is the only fixed point by definition, all other orbits
have size greater than $`1`.
The Orbit-stabilizer theorem says that each orbit now has size dividing $`p^n`,
so they must all have size zero mod $`p`.

But then summing across all orbits (which partition $`G`),
we obtain $`\left\lvert G \right\rvert \equiv 1 \pmod p`,
which is a contradiction.

*Athemath Community-Building Event \\\#1, Fall 2022.*

_Solution._ I can't remember what solution I had in mind when I added this problem in.
There's a more technical solution outlined at
[https://github.com/vEnhance/napkin/pull/268\#issuecomment-2767676253](https://github.com/vEnhance/napkin/pull/268\#issuecomment-2767676253)
but I don't think it's the one I originally had.


# The PID structure theorem

*Finite-dimensional vector spaces are all isomorphic.*

_Hint._ In the structure theorem, $`k / (s_i) \in \{0,k\}`.

*Frobenius normal form.*

_Hint._ By theorem $`V \cong \bigoplus_i k[x] / (s_i)` for some polynomials $`s_i`.
Write each block in the form described.

*Jordan normal form.*

_Hint._ Copy the previous proof, except using the other form of the structure theorem.
Since $`k[x]` is algebraically closed each $`p_i` is a linear factor.

*Find two abelian groups $`G` and $`H` which are not isomorphic, but for which there are injective homomorphisms $`G \hookrightarrow H` and….*

_Hint._ The structure theorem is an anti-result here:
it more or less implies that finitely generated abelian groups won't work.
So, look for an infinitely generated example.

_Solution._ Take $`G = \mathbb{Z}/3\mathbb{Z} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \dots`
and $`H = \mathbb{Z}/9\mathbb{Z} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \mathbb{Z}/9\mathbb{Z} \oplus \dots`.
Then there are maps $`G \hookrightarrow H` and $`H \hookrightarrow G`,
but the groups are not isomorphic since e.g.\\
$`G` has an element $`g \in G` of order $`3`
for which there's no $`g' \in G` with $`g = 3g'`.

*Let $`A \subseteq B \subseteq C` be rings.*

_Hint._ I think the result is true if you add the assumption $`A` is Noetherian,
so look for trouble by picking $`A` not Noetherian.

_Solution._ Nope! Pick

$$`\begin{aligned}A &= \mathbb{Z}[x_1, x_2, \dots] \\ B &= \mathbb{Z}[x_1, x_2, \dots, \varepsilon x_1, \varepsilon x_2, \dots] \\ C &= \mathbb{Z}[x_1, x_2, \dots, \varepsilon].\end{aligned}`

where $`\varepsilon \neq 0` but $`\varepsilon^2 = 0`.
I think the result is true if you add the assumption $`A` is Noetherian.
