import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Hints and solutions: Algebraic Geometry and Set Theory" =>

%%%
file := "Hints-and-solutions-Algebraic-Geometry-and-Set-Theory"
%%%

This appendix collects the hints and sketched solutions for the problems in the algebraic geometry and set theory chapters.
Each entry names its problem; consult the corresponding chapter for the full statement.

# Affine varieties

*Real affine varieties are a single vanishing locus.*

_Hint._ Squares are nonnegative.

_Solution._ If $`V = \mathbb{V}(I)` with $`I = (f_1, \dots, f_m)` (as usual there are finitely many polynomials since $`\mathbb{R}[x_1, \dots, x_n]` is Noetherian) then we can take $`f = f_1^2 + \dots + f_m^2`.

*Complex varieties can't be empty.*

_Hint._ This is actually an equivalent formulation of the Weak Nullstellensatz.

_Solution._ Let $`I` be an ideal, and let $`\mathfrak{m}` be a maximal ideal contained in it.
(If you are worried about the existence of $`\mathfrak{m}`, it follows from Krull's theorem.)
Then $`\mathfrak{m} = (x_1 - a_1, \dots, x_n - a_n)` by the Weak Nullstellensatz.
Consequently, $`(a_1, \dots, a_n)` is the unique point of $`\mathbb{V}(\mathfrak{m})`, and hence this point is also in $`\mathbb{V}(I)`.

*Hilbert's Nullstellensatz from the weak form (the Rabinowitsch trick).*

_Hint._ Use the weak Nullstellensatz on $`n+1` dimensions.
Given $`f` vanishing on everything, consider $`x_{n+1}f - 1`.

_Solution._ The point is to check that if $`f` vanishes on all of $`\mathbb{V}(I)`, then $`f \in \sqrt I`.

Take a set of generators $`f_1, \dots, f_m`, in the original ring $`\mathbb{C}[x_1, \dots, x_n]`; we may assume it's finite by the Hilbert basis theorem.

We're going to do a trick now: consider $`S = \mathbb{C}[x_1, \dots, x_n, x_{n+1}]` instead.
Consider the ideal $`I' \subseteq S` in the bigger ring generated by $`\{f_1, \dots, f_m\}` and the polynomial $`x_{n+1} f - 1`.
The point of the last guy is that its zero locus does not touch our copy $`x_{n+1} = 0` of $`\mathbb{A}^n` nor any point in the "projection" of $`f` through $`\mathbb{A}^{n+1}` (one can think of this as $`\mathbb{V}(I)` in the smaller ring direct multiplied with $`\mathbb{C}`).
Thus $`\mathbb{V}(I') = \varnothing`, and by the weak Nullstellensatz we in fact have $`I' = \mathbb{C}[x_1, \dots, x_{n+1}]`.
So $$`1 = g_1 f_1 + \dots + g_m f_m + g_{m+1} \left( x_{n+1} f - 1 \right).`
Now the hack: *replace every instance of $`x_{n+1}` by $`\frac 1f`*, and then clear all denominators.
Thus for some large enough integer $`N` we can get $$`f^N = f^N(g_1 f_1 + \dots + g_m f_m)`
which eliminates any fractional powers of $`f` in the right-hand side.
It follows that $`f^N \in I`.

# Bonus: Bézout's theorem

*Completing the proof of Bézout's theorem.*

_Solution._ From the exactness, $`h_I(d) = h_I(d - k) + h_{I + (f)}(d)`, and it follows that $$`\chi_{I + (f)}(d) = \chi_I(d) - \chi_I(d - k).`
Let $`m = \dim \mathbb{V}_+(I) \ge 1`.
Now $`\dim \mathbb{V}_+(I + (f)) = m - 1`, so writing $`c_{\text{new}} = \deg (I + (f))` we have $$`\frac{\deg (I + (f)) \, d^{m-1} + \dots}{(m-1)!} = \frac{1}{m!} \left( \deg I \, (d^m - (d - k)^m) + \text{lower order terms} \right)`
from which we read off $$`\deg (I + (f)) = \frac{(m-1)!}{m!} \cdot k \binom m1 \deg I = k \deg I`
as needed.

*USA TST 2016/6.*

_Hint._ You will need to know about complex numbers in Euclidean geometry to solve this problem.

_Solution._ In complex numbers with $`ABC` the unit circle, it is equivalent to solving the two cubic equations $$`\begin{aligned} (p - a)(p - b)(p - c) &= (abc)^2 (q - 1/a)(q - 1/b)(q - 1/c) \\ 0 &= \prod_{\text{cyc}} (p + c - b - bcq) + \prod_{\text{cyc}} (p + b - c - bcq) \end{aligned}`
in $`p` and $`q = \overline p`.
Viewing this as two cubic curves in $`(p, q) \in \mathbb{C}^2`, by Bézout's theorem it follows there are at most nine solutions (unless both curves are not irreducible, but one can check the first one cannot be factored).
Moreover it is easy to name nine solutions (for $`ABC` scalene): the three vertices, the three excenters, and $`I`, $`O`, $`H`.
Hence the answer is just those three triangle centers $`I`, $`O` and $`H`.

# Morphisms of varieties

*Projective varieties are locally affine.*

_Hint._ Use the standard affine charts.

*An affine variety isomorphic to an irreducible projective variety is a point.*

_Hint._ Examine the global regular functions.

_Solution._ If they were isomorphic, we would have $`\mathcal{O}_V(V) \cong \mathcal{O}_W(W)`.
For irreducible projective varieties, $`\mathcal{O}_W(W) \cong \mathbb{C}`, while for affine varieties $`\mathcal{O}_V(V) \cong \mathbb{C}[V]`.
Thus we conclude $`V` must be a single point.

*The punctured plane is not affine.*

_Hint._ Assume $`f` was an isomorphism.
Then it gives an isomorphism $`f^\sharp \colon \mathcal{O}_V(V) \to \mathcal{O}_X(X) = \mathbb{C}[x, y]`.
Thus we may write $`\mathcal{O}_V(V) = \mathbb{C}[a, b]`, where $`f^\sharp(a) = x` and $`f^\sharp(b) = y`.
Let $`f(p) = q` where $`\mathbb{V}(a, b) = \{q\}`.
Use the definition of pullback to prove $`p \in \mathbb{V}(x, y)`, contradiction.

_Solution._ Assume for contradiction there is an affine variety $`V` and an isomorphism $`f \colon X \to V`.
Then taking the pullback we get a ring isomorphism $$`f^\sharp \colon \mathcal{O}_V(V) \to \mathcal{O}_X(X) = \mathbb{C}[x, y].`
Now let $`\mathcal{O}_V(V) = \mathbb{C}[a, b]` where $`f^\sharp(a) = x`, $`f^\sharp(b) = y`.
In particular, we actually have to have $`V \cong \mathbb{A}^2`.

Now in the _affine_ variety $`V` we can take $`\mathbb{V}(a)` and $`\mathbb{V}(b)`; these have nonempty intersection since $`(a, b)` is a maximal ideal in $`\mathcal{O}_V(V)`.
Call this point $`q`, and let $`p` be a point with $`f(p) = q`.

Then $$`0 = a(q) = (f^\sharp a)(p) = x(p)`
and so $`p \in \mathbb{V}(x) \subseteq X`.
Similarly, $`p \in \mathbb{V}(y) \subseteq X`, but this is a contradiction since $`\mathbb{V}(x, y) = \varnothing`.

# Sheaves and ringed spaces

*A sheaf equals its sheafification.*

_Solution._ Because the stalks are preserved by sheafification, there is essentially nothing to prove: both sides correspond to sequences of compatible $`\mathcal{F}`-germs over $`U`.

*Skyscraper sheaf.*

_Hint._ The stalk is $`R` at points in the closure of $`\{p\}`, and $`0` elsewhere.

*The support of a global section is closed.*

_Hint._ Show that the complement $`\{ p \mid [s]_p = 0 \}` is open.

# Localization

*Localizing $`\mathbb{Z}/2016\mathbb{Z}`$ away from $`60`$.*

_Solution._ One should get $`A[1/60] = \mathbb{Z}/7\mathbb{Z}`.

*Injectivity of localizations.*

_Hint._ Consider zero divisors.

_Solution._ If and only if $`S` has no zero divisors.

*Alluding to local rings.*

_Hint._ Only one!
(A proof is given a few chapters later.)

*A ring local at every prime need not be a domain.*

_Hint._ No.
Use a product ring.

_Solution._ Take $`A = \mathbb{C} \times \mathbb{C}`, or more generally a product of two or more integral domains.

# Affine schemes: the Zariski topology

*The spectrum $`\operatorname{Spec}\mathbb{Q}[x]`$.*

_Hint._ Galois conjugates.

# Affine schemes: the sheaf

*Punctured gyrotop (communicated by Aaron Pixton).*

_Hint._ The answer is $`k[x, y] \times k[z, z^{-1}]`.

_Solution._ Let $`V = D(x) \cup D(y) \subset U` denote the punctured plane, so its complement $`D(z)` looks like a punctured line.
Then $`V \cap D(z) = \varnothing` and the following diagram of restriction maps commutes

:::figure "figures/algebraic-geometry/gyrotop-restriction.svg"
:::

By sheaf axioms we should actually have $$`\mathcal{O}_X(U) = \mathcal{O}_X(D(z)) \times \mathcal{O}_X(V).`
We have $`\mathcal{O}_X(D(z)) = A_z = k[x, y, z, z^{-1}]/(xz, yz) \cong k[z, z^{-1}]`.
On the other hand $`\mathcal{O}_X(V) = k[x, y]` as shown in §4.4.1 of Vakil.
So $$`\mathcal{O}_X(U) = k[x, y] \times k[z, z^{-1}].`

*Localizing a local ring at its maximal ideal.*

_Hint._ It's isomorphic to $`R`!

# Morphisms of locally ringed spaces

*The unique morphism to $`\operatorname{Spec}\mathbb{Z}`$.*

_Hint._ Use the fact that $`\mathbf{AffSch} \simeq \mathbf{CRing}`.

_Solution._ Since $`\mathbb{Z}` is the initial object of $`\mathbf{CRing}`, it follows $`\operatorname{Spec}\mathbb{Z}` is the final object of $`\mathbf{AffSch}`.
A prime $`\mathfrak{p}` gets sent to the characteristic of the field $`\mathcal{O}_{X, \mathfrak{p}} / \mathfrak{m}_{X, \mathfrak{p}}`.

# Interlude: Cauchy's functional equation and Zorn's lemma

*A rapidly growing additive function.*

_Hint._ Let $`\varepsilon = \pi - 3.141592653 < 10^{-9}`.
Find $`f(\varepsilon)`.

_Solution._ Let $`\varepsilon = \pi - 3.141592653 < 10^{-9}`.
Then $$`\frac{22}{7} = f(\pi) = f(3.141592653) + f(\varepsilon) = 3.141592653 + f(\varepsilon).`
Therefore, $$`f(\varepsilon) = \frac{22}{7} - 3.141592653 = \frac{22 - 21.991148571}{7} > \frac{0.008}{7} > 10^{-3}.`
So $$`f(10^8 \varepsilon) = 10^8 f(\varepsilon) > 10^5 > 9000`
and $`10^8 \varepsilon < 1`, as needed.

*True/false statements about Cauchy's equation.*

_Solution._ Every statement is true.

The first statement follows by simply extending $`f` via $$`x \mapsto \begin{cases} f(x) & x > 0 \\ 0 & x = 0 \\ -f(-x) & x < 0. \end{cases}`
The second statement is true for any additive function $`\mathbb{R} \to \mathbb{R}`.
Indeed, $`f(0) = f(0) + f(0) \implies f(0) = 0`, and oddness follows.

The third and fourth statement follow from [this Wikipedia article](https://en.wikipedia.org/wiki/Cauchy%27s_functional_equation#Properties_of_nonlinear_solutions_over_the_real_numbers).

The fifth statement is kind of stupid.
If $`f` was surjective, there should exist $`a > 0` such that $`f(a) = 0`.
But then $`f(2a) = f(a) + f(a) = 0`, so $`f` is not injective.

For the rest, fix a Hamel basis $$`E = \{e_\alpha \mid \alpha \in S \coloneqq \{ 0, 1, 2, \dots \} \dots \}.`
Here $`S` is an uncountable set of ordinals.
Without loss of generality, $`e_0 = 1` and $`e_\alpha > 0` for all $`\alpha \in S`.
Then $`f` is uniquely determined by the value of $`f(e_\alpha)` for each $`\alpha \in S`.

- For the sixth statement, let $`f(e_0) = e_1`, $`f(e_1) = e_0`, and $`f(e_\alpha) = e_\alpha` for all other $`\alpha \ge 2`.
- The seventh statement is the most complicated.
  Since $`S` is infinite, it's possible to construct a $`2`-to-$`1` map $`\psi \colon S \to S`, meaning every element of the codomain is the image of exactly two elements in the domain.
  Then if $`\psi(\alpha) = \psi(\beta) = \gamma` for $`\alpha \neq \beta`, set $`f(e_\alpha) = e_\gamma`, $`f(e_\beta) = -e_\gamma`.
- For the eighth statement, let $`f(e_\alpha) = 1` for every $`\alpha \in S`.
- For the ninth statement, let $`f(e_\alpha)` be a linearly independent irrational number for every $`\alpha \in S`.

# Zermelo–Fraenkel with choice

*Hats of three colors (from Taiwan IMO training camp).*

_Hint._ This is an application of the Axiom of Choice.

_Solution._ Define an equivalence relation equating two hat configurations if they differ in only finitely many places.
Now for each equivalence class, everyone pre-agrees on a particular representative.
Finally, note that a person can determine which equivalence class the group is in even without their own hat color.
Hence they unanimously select the same representative, QED.

# Cardinals

*The cardinality of $`V_\omega`$.*

_Hint._ It is $`\sup_{k \in \omega} \left\lvert V_k \right\rvert`.

*Cofinality is a regular cardinal.*

_Hint._ Rearrange the cofinal maps to be nondecreasing.

# Inner model theory

*Reflection.*

_Hint._ This is very similar to the proof of Löwenheim–Skolem.
For a sentence $`\phi`, let $`f_\phi` send $`\alpha` to the least $`\beta < \kappa` such that for all $`\vec b \in V_\alpha`, if there exists $`a \in M` such that $`V_\kappa \vDash \phi[a, \vec b]` then $`\exists a \in V_\beta` such that $`V_\kappa \vDash \phi[a, \vec b]`.
(To prove this $`\beta` exists, use the fact that $`\kappa` is cofinal.)
Then, take the supremum over the countably many sentences for each $`\alpha`.

_Solution._ For a sentence $`\phi` let $`f_\phi \colon \kappa \to \kappa` send $`\alpha` to the least $`\beta < \kappa` such that for all $`\vec b \in V_\alpha`, if there exists $`a \in V_\kappa` such that $`V_\kappa \vDash \phi[a, \vec b]` then $`\exists a \in V_\beta` such that $`V_\kappa \vDash \phi[a, \vec b]`.

We claim this is well-defined.
There are only $`\left\lvert V_\alpha \right\rvert^n` many possible choices of $`\vec b`, and in particular there are fewer than $`\kappa` of these (since we know $`\left\lvert V_\alpha \right\rvert < \kappa`, comparing the strongly-inaccessible problem earlier).
Otherwise, we can construct a cofinal map from $`\left\lvert V_\alpha^n \right\rvert` into $`\kappa` by mapping each vector $`\vec b` into a $`\beta` for which the proposition fails.
And that's impossible since $`\kappa` is regular!

In other words, what we've done is fix $`\phi` and then use Tarski–Vaught on all the $`\vec b \in V_\alpha^n`.
Now let $`g \colon \kappa \to \kappa` be defined by $$`\alpha \mapsto \sup_\phi f_\phi(\alpha).`
Since $`\kappa` is regular and there are only countably many formulas, $`g(\alpha)` is well-defined.

Check that if $`\alpha` has the property that $`g` maps $`\alpha` into itself (in other words, $`\alpha` is closed under $`g`), then by the Tarski–Vaught test, we have $`V_\alpha \prec V_\kappa`.

So it suffices to show there are arbitrarily large $`\alpha < \kappa` which are closed under $`g`.
Fix $`\alpha_0`.
Let $`\alpha_1 = g(\alpha_0)`, et cetera, and define $$`\alpha = \sup_{n < \omega} \alpha_n.`
This $`\alpha` is closed under $`g`, and by making $`\alpha_0` arbitrarily large we can make $`\alpha` as large as we like.

*Strongly inaccessible cardinals produce models.*

_Hint._ Use the fact that a transitive set satisfying the right closure conditions models ZFC.
To prove $`V_\kappa \vDash` Power Set you need $`\kappa` to be a strong limit cardinal, and to prove $`V_\kappa \vDash` Replacement you need $`\kappa` to be inaccessible — this is why we cared about cofinality and inaccessibility.

# Forcing

*Rasiowa–Sikorski lemma.*

_Hint._ Let $`D_1, D_2, \dots` be the dense sets (there are countably many of them).

_Solution._ Since $`M` is countable, there are only countably many dense sets (they live in $`M`!), say $$`D_1, D_2, \ldots, D_n, \ldots \in M.`
Using Choice, let $`p_1 \in D_1`, and then let $`p_2 \le p_1` such that $`p_2 \in D_2` (this is possible since $`D_2` is dense), and so on.
In this way we can inductively exhibit a chain $$`p_1 \ge p_2 \ge p_3 \ge \dots`
with $`p_i \in D_i` for every $`i`.

Hence, we want to generate a filter from the $`\{p_i\}`.
Just take the upwards closure — let $`G` be the set of $`q \in \mathbb{P}` such that $`q \ge p_n` for some $`n`.
By construction, $`G` is a filter (this is actually trivial).
Moreover, $`G` intersects all the dense sets by construction.

# Breaking the continuum hypothesis

*The chain condition preserves regularity.*

_Hint._ Assume not, and take $`\lambda > \kappa` regular in $`M`; if $`f \colon \overline\lambda \to \lambda`, use the Possible Values Argument on $`f` to generate a function in $`M` that breaks cofinality of $`\lambda`.

_Solution._ It suffices to show that $`\mathbb{P}` preserves regularity greater than or equal to $`\kappa`.
Consider $`\lambda > \kappa` which is regular in $`M`, and suppose for contradiction that $`\lambda` is not regular in $`M[G]`.
That's the same as saying that there is a function $`f \in M[G]`, $`f \colon \overline\lambda \to \lambda` cofinal, with $`\overline\lambda < \lambda`.
Then by the Possible Values Argument, there exists a function $`F \in M` from $`\overline\lambda \to \mathcal{P}(\lambda)` such that $`f(\alpha) \in F(\alpha)` and $`\left\lvert F(\alpha) \right\rvert^M < \kappa` for every $`\alpha`.

Now we work in $`M` again.
Note for each $`\alpha \in \overline\lambda`, $`F(\alpha)` is bounded in $`\lambda` since $`\lambda` is regular in $`M` and greater than $`\left\lvert F(\alpha) \right\rvert`.
Now look at the function $`\overline\lambda \to \lambda` in $`M` by just $$`\alpha \mapsto \bigcup F(\alpha) < \lambda.`
This is cofinal in $`M`, contradiction.
