import VersoManual
import Napkin.Meta.Lean
import Napkin.Meta.Directives
import Napkin.Meta.Citations

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

open Napkin

set_option pp.rawOnError true

#doc (Manual) "Hints and solutions: Geometry and Number Theory" =>

%%%
file := "Hints-and-solutions-Geometry-and-Number-Theory"
%%%

This appendix collects the hints and solution sketches for the problems in the differential geometry, Riemann surfaces, and algebraic number theory chapters.
Each entry names its problem; only problems for which the source provides a hint or solution appear.

# Multivariable calculus done correctly

*Symmetry of the higher derivatives.*

_Hint._ Simply induct, with the work having been done on the $`k = 2` case.

# Differential forms

*The identity $`d^2 = 0`.*

_Hint._ This is just a summation.
You will need the fact that mixed partials are symmetric.

# Integrating differential forms

*Green's theorem.*

_Hint._ Direct application of Stokes' theorem to $`\alpha = f \, dx + g \, dy`.

*The identity $`\partial^2 = 0`.*

_Hint._ This is just an exercise in sigma notation.

*Pullback and $`d` commute.*

_Hint._ This is a straightforward (but annoying) computation.

*Arc length isn't a form.*

_Hint._ We would want $`\alpha_p(v) = \lVert v \rVert`.

*Integrals of an exact form over concentric circles.*

_Hint._ Show that $`d^2 = 0` implies $`\int_{\partial c} \alpha = 0` for exact $`\alpha`.
Draw an annulus.

# Algebraic integers

*Brazil 2006.*

_Hint._ Note that $`p(x)` is a minimal polynomial for $`r`, but so is $`q(x) = x^{\deg p} p(1/x)`.
So $`q` and $`p` must be multiples of each other.

*The roots-of-unity averaging lemma.*

_Hint._ $`\left\lvert \tfrac 1n(\varepsilon_1 + \dots + \varepsilon_n) \right\rvert \le 1`.

*Which $`q` satisfy $`\cos(q\pi) \in \mathbb{Q}`.*

_Hint._ Only the obvious ones.
Assume $`\cos(q\pi) \in \mathbb{Q}`.
Let $`\zeta` be a root of unity (an algebraic integer, as $`\zeta^N - 1 = 0` for some $`N`) and note that $`2\cos(q\pi) = \zeta + \zeta^{N-1}` is both an algebraic integer and a rational number.

*MOP 2010 (lamps on a circle).*

_Hint._ View as roots of unity.
Note $`\tfrac12` isn't an algebraic integer.

*Kronecker's theorem.*

_Hint._ Let $`\alpha = \alpha_1`, $`\alpha_2`, …, $`\alpha_n` be its conjugates.
Look at the polynomial $`(x - \alpha_1^e) \dots (x - \alpha_n^e)` across $`e \in \mathbb{N}`.
Pigeonhole principle on all possible polynomials.

# The ring of integers

*Units have norm $`\pm 1`.*

_Hint._ The norm is multiplicative and equal to the product of Galois conjugates.

*The field of fractions of $`\mathcal{O}_K`.*

_Hint._ It's isomorphic to $`K`.

*Russian olympiad 1984.*

_Hint._ Taking the standard norm on $`\mathbb{Q}(\sqrt2)` will destroy it.

*USA TST 2012.*

_Hint._ Norm in $`\mathbb{Q}(\sqrt[3]2)`.

*The cyclotomic field.*

_Hint._ Obviously $`\mathbb{Z}[\zeta_p] \subseteq \mathcal{O}_K`, so our goal is to show the reverse inclusion.
Show that for any $`\alpha \in \mathcal{O}_K`, the trace of $`\alpha(1 - \zeta_p)` is divisible by $`p`.
Given $`x = a_0 + a_1\zeta_p + \dots + a_{p-2}\zeta^{p-2} \in \mathcal{O}_K` (where $`a_i \in \mathbb{Q}`), consider $`(1 - \zeta_p)x`.

# Unique factorization (finally!)

*Fermat's little theorem.*

_Hint._ Copy the proof of the usual Fermat's little theorem.

_Solution._ If $`\alpha \equiv 0 \pmod{\mathfrak{p}}` it's clear, so assume this isn't the case.
Then $`\mathcal{O}_K/\mathfrak{p}` is a finite field with $`\operatorname{Norm}(\mathfrak{p})` elements.
Looking at $`(\mathcal{O}_K/\mathfrak{p})^\ast`, it's a multiplicative group with $`\operatorname{Norm}(\mathfrak{p}) - 1` elements, so $`\alpha^{\operatorname{Norm}(\mathfrak{p}) - 1} \equiv 1 \pmod{\mathfrak{p}}`, as desired.

*Alternative definition of a fractional ideal.*

_Hint._ Clear denominators!

_Solution._ Suppose it's generated by some elements in $`K`; we can write them as $`\frac{\beta_i}{\alpha_i}` for $`\alpha_i, \beta_i \in \mathcal A`.
Hence $$`J = \left\{ \sum_i \gamma_i \cdot \frac{\beta_i}{\alpha_i} \mid \alpha_i, \beta_i, \gamma_i \in \mathcal{O}_K \right\}.`
Now "clear denominators".
Set $`\alpha = \alpha_1 \dots \alpha_n`, and show that $`\alpha J` is an integral ideal.

*Correctness of the factoring algorithm.*

_Hint._ Part (a) is straightforward.
For (b) work mod $`p`.
For (c) use norms.

_Solution._ For part (a), note that the $`\mathfrak{p}_i` are prime just because $$`\mathcal{O}_K / \mathfrak{p}_i \cong (\mathbb{Z}[x] / f) / (p, f_i) \cong \mathbb{F}_p[x] / (f_i)`
is a field, since the $`f_i` are irreducible.

We check (b).
Computing the product modulo $`p` yields{margin}[For example, suppose we want to know that $`(3, 1 + \sqrt{7})(3, 1 - \sqrt{7})` is contained in $`(3)`. We could do the full computation and get $`(9, 3 + 3\sqrt{7}, 3 - 3\sqrt{7}, 6)`. But if all we care about is that every element is divisible by $`3`, we could have just taken "mod $`3`" at the beginning and looked at just $`(1 + \sqrt{7})(1 - \sqrt{7}) = (6)`; all the other products we get will obviously have factors of $`3`.] $$`\prod_{i=1}^{g} (f_i(\theta))^{e_i} \equiv (f(\theta)) \equiv 0 \pmod p`
so we've shown that $`I \subseteq (p)`.

Finally, we prove (c) with a size argument.
The idea is that $`I` and $`(p)` really should have the same size; to nail this down we'll use the ideal norm.
Since $`(p)` divides $`I`, we can write $`(p) = \prod_{i=1}^g \mathfrak{p}_i^{e_i'}` where $`e_i' \le e_i` for each $`i`.
Remark that $`\mathcal{O}_K / (p) \cong (\mathbb{Z}/p\mathbb{Z})[x] / (f)` has size $`p^{\deg f}`.
Similarly, $`\mathcal{O}_K / (\mathfrak{p}_i)` has degree $`p^{\deg f_i}` for each $`i`.
Compute $`\operatorname{Norm}((p))` using the $`e_i'` now and compare the results.

*USEMO 2025.*

_Hint._ Let $`\omega` be a $`k`th root of unity.
Let $`\mathfrak{p}` be any prime ideal above $`p` in the ring of integers of $`K = \mathbb{Q}(\omega)`.
Show that there exist indices $`i` and $`j` such that $`2025 - \omega^i` and $`2026 - \omega^j` are in $`\mathfrak{p}`.
Then show that $`1 + \omega^i - \omega^j` is nonzero with norm at most $`3^k`.

_Solution._ Set $`\omega \coloneqq e^{\frac{2i\pi}{k}}`.
Let $`K = \mathbb{Q}(\omega)` and choose any prime ideal $`\mathfrak{p}` of $`\mathcal{O}_K` lying over $`p\mathbb{Z}`.
We know that $$`\prod_{i=0}^{k-1} (2025 - \omega^i) = 2025^k - 1 \in (p) \subseteq \mathfrak{p}`
and since $`\mathfrak{p}` is a prime ideal, we know $`2025 - \omega^i \in \mathfrak{p}` for some $`i`.
Similarly $`2026 - \omega^j \in \mathfrak{p}` for some $`j`.
Subtracting, $$`(2026 - \omega^j) - (2025 - \omega^i) = 1 + \omega^i - \omega^j \in \mathfrak{p} \implies p \mid \operatorname{Norm}_{K/\mathbb{Q}}(1 + \omega^i - \omega^j).`
Since $`6 \nmid k`, it follows that $`1 + \omega^i - \omega^j \neq 0`, and so $`p` is at most the norm above.
However, straight from the definitions, $$`\left\lvert \operatorname{Norm}_{\mathbb{Q}(\omega)/\mathbb{Q}}(1 + \omega^i - \omega^j) \right\rvert = \prod_{\gcd(m, k) = 1, \, 1 \le m \le k} |1 + \omega^{mi} - \omega^{mj}| \le 3^k.`

# More properties of the discriminant

*Discriminant of a cyclotomic field.*

_Hint._ Direct linear algebra computation.

*Trace representation of $`\Delta_K`.*

_Hint._ Let $`M` be the "embedding" matrix.
Look at $`M^\top M`, where $`M^\top` is the transpose matrix.

*Root representation of $`\Delta_K`.*

_Hint._ Vandermonde matrices.

*Every number field $`K \neq \mathbb{Q}` has $`\left\lvert \Delta_K \right\rvert > 1`.*

_Hint._ $`M_K \ge 1` must hold.
Bash.

# Minkowski bound and class groups

*$`\mathbb{Q}(\sqrt{-163})` has trivial class group.*

_Hint._ Repeat the previous procedure.{margin}[In fact, $`n = 163` is the largest number for which $`\mathbb{Q}(\sqrt{-n})` has trivial class group. The complete list is $`1, 2, 3, 7, 11, 19, 43, 67, 163`, the *Heegner numbers*. You might notice Euler's prime-generating polynomial $`t^2 + t + 41` when doing the above problem. Not a coincidence!]

*The class group of $`\mathbb{Q}(\sqrt{-31})`.*

_Hint._ You should get a group of order three.

*China TST 1998.*

_Hint._ Mimic the proof of part (a) of Minkowski's theorem.

*The mesh of $`\mathcal{O}_K` under the canonical embedding.*

_Hint._ Linear algebra.

*Primes $`p \equiv 1 \pmod 4` are sums of two squares.*

_Hint._ Factor in $`\mathbb{Q}(i)`.

*Korea national olympiad 2014.*

_Hint._ Factor $`p`, and show that the class group of $`\mathbb{Q}(\sqrt{-5})` has order two.

_Solution._ Let $`K = \mathbb{Q}(\sqrt{-5})`.
Check that $`\operatorname{Cl}_K` has order two using the Minkowski bound; moreover $`\Delta_K = 20`.
Now note that $`\mathcal{O}_K = \mathbb{Z}[\sqrt{-5}]`, and $`x^2 + 5` factors mod $`p` as $`(x + k)(x - k)`; hence in $`\mathcal{O}_K` we have $`(p) = (p, \sqrt{-5} + k)(p, \sqrt{-5} - k) = \mathfrak{p}_1 \mathfrak{p}_2`, say.
For $`p > 5` the prime $`p` does not ramify and we have $`\mathfrak{p}_1 \neq \mathfrak{p}_2`, since $`\Delta_K = 20`.
Then $`(p^2) = \mathfrak{p}_1^2 \cdot \mathfrak{p}_2^2`.
Because the class group has order two, both $`\mathfrak{p}_1^2` and $`\mathfrak{p}_2^2` are principal, and because $`\mathfrak{p}_1 \neq \mathfrak{p}_2` they are distinct.
Thus $`p^2` is a nontrivial product of two elements of $`\mathcal{O}_K`; from this we can extract the desired factorization.

*A generator visible to only one prime.*

_Hint._ Let $`n` be a positive integer such that $`\mathfrak{p}^n` is principal.

_Solution._ Let $`n` be a positive integer such that $`\mathfrak{p}^n` is principal (for example, $`n = |\operatorname{Cl}_K|`).
If $`\mathfrak{p}^n = (x)`, then $`x` works.

# Things Galois

*Galois group of the cyclotomic field.*

_Hint._ Look at the image of $`\zeta_p`.

_Solution._ It's just $`\mathbb{Z}/(p-1)\mathbb{Z}`, since $`\zeta_p` needs to get sent to one (any) of the $`p - 1` primitive roots of unity.

*The three Greek constructions.*

_Hint._ Repeated quadratic extensions have degree $`2`, so one can only get powers of two.

*China Hong Kong Math Olympiad.*

_Solution._ A similar (but not identical) problem is solved at [https://aops.com/community/c6h149153p842956](https://aops.com/community/c6h149153p842956).

*The only automorphism of $`\mathbb{R}` is the identity.*

_Hint._ $`\sigma(x^2) = \sigma(x)^2 \ge 0` plus Cauchy's functional equation.

*Artin's primitive element theorem.*

_Hint._ By induction, it suffices to show $`\mathbb{Q}(\alpha, \beta) = \mathbb{Q}(\gamma)` for some $`\gamma` in terms of $`\alpha` and $`\beta`.
For all but finitely many rational $`\lambda`, the choice $`\gamma = \alpha + \lambda \beta` will work.

_Solution._ See [https://www.math.cornell.edu/~kbrown/6310/primitive.pdf](https://www.math.cornell.edu/~kbrown/6310/primitive.pdf).

# Finite fields

*HMMT 2017 (period of the Fibonacci sequence modulo $`127`).*

_Hint._ The Fibonacci sequence is given by $`F_n = \frac{\alpha^n - \beta^n}{\alpha - \beta}` where $`\alpha = \frac{1 + \sqrt5}{2}` and $`\beta = \frac{1 - \sqrt5}{2}` are the two roots of $`P(X) \coloneqq X^2 - X - 1`.
Show the polynomial $`P(X)` is irreducible modulo $`127`; then work in the splitting field of $`P`, namely $`\mathbb{F}_{p^2}`.
Show that $`F_p = -1`, $`F_{p+1} = 0`, $`F_{2p+1} = 1`, $`F_{2p+2} = 0`.
(Look at the action of $`\operatorname{Gal}(\mathbb{F}_{p^2}/\mathbb{F}_p)` on the roots of $`P`.)

_Solution._ Recall that the Fibonacci sequence is given by $$`F_n = \frac{\alpha^n - \beta^n}{\alpha - \beta}`
where $`\alpha = \frac{1 + \sqrt5}{2}` and $`\beta = \frac{1 - \sqrt5}{2}` are the two roots of $`P(X) \coloneqq X^2 - X - 1`.

Let $`p = 127` and work modulo $`p`.
As $$`\left( \frac5p \right) = \left( \frac p5 \right) = \left( \frac 25 \right) = -1`
we see $`5` is not a quadratic residue mod $`127`.
Thus the polynomial $`P(X)`, viewed as a polynomial in $`\mathbb{F}_p[X]`, is irreducible (intuitively, $`\alpha` and $`\beta` are not elements of $`\mathbb{F}_p`).
Accordingly we will work in the finite field $`\mathbb{F}_{p^2}`, which is the $`\mathbb{F}_p`-splitting field of $`P(X)`.
In other words we interpret $`\alpha` and $`\beta` as elements of $`\mathbb{F}_{p^2}` which do not lie in $`\mathbb{F}_p`.

Let $`\sigma \colon \mathbb{F}_{p^2} \to \mathbb{F}_{p^2}` by $`t \mapsto t^p` be the nontrivial element of $`\operatorname{Gal}\left( \mathbb{F}_{p^2} / \mathbb{F}_p \right)`; in other words, $`\sigma` is the non-identity automorphism of $`\mathbb{F}_{p^2}`.
Since the fixed points of $`\sigma` are the elements of $`\mathbb{F}_p`, this means $`\sigma` does not fix either root of $`P`; thus we must have $$`\alpha^p = \sigma(\alpha) = \beta, \qquad \beta^p = \sigma(\beta) = \alpha.`
Now, compute $$`\begin{aligned} F_{p} &= \frac{\alpha^{p} - \beta^{p}}{\alpha - \beta} = \frac{\beta - \alpha}{\alpha - \beta} = -1, \\ F_{p+1} &= \frac{\alpha^{p+1} - \beta^{p+1}}{\alpha - \beta} = \frac{\alpha\beta - \beta\alpha}{\alpha - \beta} = 0, \\ F_{2p+1} &= \frac{\alpha^{2p+1} - \beta^{2p+1}}{\alpha - \beta} = \frac{\beta^2\alpha - \alpha^2\beta}{\alpha - \beta} = -\alpha \beta = 1, \\ F_{2p+2} &= \frac{\alpha^{2p+2} - \beta^{2p+2}}{\alpha - \beta} = \frac{\beta^2\alpha^2 - \alpha^2\beta^2}{\alpha - \beta} = 0. \end{aligned}`
Consequently, the period must divide $`2p + 2` but not $`p + 1`.
We now use for the first time the exact numerical value $`p = 127` to see the period divides $`2p + 2 = 256 = 2^8`, but not $`p + 1 = 128 = 2^7`.
(Previously we only used the fact that $`(5/p) = -1`.)
Thus the period must be exactly $`256`.

# Ramification theory

*No rational prime is inert in the splitting field of $`x^3 - 2`.*

_Hint._ Show that no rational prime $`p` can remain inert if $`\operatorname{Gal}(K/\mathbb{Q})` is not cyclic.
Indeed, if $`p` is inert then $`D_\mathfrak{p} \cong \operatorname{Gal}(K/\mathbb{Q})`.

# The Frobenius element

*The formula $`\left( \frac 2p \right) = (-1)^{\frac 18(p^2 - 1)}`.*

_Hint._ Modify the end of the proof of quadratic reciprocity.

_Solution._ It is still true that $$`\left( \frac 2q \right) = 1 \iff \sigma_2 \in H \iff 2 \text{ splits in } \mathbb{Z}\left[ \tfrac12(1 + \sqrt{q^\ast}) \right].`
Now, $`2` splits in the ring if and only if $`t^2 - t - \tfrac14(1 - q^\ast)` factors mod $`2`.
This happens if and only if $`q^\ast \equiv 1 \pmod 8`.
One can check this is exactly when $`q \equiv \pm 1 \pmod 8`, which gives the conclusion.

*Dirichlet's theorem on arithmetic progressions.*

_Hint._ Chebotarev density on $`\mathbb{Q}(\zeta_m)`.

_Solution._ Let $`K = \mathbb{Q}(\zeta_m)`.
One can show that $`\operatorname{Gal}(K/\mathbb{Q}) \cong (\mathbb{Z}/m\mathbb{Z})^\times` exactly as before.
In particular, $`\operatorname{Gal}(K/\mathbb{Q})` is abelian and therefore its conjugacy classes are singleton sets; there are $`\phi(m)` of them.
As long as $`p` is sufficiently large, it is unramified and $`\sigma_p = \operatorname{Frob}_\mathfrak{p}` for any $`\mathfrak{p}` above $`p` (as $`m`th roots of unity will be distinct modulo $`p`; differentiate $`x^m - 1` mod $`p` again).

*Putnam 2012 B6.*

_Hint._ By primitive roots, it's the same as the action of $`\times 3` on $`\mathbb{Z}/(p-1)\mathbb{Z}`.
Let $`\zeta` be a $`(p-1)`st root of unity.
Take $`d = \prod_{i < j} (\zeta^i - \zeta^j)`, think about $`\mathbb{Q}(d)`, and figure out how to act on it by $`x \mapsto x^3`.

_Solution._ This solution is by David Corwin.
By primitive roots, it's the same as the action of $`\times 3` on $`\mathbb{Z}/(p-1)\mathbb{Z}`.
Let $`\zeta` be a $`(p-1)`st root of unity.
Consider $$`d = \prod_{0 \le i < j < p-1} (\zeta^i - \zeta^j).`
This is the square root of the discriminant of the polynomial $`X^{p-1} - 1`; in other words $`d^2 \in \mathbb{Z}`.
In fact, by elementary methods one can compute $$`(-1)^{\binom{p-1}{2}} d^2 = -(p-1)^{p-1}.`
Now take the extension $`K = \mathbb{Q}(d)`, noting that

- if $`p \equiv 3 \pmod 4`, then $`d = (p-1)^{\frac12(p-1)}`, so $`K = \mathbb{Q}`;
- if $`p \equiv 1 \pmod 4`, then $`d = i(p-1)^{\frac12(p-1)}`, so $`K = \mathbb{Q}(i)`.

Either way, in $`\mathcal{O}_K`, let $`\mathfrak{p}` be a prime ideal above $`(3) \subseteq \mathcal{O}_K`.
Let $`\sigma = \operatorname{Frob}_\mathfrak{p}` then be the unique element such that $`\sigma(x) = x^3 \pmod{\mathfrak{p}}` for all $`x`.
Then, we observe that $$`\sigma(d) \equiv \prod_{0 \le i < j < p-1} (\zeta^{3i} - \zeta^{3j}) \equiv \begin{cases} +d & \text{if } \pi \text{ is even} \\ -d & \text{if } \pi \text{ is odd} \end{cases} \pmod{\mathfrak{p}}.`
Now if $`K = \mathbb{Q}`, then $`\sigma` is the identity, thus $`\sigma` is even.
Conversely, if $`K = \mathbb{Q}(i)`, then $`3` does not split, so $`\sigma(d) = -d` (actually $`\sigma` is complex conjugation), thus $`\pi` is odd.
Note that the condition $`p \equiv 2 \pmod 3` is used only to guarantee that $`\pi` is actually a permutation (and thus $`d \neq 0`); it does not play any substantial role in the solution.

*Kronecker–Weber theorem.*

_Hint._ Pick $`m` so that $`\mathfrak{f}(L/\mathbb{Q}) \mid m\infty`.

_Solution._ Suppose $`\mathfrak{f}(L/\mathbb{Q}) \mid m\infty` for some $`m`.
Then by the earlier example we have the chain $$`P_{\mathbb{Q}}(m\infty) = H(\mathbb{Q}(\zeta)/\mathbb{Q}, m\infty) \subseteq H(L/\mathbb{Q}, m) \subseteq I_\mathbb{Q}(m\infty).`
So by inclusion reversal we're done.

*Hilbert class field.*

_Hint._ Apply the Takagi existence theorem with $`\mathfrak{m} = 1`.

_Solution._ Apply the Takagi existence theorem with $`\mathfrak{m} = 1` to obtain an unramified extension $`E/K` such that $`H(E/K, 1) = P_K(1)`.
We claim this works:

- To see it is maximal by inclusion, note that any other extension $`M/K` with this property has conductor $`1` (no primes divide the conductor), and then we have $`P_K(1) = H(E/K, 1) \subseteq H(M/K, 1) \subseteq I_K(1)`, so inclusion reversal gives $`M \subseteq E`.
- We have $`\operatorname{Gal}(E/K) \cong I_K(1) / P_K(1) = C_K(1)`, the class group.
- The isomorphism in the previous part is given by the Artin symbol.
  So $`\mathfrak{p}` splits completely if and only if $`\left( \frac{E/K}{\mathfrak{p}} \right) = \operatorname{id}`, if and only if $`\mathfrak{p}` is principal (trivial in $`C_K(1)`).

*Representing primes as $`x^2 + 23y^2`.*

_Hint._ The extension $`L/\mathbb{Q}` is not abelian.
